;; Generated by the revl cordis-wasm backend (ir_version 1) — do not edit.
;; component Auditor
(module
  (import "coeffect:kv" "set" (func $req_kv_set (param i64) (param i64)))
  (import "coeffect:status" "shared" (func $req_status_shared (result i64)))
  (global $__step (mut i32) (i32.const 0))
  (func (export "activate_step") (result i32)
    (if (i32.eq (global.get $__step) (i32.const 0))
      (then
      (call $req_kv_set (i64.const 9) (call $req_status_shared))
      (global.set $__step (i32.const 1))
      (return (i32.const 0))))
    (i32.const 0))
  (func (export "deactivate")
    (if (i32.ge_s (global.get $__step) (i32.const 1))
      (then
      (call $req_kv_set (i64.const 9) (i64.const 0))))
  )
)
