;; Generated by the revl cordis-wasm backend (ir_version 1) — do not edit.
;; component Beacon
(module
  (import "coeffect:kv" "get" (func $req_kv_get (param i64) (result i64)))
  (import "coeffect:kv" "set" (func $req_kv_set (param i64) (param i64)))
  (global $__step (mut i32) (i32.const 0))
  (func (export "activate_step") (result i32)
    (if (i32.eq (global.get $__step) (i32.const 0))
      (then
      (call $req_kv_set (i64.const 7) (i64.const 100))
      (global.set $__step (i32.const 1))
      (return (i32.const 1))))
    (if (i32.eq (global.get $__step) (i32.const 1))
      (then
      (call $req_kv_set (i64.const 8) (i64.const 200))
      (global.set $__step (i32.const 2))
      (return (i32.const 0))))
    (i32.const 0))
  (func (export "deactivate")
    (if (i32.ge_s (global.get $__step) (i32.const 2))
      (then
      (call $req_kv_set (i64.const 8) (i64.const 0))))
    (if (i32.ge_s (global.get $__step) (i32.const 1))
      (then
      (call $req_kv_set (i64.const 7) (i64.const 0))))
  )
  (func (export "provide:status.shared") (result i64)
    (call $req_kv_get (i64.const 7)))
)
