;; Generated by the revl cordis-wasm backend (ir_version 3) — do not edit.
;; pure functions + documented type layouts; Int is i64 (values), addresses
;; are i32; Str/List/record values use canonical-ABI-shaped linear memory
;; (u32 length/count prefix, then one 8-byte slot per field/element)
(module
  (memory (export "memory") 1)
  (data (i32.const 0) "\01\00\00\00!")
  (data (i32.const 8) "\07\00\00\00Hello, ")
  (global $__hp (mut i32) (i32.const 32))
  ;; item 432(e): the per-call arena floor. Every canonical export
  ;; rewinds $__hp here on the way out, so nothing a call allocates
  ;; survives it (see `_arena_safe` for why that is sound here).
  (global $__canon_arena_base i32 (i32.const 32))
  ;; item 432(f): the canonical return area is constant for the
  ;; module (the host reads it before it can re-enter), so one
  ;; cell serves every call instead of one bump allocation each.
  (global $__canon_ret_area i32 (i32.const 24))
  (func $__heap_exhausted
    (unreachable))
  (func $__heap_grow (param $end i32)
    (local $want i32)
    (local $have i32)
    (local.set $want
      (i32.add
        (i32.shr_u (local.get $end) (i32.const 16))
        (i32.ne
          (i32.and (local.get $end) (i32.const 65535))
          (i32.const 0))))
    (local.set $have (memory.size))
    (if (i32.le_u (local.get $want) (local.get $have))
      (then (return)))
    (if (i32.eq
          (memory.grow (i32.sub (local.get $want) (local.get $have)))
          (i32.const -1))
      (then (call $__heap_exhausted))))
  (func $alloc (param $n i32) (result i32)
    (local $p i32)
    (local $sz i32)
    (local $end i32)
    (local.set $sz
      (i32.and
        (i32.add (local.get $n) (i32.const 7))
        (i32.const -8)))
    (if (i32.lt_u (local.get $sz) (local.get $n))
      (then (call $__heap_exhausted)))
    (local.set $p (global.get $__hp))
    (local.set $end (i32.add (local.get $p) (local.get $sz)))
    (if (i32.lt_u (local.get $end) (local.get $p))
      (then (call $__heap_exhausted)))
    (if (i32.gt_u
          (local.get $end)
          (i32.shl (memory.size) (i32.const 16)))
      (then (call $__heap_grow (local.get $end))))
    (global.set $__hp (local.get $end))
    (local.get $p))
  (func $alloc_str (param $len i32) (result i32)
    (local $p i32)
    (local.set $p (call $alloc (i32.add (local.get $len) (i32.const 4))))
    (i32.store (local.get $p) (local.get $len))
    (local.get $p))
  (func $str_concat (param $a i32) (param $b i32) (result i32)
    (local $la i32)
    (local $lb i32)
    (local $p i32)
    (local.set $la (i32.load (local.get $a)))
    (local.set $lb (i32.load (local.get $b)))
    (local.set $p (call $alloc_str (i32.add (local.get $la) (local.get $lb))))
    (memory.copy
      (i32.add (local.get $p) (i32.const 4))
      (i32.add (local.get $a) (i32.const 4))
      (local.get $la))
    (memory.copy
      (i32.add (i32.add (local.get $p) (i32.const 4)) (local.get $la))
      (i32.add (local.get $b) (i32.const 4))
      (local.get $lb))
    (local.get $p))
  ;; item 432(d): one concat per template literal — one length
  ;; pass, one allocation, one copy per part.
  (func $str_concat3 (param $a0 i32) (param $a1 i32) (param $a2 i32) (result i32)
    (local $l0 i32)
    (local $l1 i32)
    (local $l2 i32)
    (local $p i32)
    (local $o i32)
    (local.set $l0 (i32.load (local.get $a0)))
    (local.set $l1 (i32.load (local.get $a1)))
    (local.set $l2 (i32.load (local.get $a2)))
    (local.set $p (call $alloc_str (i32.add (i32.add (local.get $l0) (local.get $l1)) (local.get $l2))))
    (local.set $o (i32.add (local.get $p) (i32.const 4)))
    (memory.copy (local.get $o) (i32.add (local.get $a0) (i32.const 4)) (local.get $l0))
    (local.set $o (i32.add (local.get $o) (local.get $l0)))
    (memory.copy (local.get $o) (i32.add (local.get $a1) (i32.const 4)) (local.get $l1))
    (local.set $o (i32.add (local.get $o) (local.get $l1)))
    (memory.copy (local.get $o) (i32.add (local.get $a2) (i32.const 4)) (local.get $l2))
    (local.get $p))

  (func $echo (export "echo") (param $p_s i32) (result i32) (local $__revl_tmp i32)
    (local.get $p_s)
    return)

  (func $shout (export "shout") (param $p_s i32) (result i32) (local $__revl_tmp i32)
    (local.get $p_s)
      (i32.const 0)
      (call $str_concat)
    return)

  (func $greet (export "greet") (param $p_name i32) (result i32) (local $__revl_tmp i32)
    (i32.const 8)
      (local.get $p_name)
      (i32.const 0)
      (call $str_concat3)
    return)
  ;; --- canonical ABI boundary (item 41) ---
  ;; cabi_realloc: the standard allocator a component host calls to
  ;; place an incoming string/list into this module's memory. Backed
  ;; by the same bump heap ($__hp / $alloc); old/align are unused (a
  ;; bump allocator never frees, and $alloc already 8-aligns).
  ;; item 432(a): every buffer is handed out with 8 bytes of headroom
  ;; below it, so lifting a canonical string into the internal
  ;; [u32 len][bytes] layout is one store instead of a copy.
  (func (export "cabi_realloc")
      (param $old i32) (param $old_size i32) (param $align i32) (param $new_size i32)
      (result i32)
    (i32.add
      (call $alloc (i32.add (local.get $new_size) (i32.const 8)))
      (i32.const 8)))
  ;; bare (ptr,len) canonical string <-> internal [u32 len][bytes].
  ;; The lift is zero-copy for a buffer that came from the
  ;; cabi_realloc above (every conforming host's string param), and
  ;; falls back to a bulk copy for any pointer outside this heap.
  (func $__canon_lift_str (param $ptr i32) (param $len i32) (result i32)
    (local $s i32)
    (if (i32.ge_u (local.get $ptr) (i32.const 40))
      (then
        (i32.store (i32.sub (local.get $ptr) (i32.const 4)) (local.get $len))
        (return (i32.sub (local.get $ptr) (i32.const 4)))))
    (local.set $s (call $alloc_str (local.get $len)))
    (memory.copy
      (i32.add (local.get $s) (i32.const 4))
      (local.get $ptr)
      (local.get $len))
    (local.get $s))
  (func $__canon_lower_str (param $s i32) (param $dst i32)
    (i32.store (local.get $dst) (i32.add (local.get $s) (i32.const 4)))
    (i32.store offset=4 (local.get $dst) (i32.load (local.get $s))))
  ;; canonical export of `echo` -> WIT `echoer#echo`
  (func (export "revl:exported/echoer#echo") (param $c0 i32) (param $c1 i32) (result i32)
    (local $a0 i32) (local $rv i32) (local $area i32)
    (local.set $a0 (call $__canon_lift_str (local.get $c0) (local.get $c1)))
    (local.set $rv (call $echo (local.get $a0)))
    (local.set $area (global.get $__canon_ret_area))
    (call $__canon_lower_str (local.get $rv) (local.get $area))
    (global.set $__hp (global.get $__canon_arena_base))
    (local.get $area))
  ;; canonical export of `shout` -> WIT `echoer#shout`
  (func (export "revl:exported/echoer#shout") (param $c0 i32) (param $c1 i32) (result i32)
    (local $a0 i32) (local $rv i32) (local $area i32)
    (local.set $a0 (call $__canon_lift_str (local.get $c0) (local.get $c1)))
    (local.set $rv (call $shout (local.get $a0)))
    (local.set $area (global.get $__canon_ret_area))
    (call $__canon_lower_str (local.get $rv) (local.get $area))
    (global.set $__hp (global.get $__canon_arena_base))
    (local.get $area))
  ;; canonical export of `greet` -> WIT `echoer#greet`
  (func (export "revl:exported/echoer#greet") (param $c0 i32) (param $c1 i32) (result i32)
    (local $a0 i32) (local $rv i32) (local $area i32)
    (local.set $a0 (call $__canon_lift_str (local.get $c0) (local.get $c1)))
    (local.set $rv (call $greet (local.get $a0)))
    (local.set $area (global.get $__canon_ret_area))
    (call $__canon_lower_str (local.get $rv) (local.get $area))
    (global.set $__hp (global.get $__canon_arena_base))
    (local.get $area))
)
