;; Generated by the revl cordis-wasm backend (ir_version 3) — do not edit.
;; pure functions + documented type layouts; Str/List/record values use
;; canonical-ABI-shaped linear memory (u32 length/count prefix)
(module
  (memory (export "memory") 1)
  (data (i32.const 0) "\02\00\00\00hi")
  (data (i32.const 8) "\03\00\00\00neg")
  (data (i32.const 16) "\03\00\00\00pos")
  (global $__hp (mut i32) (i32.const 24))
  (func $alloc (param $n i32) (result i32)
    (local $p i32)
    (local.set $p (global.get $__hp))
    (global.set $__hp
      (i32.add
        (global.get $__hp)
        (i32.and
          (i32.add (local.get $n) (i32.const 3))
          (i32.const -4))))
    (local.get $p))
  (func $alloc_str (param $len i32) (result i32)
    (local $p i32)
    (local.set $p (call $alloc (i32.add (local.get $len) (i32.const 4))))
    (i32.store (local.get $p) (local.get $len))
    (local.get $p))
  (func $int_to_str (param $n i32) (result i32)
    (local $neg i32)
    (local $x i32)
    (local $len i32)
    (local $p i32)
    (local $i i32)
    (if (i32.eqz (local.get $n))
      (then
        (local.set $p (call $alloc_str (i32.const 1)))
        (i32.store8 (i32.add (local.get $p) (i32.const 4)) (i32.const 48))
        (return (local.get $p))))
    (local.set $neg (i32.lt_s (local.get $n) (i32.const 0)))
    (local.set $x (select
      (i32.sub (i32.const 0) (local.get $n))
      (local.get $n)
      (local.get $neg)))
    (local.set $len (i32.const 0))
    (local.set $i (local.get $x))
    (block (loop
      (br_if 1 (i32.eqz (local.get $i)))
      (local.set $len (i32.add (local.get $len) (i32.const 1)))
      (local.set $i (i32.div_u (local.get $i) (i32.const 10)))
      (br 0)))
    (local.set $p (call $alloc_str (i32.add (local.get $len) (local.get $neg))))
    (if (local.get $neg)
      (then (i32.store8 (i32.add (local.get $p) (i32.const 4)) (i32.const 45))))
    (local.set $i (i32.add (local.get $len) (local.get $neg)))
    (block (loop
      (br_if 1 (i32.eqz (local.get $x)))
      (local.set $i (i32.sub (local.get $i) (i32.const 1)))
      (i32.store8
        (i32.add (i32.add (local.get $p) (i32.const 4)) (local.get $i))
        (i32.add (i32.rem_u (local.get $x) (i32.const 10)) (i32.const 48)))
      (local.set $x (i32.div_u (local.get $x) (i32.const 10)))
      (br 0)))
    (local.get $p))
  (func $str_concat (param $a i32) (param $b i32) (result i32)
    (local $la i32)
    (local $lb i32)
    (local $p i32)
    (local.set $la (i32.load (local.get $a)))
    (local.set $lb (i32.load (local.get $b)))
    (local.set $p (call $alloc_str (i32.add (local.get $la) (local.get $lb))))
    (memory.copy
      (i32.add (local.get $p) (i32.const 4))
      (i32.add (local.get $a) (i32.const 4))
      (local.get $la))
    (memory.copy
      (i32.add (i32.add (local.get $p) (i32.const 4)) (local.get $la))
      (i32.add (local.get $b) (i32.const 4))
      (local.get $lb))
    (local.get $p))
  (func $str_eq (param $a i32) (param $b i32) (result i32)
    (local $n i32)
    (local $i i32)
    (local.set $n (i32.load (local.get $a)))
    (if (i32.ne (local.get $n) (i32.load (local.get $b)))
      (then (return (i32.const 0))))
    (local.set $i (i32.const 0))
    (block $done
      (loop $loop
        (br_if $done (i32.ge_u (local.get $i) (local.get $n)))
        (if (i32.ne
              (i32.load8_u (i32.add (i32.add (local.get $a) (i32.const 4)) (local.get $i)))
              (i32.load8_u (i32.add (i32.add (local.get $b) (i32.const 4)) (local.get $i))))
          (then (return (i32.const 0))))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (br $loop)))
    (i32.const 1))
  (func $str_slice (param $s i32) (param $start i32) (param $end i32) (result i32)
    (local $len i32)
    (local $p i32)
    (local.set $len (i32.sub (local.get $end) (local.get $start)))
    (local.set $p (call $alloc_str (local.get $len)))
    (memory.copy
      (i32.add (local.get $p) (i32.const 4))
      (i32.add (i32.add (local.get $s) (i32.const 4)) (local.get $start))
      (local.get $len))
    (local.get $p))
  (func $str_char_at (param $s i32) (param $idx i32) (result i32)
    (local $p i32)
    (local.set $p (call $alloc_str (i32.const 1)))
    (i32.store8
      (i32.add (local.get $p) (i32.const 4))
      (i32.load8_u (i32.add (i32.add (local.get $s) (i32.const 4)) (local.get $idx))))
    (local.get $p))
  (func $str_char_code_at (param $s i32) (param $idx i32) (result i32)
    (i32.load8_u (i32.add (i32.add (local.get $s) (i32.const 4)) (local.get $idx))))
  (func $list_push (param $list i32) (param $elem i32) (result i32)
    (local $n i32)
    (local $p i32)
    (local.set $n (i32.load (local.get $list)))
    (local.set $p
      (call $alloc
        (i32.add
          (i32.mul (i32.add (local.get $n) (i32.const 1)) (i32.const 4))
          (i32.const 4))))
    (i32.store (local.get $p) (i32.add (local.get $n) (i32.const 1)))
    (memory.copy
      (i32.add (local.get $p) (i32.const 4))
      (i32.add (local.get $list) (i32.const 4))
      (i32.mul (local.get $n) (i32.const 4)))
    (i32.store
      (i32.add
        (i32.add (local.get $p) (i32.const 4))
        (i32.mul (local.get $n) (i32.const 4)))
      (local.get $elem))
    (local.get $p))
  (func $list_concat (param $a i32) (param $b i32) (result i32)
    (local $na i32)
    (local $nb i32)
    (local $p i32)
    (local.set $na (i32.load (local.get $a)))
    (local.set $nb (i32.load (local.get $b)))
    (local.set $p
      (call $alloc
        (i32.add
          (i32.mul (i32.add (local.get $na) (local.get $nb)) (i32.const 4))
          (i32.const 4))))
    (i32.store (local.get $p) (i32.add (local.get $na) (local.get $nb)))
    (memory.copy
      (i32.add (local.get $p) (i32.const 4))
      (i32.add (local.get $a) (i32.const 4))
      (i32.mul (local.get $na) (i32.const 4)))
    (memory.copy
      (i32.add
        (i32.add (local.get $p) (i32.const 4))
        (i32.mul (local.get $na) (i32.const 4)))
      (i32.add (local.get $b) (i32.const 4))
      (i32.mul (local.get $nb) (i32.const 4)))
    (local.get $p))
  (func $list_slice (param $s i32) (param $start i32) (param $end i32) (result i32)
    (local $len i32)
    (local $p i32)
    (local.set $len (i32.sub (local.get $end) (local.get $start)))
    (local.set $p
      (call $alloc
        (i32.add (i32.mul (local.get $len) (i32.const 4)) (i32.const 4))))
    (i32.store (local.get $p) (local.get $len))
    (memory.copy
      (i32.add (local.get $p) (i32.const 4))
      (i32.add
        (i32.add (local.get $s) (i32.const 4))
        (i32.mul (local.get $start) (i32.const 4)))
      (i32.mul (local.get $len) (i32.const 4)))
    (local.get $p))
  ;; --- record/variant layouts (docs/syntax-2.0.md §2) ---
  ;; @record Row { id:Int name:Str }
  ;; @variant Outcome (tagged union layout)
  ;;   case Ok: Row
  ;;   case NotFound: unit
  ;;   case Invalid: Str

  (func $add (export "add") (param $p_a i32) (param $p_b i32) (result i32) (local $__revl_tmp i32)
    (local.get $p_a)
      (local.get $p_b)
      (i32.add)
    return)

  (func $negate (export "negate") (param $p_b i32) (result i32) (local $__revl_tmp i32)
    (local.get $p_b)
      (i32.eqz)
    return)

  (func $name (export "name") (param $p_row i32) (result i32) (local $__revl_tmp i32)
    (i32.load (i32.add (local.get $p_row) (i32.const 4)))
    return)

  (func $first (export "first") (param $p_xs i32) (result i32) (local $__revl_tmp i32)
    (i32.load (i32.add (local.get $p_xs) (i32.const 4)))
    return)

  (func $greet (export "greet") (result i32) (local $__revl_tmp i32)
    (i32.const 0)
    return)

  (func $make_row (export "make_row") (param $p_id i32) (param $p_name i32) (result i32) (local $__revl_tmp i32)
    (call $alloc (i32.const 8))
      (local.set $__revl_tmp)
      (i32.store (local.get $__revl_tmp) (local.get $p_id))
      (i32.store (i32.add (local.get $__revl_tmp) (i32.const 4)) (local.get $p_name))
      (local.get $__revl_tmp)
    return)

  (func $classify (export "classify") (param $p_n i32) (result i32) (local $__revl_tmp i32)
    (local.get $p_n)
      (i32.const 0)
      (i32.lt_s)
    (if
      (then
        (i32.const 8)
        return
      )
    )
    (i32.const 16)
    return)

)
