;; Generated by the revl cordis-wasm backend (ir_version 1) — do not edit.
;; component Pulse
(module
  (import "coeffect:kv" "set" (func $req_kv_set (param i64) (param i64)))
  (import "host" "job_run" (func $host_job_run (param i32)))
  (global $__step (mut i32) (i32.const 0))
  (func (export "activate_step") (result i32)
    (if (i32.eq (global.get $__step) (i32.const 0))
      (then
      (call $req_kv_set (i64.const 1) (i64.const 11))
      (global.set $__step (i32.const 1))
      (return (i32.const 1))))
    (if (i32.eq (global.get $__step) (i32.const 1))
      (then
      (call $host_job_run (i32.const 1))
      (global.set $__step (i32.const 2))
      (return (i32.const 1))))
    (if (i32.eq (global.get $__step) (i32.const 2))
      (then
      (call $req_kv_set (i64.const 2) (i64.const 22))
      (global.set $__step (i32.const 3))
      (return (i32.const 0))))
    (i32.const 0))
  (func (export "deactivate")
    (if (i32.ge_s (global.get $__step) (i32.const 3))
      (then
      (call $req_kv_set (i64.const 2) (i64.const 0))))
    (if (i32.ge_s (global.get $__step) (i32.const 1))
      (then
      (call $req_kv_set (i64.const 1) (i64.const 0))))
  )
)
