// Code generated by backends/go/emit.py — DO NOT EDIT.
// revl -> cordis-go, targeting github.com/0xdenny218/stc-go.
package tenants

import (
	"fmt"
	"sync"

	stc "github.com/0xdenny218/stc-go"
)

var _ = fmt.Sprintf

// ---- host runtime (minimal, recording) --------------------------------
// A deterministic in-memory stand-in for revl host objects, instrumented so
// scenarios can assert the exact effect/undo order of emitted code.

var _hostMu sync.Mutex
var _hostLog []string

func hostRecord(op string) {
	_hostMu.Lock()
	_hostLog = append(_hostLog, op)
	_hostMu.Unlock()
}

// HostMarks returns an ordered snapshot of host operations.
func HostMarks() []string {
	_hostMu.Lock()
	defer _hostMu.Unlock()
	out := make([]string, len(_hostLog))
	copy(out, _hostLog)
	return out
}

// HostReset clears the host op log (call between scenarios).
func HostReset() {
	_hostMu.Lock()
	_hostLog = nil
	_hostMu.Unlock()
}

// Row is a query result row.
type Row = map[string]string

// Pool is a deterministic in-memory connection pool.
type Pool struct {
	url  string
	size int
}

func PoolOpen(url string, size int) *Pool {
	hostRecord("pool.open")
	return &Pool{url: url, size: size}
}
func (p *Pool) Close() { hostRecord("pool.close") }
func (p *Pool) Query(sql string) []Row {
	hostRecord("pool.query:" + sql)
	return nil
}
func (p *Pool) Execute(sql string) int {
	hostRecord("pool.execute:" + sql)
	return 0
}

// Map is a thread-safe string map.
type Map struct {
	mu sync.Mutex
	m  map[string]string
}

func MapNew() *Map {
	hostRecord("map.new")
	return &Map{m: map[string]string{}}
}
func (m *Map) Drop() { hostRecord("map.drop") }
func (m *Map) Insert(k, v string) {
	m.mu.Lock()
	m.m[k] = v
	m.mu.Unlock()
}
func (m *Map) Remove(k string) {
	m.mu.Lock()
	delete(m.m, k)
	m.mu.Unlock()
}
func (m *Map) Get(k string) (string, bool) {
	m.mu.Lock()
	defer m.mu.Unlock()
	v, ok := m.m[k]
	return v, ok
}

// service Kv
type Kv interface {
	Get(k string) (string, bool)
	Set(k string, v string)
}

var _keyKv = stc.NewKey[Kv]("kv")

var (
	_revlRealmMu sync.Mutex
	_revlRealmBy = map[string]*stc.Realm{}
)

// _revlRealm interns a realm by name under the root realm so every load
// site naming the same realm shares the same *stc.Realm (provKey is
// keyed by pointer, not name).
func _revlRealm(name string) *stc.Realm {
	_revlRealmMu.Lock()
	defer _revlRealmMu.Unlock()
	if r, ok := _revlRealmBy[name]; ok {
		return r
	}
	r := stc.NewRealm(stc.RootRealm(), name)
	_revlRealmBy[name] = r
	return r
}

func TenantAStore() stc.Component {
	return stc.Component{
		Name:    "TenantAStore",
		Provide: []stc.Key{_keyKv},
		Apply: func(ctx *stc.Context) (stc.Inverse, error) {
			var store *Map
			if err := ctx.Effect(func() stc.Inverse {
				store = MapNew()
				return func() error { store.Drop(); return nil }
			}); err != nil {
				return nil, err
			}
			_implKv := &TenantAStore_kv{ctx: ctx, store: store}
			if _, err := ctx.Provide(_keyKv, Kv(_implKv)); err != nil {
				return nil, err
			}
			_ = store
			return nil, nil
		},
	}
}

type TenantAStore_kv struct {
	ctx   *stc.Context
	store *Map
}

func (s *TenantAStore_kv) Get(k string) (string, bool) {
	return s.store.Get(k)
}

func (s *TenantAStore_kv) Set(k string, v string) {
	s.ctx.Effect(func() stc.Inverse {
		s.store.Insert(k, v)
		return func() error { s.store.Remove(k); return nil }
	})
}

func TenantBStore() stc.Component {
	return stc.Component{
		Name:    "TenantBStore",
		Provide: []stc.Key{_keyKv},
		Apply: func(ctx *stc.Context) (stc.Inverse, error) {
			var store *Map
			if err := ctx.Effect(func() stc.Inverse {
				store = MapNew()
				return func() error { store.Drop(); return nil }
			}); err != nil {
				return nil, err
			}
			_implKv := &TenantBStore_kv{ctx: ctx, store: store}
			if _, err := ctx.Provide(_keyKv, Kv(_implKv)); err != nil {
				return nil, err
			}
			_ = store
			return nil, nil
		},
	}
}

type TenantBStore_kv struct {
	ctx   *stc.Context
	store *Map
}

func (s *TenantBStore_kv) Get(k string) (string, bool) {
	return s.store.Get(k)
}

func (s *TenantBStore_kv) Set(k string, v string) {
	s.ctx.Effect(func() stc.Inverse {
		s.store.Insert(k, v)
		return func() error { s.store.Remove(k); return nil }
	})
}

func TenantAApp() stc.Component {
	return stc.Component{
		Name:   "TenantAApp",
		Inject: []stc.Key{_keyKv},
		Apply: func(ctx *stc.Context) (stc.Inverse, error) {
			kv, err := stc.Service[Kv](ctx, _keyKv)
			if err != nil {
				return nil, err
			}
			if err := ctx.Effect(func() stc.Inverse {
				kv.Set("who", "alice")
				return func() error { kv.Set("who", ""); return nil }
			}); err != nil {
				return nil, err
			}
			_ = kv
			return nil, nil
		},
	}
}

func TenantBApp() stc.Component {
	return stc.Component{
		Name:   "TenantBApp",
		Inject: []stc.Key{_keyKv},
		Apply: func(ctx *stc.Context) (stc.Inverse, error) {
			kv, err := stc.Service[Kv](ctx, _keyKv)
			if err != nil {
				return nil, err
			}
			if err := ctx.Effect(func() stc.Inverse {
				kv.Set("who", "bob")
				return func() error { kv.Set("who", ""); return nil }
			}); err != nil {
				return nil, err
			}
			_ = kv
			return nil, nil
		},
	}
}

func LoadTenantAStore(target *stc.Context) *stc.Fiber {
	ctx := target.Child()
	ctx.Isolate(_keyKv, _revlRealm("tenant_a"))
	return ctx.Load(TenantAStore())
}

func LoadTenantBStore(target *stc.Context) *stc.Fiber {
	ctx := target.Child()
	ctx.Isolate(_keyKv, _revlRealm("tenant_b"))
	return ctx.Load(TenantBStore())
}

func LoadTenantAApp(target *stc.Context) *stc.Fiber {
	ctx := target.Child()
	ctx.Isolate(_keyKv, _revlRealm("tenant_a"))
	ctx.Intercept(_keyKv, map[string]any{"quota": 5, "tags": []any{"tenant_a"}})
	return ctx.Load(TenantAApp())
}

func LoadTenantBApp(target *stc.Context) *stc.Fiber {
	ctx := target.Child()
	ctx.Isolate(_keyKv, _revlRealm("tenant_b"))
	ctx.Intercept(_keyKv, map[string]any{"quota": 9, "tags": []any{"tenant_b"}})
	return ctx.Load(TenantBApp())
}
