// Code generated by backends/go/emit.py — DO NOT EDIT.
// revl -> cordis-go, targeting github.com/0xdenny218/stc-go.
package spawn

import (
	stdctx "context"
	"fmt"
	"sync"

	stc "github.com/0xdenny218/stc-go"
)

var _ = fmt.Sprintf

// ---- host runtime (minimal, recording) --------------------------------

// R1 live-resource accounting (docs/backend-ir.md §Required semantics, the
// same pairing the py reference tier's `assert no_residue` checks): every host
// object acquired must be released by its `undo`, or the lifecycle
// `assert no_residue` fails. The counter is package-wide, so it is per-test
// and cross-test safe: a clean test returns to zero.
var _revlLiveMu sync.Mutex
var _revlLiveHostResources int

func revlHostAcquire() { _revlLiveMu.Lock(); _revlLiveHostResources++; _revlLiveMu.Unlock() }
func revlHostRelease() { _revlLiveMu.Lock(); _revlLiveHostResources--; _revlLiveMu.Unlock() }
func revlHostLive() int {
	_revlLiveMu.Lock()
	defer _revlLiveMu.Unlock()
	return _revlLiveHostResources
}

// A deterministic in-memory stand-in for revl host objects, instrumented so
// scenarios can assert the exact effect/undo order of emitted code.

var _hostMu sync.Mutex
var _hostLog []string

func hostRecord(op string) {
	_hostMu.Lock()
	_hostLog = append(_hostLog, op)
	_hostMu.Unlock()
}

// HostMarks returns an ordered snapshot of host operations.
func HostMarks() []string {
	_hostMu.Lock()
	defer _hostMu.Unlock()
	out := make([]string, len(_hostLog))
	copy(out, _hostLog)
	return out
}

// HostReset clears the host op log (call between scenarios).
func HostReset() {
	_hostMu.Lock()
	_hostLog = nil
	_hostMu.Unlock()
}

// Row is a query result row.
type Row = map[string]string

// Pool is a deterministic in-memory connection pool.
type Pool struct {
	url  string
	size int64
}

func PoolOpen(url string, size int64) *Pool {
	hostRecord("pool.open")
	revlHostAcquire()
	return &Pool{url: url, size: size}
}
func (p *Pool) Close() { hostRecord("pool.close"); revlHostRelease() }
func (p *Pool) Query(sql string) []Row {
	hostRecord("pool.query:" + sql)
	return nil
}
func (p *Pool) Execute(sql string) int64 {
	hostRecord("pool.execute:" + sql)
	return 0
}

// Map is a thread-safe string map.
type Map struct {
	mu sync.Mutex
	m  map[string]string
}

func MapNew() *Map {
	hostRecord("map.new")
	revlHostAcquire()
	return &Map{m: map[string]string{}}
}
func (m *Map) Drop() { hostRecord("map.drop"); revlHostRelease() }
func (m *Map) Insert(k, v string) {
	m.mu.Lock()
	m.m[k] = v
	m.mu.Unlock()
}
func (m *Map) Remove(k string) {
	m.mu.Lock()
	delete(m.m, k)
	m.mu.Unlock()
}
func (m *Map) Get(k string) (string, bool) {
	m.mu.Lock()
	defer m.mu.Unlock()
	v, ok := m.m[k]
	return v, ok
}

// service Probe
type Probe interface {
	Mark(m string) int64
}

// service Counter
type Counter interface {
	Value() int64
}

// service Ctl
type Ctl interface {
	RetireA() int64
}

var _keyCounter = stc.NewKey[Counter]("counter")
var _keyProbe = stc.NewKey[Probe]("probe")
var _keyCtl = stc.NewKey[Ctl]("ctl")

type WorkerConfig struct {
	Tag string
	Id  int64
}

func DefaultWorkerConfig() WorkerConfig {
	return WorkerConfig{}
}

func Worker(cfg WorkerConfig) stc.Component {
	return stc.Component{
		Name:    "Worker",
		Inject:  []stc.Key{_keyProbe},
		Provide: []stc.Key{_keyCounter},
		Apply: func(ctx *stc.Context) (stc.Inverse, error) {
			probe, err := stc.Service[Probe](ctx, _keyProbe)
			if err != nil {
				return nil, err
			}
			if err := ctx.Effect(func() stc.Inverse {
				probe.Mark(fmt.Sprintf("up:%v", cfg.Tag))
				return func() error { probe.Mark(fmt.Sprintf("d1:%v", cfg.Tag)); return nil }
			}); err != nil {
				return nil, err
			}
			if err := ctx.Effect(func() stc.Inverse {
				probe.Mark("up2")
				return func() error { probe.Mark("d2"); return nil }
			}); err != nil {
				return nil, err
			}
			_implCounter := &Worker_counter{ctx: ctx, cfg: cfg, probe: probe}
			if _, err := ctx.Provide(_keyCounter, Counter(_implCounter)); err != nil {
				return nil, err
			}
			_ = probe
			_ = cfg
			return nil, nil
		},
	}
}

type Worker_counter struct {
	ctx   *stc.Context
	cfg   WorkerConfig
	probe Probe
}

func (s *Worker_counter) Value() int64 {
	return s.cfg.Id
}

func Supervisor() stc.Component {
	return stc.Component{
		Name:    "Supervisor",
		Inject:  []stc.Key{_keyProbe},
		Provide: []stc.Key{_keyCtl},
		Apply: func(ctx *stc.Context) (stc.Inverse, error) {
			probe, err := stc.Service[Probe](ctx, _keyProbe)
			if err != nil {
				return nil, err
			}
			var w1 *RevlSpawnHandle
			if err := ctx.Effect(func() stc.Inverse {
				w1 = revlSpawnWorker(ctx, WorkerConfig{Tag: "a", Id: 1})
				return func() error { w1.Dispose(); return nil }
			}); err != nil {
				return nil, err
			}
			var w2 *RevlSpawnHandle
			if err := ctx.Effect(func() stc.Inverse {
				w2 = revlSpawnWorker(ctx, WorkerConfig{Tag: "b", Id: 2})
				return func() error { w2.Dispose(); return nil }
			}); err != nil {
				return nil, err
			}
			_implCtl := &Supervisor_ctl{ctx: ctx, w1: w1, w2: w2, probe: probe}
			if _, err := ctx.Provide(_keyCtl, Ctl(_implCtl)); err != nil {
				return nil, err
			}
			_ = w1
			_ = w2
			_ = probe
			return nil, nil
		},
	}
}

type Supervisor_ctl struct {
	ctx   *stc.Context
	w1    *RevlSpawnHandle
	w2    *RevlSpawnHandle
	probe Probe
}

func (s *Supervisor_ctl) RetireA() int64 {
	r := s.w1.Dispose()
	_ = r
	return 1
}

// LoadWorker isolates the load-target per the component's realm placement, then loads it.
func LoadWorker(target *stc.Context, cfg WorkerConfig) *stc.Fiber {
	return target.Load(Worker(cfg))
}

func LoadSupervisor(target *stc.Context) *stc.Fiber {
	return target.Load(Supervisor())
}

// ---- instance-parametric spawn (docs/design-v2-instances.md) ----------
// A live spawned-component instance. The instance is a CHILD FIBER of its
// spawner — its own nested teardown scope. Dispose() unloads that fiber,
// running the instance's LIFO teardown NOW, independent of the spawner, so
// a request-scoped instance is reclaimed when the request ends and is never
// deferred to the component's teardown. Dispose is idempotent (the fiber is
// taken once), so the spawner's own undo — w.dispose() — is a harmless no-op
// once the instance is already gone: an un-disposed instance still cannot
// outlive its spawner, but a disposed one is reclaimed early.
type RevlSpawnHandle struct {
	mu    sync.Mutex
	fiber *stc.Fiber
	ctx   *stc.Context
}

func newRevlSpawnHandle(fiber *stc.Fiber, ctx *stc.Context) *RevlSpawnHandle {
	return &RevlSpawnHandle{fiber: fiber, ctx: ctx}
}

// Dispose unloads the instance's fiber (its LIFO teardown). Idempotent.
func (h *RevlSpawnHandle) Dispose() error {
	h.mu.Lock()
	f := h.fiber
	h.fiber = nil
	h.mu.Unlock()
	if f != nil {
		f.Dispose()
	}
	return nil
}

// Ctx exposes the instance's own isolated context, so its spawner (the sole
// holder of this handle) can resolve a provision the instance published in
// its private local realm. A sibling, isolated into a different local realm,
// cannot reach it — supervision-tree addressing.
func (h *RevlSpawnHandle) Ctx() *stc.Context {
	h.mu.Lock()
	defer h.mu.Unlock()
	// the instance's provision lives in the FIBER's live context (set at
	// async load, replaced on inertial reload), not the pre-load child ctx
	// the handle was constructed with — resolve through the fiber so the
	// accessor reads the instance's own realm, exactly like the py
	// reference's SpawnHandle.get (docs/design-v2-instances.md).
	if h.fiber != nil {
		if c := h.fiber.Context(); c != nil {
			return c
		}
	}
	return h.ctx
}

// Fiber exposes the live fiber (nil once disposed) for lifecycle assertions.
func (h *RevlSpawnHandle) Fiber() *stc.Fiber {
	h.mu.Lock()
	defer h.mu.Unlock()
	return h.fiber
}

// revlSpawnWorker plugs a fresh Worker instance as a CHILD FIBER of the
// spawner, each provided key isolated into its OWN fresh local realm — a
// distinct *stc.Realm per call, so two instances never collide on a
// provision (disjoint by construction, no label). The handle it returns
// reclaims exactly this instance on Dispose().
func revlSpawnWorker(parent *stc.Context, cfg WorkerConfig) *RevlSpawnHandle {
	child := parent.Child()
	child.Isolate(_keyCounter, stc.NewRealm(stc.RootRealm(), "spawn:Worker:counter"))
	fiber := child.Load(Worker(cfg))
	// stc-go loads asynchronously: the instance is 'live' (its provisions
	// resolvable) only once its fiber is Active. Wait for that here so the
	// handle the spawner binds is a live instance — the accessor's
	// s.<key>.method() reads through it without racing the async load
	// (matches the reference tier's synchronous spawn semantics).
	if err := fiber.Ready(stdctx.Background()); err != nil {
		panic("revl: spawned instance " + "Worker" + " failed to activate: " + err.Error())
	}
	return newRevlSpawnHandle(fiber, child)
}
