"""IR v3 type/function lowering for the cordis-wasm backend.

Run with:
    .venv/bin/pytest backends/wasm/test_v3_emit.py -q
"""

import importlib.util
import sys
from pathlib import Path

import pytest

BACKEND = Path(__file__).resolve().parent
ROOT = BACKEND.parents[1]
sys.path.insert(0, str(ROOT / "src"))

from revl import compile_source  # noqa: E402


def _emitter():
    spec = importlib.util.spec_from_file_location("revl_wasm_emit", BACKEND / "emit.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def test_v3_types_and_int_functions_emit():
    emit = _emitter()
    ir = compile_source(
        """
        type Row = { id: Int, name: Str }
        type Outcome = Ok(Row) | NotFound | Invalid(Str)

        fn add(a: Int, b: Int) -> Int { return a + b }
        fn classify(n: Int) -> Int {
          if (n < 0) return 0
          return n === 0 ? 1 : 2
        }
        fn negate(b: Bool) -> Bool { return !b }
        """
    )
    modules = emit.emit(ir)
    assert set(modules) == {"functions"}
    wat = modules["functions"]
    assert wat.startswith(";; Generated by the revl cordis-wasm backend (ir_version 3)")
    assert "@record Row { id:Int name:Str }" in wat
    assert "@variant Outcome (tagged union layout)" in wat
    assert "case Ok: Row" in wat
    assert 'case NotFound: unit' in wat
    assert 'case Invalid: Str' in wat
    assert '(func (export "add")' in wat
    assert '(func (export "classify")' in wat
    assert '(func (export "negate")' in wat
    assert "(i32.eqz)" in wat


def test_v3_str_list_record_functions_emit():
    emit = _emitter()
    ir = compile_source(
        """
        type Row = { id: Int, name: Str }

        fn name(row: Row) -> Str { return row.name }
        fn first(xs: List[Int]) -> Int { return xs[0] }
        fn greet() -> Str { return "hi" }
        fn make_row(id: Int, name: Str) -> Row { return { id: id, name: name } }
        """
    )
    modules = emit.emit(ir)
    assert set(modules) == {"functions"}
    wat = modules["functions"]
    assert '(func (export "name")' in wat
    assert '(func (export "first")' in wat
    assert '(func (export "greet")' in wat
    assert '(func (export "make_row")' in wat
    assert "(i32.load (i32.add (local.get $p_row) (i32.const 4)))" in wat
    assert "(i32.load (i32.add (local.get $p_xs) (i32.const 4)))" in wat
    assert '  (data (i32.const 0) "\\02\\00\\00\\00hi")' in wat


def test_v3_functions_golden_is_byte_identical():
    emit = _emitter()
    ir = compile_source(
        """
        type Row = { id: Int, name: Str }
        type Outcome = Ok(Row) | NotFound | Invalid(Str)

        fn add(a: Int, b: Int) -> Int { return a + b }
        fn negate(b: Bool) -> Bool { return !b }
        fn name(row: Row) -> Str { return row.name }
        fn first(xs: List[Int]) -> Int { return xs[0] }
        fn greet() -> Str { return "hi" }
        fn make_row(id: Int, name: Str) -> Row { return { id: id, name: name } }
        fn classify(n: Int) -> Str {
          if (n < 0) return "neg"
          return "pos"
        }
        """
    )
    wat = emit.emit(ir)["functions"]
    golden = (BACKEND / "golden" / "functions.wat").read_text()
    assert wat == golden


def test_version_gate_accepts_1_2_3_and_rejects_4():
    emit = _emitter()
    base = {
        "services": {"Svc": {"methods": {"ping": {"params": [], "returns": None, "emission": False}}}},
        "components": [
            {
                "name": "C",
                "config": [],
                "requires": {},
                "provides": {},
                "body": [],
            }
        ],
    }
    emit.emit({**base, "ir_version": 1})
    emit.emit({**base, "ir_version": 2})
    emit.emit({**base, "ir_version": 3, "types": {}, "functions": [], "externs": [], "tests": []})
    with pytest.raises(emit.EmitError, match="ir_version"):
        emit.emit({**base, "ir_version": 4})


def test_v3_externs_and_tests_are_documented_not_rejected():
    emit = _emitter()
    ir = compile_source(
        """
        extern pure fn host_call() -> Int = @py { return 1 }
        test "would run on a hosted backend" { assert true }
        """
    )
    modules = emit.emit(ir)
    assert "functions" in modules
    wat = modules["functions"]
    assert "unsupported on this tier: externs host_call" in wat
    assert "unsupported on this tier: tests 'would run on a hosted backend'" in wat
