"""IR v3 type/function lowering for the cordis-wasm backend.

Run with:
    .venv/bin/pytest backends/wasm/test_v3_emit.py -q
"""

import functools
import importlib.util
import os
import shutil
import sys
from pathlib import Path

import pytest

BACKEND = Path(__file__).resolve().parent
ROOT = BACKEND.parents[1]
sys.path.insert(0, str(ROOT / "src"))

from revl import compile_source  # noqa: E402


# --- wasmtime gate -----------------------------------------------------------
# The runtime-execution tests below are the only thing standing between this
# tier's claims (variants/Opt/Result lowering, native loops, Turing-complete
# functions, inlined closures) and a silent regression. They used to skip
# whenever `wasmtime` was absent - including in CI, which never installed it,
# so the whole runtime half of the tier was unguarded while reading green.
#
# CI now installs a pinned wasmtime AND sets REVL_REQUIRE_WASMTIME=1: with the
# flag set a missing runtime is a hard failure instead of a quiet skip. Local
# dev without the flag keeps the plain skip.
_REQUIRE_WASMTIME = os.environ.get("REVL_REQUIRE_WASMTIME", "").strip().lower() not in (
    "", "0", "false", "no",
)


def _wasmtime_or_fail() -> str:
    """Path to `wasmtime`, or skip/fail depending on REVL_REQUIRE_WASMTIME."""
    found = shutil.which("wasmtime")
    if found:
        return found
    if _REQUIRE_WASMTIME:
        pytest.fail(
            "wasmtime is not on PATH, so this tier's runtime coverage cannot "
            "run. REVL_REQUIRE_WASMTIME is set, which means this environment "
            "(CI) is expected to provide it - failing instead of skipping "
            "silently.",
            pytrace=False,
        )
    pytest.skip("wasmtime not installed (set REVL_REQUIRE_WASMTIME=1 to make this a failure)")


def _needs_wasmtime(fn):
    """Decorator form of `_wasmtime_or_fail` for whole-test gating."""

    @functools.wraps(fn)
    def wrapper(*args, **kwargs):
        _wasmtime_or_fail()
        return fn(*args, **kwargs)

    return wrapper


def _emitter():
    spec = importlib.util.spec_from_file_location("revl_wasm_emit", BACKEND / "emit.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _run_module(tmp_path, source: str):
    """Compile `source` to WAT and return an `invoke(fn, *args) -> int` bound to
    it, run on the real wasmtime substrate — the same harness the collatz/fib
    tests use (write WAT, `wasmtime --invoke`, read the last stdout line),
    factored out so the scenarios below can share one module per program."""
    import subprocess

    _wasmtime_or_fail()
    wat_path = tmp_path / "mod.wat"
    wat_path.write_text(_emitter().emit(compile_source(source))["functions"], encoding="utf-8")

    def invoke(fn: str, *args) -> int:
        out = subprocess.run(
            ["wasmtime", "--invoke", fn, str(wat_path), *[str(a) for a in args]],
            capture_output=True, text=True, timeout=60,
        )
        assert out.returncode == 0, out.stderr
        return int(out.stdout.strip().splitlines()[-1])

    return invoke


def test_v3_types_and_int_functions_emit():
    emit = _emitter()
    ir = compile_source(
        """
        type Row = { id: Int, name: Str }
        type Outcome = Ok(Row) | NotFound | Invalid(Str)

        fn add(a: Int, b: Int) -> Int { return a + b }
        fn classify(n: Int) -> Int {
          if (n < 0) return 0
          return n === 0 ? 1 : 2
        }
        fn negate(b: Bool) -> Bool { return !b }
        """
    )
    modules = emit.emit(ir)
    assert set(modules) == {"functions"}
    wat = modules["functions"]
    assert wat.startswith(";; Generated by the revl cordis-wasm backend (ir_version 3)")
    assert "@record Row { id:Int name:Str }" in wat
    assert "@variant Outcome (tagged union layout)" in wat
    assert "case Ok: Row" in wat
    assert 'case NotFound: unit' in wat
    assert 'case Invalid: Str' in wat
    assert '(export "add")' in wat
    assert '(export "classify")' in wat
    assert '(export "negate")' in wat
    assert "(i32.eqz)" in wat


def test_v3_str_list_record_functions_emit():
    emit = _emitter()
    ir = compile_source(
        """
        type Row = { id: Int, name: Str }

        fn name(row: Row) -> Str { return row.name }
        fn first(xs: List[Int]) -> Int { return xs[0] }
        fn greet() -> Str { return "hi" }
        fn make_row(id: Int, name: Str) -> Row { return { id: id, name: name } }
        """
    )
    modules = emit.emit(ir)
    assert set(modules) == {"functions"}
    wat = modules["functions"]
    assert '(export "name")' in wat
    assert '(export "first")' in wat
    assert '(export "greet")' in wat
    assert '(export "make_row")' in wat
    # a record field / list element is one 8-byte slot: the Str field comes
    # back through the slot and is narrowed to its i32 address, the Int element
    # is the slot
    assert "(i32.wrap_i64 (i64.load (i32.add (local.get $p_row) (i32.const 8))))" in wat
    assert "(i64.load (i32.add (local.get $p_xs) (i32.const 8)))" in wat
    assert '  (data (i32.const 0) "\\02\\00\\00\\00hi")' in wat


def test_v3_functions_golden_is_byte_identical():
    emit = _emitter()
    ir = compile_source(
        """
        type Row = { id: Int, name: Str }
        type Outcome = Ok(Row) | NotFound | Invalid(Str)

        fn add(a: Int, b: Int) -> Int { return a + b }
        fn negate(b: Bool) -> Bool { return !b }
        fn name(row: Row) -> Str { return row.name }
        fn first(xs: List[Int]) -> Int { return xs[0] }
        fn greet() -> Str { return "hi" }
        fn make_row(id: Int, name: Str) -> Row { return { id: id, name: name } }
        fn classify(n: Int) -> Str {
          if (n < 0) return "neg"
          return "pos"
        }
        """
    )
    wat = emit.emit(ir)["functions"]
    golden = (BACKEND / "golden" / "functions.wat").read_text()
    assert wat == golden


def test_version_gate_accepts_1_2_3_and_rejects_4():
    emit = _emitter()
    base = {
        "services": {"Svc": {"methods": {"ping": {"params": [], "returns": None, "emission": False}}}},
        "components": [
            {
                "name": "C",
                "config": [],
                "requires": {},
                "provides": {},
                "body": [],
            }
        ],
    }
    emit.emit({**base, "ir_version": 1})
    emit.emit({**base, "ir_version": 2})
    emit.emit({**base, "ir_version": 3, "types": {}, "functions": [], "externs": [], "tests": []})
    with pytest.raises(emit.EmitError, match="ir_version"):
        emit.emit({**base, "ir_version": 4})


def test_v3_externs_and_tests_are_documented_not_rejected():
    emit = _emitter()
    ir = compile_source(
        """
        extern pure fn host_call() -> Int = @py { return 1 }
        test "would run on a hosted backend" { assert true }
        """
    )
    modules = emit.emit(ir)
    assert "functions" in modules
    wat = modules["functions"]
    assert "unsupported on this tier: externs host_call" in wat
    assert "unsupported on this tier: tests 'would run on a hosted backend'" in wat


# tagged unions (user variants, Result, Opt) lower to
# [u32 tag][pad][8-byte payload slot] in linear memory; match dispatches on
# the tag, which stays a u32 because it is a discriminant, not an Int value.
_ADT_SRC = """
type O = Found(Int) | Missing
fn mk_u(h: Bool) -> Int { let o = h ? Found(9) : Missing  return match o { Found(v) => v, Missing => 0 } }
fn r_d(ok: Bool) -> Int { let x = ok ? Ok(7) : Err(1)  return match x { Ok(v) => v, Err(e) => 0 - e } }
fn opt_or(some: Bool) -> Int { let x = some ? Some(5) : None  return match x { Some(v) => v, None => 0 } }
"""


def test_v3_variant_result_opt_emit():
    emit = _emitter()
    wat = emit.emit(compile_source(_ADT_SRC))["functions"]
    # construction: alloc two slots, store tag + payload
    assert "(call $alloc (i32.const 16))" in wat
    assert "(i32.store (local.get $__revl_tmp) (i32.const 0))" in wat  # a tag store
    # match: dispatch on the loaded tag
    assert "(i32.eq (i32.load (local.get $msc_1)) (i32.const" in wat


@_needs_wasmtime
def test_v3_variant_result_opt_run_on_wasmtime(tmp_path):
    """Not just emitted — construct + match execute on the real substrate:
    user variants, Result (Ok/Err discriminated), and Opt."""
    import subprocess

    emit = _emitter()
    wat_path = tmp_path / "adt.wat"
    wat_path.write_text(emit.emit(compile_source(_ADT_SRC))["functions"], encoding="utf-8")

    def invoke(fn: str, arg: str) -> int:
        out = subprocess.run(
            ["wasmtime", "--invoke", fn, str(wat_path), arg],
            capture_output=True, text=True, timeout=60,
        )
        assert out.returncode == 0, out.stderr
        return int(out.stdout.strip().splitlines()[-1])

    assert invoke("mk_u", "1") == 9 and invoke("mk_u", "0") == 0
    assert invoke("r_d", "1") == 7 and invoke("r_d", "0") == -1   # Ok vs Err
    assert invoke("opt_or", "1") == 5 and invoke("opt_or", "0") == 0


# `while` / `for` lower to native wasm loops — the functions tier is now
# Turing-complete on wasm (fib loop-form + Collatz, the README's examples).
_LOOP_SRC = """
fn fib(n: Int) -> Int { var a = 0  var b = 1  var i = 0  while (i < n) { let t = a + b  a = b  b = t  i += 1 }  return a }
fn collatz(n: Int) -> Int { var c = 0  var m = n  while (m != 1) { if (m % 2 == 0) { m = m.div_trunc(2) } else { m = 3 * m + 1 }  c += 1 }  return c }
fn sum_demo() -> Int { let xs = [3, 5, 8, 1]  var s = 0  for (x of xs) { s += x }  return s }
fn nested() -> Int { let rows = [2, 3]  var total = 0  for (r of rows) { var k = 0  while (k < r) { total += 1  k += 1 } }  return total }
"""


def test_v3_loops_emit():
    emit = _emitter()
    wat = emit.emit(compile_source(_LOOP_SRC))["functions"]
    assert "(loop" in wat and "(br_if 1)" in wat and "(br 0)" in wat


@_needs_wasmtime
def test_v3_loops_run_on_wasmtime(tmp_path):
    """fib/Collatz (while) and for-of execute on the real substrate — the
    Turing-completeness the README demonstrates, now on wasm too."""
    import subprocess

    emit = _emitter()
    wat_path = tmp_path / "loops.wat"
    wat_path.write_text(emit.emit(compile_source(_LOOP_SRC))["functions"], encoding="utf-8")

    def invoke(fn: str, *args: str) -> int:
        out = subprocess.run(
            ["wasmtime", "--invoke", fn, str(wat_path), *args],
            capture_output=True, text=True, timeout=60,
        )
        assert out.returncode == 0, out.stderr
        return int(out.stdout.strip().splitlines()[-1])

    assert invoke("fib", "10") == 55 and invoke("fib", "20") == 6765
    assert invoke("collatz", "27") == 111
    assert invoke("sum_demo") == 17
    assert invoke("nested") == 5


# `${expr}` templates (Str-typed on this tier) + one v3 function calling
# another (`call $name`).
_STR_TPL_SRC = """
fn greet(s: Str) -> Str { return `hi ${s}` }
fn greet_len() -> Int { let s = "bob"  return greet(s).length() }
"""


def test_v3_str_template_and_intra_call_run_on_wasmtime(tmp_path):
    import subprocess
    _wasmtime_or_fail()
    emit = _emitter()
    wat = tmp_path / "t.wat"
    wat.write_text(emit.emit(compile_source(_STR_TPL_SRC))["functions"], encoding="utf-8")
    out = subprocess.run(["wasmtime", "--invoke", "greet_len", str(wat)],
                         capture_output=True, text=True, timeout=60)
    assert out.returncode == 0, out.stderr
    assert int(out.stdout.strip().splitlines()[-1]) == 6   # "hi bob"


def test_v3_int_interpolation_runs_on_wasmtime(tmp_path):
    """`${intExpr}` stringifies via an itoa helper (`$int_to_str`)."""
    import subprocess
    _wasmtime_or_fail()
    emit = _emitter()
    wat = tmp_path / "i.wat"
    # return each char code of `${n}` so we can assert the exact digits
    wat.write_text(
        emit.emit(compile_source(
            "fn ch(n: Int, i: Int) -> Int { return `${n}`.charCodeAt(i) }\n"
            "fn width(n: Int) -> Int { return `${n}`.length() }\n"
        ))["functions"], encoding="utf-8")

    def inv(fn, *a):
        out = subprocess.run(["wasmtime", "--invoke", fn, str(wat), *a],
                             capture_output=True, text=True, timeout=60)
        assert out.returncode == 0, out.stderr
        return int(out.stdout.strip().splitlines()[-1])

    assert [inv("ch", "12345", str(i)) for i in range(5)] == [ord(c) for c in "12345"]
    assert [inv("ch", "-70", str(i)) for i in range(3)] == [ord(c) for c in "-70"]
    assert inv("width", "0") == 1 and inv("width", "-100") == 4


def test_v3_compound_interpolation_rejected_by_tier():
    emit = _emitter()
    with pytest.raises(emit.EmitError, match="Str or Int on this tier"):
        emit.emit(compile_source("fn f(xs: List[Int]) -> Str { return `xs=${xs}` }"))


# local arrows (`let f = x => …; f(a)`) are inlined — they can't escape this
# tier (no lowerable function type), so no funcref/call_indirect is needed.
_ARROW_SRC = """
fn add_n(n: Int) -> Int { let f = x => x + n  return f(1) }
fn twice() -> Int { let g = x => x * 2  return g(3) + g(10) }
fn capture_by_value() -> Int { var n = 1  let f = y => y + n  n = 100  return f(5) }
"""


def test_v3_local_arrows_run_on_wasmtime(tmp_path):
    import subprocess
    _wasmtime_or_fail()
    emit = _emitter()
    wat = tmp_path / "a.wat"
    wat.write_text(emit.emit(compile_source(_ARROW_SRC))["functions"], encoding="utf-8")

    def invoke(fn: str, *args: str) -> int:
        out = subprocess.run(["wasmtime", "--invoke", fn, str(wat), *args],
                             capture_output=True, text=True, timeout=60)
        assert out.returncode == 0, out.stderr
        return int(out.stdout.strip().splitlines()[-1])

    assert invoke("add_n", "5") == 6
    assert invoke("twice") == 26                 # inlined at two call sites
    assert invoke("capture_by_value") == 6       # snapshots n=1, ignores n=100


def test_v3_escaping_arrow_still_rejected():
    # an arrow can only be inlined if it can't escape; a function-typed param
    # is not lowerable on this tier, so passing an arrow stays rejected
    emit = _emitter()
    with pytest.raises(emit.EmitError, match="not lowerable"):
        emit.emit(compile_source("fn apply(f: Fn[Int, Int], x: Int) -> Int { return f(x) }"))


# ---------------------------------------------------------------------------
# EXECUTED runtime scenarios for the v3 `fn` tier.
#
# The tests above this block that end in `_emit` assert on emitted *text*
# (`assert '(export "add")' in wat`) — they prove the emitter did not raise,
# not that the module computes the right answer. A silent lowering bug (a
# clobbered scratch pointer, an off-by-one memory offset, a mis-dispatched
# tag) sails straight through a string assertion. The scenarios below hand the
# module to wasmtime and assert the COMPUTED RESULT, closing that gap for the
# constructs that previously had emit-string-only or no runtime coverage.
# ---------------------------------------------------------------------------


def test_v3_int_scalar_functions_run_on_wasmtime(tmp_path):
    """Int arithmetic, `if`-return, the `?:` ternary and the `!` Bool operator
    ACTUALLY COMPUTE — previously asserted only as emitted text in
    `test_v3_types_and_int_functions_emit`."""
    invoke = _run_module(tmp_path, """
        fn add(a: Int, b: Int) -> Int { return a + b }
        fn classify(n: Int) -> Int {
          if (n < 0) return 0
          return n === 0 ? 1 : 2
        }
        fn negate(b: Bool) -> Int { return !b ? 1 : 0 }
    """)
    assert invoke("add", 3, 4) == 7 and invoke("add", -8, 8) == 0
    assert invoke("classify", -5) == 0
    assert invoke("classify", 0) == 1
    assert invoke("classify", 9) == 2
    assert invoke("negate", 0) == 1 and invoke("negate", 1) == 0


def test_v3_record_linear_memory_roundtrip_runs_on_wasmtime(tmp_path):
    """A record built in linear memory reads its fields back with the right
    values — construction + field access (Int and Str fields, and a List
    field). `test_v3_str_list_record_functions_emit` only checks the WAT
    string, so a wrong field offset would not be caught there."""
    invoke = _run_module(tmp_path, """
        type Row = { id: Int, name: Str }
        type Bag = { xs: List[Int], n: Int }
        fn make_row(id: Int, name: Str) -> Row { return { id: id, name: name } }
        fn row_id(id: Int) -> Int { let r = make_row(id, "x")  return r.id }
        fn row_name_len() -> Int { let r = { id: 7, name: "abcde" }  return r.name.length() + r.id }
        fn bag_pick(i: Int) -> Int { let b = { xs: [4, 5, 6], n: 2 }  return b.xs[i] + b.n }
    """)
    assert invoke("row_id", 42) == 42
    assert invoke("row_name_len") == 12          # len("abcde")=5 + id 7
    assert invoke("bag_pick", 0) == 6 and invoke("bag_pick", 2) == 8


def test_v3_nested_allocation_does_not_clobber_base_pointer(tmp_path):
    """REGRESSION: a record/list/variant used as a *field, element, or payload*
    of another one used to reuse a single `$__revl_tmp` scratch pointer, so the
    inner allocation overwrote the outer's base pointer mid-construction. The
    emitter did not raise and the emitted text looked plausible — only running
    it revealed the corruption (e.g. `{ inner: { v: 11 }, k: 5 }` returned 1285
    instead of 16). Every construct here allocates inside another; the results
    are exact."""
    invoke = _run_module(tmp_path, """
        type Inner = { v: Int }
        type Outer = { inner: Inner, k: Int }
        type A = { v: Int }
        type B = { a: A, x: Int }
        type C = { b: B, y: Int }
        type T = { p: List[Int], q: Int, r: List[Int] }
        type Rec = { w: Int }
        fn nested_record() -> Int { let o = { inner: { v: 11 }, k: 5 }  return o.inner.v + o.k }
        fn triple_nested() -> Int {
          let c = { b: { a: { v: 1 }, x: 2 }, y: 4 }
          return c.b.a.v * 100 + c.b.x * 10 + c.y
        }
        fn two_alloc_fields() -> Int {
          let t = { p: [1, 2], q: 5, r: [3, 4, 9] }
          return t.p[1] + t.q + t.r[2]
        }
        fn list_of_records() -> Int {
          let rs = [{ w: 2 }, { w: 3 }, { w: 4 }]
          var s = 0  for (rec of rs) { s += rec.w }  return s
        }
    """)
    assert invoke("nested_record") == 16      # was 1285 before the fix
    assert invoke("triple_nested") == 124
    assert invoke("two_alloc_fields") == 16   # 2 + 5 + 9
    assert invoke("list_of_records") == 9     # 2 + 3 + 4, was 13 before the fix


def test_v3_list_linear_memory_roundtrip_runs_on_wasmtime(tmp_path):
    """List literals in linear memory: index, length, and the persistent
    `push`/`concat`/`slice` builtins compute the right values. Only `first`
    had emit-string coverage before; the persistent builtins had none."""
    invoke = _run_module(tmp_path, """
        fn first(xs: List[Int]) -> Int { return xs[0] }
        fn sum3() -> Int { let xs = [10, 20, 30]  return xs[0] + xs[1] + xs[2] }
        fn len4() -> Int { let xs = [1, 2, 3, 4]  return xs.length() }
        fn pushed() -> Int { let xs = [1, 2]  let ys = xs.push(3)  return ys[2] * 10 + ys.length() }
        fn joined() -> Int { let xs = [1, 2]  let ys = [3, 4, 5]  return xs.concat(ys).length() }
        fn sliced() -> Int { let xs = [1, 2, 3, 4]  let ys = xs.slice(1, 3)  return ys[0] * 10 + ys.length() }
    """)
    assert invoke("sum3") == 60
    assert invoke("len4") == 4
    assert invoke("pushed") == 33            # ys[2]==3, len==3
    assert invoke("joined") == 5
    assert invoke("sliced") == 22            # ys[0]==2, len==2


def test_v3_str_builtins_run_on_wasmtime(tmp_path):
    """`length`/`concat`/`charCodeAt`/`charAt`/`slice` and Str `==` compute the
    right values on the linear-memory string model. These had NO runtime
    coverage — only `greet_len` (one `.length()`) and int interpolation did."""
    invoke = _run_module(tmp_path, """
        fn slen() -> Int { let s = "hello"  return s.length() }
        fn cat_len() -> Int { return "foo".concat("bar").length() }
        fn code(i: Int) -> Int { return "ABC".charCodeAt(i) }
        fn char_code() -> Int { return "ABC".charAt(1).charCodeAt(0) }
        fn slice_len() -> Int { return "hello".slice(1, 3).length() }
        fn eq_same() -> Int { return "abcd" == "abcd" ? 1 : 0 }
        fn eq_difflen() -> Int { return "ab" == "abc" ? 1 : 0 }
        fn eq_diff() -> Int { return "abc" == "abd" ? 1 : 0 }
    """)
    assert invoke("slen") == 5
    assert invoke("cat_len") == 6
    assert [invoke("code", i) for i in range(3)] == [ord(c) for c in "ABC"]
    assert invoke("char_code") == ord("B")
    assert invoke("slice_len") == 2
    assert invoke("eq_same") == 1
    assert invoke("eq_difflen") == 0 and invoke("eq_diff") == 0


def test_v3_variant_allocated_payload_runs_on_wasmtime(tmp_path):
    """A user variant whose case carries a RECORD or Str payload: construct,
    `match`, then read a field / length of the payload. This exercises the
    tagged-cell path with an *allocated* payload (the same clobber surface as
    the regression above, from the variant side), which the existing
    `Found(9)`/`Ok(7)`/`Some(5)` runtime cases — all i32 payloads — did not."""
    invoke = _run_module(tmp_path, """
        type Rec = { a: Int, b: Int }
        type Boxed = Box(Rec) | Empty
        type Note = Msg(Str) | Silent
        fn unbox(h: Int) -> Int {
          let w = h == 1 ? Box({ a: 3, b: 4 }) : Empty
          return match w { Box(r) => r.a * 10 + r.b, Empty => 0 }
        }
        fn note_len(h: Int) -> Int {
          let m = h == 1 ? Msg("hello") : Silent
          return match m { Msg(s) => s.length(), Silent => 0 }
        }
    """)
    assert invoke("unbox", 1) == 34 and invoke("unbox", 0) == 0
    assert invoke("note_len", 1) == 5 and invoke("note_len", 0) == 0


def test_v3_nullish_coalesce_runs_on_wasmtime(tmp_path):
    """`a ?? b` reads the Opt tag and takes the payload-or-default at runtime,
    including when the `??` is nested inside a record field (a clobber site).
    `??` had emit coverage in the component tier only."""
    invoke = _run_module(tmp_path, """
        fn pick(some: Int) -> Int { let o = some == 1 ? Some(9) : None  return o ?? 0 }
        fn in_record(some: Int) -> Int {
          let o = some == 1 ? Some(9) : None
          let h = { v: o ?? 0, w: 100 }
          return h.v + h.w
        }
    """)
    assert invoke("pick", 1) == 9 and invoke("pick", 0) == 0
    assert invoke("in_record", 1) == 109 and invoke("in_record", 0) == 100


def test_v3_match_bind_inside_loop_runs_on_wasmtime(tmp_path):
    """REGRESSION: a `match` with a payload binding used as an OPERAND (e.g.
    `s += match x { J(v) => v, K => 100 }`, the natural shape inside a loop)
    raised EmitError "unbound name 'v'". `_infer_type` descended into the arm
    body WITHOUT binding the arm payload, so type inference of the enclosing
    binary/`+=` expression failed even though the construct lowers fine. Now it
    both emits and computes."""
    invoke = _run_module(tmp_path, """
        type V = J(Int) | K
        fn while_sum(n: Int) -> Int {
          var s = 0  var i = 0
          while (i < n) {
            let x = i == 1 ? J(i) : K
            s += match x { J(v) => v, K => 100 }
            i += 1
          }
          return s
        }
        fn for_sum() -> Int {
          let items = [J(2), K, J(5)]
          var s = 0
          for (x of items) { s += match x { J(v) => v, K => 100 } }
          return s
        }
    """)
    assert invoke("while_sum", 3) == 201     # K(100) + J(1) + K(100)
    assert invoke("for_sum") == 107          # 2 + 100 + 5


def test_v3_indexof_rejected_by_tier():
    """DELIBERATE BOUNDARY: `indexOf` is not lowerable on this tier (it needs a
    search loop the i32 model does not spell yet). A boundary that silently
    started emitting would be as much a regression as a miscompile."""
    emit = _emitter()
    with pytest.raises(emit.EmitError, match="indexOf is not lowerable"):
        emit.emit(compile_source('fn f(xs: List[Int]) -> Int { return xs.indexOf(3) }'))


# ---------------------------------------------------------------------------
# `Int` is 64-bit two's complement and overflow TRAPS (docs/arithmetic.md).
#
# This tier was i32 throughout its emitter until the port, which made it the
# narrowest of the six — narrower than the spec, silently. Emitted text cannot
# demonstrate the claim (an `i64.add` proves nothing about the bound), so every
# case below is EXECUTED on wasmtime, and the overflow cases assert that the
# module *traps* rather than returning a wrapped value.
# ---------------------------------------------------------------------------

INT_MAX = 9223372036854775807
INT_MIN = -9223372036854775808

_INT64_SRC = """
fn add(a: Int, b: Int) -> Int { return a + b }
fn sub(a: Int, b: Int) -> Int { return a - b }
fn mul(a: Int, b: Int) -> Int { return a * b }
fn wide() -> Int { return 9007199254740993 - 9007199254740992 }
fn near_max() -> Int { return 9223372036854775807 - 1 }
fn million_squared() -> Int { return 1000000 * 1000000 }
fn in_list(a: Int) -> Int { let xs = [a, 2]  return xs[0] }
fn pushed(a: Int) -> Int { let xs = [1]  return xs.push(a)[1] }
fn in_record(a: Int) -> Int { let r = { v: a, w: 1 }  return r.v }
fn in_opt(a: Int) -> Int { let o = Some(a)  return o ?? 0 }
fn in_loop(a: Int) -> Int { let xs = [a, 0 - 1]  var s = 0  for (x of xs) { s = s + x }  return s }
fn width(n: Int) -> Int { return `${n}`.length() }
fn digit(n: Int, i: Int) -> Int { return `${n}`.charCodeAt(i) }
"""


def _int64_module(tmp_path):
    """Compile `_INT64_SRC` once and return `(invoke, traps)` against it."""
    import subprocess

    _wasmtime_or_fail()
    wat = tmp_path / "int64.wat"
    wat.write_text(_emitter().emit(compile_source(_INT64_SRC))["functions"],
                   encoding="utf-8")

    def run(fn: str, *args):
        return subprocess.run(
            ["wasmtime", "--invoke", fn, str(wat), *[str(a) for a in args]],
            capture_output=True, text=True, timeout=60,
        )

    def invoke(fn: str, *args) -> int:
        out = run(fn, *args)
        assert out.returncode == 0, f"{fn}{args}: {out.stderr}"
        return int(out.stdout.strip().splitlines()[-1])

    def traps(fn: str, *args) -> bool:
        out = run(fn, *args)
        return out.returncode != 0 and "wasm trap" in out.stderr

    return invoke, traps


@_needs_wasmtime
def test_v3_int_is_64_bit_on_wasmtime(tmp_path):
    """The whole 64-bit range round-trips — through parameters, results, list
    elements, record fields, an Opt payload, a for-of binding and itoa. Each of
    those is a place the value crosses a *slot*, which is where a half-done
    widening would show up as a truncated answer rather than an error."""
    invoke, _traps = _int64_module(tmp_path)
    assert invoke("add", INT_MAX - 1, 1) == INT_MAX
    assert invoke("sub", INT_MIN + 1, 1) == INT_MIN
    assert invoke("near_max") == 9223372036854775806
    assert invoke("million_squared") == 1000000000000
    # the value TypeScript cannot represent: exact past 2^53
    assert invoke("wide") == 1
    for carrier in ("in_list", "pushed", "in_record", "in_opt"):
        assert invoke(carrier, INT_MAX) == INT_MAX, carrier
        assert invoke(carrier, INT_MIN) == INT_MIN, carrier
    assert invoke("in_loop", INT_MAX) == INT_MAX - 1
    assert invoke("width", INT_MAX) == 19
    assert invoke("width", INT_MIN) == 20
    rendered = "".join(chr(invoke("digit", INT_MIN, i)) for i in range(20))
    assert rendered == str(INT_MIN)


@_needs_wasmtime
def test_v3_int_overflow_traps_on_wasmtime(tmp_path):
    """A tier that *returns* here has silently wrapped, which is the whole
    thing this guarantee exists to prevent. wasm has no checked arithmetic, so
    the check is emitted and the fault is `unreachable` — a wasm trap."""
    invoke, traps = _int64_module(tmp_path)
    assert traps("add", INT_MAX, 1)
    assert traps("add", INT_MIN, -1)
    assert traps("sub", INT_MIN, 1)
    assert traps("sub", INT_MAX, -1)
    assert traps("mul", INT_MAX, 2)
    assert traps("mul", INT_MIN, -1)
    assert traps("mul", -1, INT_MIN)
    # …and the neighbouring in-range cases still compute, so the check is not
    # simply refusing everything
    assert invoke("mul", 0, INT_MIN) == 0
    assert invoke("mul", 1, INT_MIN) == INT_MIN
    assert invoke("mul", INT_MAX, 1) == INT_MAX


_NAMED_DIVISION_SRC = """
fn div_trunc(a: Int, b: Int) -> Int { return a.div_trunc(b) }
fn div_floor(a: Int, b: Int) -> Int { return a.div_floor(b) }
fn div_euclid(a: Int, b: Int) -> Int { return a.div_euclid(b) }
fn modulo(a: Int, b: Int) -> Int { return a.mod(b) }
fn rem(a: Int, b: Int) -> Int { return a % b }
"""


@_needs_wasmtime
def test_v3_named_integer_arithmetic_runs_on_wasmtime(tmp_path):
    """The table in docs/arithmetic.md, executed at 64 bits — the negatives are
    the point, and so is the pairing law that makes the convention checkable
    rather than a matter of taste."""
    import subprocess

    _wasmtime_or_fail()
    wat = tmp_path / "div.wat"
    wat.write_text(_emitter().emit(compile_source(_NAMED_DIVISION_SRC))["functions"],
                   encoding="utf-8")

    def invoke(fn: str, *args) -> int:
        out = subprocess.run(
            ["wasmtime", "--invoke", fn, str(wat), *[str(a) for a in args]],
            capture_output=True, text=True, timeout=60)
        assert out.returncode == 0, f"{fn}{args}: {out.stderr}"
        return int(out.stdout.strip().splitlines()[-1])

    assert invoke("rem", -7, 3) == -1          # sign of the dividend
    assert invoke("rem", 7, -3) == 1
    assert invoke("rem", -7, -3) == -1
    assert invoke("div_trunc", -7, 2) == -3    # toward zero
    assert invoke("div_trunc", 7, 2) == 3
    assert invoke("div_floor", -7, 2) == -4    # toward -infinity
    assert invoke("div_euclid", -7, 2) == -4
    assert invoke("div_euclid", -7, -2) == 4
    assert invoke("modulo", -7, 3) == 2        # never negative
    assert invoke("modulo", 7, -3) == 1
    assert invoke("modulo", 7, 3) == 1
    # the pairing law, over both signs of both operands
    for a, b in [(7, 3), (-7, 3), (7, -3), (-7, -3), (9, 3), (-9, 3), (1, 7), (-1, 7)]:
        assert invoke("div_trunc", a, b) * b + invoke("rem", a, b) == a, (a, b)
        assert invoke("div_euclid", a, b) * b + invoke("modulo", a, b) == a, (a, b)
    # …and it holds at the top of the range, which an i32 tier could not reach
    assert invoke("div_trunc", INT_MAX, 2) == INT_MAX // 2
    assert invoke("div_floor", INT_MIN, 2) == INT_MIN // 2


@_needs_wasmtime
def test_v3_integer_division_by_zero_faults_on_wasmtime(tmp_path):
    """Integer division has no value at zero, and this tier must fault rather
    than invent one. A *computed* divisor is the only way to reach it — a
    literal zero is refused by the checker."""
    import subprocess

    _wasmtime_or_fail()
    wat = tmp_path / "zero.wat"
    wat.write_text(_emitter().emit(compile_source(_NAMED_DIVISION_SRC))["functions"],
                   encoding="utf-8")
    for fn in ("div_trunc", "div_floor", "div_euclid", "modulo", "rem"):
        out = subprocess.run(["wasmtime", "--invoke", fn, str(wat), "7", "0"],
                             capture_output=True, text=True, timeout=60)
        assert out.returncode != 0 and "wasm trap" in out.stderr, (fn, out.stdout)


@_needs_wasmtime
def test_component_boundary_carries_a_64_bit_int(tmp_path):
    """The coeffect/provision ABI is `Int` too, so it is i64 in and i64 out. A
    boundary left at i32 would truncate exactly where the tier claims to be
    handing a value to another component."""
    import subprocess

    _wasmtime_or_fail()
    wat = tmp_path / "boundary.wat"
    wat.write_text(_emitter().emit(compile_source(
        "service S { fn f(x: Int) -> Int }\n"
        "component C provides s: S { provide s { fn f(x) = x - 1 } }"
    ))["C"], encoding="utf-8")
    assert '(param $p_x i64) (result i64)' in wat.read_text()
    out = subprocess.run(
        ["wasmtime", "--invoke", "provide:s.f", str(wat), str(INT_MAX)],
        capture_output=True, text=True, timeout=60)
    assert out.returncode == 0, out.stderr
    assert int(out.stdout.strip().splitlines()[-1]) == INT_MAX - 1


@_needs_wasmtime
def test_arithmetic_helpers_reach_a_memory_free_component(tmp_path):
    """REGRESSION: the helper functions were gated on the *memory* tokens, so a
    component that called `$int_div_floor` (or, after the port, `$int_add`) but
    never touched linear memory emitted a call to a function the module did not
    define — invalid wasm that no test caught, because nothing executed it."""
    import subprocess

    _wasmtime_or_fail()
    wat = tmp_path / "arith.wat"
    module = _emitter().emit(compile_source(
        "service S { fn f(x: Int) -> Int }\n"
        "component C provides s: S { provide s { fn f(x) = x.div_floor(2) + 1 } }"
    ))["C"]
    assert "(memory" not in module        # still no linear memory
    assert "(func $int_div_floor" in module and "(func $int_add" in module
    wat.write_text(module, encoding="utf-8")
    out = subprocess.run(["wasmtime", "--invoke", "provide:s.f", str(wat), "-7"],
                         capture_output=True, text=True, timeout=60)
    assert out.returncode == 0, out.stderr
    assert int(out.stdout.strip().splitlines()[-1]) == -3     # (-7).div_floor(2) + 1
