"""IR v3 type/function lowering for the cordis-wasm backend.

Run with:
    .venv/bin/pytest backends/wasm/test_v3_emit.py -q
"""

import importlib.util
import sys
from pathlib import Path

import pytest

BACKEND = Path(__file__).resolve().parent
ROOT = BACKEND.parents[1]
sys.path.insert(0, str(ROOT / "src"))

from revl import compile_source  # noqa: E402


def _emitter():
    spec = importlib.util.spec_from_file_location("revl_wasm_emit", BACKEND / "emit.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def test_v3_types_and_int_functions_emit():
    emit = _emitter()
    ir = compile_source(
        """
        type Row = { id: Int, name: Str }
        type Outcome = Ok(Row) | NotFound | Invalid(Str)

        fn add(a: Int, b: Int) -> Int { return a + b }
        fn classify(n: Int) -> Int {
          if (n < 0) return 0
          return n === 0 ? 1 : 2
        }
        fn negate(b: Bool) -> Bool { return !b }
        """
    )
    modules = emit.emit(ir)
    assert set(modules) == {"functions"}
    wat = modules["functions"]
    assert wat.startswith(";; Generated by the revl cordis-wasm backend (ir_version 3)")
    assert "@record Row { id:Int name:Str }" in wat
    assert "@variant Outcome (tagged union layout)" in wat
    assert "case Ok: Row" in wat
    assert 'case NotFound: unit' in wat
    assert 'case Invalid: Str' in wat
    assert '(export "add")' in wat
    assert '(export "classify")' in wat
    assert '(export "negate")' in wat
    assert "(i32.eqz)" in wat


def test_v3_str_list_record_functions_emit():
    emit = _emitter()
    ir = compile_source(
        """
        type Row = { id: Int, name: Str }

        fn name(row: Row) -> Str { return row.name }
        fn first(xs: List[Int]) -> Int { return xs[0] }
        fn greet() -> Str { return "hi" }
        fn make_row(id: Int, name: Str) -> Row { return { id: id, name: name } }
        """
    )
    modules = emit.emit(ir)
    assert set(modules) == {"functions"}
    wat = modules["functions"]
    assert '(export "name")' in wat
    assert '(export "first")' in wat
    assert '(export "greet")' in wat
    assert '(export "make_row")' in wat
    assert "(i32.load (i32.add (local.get $p_row) (i32.const 4)))" in wat
    assert "(i32.load (i32.add (local.get $p_xs) (i32.const 4)))" in wat
    assert '  (data (i32.const 0) "\\02\\00\\00\\00hi")' in wat


def test_v3_functions_golden_is_byte_identical():
    emit = _emitter()
    ir = compile_source(
        """
        type Row = { id: Int, name: Str }
        type Outcome = Ok(Row) | NotFound | Invalid(Str)

        fn add(a: Int, b: Int) -> Int { return a + b }
        fn negate(b: Bool) -> Bool { return !b }
        fn name(row: Row) -> Str { return row.name }
        fn first(xs: List[Int]) -> Int { return xs[0] }
        fn greet() -> Str { return "hi" }
        fn make_row(id: Int, name: Str) -> Row { return { id: id, name: name } }
        fn classify(n: Int) -> Str {
          if (n < 0) return "neg"
          return "pos"
        }
        """
    )
    wat = emit.emit(ir)["functions"]
    golden = (BACKEND / "golden" / "functions.wat").read_text()
    assert wat == golden


def test_version_gate_accepts_1_2_3_and_rejects_4():
    emit = _emitter()
    base = {
        "services": {"Svc": {"methods": {"ping": {"params": [], "returns": None, "emission": False}}}},
        "components": [
            {
                "name": "C",
                "config": [],
                "requires": {},
                "provides": {},
                "body": [],
            }
        ],
    }
    emit.emit({**base, "ir_version": 1})
    emit.emit({**base, "ir_version": 2})
    emit.emit({**base, "ir_version": 3, "types": {}, "functions": [], "externs": [], "tests": []})
    with pytest.raises(emit.EmitError, match="ir_version"):
        emit.emit({**base, "ir_version": 4})


def test_v3_externs_and_tests_are_documented_not_rejected():
    emit = _emitter()
    ir = compile_source(
        """
        extern pure fn host_call() -> Int = @py { return 1 }
        test "would run on a hosted backend" { assert true }
        """
    )
    modules = emit.emit(ir)
    assert "functions" in modules
    wat = modules["functions"]
    assert "unsupported on this tier: externs host_call" in wat
    assert "unsupported on this tier: tests 'would run on a hosted backend'" in wat


# tagged unions (user variants, Result, Opt) lower to [i32 tag][i32 payload]
# in linear memory; match dispatches on the tag.
_ADT_SRC = """
type O = Found(Int) | Missing
fn mk_u(h: Bool) -> Int { let o = h ? Found(9) : Missing  return match o { Found(v) => v, Missing => 0 } }
fn r_d(ok: Bool) -> Int { let x = ok ? Ok(7) : Err(1)  return match x { Ok(v) => v, Err(e) => 0 - e } }
fn opt_or(some: Bool) -> Int { let x = some ? Some(5) : None  return match x { Some(v) => v, None => 0 } }
"""


def test_v3_variant_result_opt_emit():
    emit = _emitter()
    wat = emit.emit(compile_source(_ADT_SRC))["functions"]
    # construction: alloc 8, store tag + payload
    assert "(call $alloc (i32.const 8))" in wat
    assert "(i32.store (local.get $__revl_tmp) (i32.const 0))" in wat  # a tag store
    # match: dispatch on the loaded tag
    assert "(i32.eq (i32.load (local.get $msc_1)) (i32.const" in wat


@pytest.mark.skipif(__import__("shutil").which("wasmtime") is None, reason="wasmtime not installed")
def test_v3_variant_result_opt_run_on_wasmtime(tmp_path):
    """Not just emitted — construct + match execute on the real substrate:
    user variants, Result (Ok/Err discriminated), and Opt."""
    import subprocess

    emit = _emitter()
    wat_path = tmp_path / "adt.wat"
    wat_path.write_text(emit.emit(compile_source(_ADT_SRC))["functions"], encoding="utf-8")

    def invoke(fn: str, arg: str) -> int:
        out = subprocess.run(
            ["wasmtime", "--invoke", fn, str(wat_path), arg],
            capture_output=True, text=True, timeout=60,
        )
        assert out.returncode == 0, out.stderr
        return int(out.stdout.strip().splitlines()[-1])

    assert invoke("mk_u", "1") == 9 and invoke("mk_u", "0") == 0
    assert invoke("r_d", "1") == 7 and invoke("r_d", "0") == -1   # Ok vs Err
    assert invoke("opt_or", "1") == 5 and invoke("opt_or", "0") == 0


# `while` / `for` lower to native wasm loops — the functions tier is now
# Turing-complete on wasm (fib loop-form + Collatz, the README's examples).
_LOOP_SRC = """
fn fib(n: Int) -> Int { var a = 0  var b = 1  var i = 0  while (i < n) { let t = a + b  a = b  b = t  i += 1 }  return a }
fn collatz(n: Int) -> Int { var c = 0  var m = n  while (m != 1) { if (m % 2 == 0) { m = m / 2 } else { m = 3 * m + 1 }  c += 1 }  return c }
fn sum_demo() -> Int { let xs = [3, 5, 8, 1]  var s = 0  for (x of xs) { s += x }  return s }
fn nested() -> Int { let rows = [2, 3]  var total = 0  for (r of rows) { var k = 0  while (k < r) { total += 1  k += 1 } }  return total }
"""


def test_v3_loops_emit():
    emit = _emitter()
    wat = emit.emit(compile_source(_LOOP_SRC))["functions"]
    assert "(loop" in wat and "(br_if 1)" in wat and "(br 0)" in wat


@pytest.mark.skipif(__import__("shutil").which("wasmtime") is None, reason="wasmtime not installed")
def test_v3_loops_run_on_wasmtime(tmp_path):
    """fib/Collatz (while) and for-of execute on the real substrate — the
    Turing-completeness the README demonstrates, now on wasm too."""
    import subprocess

    emit = _emitter()
    wat_path = tmp_path / "loops.wat"
    wat_path.write_text(emit.emit(compile_source(_LOOP_SRC))["functions"], encoding="utf-8")

    def invoke(fn: str, *args: str) -> int:
        out = subprocess.run(
            ["wasmtime", "--invoke", fn, str(wat_path), *args],
            capture_output=True, text=True, timeout=60,
        )
        assert out.returncode == 0, out.stderr
        return int(out.stdout.strip().splitlines()[-1])

    assert invoke("fib", "10") == 55 and invoke("fib", "20") == 6765
    assert invoke("collatz", "27") == 111
    assert invoke("sum_demo") == 17
    assert invoke("nested") == 5


# `${expr}` templates (Str-typed on this tier) + one v3 function calling
# another (`call $name`).
_STR_TPL_SRC = """
fn greet(s: Str) -> Str { return `hi ${s}` }
fn greet_len() -> Int { let s = "bob"  return greet(s).length() }
"""


def test_v3_str_template_and_intra_call_run_on_wasmtime(tmp_path):
    import shutil, subprocess
    if shutil.which("wasmtime") is None:
        import pytest as _pt
        _pt.skip("wasmtime not installed")
    emit = _emitter()
    wat = tmp_path / "t.wat"
    wat.write_text(emit.emit(compile_source(_STR_TPL_SRC))["functions"], encoding="utf-8")
    out = subprocess.run(["wasmtime", "--invoke", "greet_len", str(wat)],
                         capture_output=True, text=True, timeout=60)
    assert out.returncode == 0, out.stderr
    assert int(out.stdout.strip().splitlines()[-1]) == 6   # "hi bob"


def test_v3_non_str_interpolation_rejected_by_tier():
    emit = _emitter()
    with pytest.raises(emit.EmitError, match="Str only on this tier"):
        emit.emit(compile_source("fn f(n: Int) -> Str { return `n=${n}` }"))


# local arrows (`let f = x => …; f(a)`) are inlined — they can't escape this
# tier (no lowerable function type), so no funcref/call_indirect is needed.
_ARROW_SRC = """
fn add_n(n: Int) -> Int { let f = x => x + n  return f(1) }
fn twice() -> Int { let g = x => x * 2  return g(3) + g(10) }
fn capture_by_value() -> Int { var n = 1  let f = y => y + n  n = 100  return f(5) }
"""


def test_v3_local_arrows_run_on_wasmtime(tmp_path):
    import shutil, subprocess
    if shutil.which("wasmtime") is None:
        import pytest as _pt
        _pt.skip("wasmtime not installed")
    emit = _emitter()
    wat = tmp_path / "a.wat"
    wat.write_text(emit.emit(compile_source(_ARROW_SRC))["functions"], encoding="utf-8")

    def invoke(fn: str, *args: str) -> int:
        out = subprocess.run(["wasmtime", "--invoke", fn, str(wat), *args],
                             capture_output=True, text=True, timeout=60)
        assert out.returncode == 0, out.stderr
        return int(out.stdout.strip().splitlines()[-1])

    assert invoke("add_n", "5") == 6
    assert invoke("twice") == 26                 # inlined at two call sites
    assert invoke("capture_by_value") == 6       # snapshots n=1, ignores n=100


def test_v3_escaping_arrow_still_rejected():
    # an arrow can only be inlined if it can't escape; a function-typed param
    # is not lowerable on this tier, so passing an arrow stays rejected
    emit = _emitter()
    with pytest.raises(emit.EmitError, match="not lowerable"):
        emit.emit(compile_source("fn apply(f: Fn[Int, Int], x: Int) -> Int { return f(x) }"))
