"""The IR-boundary cross-tier drift gate (roadmap item 479).

A staged IR document re-entering a gate is where a gate-crate / frontend SKEW
goes undetected: an unknown top-level field, or an unrecognised schema revision,
that one tier silently ignores while the other refuses is a wave-through of an
unaccounted-for member. The Python frontend refuses BY NAME
(`revl.compiler._refuse_unknown_ir_fields` / `_refuse_unknown_schema_revision`);
`crates/revl-gate`'s `ir` module is the rust mirror. This file is the gate that
holds the TWO TIERS to the same known-field / known-revision sets AND to the
same refusal message for the same input.

It needs no rust toolchain: the crate's IR module carries the known sets and the
message wording as GENERATED bytes derived from the reference frontend, so this
test compares the frontend's own tables and messages against those generated
bytes. The half that actually runs the rust refusal is
`crates/revl-gate/tests/ir.rs` (`cargo test`); a green here means the two tiers
are built from the same sets and worded identically, and a green there means the
rust tier really refuses. Both are needed and neither is skippable-and-green.
"""

from __future__ import annotations

import importlib.util
import json
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
CRATE = ROOT / "crates" / "revl-gate"
IR_RS = CRATE / "src" / "ir.rs"

sys.path.insert(0, str(ROOT / "src"))

from revl.compiler import (  # noqa: E402
    _refuse_unknown_ir_fields,
    _refuse_unknown_schema_revision,
)
from revl.errors import RevlError  # noqa: E402
from revl.lower import IR_SCHEMA_REVISIONS, IR_TOPLEVEL_FIELDS  # noqa: E402


def _generator():
    path = ROOT / "tools" / "build_gate_crate.py"
    spec = importlib.util.spec_from_file_location("revl_build_gate_crate_ir", path)
    module = importlib.util.module_from_spec(spec)
    sys.modules["revl_build_gate_crate_ir"] = module
    spec.loader.exec_module(module)
    return module


GEN = _generator()


# ---------------------------------------------------- the sets are one surface


def test_the_generator_reads_the_known_sets_from_the_frontend():
    """`ir_tables()` is the frontend's own `IR_TOPLEVEL_FIELDS` /
    `IR_SCHEMA_REVISIONS`, sorted — not a hand-listed copy that could drift."""
    tables = GEN.ir_tables()
    assert tables["fields"] == sorted(IR_TOPLEVEL_FIELDS)
    assert tables["revisions"] == sorted(IR_SCHEMA_REVISIONS)


def test_the_crate_known_fields_equal_the_frontend_surface():
    """The rust `KNOWN_IR_FIELDS` array carries exactly the frontend's known
    top-level fields, in sorted order. A field added to `IR_TOPLEVEL_FIELDS`
    without regenerating the crate reds this (and the byte drift gate)."""
    ir_rs = IR_RS.read_text(encoding="utf-8")
    for field in sorted(IR_TOPLEVEL_FIELDS):
        assert f'    "{field}",' in ir_rs, f"crate is missing known field {field!r}"
    # and no EXTRA field the frontend does not know
    array = ir_rs.split("pub const KNOWN_IR_FIELDS: &[&str] = &[", 1)[1].split("];", 1)[0]
    listed = {line.strip().strip(',').strip('"') for line in array.splitlines() if line.strip()}
    assert listed == set(IR_TOPLEVEL_FIELDS), (
        "crate KNOWN_IR_FIELDS and revl.lower.IR_TOPLEVEL_FIELDS disagree: "
        f"{listed ^ set(IR_TOPLEVEL_FIELDS)}")


def test_the_crate_known_revisions_equal_the_frontend_set():
    ir_rs = IR_RS.read_text(encoding="utf-8")
    array = ir_rs.split("pub const KNOWN_IR_REVISIONS: &[i64] = &[", 1)[1].split("];", 1)[0]
    listed = {int(line.strip().strip(',')) for line in array.splitlines() if line.strip()}
    assert listed == set(IR_SCHEMA_REVISIONS)


def test_the_provenance_records_the_ir_surface():
    meta = json.loads((CRATE / "GENERATED.json").read_text(encoding="utf-8"))
    assert meta["ir_toplevel_fields"] == sorted(IR_TOPLEVEL_FIELDS)
    assert meta["ir_schema_revisions"] == sorted(IR_SCHEMA_REVISIONS)


# ------------------------------------- both tiers refuse the same shape, worded
#                                        identically
#
# The Python message is produced by the real frontend functions. The rust
# message is produced by `format!(<literal>, ...)` in the generated ir.rs. These
# helpers rebuild what that `format!` yields from the SAME literal the crate
# ships (asserted present below), so an assertion that the two are equal is an
# assertion that the two tiers say the same thing for the same input.

FIELD_LITERAL = (
    "staged IR carries unknown top-level field{} {}; this frontend refuses an "
    "IR document with a field it does not know rather than ignoring it (known "
    "fields: {})")
REVISION_LITERAL = (
    "staged IR declares unknown schema revision `ir_version` {}; this frontend "
    "refuses an IR document at a revision it does not know rather than decoding "
    "it under the wrong one (known revisions: {})")


def test_the_message_wording_is_carried_verbatim_in_the_crate():
    """The exact rust format literals are in ir.rs, so the message this test
    reconstructs is the one the crate actually emits."""
    ir_rs = IR_RS.read_text(encoding="utf-8")
    assert FIELD_LITERAL in ir_rs, "the crate's unknown-field message wording changed"
    assert REVISION_LITERAL in ir_rs, "the crate's unknown-revision message wording changed"


def _py_field_message(manifest: dict) -> str:
    try:
        _refuse_unknown_ir_fields(manifest, "<doc>")
    except RevlError as err:
        return err.message
    raise AssertionError(f"the Python frontend did not refuse {manifest!r}")


def _py_revision_message(manifest: dict) -> str:
    try:
        _refuse_unknown_schema_revision(manifest, "<doc>")
    except RevlError as err:
        return err.message
    raise AssertionError(f"the Python frontend did not refuse {manifest!r}")


def _rust_field_message(unknown: list[str]) -> str:
    unknown = sorted(unknown)
    named = ", ".join(f"`{field}`" for field in unknown)
    plural = "s" if len(unknown) > 1 else ""
    known = ", ".join(sorted(IR_TOPLEVEL_FIELDS))
    return FIELD_LITERAL.format(plural, named, known)


def _rust_revision_message(revision: int) -> str:
    known = ", ".join(str(rev) for rev in sorted(IR_SCHEMA_REVISIONS))
    return REVISION_LITERAL.format(revision, known)


@pytest.mark.parametrize("unknown", [
    ["wobble"],
    ["surprise"],
    ["alpha", "zebra"],
    ["a", "b", "c"],
])
def test_both_tiers_refuse_the_same_unknown_field_shape_identically(unknown):
    manifest = {"ir_version": 3, "services": {}}
    for field in unknown:
        manifest[field] = 1
    py = _py_field_message(manifest)
    rust = _rust_field_message(unknown)
    assert py == rust, f"tiers disagree:\n py:   {py}\n rust: {rust}"
    # and the refusal names every offending field
    for field in unknown:
        assert f"`{field}`" in py


@pytest.mark.parametrize("revision", [7, 99, 0, 4])
def test_both_tiers_refuse_the_same_unknown_revision_identically(revision):
    assert revision not in IR_SCHEMA_REVISIONS
    manifest = {"ir_version": revision}
    py = _py_revision_message(manifest)
    rust = _rust_revision_message(revision)
    assert py == rust, f"tiers disagree:\n py:   {py}\n rust: {rust}"


def test_both_tiers_accept_a_known_revision_and_a_missing_one():
    # a present-known revision, a missing one, and an explicit None all pass on
    # the Python side; the rust `check_ir_boundary` mirrors each (see ir.rs
    # tests). Nothing to refuse here — the guard is the negative of the above.
    for rev in sorted(IR_SCHEMA_REVISIONS):
        _refuse_unknown_schema_revision({"ir_version": rev}, "<doc>")
    _refuse_unknown_schema_revision({}, "<doc>")
    _refuse_unknown_schema_revision({"ir_version": None}, "<doc>")
