"""The `crates/revl-gate-wasm` drift gate (roadmap item 335, slice 1).

`crates/revl-gate-wasm` is a COMMITTED generated artifact, for the same reason
`crates/revl-gate` is: the component must build on a machine with no Python at
all. The cost of committing generated bytes is that they can go stale, so drift
is killed the way `docs/conformance.md` kills it — regenerate from the same tree
and fail on any byte difference.

What that buys here specifically: the wasm shim inherits its frontier id, its
language version and its covered-layer sentence from `crates/revl-gate`'s
provenance rather than restating them, so regenerating the rust crate (which the
self-host sources and the rust emitter already force) changes these bytes too,
and a wasm gate whose version surface lies about what it covers cannot land.

No cargo, no wasm target, no `wasm-tools`: this is a pure regenerate-and-compare
and runs on every machine. The half that needs a wasm toolchain lives in
`tests/test_gate_wasm_vector.py` behind the toolchain-honesty skip.
"""

from __future__ import annotations

import importlib.util
import json
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
CRATE = ROOT / "crates" / "revl-gate-wasm"
GATE_CRATE = ROOT / "crates" / "revl-gate"


def _generator():
    """Load `tools/build_gate_wasm.py` by path, the way the backends' own tests
    load their emitters, so the test exercises the file under comparison."""
    path = ROOT / "tools" / "build_gate_wasm.py"
    spec = importlib.util.spec_from_file_location("revl_build_gate_wasm", path)
    module = importlib.util.module_from_spec(spec)
    sys.modules["revl_build_gate_wasm"] = module
    spec.loader.exec_module(module)
    return module


GEN = _generator()


def _meta() -> dict:
    return json.loads((CRATE / "GENERATED.json").read_text(encoding="utf-8"))


# ------------------------------------------------------------------- drift


def test_the_committed_crate_matches_a_fresh_generation():
    """The gate itself. Regenerate `crates/revl-gate-wasm` from this tree and
    compare byte for byte; any difference is drift and drift is a red.

    If this fails: `python3 tools/build_gate_wasm.py`, then re-run.
    """
    problems = GEN.drift(CRATE)
    assert not problems, (
        "crates/revl-gate-wasm has drifted from the sources it is generated "
        "from:\n  " + "\n  ".join(problems)
        + "\n\nRegenerate with: python3 tools/build_gate_wasm.py")


def test_generation_is_deterministic():
    """Two generations of the same tree produce the same bytes. Without this the
    drift gate would be a coin flip rather than a gate."""
    first = GEN.build()
    second = GEN.build()
    assert first.keys() == second.keys()
    for rel in first:
        assert first[rel] == second[rel], f"{rel} is not deterministic"


@pytest.mark.parametrize("relpath", [
    "Cargo.toml", "GENERATED.json", "README.md", ".gitignore",
    "src/lib.rs", "wit/gate.wit",
])
def test_every_generated_file_is_committed(relpath):
    assert (CRATE / relpath).is_file(), f"crates/revl-gate-wasm/{relpath} is missing"


# -------------------------------------------------------------- provenance


def test_provenance_records_what_the_component_was_built_from():
    meta = _meta()
    assert meta["generator"] == "tools/build_gate_wasm.py"
    assert meta["wraps"] == "crates/revl-gate"
    assert meta["source_digest"] == GEN.source_digest()
    assert meta["layer"].startswith("1 ")
    for rel in meta["digest_inputs"]:
        assert (ROOT / rel).is_file(), f"digest input {rel} does not exist"


def test_the_version_surface_is_inherited_from_the_rust_crate_not_restated():
    """The wasm gate decides EXACTLY what `crates/revl-gate` decides, so its
    frontier id, language version and covered layer are that crate's, read from
    its provenance. A restated copy would be free to drift into a component
    whose `gate-version` claims coverage it does not have — and a stale edge
    gate lying about its own frontier is precisely the skew failure mode item
    335 exists to make detectable."""
    meta = _meta()
    crate = json.loads((GATE_CRATE / "GENERATED.json").read_text(encoding="utf-8"))
    assert meta["frontier"] == crate["frontier"]
    assert meta["language_version"] == crate["language_version"]
    assert meta["covered_layer"] == crate["covered_layer"]
    assert "crates/revl-gate/GENERATED.json" in meta["digest_inputs"], (
        "the rust crate's provenance must be a digest input, or regenerating it "
        "would not red this crate's drift gate")


def test_the_gate_api_semver_is_one_surface_across_wheel_crate_and_component():
    """`revl.gate`, `crates/revl-gate` and `crates/revl-gate-wasm` are three
    spellings of ONE surface, so their `api` semver is one value. The generator
    refuses to run when they disagree; this pins the promise in the suite too."""
    from revl.gate import GATE_API_VERSION

    crate = json.loads((GATE_CRATE / "GENERATED.json").read_text(encoding="utf-8"))
    assert GEN.GATE_API_VERSION == GATE_API_VERSION
    assert crate["gate_api_version"] == GATE_API_VERSION
    assert _meta()["gate_api_version"] == GATE_API_VERSION
    assert f"@{GATE_API_VERSION}" in GEN.WIT_PACKAGE, (
        "the WIT package version tracks the gate SURFACE semver")


# ------------------------------------------- the shape the component ships


def test_the_world_imports_nothing():
    """The design's headline soundness mechanism, held at the source: the world
    imports no clock, no filesystem, no random, no host function, so a verdict
    is a total, deterministic function of its arguments.

    This is the SOURCE half of the property. The half that reads the built
    artifact's own import section lives in `test_gate_wasm_vector.py`, which is
    where it is actually proven; a WIT with no `import` cannot be the whole
    proof because the toolchain can add imports of its own (which is exactly why
    the build target is not `wasm32-wasip2`).
    """
    wit = (CRATE / "wit" / "gate.wit").read_text(encoding="utf-8")
    # `imports: list<string>` is a PARAMETER of `admit-artifact`, not an import
    # of the world, so the check is on the declaration keyword.
    declared = [line for line in wit.splitlines()
                if not line.strip().startswith("//")
                and line.strip().split(" ")[0] == "import"]
    assert not declared, ("the gate world must import nothing:\n"
                          + "\n".join(declared))
    assert _meta()["empty_imports"] is True


def test_the_component_ships_no_admission_at_all():
    """The security clause, pinned in source.

    The wasm gate is `crates/revl-gate` packaged, and that gate decides the
    composition/guarantee layer and NOT the reference type layer, so it has no
    admission to give. The shim closes the false-admit direction structurally:
    `admitted` is written as the literal `false` at every construction site, and
    there is no expression anywhere that could set it from a verdict.
    """
    lib_rs = (CRATE / "src" / "lib.rs").read_text(encoding="utf-8")
    code = "\n".join(line for line in lib_rs.splitlines()
                     if not line.lstrip().startswith(("//!", "///", "//")))
    assert "admitted: false," in code
    assert "admitted: true" not in code, (
        "the shim must never construct an admitted verdict: the gate it wraps "
        "cannot issue one")
    # every `admitted:` in the shim is the literal false — no computed flag
    flags = [line.strip() for line in code.splitlines() if "admitted:" in line]
    assert flags and all(line == "admitted: false," for line in flags), flags
    assert _meta()["issues_admissions"] is False
    assert _meta()["verdict_kinds"] == ["refused", "no-objection",
                                        "outside-frontier"]


def test_admit_artifact_is_exported_and_fails_closed():
    """Design cut B is exported so its arrival is additive, and it DECLINES
    rather than guesses. The item-289 chain's middle set (the declared caps) is
    the G8 boundary projection, which the reference derives with a whole-IR
    reachability walk that has no native port; a shim that guessed it would be
    the wave-through this arc exists to prevent."""
    wit = (CRATE / "wit" / "gate.wit").read_text(encoding="utf-8")
    assert "export admit-artifact: func(ir: string, policy: string," in wit
    lib_rs = (CRATE / "src" / "lib.rs").read_text(encoding="utf-8")
    assert "fn admit_artifact(" in lib_rs
    assert "admit-artifact" in _meta()["unavailable_exports"]


def test_the_covered_layer_is_stated_identically_everywhere():
    """One sentence saying what this gate decides, stamped into the WIT docs,
    the README and the provenance from the rust crate's provenance, so no two
    of them can disagree."""
    meta = _meta()
    assert meta["covered_layer"] == GEN.covered_layer()
    assert "NOT the reference type layer" in meta["covered_layer"]
    readme = (CRATE / "README.md").read_text(encoding="utf-8")
    assert meta["covered_layer"] in readme
    assert "This gate issues no admissions" in readme


def test_the_binding_generator_is_pinned_exactly():
    """`wit-bindgen` writes the `component-type` custom section that
    `wasm-tools component new` reads, so it decides the artifact's shape. An
    unpinned bump could change the component under a drift gate that only
    watches source, so the dependency carries an `=` requirement."""
    cargo = (CRATE / "Cargo.toml").read_text(encoding="utf-8")
    assert f'wit-bindgen = "={GEN.WIT_BINDGEN_REQ}"' in cargo
    assert _meta()["wit_bindgen"] == GEN.WIT_BINDGEN_REQ


def test_the_target_is_the_one_with_an_empty_import_section():
    """`wasm32-wasip2` links the WASI world into every artifact through std, so
    on it the import section is not empty. The empty-import property is the
    load-bearing one (it is what makes a verdict provably a function of its
    arguments), so the target is `wasm32-unknown-unknown` and the crate says
    why."""
    assert GEN.WASM_TARGET == "wasm32-unknown-unknown"
    assert _meta()["target"] == GEN.WASM_TARGET
    readme = (CRATE / "README.md").read_text(encoding="utf-8")
    assert "wasm32-wasip2" in readme, (
        "the README must say why the obvious target was not the one chosen")
