"""The `crates/revl-gate` drift gate (roadmap item 332, Stage 3).

`crates/revl-gate` is a COMMITTED generated artifact. It has to be committed —
the crate must build on a machine with no Python at all, or item 336 (a single
rust binary shipping the compiler) and item 338 (`cargo add revl`) do not exist.
The cost of committing generated bytes is that they can go stale, so drift is
killed the way `docs/conformance.md` kills it: regenerate from the same tree and
fail on any byte difference.

That gives the frontier tables their teeth. The crate's fail-closed table is
DERIVED (`revl.lexer.KEYWORDS` minus the self-host lexer's keywords;
`revl.typecheck._BUILTIN_SIG` minus the self-host lowering's builtins), so a
reference-side construct added without a self-host port changes the generated
bytes — and this test is what makes that change impossible to land unnoticed.

No cargo needed: this is a pure regenerate-and-compare, so it runs on every
machine, toolchain or not. The half that needs a rust toolchain lives in
`tests/test_gate_crate_admit.py` behind the toolchain-honesty skip.
"""

from __future__ import annotations

import importlib.util
import json
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
CRATE = ROOT / "crates" / "revl-gate"


def _generator():
    """Load `tools/build_gate_crate.py` by path, the way the backends' own tests
    load their emitters, so the test exercises the file under comparison."""
    path = ROOT / "tools" / "build_gate_crate.py"
    spec = importlib.util.spec_from_file_location("revl_build_gate_crate", path)
    module = importlib.util.module_from_spec(spec)
    sys.modules["revl_build_gate_crate"] = module
    spec.loader.exec_module(module)
    return module


GEN = _generator()


# ------------------------------------------------------------------- drift


def test_the_committed_crate_matches_a_fresh_generation():
    """The gate itself. Regenerate `crates/revl-gate` from this tree and compare
    byte for byte; any difference is drift and drift is a red.

    If this fails: `python3 tools/build_gate_crate.py`, then re-run.
    """
    problems = GEN.drift(CRATE)
    assert not problems, (
        "crates/revl-gate has drifted from the sources it is generated from "
        "(fix: `python3 tools/regen_goldens.py gate-crate`, equivalently "
        "`python3 tools/build_gate_crate.py`, then review and commit the diff — "
        "the crate embeds emitted rust, so ANY backends/rust/emit.py or "
        "selfhost/*.rvl change rewrites it):\n  "
        + "\n  ".join(problems)
        + "\n\nRegenerate with: python3 tools/build_gate_crate.py")


def test_generation_is_deterministic():
    """Two generations of the same tree produce the same bytes. Without this the
    drift gate would be a coin flip rather than a gate."""
    first = GEN.build()
    second = GEN.build()
    assert first.keys() == second.keys()
    for rel in first:
        assert first[rel] == second[rel], f"{rel} is not deterministic"


# -------------------------------------------------------------- provenance


def test_provenance_records_what_the_crate_was_built_from():
    """`GENERATED.json` is the crate's provenance: the digest inputs, the
    self-host closure it was emitted from, and the frontier id it stamps. A
    consumer (and item 337's seam re-admission) reads the frontier id to detect
    that two gates cover different surfaces before trusting their agreement."""
    meta = json.loads((CRATE / "GENERATED.json").read_text(encoding="utf-8"))
    assert meta["generator"] == "tools/build_gate_crate.py"
    assert meta["selfhost_root"] == "selfhost/lower.rvl"
    assert meta["layer"].startswith("1 ")
    assert meta["frontier"] == f"selfhost-admit:{meta['source_digest'][:16]}"
    assert meta["source_digest"] == GEN.source_digest()
    # every digest input is a real file, or the digest is measuring nothing
    for rel in meta["digest_inputs"]:
        assert (ROOT / rel).is_file(), f"digest input {rel} does not exist"


def test_the_frontier_table_is_derived_not_hand_written():
    """The committed table equals the difference the generator computes from the
    two compilers' own tables. A hand-edited crate fails here as well as at the
    drift gate."""
    meta = json.loads((CRATE / "GENERATED.json").read_text(encoding="utf-8"))
    tables = GEN.frontier_tables()
    assert meta["frontier_excluded_keywords"] == tables["keywords"]
    assert meta["frontier_excluded_builtins"] == tables["builtins"]
    # And the rust source carries the same list, in the same order.
    frontier_rs = (CRATE / "src" / "frontier.rs").read_text(encoding="utf-8")
    for name in tables["builtins"]:
        assert f'    "{name}",' in frontier_rs


def test_the_gate_api_semver_is_one_surface_across_wheel_and_crate():
    """`revl.gate` and the crate are two spellings of ONE surface, so their
    `api` semver is one value. The generator refuses to run when they disagree;
    this pins the promise in the suite too."""
    from revl.gate import GATE_API_VERSION

    assert GEN.GATE_API_VERSION == GATE_API_VERSION
    lib_rs = (CRATE / "src" / "lib.rs").read_text(encoding="utf-8")
    assert f'pub const GATE_API_VERSION: &str = "{GATE_API_VERSION}";' in lib_rs


# ------------------------------------------------- the shape the crate ships


def test_the_crate_is_admit_only_and_says_so():
    """Stage 3 is admit-only. `compile_to` is exported but fails closed (Stage
    4), `admit_into` does not exist at all (manifest-spanning admission has no
    self-host path, and a stub that ignored the manifest would be the exact
    wave-through the crate exists to prevent), and layer 2 is a reserved empty
    module (item 334)."""
    lib_rs = (CRATE / "src" / "lib.rs").read_text(encoding="utf-8")
    assert "pub fn admit(source: &str) -> Verdict" in lib_rs
    assert "pub fn compile_to(" in lib_rs
    assert "fn admit_into" not in lib_rs, (
        "the crate must not ship an `admit_into`: there is no manifest-spanning "
        "admission on the self-host path and a fake one would wave programs "
        "through")
    assert "pub mod session;" in lib_rs
    session_rs = (CRATE / "src" / "session.rs").read_text(encoding="utf-8")
    # reserved means documented and EMPTY — no item, not even a stub type
    assert all(line.startswith("//!") or not line.strip()
               for line in session_rs.splitlines()), \
        "session.rs must stay a reserved, empty module until item 334"


def test_the_crate_ships_no_admission_at_all():
    """The security clause, pinned in source.

    `selfhost/lower.rvl`'s `admit_src` decides the composition/guarantee layer
    (G1..G4, A1, PRELUDE, BAD) and runs NO type layer, so a non-refusal from it
    can never mean "the reference would admit this"
    (`tests/test_gate_crate_admit.py::TYPE_LAYER_GAP` measures it). The crate
    closes the false-admit direction structurally rather than by discipline:
    there is no `Admitted` arm, no `is_admitted()`, and the wire shape says
    `admitted: false` on every arm.
    """
    lib_rs = (CRATE / "src" / "lib.rs").read_text(encoding="utf-8")
    # doc comments explain at length why the arm is absent; the CODE is what
    # must not have it.
    code = "\n".join(line for line in lib_rs.splitlines()
                     if not line.lstrip().startswith(("//!", "///", "//")))
    assert "OutsideFrontier { reason: String }" in code
    assert "NoObjection," in code
    assert "Verdict::Admitted" not in code, (
        "the crate must not have an `Admitted` arm: this gate does not run the "
        "reference type layer, so it cannot issue an admission")
    assert "fn is_admitted" not in code, (
        "no `is_admitted()` — a caller must not be able to ask this gate for an "
        "admission it cannot give")
    assert r'",\"admitted\":false,\"code\":"' in code, (
        "`to_json` must report `admitted: false` on every arm, so a consumer of "
        "the fixed {admitted, code, message} shape fails closed")
    assert "catch_unwind" in code, \
        "a native gate abort must become OutsideFrontier, never a verdict"


def test_the_navigation_surface_issues_no_verdict_and_is_versioned_apart():
    """`revl_gate::symbols` (item 336 slice 2) answers WHERE a declaration is,
    never WHETHER a program may run.

    Two things are pinned here because both are load-bearing. It ships no
    verdict type, so no caller can read a populated table as a green light; and
    it carries its own semver, because `GATE_API_VERSION` is held in lockstep
    with `revl.gate` on py (`test_the_gate_api_semver_is_one_surface_across_
    wheel_and_crate`) and `revl.gate` has no navigation surface to keep in step
    with."""
    symbols_rs = (CRATE / "src" / "symbols.rs").read_text(encoding="utf-8")
    code = "\n".join(line for line in symbols_rs.splitlines()
                     if not line.lstrip().startswith(("//!", "///", "//")))
    assert "pub fn symbols(source: &str) -> Symbols" in code
    assert "Verdict" not in code, (
        "the navigation surface must not deal in verdicts: it says where a "
        "declaration is, not whether the program may run")
    assert "Undecided { reason: String }" in code, \
        "a document this surface will not answer for must say so explicitly"
    assert "catch_unwind" in code, \
        "a native front-end abort must become Undecided, never an answer"
    lib_rs = (CRATE / "src" / "lib.rs").read_text(encoding="utf-8")
    assert "pub mod symbols;" in lib_rs
    assert (f'pub const SYMBOLS_API_VERSION: &str = "{GEN.SYMBOLS_API_VERSION}";'
            in lib_rs)
    meta = json.loads((CRATE / "GENERATED.json").read_text(encoding="utf-8"))
    assert meta["symbols_api_version"] == GEN.SYMBOLS_API_VERSION


def test_the_covered_layer_is_stated_identically_everywhere():
    """`COVERED_LAYER` is the one sentence saying what this gate decides. It is
    stamped into the rust source, the README and the provenance from a single
    generator constant, so the three cannot disagree."""
    meta = json.loads((CRATE / "GENERATED.json").read_text(encoding="utf-8"))
    assert meta["issues_admissions"] is False
    assert meta["verdict_arms"] == ["refused", "no_objection", "outside_frontier"]
    assert meta["covered_layer"] == GEN.COVERED_LAYER
    assert "NOT the reference type layer" in GEN.COVERED_LAYER
    lib_rs = (CRATE / "src" / "lib.rs").read_text(encoding="utf-8")
    assert f'pub const COVERED_LAYER: &str = "{GEN.COVERED_LAYER}";' in lib_rs
    readme = (CRATE / "README.md").read_text(encoding="utf-8")
    assert GEN.COVERED_LAYER in readme
    assert "This gate issues no admissions" in readme


@pytest.mark.parametrize("relpath", [
    "Cargo.toml", "GENERATED.json", "README.md",
    "src/lib.rs", "src/frontier.rs", "src/selfhost.rs", "src/session.rs",
    "src/symbols.rs",
    "tests/admit.rs", "tests/symbols.rs",
])
def test_every_generated_file_is_committed(relpath):
    assert (CRATE / relpath).is_file(), f"crates/revl-gate/{relpath} is missing"


def test_the_emitted_module_is_the_reference_emitter_output():
    """`src/selfhost.rs` is the reference rust backend's own output for
    `selfhost/lower.rvl` — not a hand-tuned copy. Its header is the emitter's."""
    head = (CRATE / "src" / "selfhost.rs").read_text(encoding="utf-8")[:400]
    assert "Generated by the revl cordis-rs backend" in head
    assert "do not edit" in head
