"""The programmatic-COMPILE consumer example — roadmap item 338, py slice.

`ci_gate.py` (tests/test_gate_consumer_example.py) proves the ADMIT half of the
promised `revl.gate` surface from an out-of-tree consumer; this file proves the
COMPILE half. `examples/ecosystem-consumer/compile_gate.py` is a small,
standalone-shaped project (its own logic, importing ONLY `revl.gate`) that a
third-party build step is once it `pip install revl`s and depends on the gate as
a library: it programmatically compiles a batch of agent-authored candidates to
real target source with `revl.gate.compile_to`, gating whether it emits/writes
each one on the SAME asymmetric contract (docs/gate-dependency-contract.md,
docs/design/338-revl-as-dependency.md §6).

Two things this file proves, matching the design's exit tests:

* **The example genuinely exercises the PACKAGED compile surface, not an
  in-tree import.** `compile_gate.py` is run as a subprocess against a freshly
  assembled, ISOLATED copy of the `revl` package (nothing of this checkout's
  `src/` on its `PYTHONPATH`), assembled in the installed-wheel layout — the
  reference emitters ship *inside* the package as `revl/backends`
  (`src/revl/_paths.py`, `backends_root()`), so `compile_to` resolves them the
  way a `pip install revl` would, never from the checkout.

* **`compile_to` fails closed on a hole draft (regression guard).** A draft
  with an open typed hole COMPILES (so an author gets the checker's verdict on
  the parts it has written) but may never run, so there is nothing to lower.
  `admit` already refuses such a draft (T3); `compile_to` must refuse it the
  SAME way — a `Verdict(admitted=False, code="T3")` with `output = None`, fail
  closed — never letting the backend emitter's hole backstop escape as an
  uncaught error (the bug this slice fixes in `src/revl/gate.py`) and never
  emitting target source `admit` would refuse.

The rule this consumer embeds against is `ci_gate.py`'s, one field wider: gate
the EMIT decision on `admitted`, write target source only for an admission,
record `frontier` with every result, and treat an emitted program as
compile-time-admitted-not-safe-to-run (it is never executed here).
"""

from __future__ import annotations

import importlib.util
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
EXAMPLE_DIR = ROOT / "examples" / "ecosystem-consumer"
CANDIDATES_DIR = EXAMPLE_DIR / "candidates"


def _load_compile_gate():
    """Import `compile_gate.py` by path (a standalone consumer's own code, not a
    package under `src/`). `tests/conftest.py` puts this checkout's `src/` on
    `sys.path`, which resolves its `from revl.gate import ...`; the subprocess
    tests below deliberately do NOT rely on that."""
    spec = importlib.util.spec_from_file_location(
        "compile_gate", EXAMPLE_DIR / "compile_gate.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


compile_gate = _load_compile_gate()


# --------------------------------------------------------------------------- #
# The example's own logic: gate EMIT on the verdict, output only on admission.
# --------------------------------------------------------------------------- #

def test_admitted_candidate_emits_real_target_source():
    version = {"api": "1.0.0", "language": "2.0.0",
               "frontier": "reference-full:2.0.0"}
    record = compile_gate.compile_candidate(
        CANDIDATES_DIR / "double_tool.rvl", "py", version)
    assert record["admitted"] is True
    assert record["code"] is None
    assert record["output"] is not None
    # real reference cordis-py backend output, not a stand-in string.
    assert "Generated by the revl cordis-py backend" in record["output"]
    assert record["frontier"] == version["frontier"]


def test_refused_candidate_carries_no_output():
    """A refusal is authoritative and fail-closed: `output` is None and there is
    nothing to emit, write, or run for the candidate (docs/gate-dependency-
    contract.md, Clause 1)."""
    version = {"api": "1.0.0", "language": "2.0.0",
               "frontier": "reference-full:2.0.0"}
    for name in ("leaky_tool.rvl", "draft_tool.rvl"):
        record = compile_gate.compile_candidate(
            CANDIDATES_DIR / name, "py", version)
        assert record["admitted"] is False, name
        assert record["output"] is None, name
        assert record["frontier"] == version["frontier"], name


def test_hole_draft_is_refused_t3_not_a_crash():
    """The bug this slice fixes: a hole draft COMPILES but cannot be lowered.
    `compile_to` must refuse it with the reference admission diagnostic (T3),
    `output = None`, the SAME verdict `admit` gives — not let the backend
    emitter's hole backstop escape as an uncaught error."""
    from revl.gate import admit, compile_to

    source = (CANDIDATES_DIR / "draft_tool.rvl").read_text(encoding="utf-8")
    emit = compile_to(source, "py")
    assert emit.verdict.admitted is False
    assert emit.verdict.code == "T3"
    assert emit.output is None
    # identical decision to the ADMIT half of the surface.
    assert admit(source).code == emit.verdict.code


def test_unknown_tier_fails_closed():
    from revl.gate import compile_to

    source = (CANDIDATES_DIR / "double_tool.rvl").read_text(encoding="utf-8")
    emit = compile_to(source, "cobol")
    assert emit.verdict.admitted is False
    assert emit.verdict.code == "UNKNOWN_TIER"
    assert emit.output is None


def test_run_compile_never_emits_a_refusal(tmp_path):
    """The security contract, demonstrated: the EMIT decision (this example's
    stand-in for "accept/write/run") must never fire for a refused candidate,
    so `--out` produces a file for the one admitted candidate ONLY."""
    logged: list[str] = []
    results = compile_gate.run_compile(
        CANDIDATES_DIR, "py", out_dir=tmp_path, log=logged.append)

    by_name = {r["name"]: r for r in results}
    assert by_name["double_tool.rvl"]["admitted"] is True
    assert by_name["leaky_tool.rvl"]["admitted"] is False
    assert by_name["draft_tool.rvl"]["admitted"] is False

    emit_lines = [line for line in logged if line.startswith("EMIT")]
    refuse_lines = [line for line in logged if line.startswith("REFUSE")]
    assert len(emit_lines) == 1
    assert "double_tool.rvl" in emit_lines[0]
    assert len(refuse_lines) == 2

    # only the admitted candidate reached the writer.
    written = sorted(p.name for p in tmp_path.iterdir())
    assert written == ["double_tool.py"]
    assert "Generated by the revl cordis-py backend" in \
        (tmp_path / "double_tool.py").read_text(encoding="utf-8")


def test_gate_version_is_logged_once():
    logged: list[str] = []
    compile_gate.run_compile(CANDIDATES_DIR, "py", log=logged.append)
    version_lines = [line for line in logged if line.startswith("gate_version:")]
    assert len(version_lines) == 1
    assert "frontier=reference-full:" in version_lines[0]


# --------------------------------------------------------------------------- #
# The genuinely-external proof: compile against an ISOLATED, packaged copy.
# --------------------------------------------------------------------------- #

import pytest


@pytest.fixture(scope="module")
def fresh_revl_install(tmp_path_factory) -> Path:
    """Assemble an isolated copy of the `revl` package in the INSTALLED-WHEEL
    layout — `revl/` with the reference emitters shipped inside it as
    `revl/backends` — so a subprocess pointed at it resolves `compile_to`'s
    emitters exactly the way `pip install revl` would (`_paths.backends_root()`
    falls back to `<pkg>/backends` when no checkout sibling is present), and
    never from this checkout's tree. Pure `shutil.copytree`, no wheel-build
    tooling required (none is installed in this environment; see
    tests/test_packaging.py)."""
    site = tmp_path_factory.mktemp("fresh-site")
    dest = site / "revl"
    ignore = shutil.ignore_patterns("__pycache__", "*.pyc")
    shutil.copytree(ROOT / "src" / "revl", dest, ignore=ignore)
    # the wheel ships `backends/` inside the package; reproduce that so the
    # isolated copy can emit without the checkout's sibling `backends/` tree.
    shutil.copytree(ROOT / "backends", dest / "backends", ignore=ignore)
    return site


def _run_compile_gate(fresh_site: Path, *extra_args: str) -> subprocess.CompletedProcess:
    env = dict(os.environ)
    # PYTHONPATH points ONLY at the isolated copy; this checkout's `src/` is
    # deliberately absent, so the subprocess can only resolve `revl.gate` and
    # its packaged emitters from the isolated copy — never from an in-tree path.
    env["PYTHONPATH"] = str(fresh_site)
    return subprocess.run(
        [sys.executable, str(EXAMPLE_DIR / "compile_gate.py"),
         str(CANDIDATES_DIR), "--tier", "py", *extra_args],
        capture_output=True, text=True, env=env, timeout=120)


def test_example_compiles_against_an_isolated_packaged_copy(fresh_revl_install):
    """The item's exit (design §8): a third-party project depending on nothing
    but the packaged `revl.gate` surface compiles a batch of candidates in a
    fresh environment, emitting real target source for the admission and nothing
    for the refusals — not from an in-tree import."""
    proc = _run_compile_gate(fresh_revl_install)
    assert proc.returncode == 0, proc.stderr

    assert "gate_version: api=1.0.0" in proc.stdout
    assert "frontier=reference-full:" in proc.stdout
    assert "EMIT   double_tool.rvl" in proc.stdout
    assert "REFUSE draft_tool.rvl  code=T3" in proc.stdout
    assert "REFUSE leaky_tool.rvl" in proc.stdout
    # the security contract, demonstrated: neither refusal is ever EMITted.
    assert "EMIT   draft_tool.rvl" not in proc.stdout
    assert "EMIT   leaky_tool.rvl" not in proc.stdout


def test_example_json_matches_inprocess_compile_oracle(fresh_revl_install):
    """The verdict this out-of-tree consumer computes from the packaged compile
    surface must be the SAME `compile_to` gives in-process on the identical
    sources (333's match discipline, from a genuinely external package): same
    admitted/code per candidate, and emitted bytes present iff admitted."""
    proc = _run_compile_gate(fresh_revl_install, "--json")
    assert proc.returncode == 0, proc.stderr
    payload = json.loads(proc.stdout)

    assert set(payload["gate_version"]) == {"api", "language", "frontier"}
    assert payload["tier"] == "py"

    from revl.gate import compile_to as inprocess_compile  # this checkout's
    # copy, used only as the reference oracle for this assertion.

    by_name = {r["name"]: r for r in payload["results"]}
    for path in sorted(CANDIDATES_DIR.glob("*.rvl")):
        oracle = inprocess_compile(path.read_text(encoding="utf-8"), "py")
        record = by_name[path.name]
        assert record["admitted"] == oracle.verdict.admitted, path.name
        assert record["code"] == oracle.verdict.code, path.name
        assert record["frontier"] == payload["gate_version"]["frontier"]
        # `--json` reports output LENGTH; it is > 0 iff the candidate admitted.
        assert (record["output"] > 0) == oracle.verdict.admitted, path.name
