"""The `crates/revl-gate` drift gate (roadmap item 332, Stage 3).

`crates/revl-gate` is a COMMITTED generated artifact. It has to be committed —
the crate must build on a machine with no Python at all, or item 336 (a single
rust binary shipping the compiler) and item 338 (`cargo add revl`) do not exist.
The cost of committing generated bytes is that they can go stale, so drift is
killed the way `docs/conformance.md` kills it: regenerate from the same tree and
fail on any byte difference.

That gives the frontier tables their teeth. The crate's fail-closed table is
DERIVED (`revl.lexer.KEYWORDS` minus the self-host lexer's keywords;
`revl.typecheck._BUILTIN_SIG` minus the self-host lowering's builtins), so a
reference-side construct added without a self-host port changes the generated
bytes — and this test is what makes that change impossible to land unnoticed.

No cargo needed: this is a pure regenerate-and-compare, so it runs on every
machine, toolchain or not. The half that needs a rust toolchain lives in
`tests/test_gate_crate_admit.py` behind the toolchain-honesty skip.
"""

from __future__ import annotations

import importlib.util
import json
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
CRATE = ROOT / "crates" / "revl-gate"


def _generator():
    """Load `tools/build_gate_crate.py` by path, the way the backends' own tests
    load their emitters, so the test exercises the file under comparison."""
    path = ROOT / "tools" / "build_gate_crate.py"
    spec = importlib.util.spec_from_file_location("revl_build_gate_crate", path)
    module = importlib.util.module_from_spec(spec)
    sys.modules["revl_build_gate_crate"] = module
    spec.loader.exec_module(module)
    return module


GEN = _generator()


# ------------------------------------------------------------------- drift


def test_the_committed_crate_matches_a_fresh_generation():
    """The gate itself. Regenerate `crates/revl-gate` from this tree and compare
    byte for byte; any difference is drift and drift is a red.

    If this fails: `python3 tools/build_gate_crate.py`, then re-run.
    """
    problems = GEN.drift(CRATE)
    assert not problems, (
        "crates/revl-gate has drifted from the sources it is generated from "
        "(fix: `python3 tools/regen_goldens.py gate-crate`, equivalently "
        "`python3 tools/build_gate_crate.py`, then review and commit the diff — "
        "the crate embeds emitted rust, so ANY backends/rust/emit.py or "
        "selfhost/*.rvl change rewrites it):\n  "
        + "\n  ".join(problems)
        + "\n\nRegenerate with: python3 tools/build_gate_crate.py")


def test_generation_is_deterministic():
    """Two generations of the same tree produce the same bytes. Without this the
    drift gate would be a coin flip rather than a gate."""
    first = GEN.build()
    second = GEN.build()
    assert first.keys() == second.keys()
    for rel in first:
        assert first[rel] == second[rel], f"{rel} is not deterministic"


# -------------------------------------------------------------- provenance


def test_provenance_records_what_the_crate_was_built_from():
    """`GENERATED.json` is the crate's provenance: the digest inputs, the
    self-host closure it was emitted from, and the frontier id it stamps. A
    consumer (and item 337's seam re-admission) reads the frontier id to detect
    that two gates cover different surfaces before trusting their agreement."""
    meta = json.loads((CRATE / "GENERATED.json").read_text(encoding="utf-8"))
    assert meta["generator"] == "tools/build_gate_crate.py"
    assert meta["selfhost_root"] == "selfhost/lower.rvl"
    assert meta["layer"].startswith("1 ")
    assert meta["frontier"] == f"selfhost-admit:{meta['source_digest'][:16]}"
    assert meta["source_digest"] == GEN.source_digest()
    # every digest input is a real file, or the digest is measuring nothing
    for rel in meta["digest_inputs"]:
        assert (ROOT / rel).is_file(), f"digest input {rel} does not exist"


def test_the_frontier_table_is_derived_not_hand_written():
    """The committed table equals the difference the generator computes from the
    two compilers' own tables. A hand-edited crate fails here as well as at the
    drift gate."""
    meta = json.loads((CRATE / "GENERATED.json").read_text(encoding="utf-8"))
    tables = GEN.frontier_tables()
    assert meta["frontier_excluded_keywords"] == tables["keywords"]
    assert meta["frontier_excluded_builtins"] == tables["builtins"]
    # And the rust source carries the same list, in the same order.
    frontier_rs = (CRATE / "src" / "frontier.rs").read_text(encoding="utf-8")
    for name in tables["builtins"]:
        assert f'    "{name}",' in frontier_rs


def test_the_gate_api_semver_is_one_surface_across_wheel_and_crate():
    """`revl.gate` and the crate are two spellings of ONE surface, so their
    `api` semver is one value. The generator refuses to run when they disagree;
    this pins the promise in the suite too."""
    from revl.gate import GATE_API_VERSION

    assert GEN.GATE_API_VERSION == GATE_API_VERSION
    lib_rs = (CRATE / "src" / "lib.rs").read_text(encoding="utf-8")
    assert f'pub const GATE_API_VERSION: &str = "{GATE_API_VERSION}";' in lib_rs


# ------------------------------------------------- the shape the crate ships


def test_the_crate_is_admit_only_and_says_so():
    """Stage 3 is admit-only. `compile_to` is exported but fails closed (Stage
    4); `admit_into` exists (issue #346) but is a REFUSAL arm too - it folds the
    G2/G3 legs over the union of a running manifest's rows and the candidate, and
    still issues no admission, so it is not the wave-through a manifest-ignoring
    stub would be. Layer 2 is item 334 slice 1: a real `Session` state machine
    that still issues NO admission (the accept half is a later slice, so a
    candidate the native gate does not refuse is fail-closed, never waved
    through)."""
    lib_rs = (CRATE / "src" / "lib.rs").read_text(encoding="utf-8")
    assert "pub fn admit(source: &str) -> Verdict" in lib_rs
    assert "pub fn compile_to(" in lib_rs
    assert "pub fn admit_into(source: &str, manifest: &str) -> Verdict" in lib_rs, (
        "the crate must ship a real manifest-aware `admit_into` (issue #346): the "
        "shape a rust embed screens a proposal AGAINST the running composition")
    # And it must be the REAL fold, not a stub that ignores its argument: the
    # binding hands the manifest to the self-host `admit_ambient`, and a binding
    # that dropped it would be the manifest-ignoring wave-through this crate
    # exists to prevent.
    assert "selfhost::admit_ambient(" in lib_rs, (
        "`admit_into` must call the self-host ambient fold, not re-derive a "
        "standalone verdict and call it a manifest answer")
    assert "pub mod session;" in lib_rs
    session_rs = (CRATE / "src" / "session.rs").read_text(encoding="utf-8")
    # Item 334 slice 1: the session is a real state machine now, not an empty
    # reservation. It carries the generation state, the untrusted-author
    # admission entry, the item-245 witnessed-call recording path, and (issue
    # #346) the manifest-aware admission entry.
    assert "pub struct Session" in session_rs, \
        "item 334 slice 1 ships a real `Session`, not a reserved empty module"
    for verb in ("fn load(", "fn propose(", "fn admit(", "fn admit_into(", "fn call(",
                 "fn commit(", "fn abort(", "fn unload("):
        assert verb in session_rs, f"session.rs must ship `{verb}...` (item 334 slice 1)"
    # But slice 1 still issues NO admission: layer 1 has no `Admitted` arm and
    # this tier has no runtime, so the CODE (doc comments excluded) must never
    # set an outcome's `admitted` to true — a candidate the gate does not refuse
    # is fail-closed, exactly the wave-through the crate exists to prevent.
    session_code = "\n".join(
        line for line in session_rs.splitlines()
        if not line.lstrip().startswith(("//!", "///", "//")))
    assert "admitted: true" not in session_code and "admitted:true" not in session_code, (
        "session.rs must never set `admitted: true`: the accept-and-swap half is "
        "a later slice, and until then a non-refusal fails closed, not admits")


def test_the_verdict_surface_still_issues_no_admission():
    """The security clause, pinned in source.

    `selfhost/lower.rvl`'s `admit_src` decides the composition/guarantee layer
    (G1..G4, A1, PRELUDE, BAD) and runs NO type layer, so a non-refusal from it
    can never mean "the reference would admit this"
    (`tests/test_gate_crate_admit.py::TYPE_LAYER_GAP` measures it). The crate
    grew an ADMISSION surface for issue #346, and this is the half of that change
    that must NOT have moved: `Verdict` still has no admitting arm, and
    `Verdict::to_json` still reports `admitted: false` on every one of its arms.

    That is what keeps the old guarantee true. A host holding a `Verdict` has no
    arm it could misread as a green, whatever the admission surface grows into;
    an admission has to be asked for by name, through a different type.
    """
    lib_rs = (CRATE / "src" / "lib.rs").read_text(encoding="utf-8")
    # doc comments explain at length why the arm is absent; the CODE is what
    # must not have it.
    code = "\n".join(line for line in lib_rs.splitlines()
                     if not line.lstrip().startswith(("//!", "///", "//")))
    assert "OutsideFrontier { reason: String }" in code
    assert "NoObjection," in code
    assert "Verdict::Admitted" not in code, (
        "`Verdict` must not gain an admitting arm: a consumer of the refusal "
        "surface must have nothing it could read as a green. An admission is a "
        "separate type, asked for by name (`issue_admission`)")
    assert "pub fn admit(source: &str) -> Verdict" in code
    assert "pub fn admit_into(source: &str, manifest: &str) -> Verdict" in code
    assert r'",\"admitted\":false,\"code\":"' in code, (
        "`Verdict::to_json` must report `admitted: false` on every arm, so a "
        "consumer of the fixed {admitted, code, message} shape fails closed")
    assert "catch_unwind" in code, \
        "a native gate abort must become OutsideFrontier, never a verdict"


def test_the_admission_arm_is_reachable_only_behind_the_refusal_gate():
    """The shape of the admission arm (issue #346), pinned in source.

    The arm is the dangerous direction, so the two things that make it sound are
    pinned here rather than left to a reading of the docs:

    * an `Admission::Admitted` is constructed at exactly TWO sites — one per
      entry point — and each one sits inside a `verdict == Verdict::NoObjection`
      guard, so an admission can never be issued over a refusal or a frontier
      gap however the certifier is widened later;
    * the certifier itself is a separate generated module with its own DERIVED
      vocabularies and its own surface id, and it is the only thing either entry
      point consults.
    """
    lib_rs = (CRATE / "src" / "lib.rs").read_text(encoding="utf-8")
    # the shipped code only: the `#[cfg(test)]` module below it exercises the arm
    # and naming it there is not a construction site a consumer can reach.
    code = "\n".join(line for line in lib_rs.split("#[cfg(test)]")[0].splitlines()
                     if not line.lstrip().startswith(("//!", "///", "//")))
    assert "mod admission;" in code, \
        "the certifier must be its own generated module, not inline in the shim"
    assert "pub enum Admission {" in code
    assert "Admitted { basis: String }," in code
    assert "Withheld { verdict: Verdict }," in code
    assert "pub fn issue_admission(source: &str) -> Admission" in code
    assert ("pub fn issue_admission_into(source: &str, manifest: &str) -> Admission"
            in code)
    assert "pub const ADMISSION_SURFACE_ID: &str = admission::SURFACE_ID;" in code
    # Every construction of the admitting arm, and the guard it sits behind.
    assert code.count("return Admission::Admitted { basis };") == 2, (
        "the admitting arm must be constructed at exactly the two entry points; "
        "a third site is a path that has not been reviewed")
    guarded = code.count(
        "if verdict == Verdict::NoObjection {\n        if let Some(basis) = admission::")
    assert guarded == 2, (
        "each admission must be issued only where the REFUSAL surface answered "
        "NoObjection: an admission over a refusal or a frontier gap is the "
        "wave-through this crate exists to prevent")

    admission_rs = (CRATE / "src" / "admission.rs").read_text(encoding="utf-8")
    assert "pub(crate) fn certify(source: &str) -> Option<String>" in admission_rs
    assert ("pub(crate) fn certify_into(source: &str, manifest: &str) -> "
            "Option<String>" in admission_rs)
    for table in ("SCALAR_TYPES", "RESERVED_TYPE_NAMES", "REFERENCE_KEYWORDS"):
        assert f"pub(crate) const {table}: &[&str]" in admission_rs, table
    assert "pub(crate) const SURFACE_ID: &str" in admission_rs


def test_the_admission_tables_are_derived_not_hand_written():
    """The certifier's vocabularies are the REFERENCE compiler's own tables, so a
    scalar the reference stops treating as a scalar cannot stay in the surface
    silently — it changes the generated bytes and reds the drift gate in the same
    wave, exactly as the frontier table does."""
    meta = json.loads((CRATE / "GENERATED.json").read_text(encoding="utf-8"))
    tables = GEN.admission_tables()
    assert meta["admission_scalar_types"] == tables["scalars"]
    assert meta["admission_reserved_type_names"] == tables["reserved"]
    assert meta["admission_surface"] == \
        GEN.admission_surface_id(meta["source_digest"])
    assert meta["admitted_layer"] == GEN.ADMITTED_LAYER
    admission_rs = (CRATE / "src" / "admission.rs").read_text(encoding="utf-8")
    for name in tables["scalars"]:
        assert f'    "{name}",' in admission_rs
    # a generic head is not a scalar, and must never be admitted as one
    for head in ("Opt", "List", "Map", "Result", "Any", "Never", "Value"):
        assert head not in tables["scalars"], head
        assert head in tables["reserved"], head
    lib_rs = (CRATE / "src" / "lib.rs").read_text(encoding="utf-8")
    assert f'pub const ADMITTED_LAYER: &str = "{GEN.ADMITTED_LAYER}";' in lib_rs


def test_the_navigation_surface_issues_no_verdict_and_is_versioned_apart():
    """`revl_gate::symbols` (item 336 slice 2) answers WHERE a declaration is,
    never WHETHER a program may run.

    Two things are pinned here because both are load-bearing. It ships no
    verdict type, so no caller can read a populated table as a green light; and
    it carries its own semver, because `GATE_API_VERSION` is held in lockstep
    with `revl.gate` on py (`test_the_gate_api_semver_is_one_surface_across_
    wheel_and_crate`) and `revl.gate` has no navigation surface to keep in step
    with."""
    symbols_rs = (CRATE / "src" / "symbols.rs").read_text(encoding="utf-8")
    code = "\n".join(line for line in symbols_rs.splitlines()
                     if not line.lstrip().startswith(("//!", "///", "//")))
    assert "pub fn symbols(source: &str) -> Symbols" in code
    assert "Verdict" not in code, (
        "the navigation surface must not deal in verdicts: it says where a "
        "declaration is, not whether the program may run")
    assert "Undecided { reason: String }" in code, \
        "a document this surface will not answer for must say so explicitly"
    assert "catch_unwind" in code, \
        "a native front-end abort must become Undecided, never an answer"
    lib_rs = (CRATE / "src" / "lib.rs").read_text(encoding="utf-8")
    assert "pub mod symbols;" in lib_rs
    assert (f'pub const SYMBOLS_API_VERSION: &str = "{GEN.SYMBOLS_API_VERSION}";'
            in lib_rs)
    meta = json.loads((CRATE / "GENERATED.json").read_text(encoding="utf-8"))
    assert meta["symbols_api_version"] == GEN.SYMBOLS_API_VERSION


def test_the_covered_layer_is_stated_identically_everywhere():
    """`COVERED_LAYER` is the one sentence saying what this gate decides. It is
    stamped into the rust source, the README and the provenance from a single
    generator constant, so the three cannot disagree."""
    meta = json.loads((CRATE / "GENERATED.json").read_text(encoding="utf-8"))
    # The gate DOES issue admissions now (issue #346) — but only through the
    # separate `Admission` surface, and only inside `admitted_layer`. The VERDICT
    # arms are unchanged, which is the property a consumer of `admit` relies on.
    assert meta["issues_admissions"] is True
    assert meta["verdict_arms"] == ["refused", "no_objection", "outside_frontier"]
    assert meta["admission_arms"] == ["admitted", "withheld"]
    assert "issue_admission" in meta["admission_arm"]
    assert "NoObjection" in meta["admission_arm"]
    # The manifest arm (issue #346) added no VERDICT arm: `admit_into` returns one
    # of the same three, and the provenance says which surface answers the
    # manifest question rather than implying a new power. An admitting arm on
    # `Verdict` would be the admission this surface may not issue.
    assert "admit_into" in meta["manifest_arm"]
    assert "issues no admission" in meta["manifest_arm"]
    assert "manifest" in meta["note"]
    assert meta["covered_layer"] == GEN.COVERED_LAYER
    assert "NOT the reference type layer" in GEN.COVERED_LAYER
    lib_rs = (CRATE / "src" / "lib.rs").read_text(encoding="utf-8")
    assert f'pub const COVERED_LAYER: &str = "{GEN.COVERED_LAYER}";' in lib_rs
    readme = (CRATE / "README.md").read_text(encoding="utf-8")
    assert GEN.COVERED_LAYER in readme
    assert "The verdict surface issues no admissions" in readme
    assert GEN.ADMITTED_LAYER in readme


@pytest.mark.parametrize("relpath", [
    "Cargo.toml", "GENERATED.json", "README.md",
    "src/lib.rs", "src/admission.rs", "src/frontier.rs", "src/ir.rs",
    "src/selfhost.rs",
    "src/session.rs", "src/symbols.rs",
    "tests/admit.rs", "tests/ir.rs", "tests/symbols.rs",
])
def test_every_generated_file_is_committed(relpath):
    assert (CRATE / relpath).is_file(), f"crates/revl-gate/{relpath} is missing"


def test_the_emitted_module_is_the_reference_emitter_output():
    """`src/selfhost.rs` is the reference rust backend's own output for
    `selfhost/lower.rvl` — not a hand-tuned copy. Its header is the emitter's."""
    head = (CRATE / "src" / "selfhost.rs").read_text(encoding="utf-8")[:400]
    assert "Generated by the revl cordis-rs backend" in head
    assert "do not edit" in head
