"""Every committed emitted artifact is byte-compared against a fresh emission.

Issue #1089. `backends/go/scenarios/emitted/secret_trace/gen_secret_trace_test.go`
sat 239 lines stale on main. CI *compiled and ran* it, it was valid Go, it
satisfied its own assertions, and every check reported green — because
"this generated artifact still works" and "this generated artifact is what the
emitter produces today" are different properties, and only the second one
catches emitter drift.

That is the week's recurring shape rather than a one-off: a mechanism that
existed and could not see the thing it named. The `frontend-assets` job failed
at `npm ci` before reaching the legs it was added to run; `test_str_ordering_
agrees_everywhere` walked three of six tiers; `tests/test_cross_tier_execution.py`
named wasm in no tier tuple at all. Each reported green while the property went
unchecked.

`tools/regen_goldens.py` is the registry that answers the second question: each
target knows how to produce the bytes of every file it owns, and `--check`
emits them and compares. Its own docstring states the rule — "a target must
declare every file it owns: an undeclared file is an unchecked file" — and the
worker enforces one direction of it, refusing a producer that writes a file the
target does not declare. The other direction was not enforced anywhere: a
committed emitted file that NO target declares is invisible to the registry and
to `--check`, and so is exactly the artifact that drifts.

This file closes that direction, and the wiring question behind it:

  1. every committed file under `backends/` that says it was generated is
     declared by a golden target, or carries a written reason here;
  2. every golden target is `--check`ed by a CI job that also has the tools its
     producer requires — issue #1083's lesson, "the guard was never missing, it
     was only ever in a job nobody was required to watch", and `regen_goldens`
     loud-SKIPS a target whose tool is absent, so a check running in the wrong
     job is a green line that compared nothing.

Both checks carry a self-test that reintroduces the bug they exist for, because
a checker that has never been shown to catch anything is the same shape of gap
as the one it closes.
"""

from __future__ import annotations

import importlib.util
import re
import subprocess
import sys
from pathlib import Path

import pytest
# A HARD import (issue #266): `importorskip` here would let the CI-pairing
# check below skip wherever PyYAML is absent, which is a guard against silent
# skips silently skipping. `pyyaml` is in the `test` extra.
import yaml

ROOT = Path(__file__).resolve().parents[1]
WORKFLOWS = ROOT / ".github" / "workflows"


def _regen_goldens():
    """`tools/regen_goldens.py`, loaded by path under an explicit name (the
    module is a script, not an installed package)."""
    spec = importlib.util.spec_from_file_location(
        "revl_regen_goldens_registry", ROOT / "tools" / "regen_goldens.py")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module          # dataclasses needs the module visible
    spec.loader.exec_module(module)
    return module


def _declared_files() -> set[str]:
    """Every repo-relative path any golden target declares. A target may name a
    directory (the gate crates), which owns everything under it."""
    declared: set[str] = set()
    for target in _regen_goldens().TARGETS:
        for rel in target.files:
            path = ROOT / rel
            if path.is_dir():
                declared |= {str(child.relative_to(ROOT))
                             for child in path.rglob("*") if child.is_file()}
            else:
                declared.add(rel)
    return declared


# The marker every emitter in this repo writes into its own output, in each
# tier's comment syntax: "Code generated by …", "Generated by the revl cordis-rs
# backend …", "Generated by `revl import a2a`". Two independent halves, both
# required, so a hand-written file that merely discusses generated code is not
# swept in.
_GENERATED = re.compile(r"generated (?:by|from)", re.IGNORECASE)
_DO_NOT_EDIT = re.compile(r"do not edit", re.IGNORECASE)
_HEADER_LINES = 8


def _looks_generated(text: str) -> bool:
    head = "\n".join(text.splitlines()[:_HEADER_LINES])
    return bool(_GENERATED.search(head) and _DO_NOT_EDIT.search(head))


def _tracked_backend_files() -> list[str]:
    proc = subprocess.run(["git", "-C", str(ROOT), "ls-files", "backends"],
                          capture_output=True, text=True)
    if proc.returncode != 0:                 # a source tarball, no git
        pytest.skip("not a git checkout")
    return proc.stdout.split()


def _swept(paths: list[str], read) -> list[str]:
    """The pure half, so the self-test below can feed it a synthetic tree."""
    out = []
    for rel in paths:
        try:
            text = read(rel)
        except (OSError, UnicodeDecodeError):
            continue
        if _looks_generated(text):
            out.append(rel)
    return sorted(out)


# --- artifacts deliberately outside the golden registry ---------------------
#
# Point 3 of issue #1089: compile-and-run (or a gate somewhere else) can be the
# whole contract for a particular artifact, but then the reason is written down
# where the next reader finds it, so the absence is a recorded decision rather
# than a gap. Each entry is a repo-relative path or a `dir/` prefix.
_EXEMPT: dict[str, str] = {
    "backends/typescript/tests/generated/": (
        "REGENERATED BEFORE EVERY RUN, not compared. backends/typescript/"
        "vitest.config.ts calls emitFixtures() while the config is being "
        "evaluated — before vitest resolves its include glob — so the bytes the "
        "suite typechecks and executes are always a fresh emission and there is "
        "no committed copy in the loop to go stale. The copy IS committed, but "
        "only so a cold checkout collects the same test files as a warm one "
        "(one of them, v3_tests.test.ts, is itself a test module); "
        "backends/typescript/tests/generated_coverage.test.ts pins that and the "
        "count of lowered `test` blocks. A byte gate here would compare a file "
        "the next run overwrites."
    ),
    "backends/typescript/tests/fixtures/a2a_agent.rvl": (
        "BYTE-GATED ELSEWHERE. It is `revl import a2a`'s output rather than a "
        "backend emitter's, and tests/test_import_a2a.py::"
        "test_the_ts_backend_fixture_is_current re-runs the importer on the "
        "committed Agent Card and compares. Its producer is "
        "backends/typescript/tests/fixtures/_gen_a2a_agent.py."
    ),
}


def _exempt(rel: str) -> bool:
    return any(rel == key or (key.endswith("/") and rel.startswith(key))
               for key in _EXEMPT)


def test_every_committed_emitted_artifact_is_declared_or_exempt():
    """The direction `regen_goldens.py`'s worker does not check: a committed
    file that says an emitter wrote it, and that no target owns, is regenerated
    by nothing and compared to nothing."""
    tracked = _tracked_backend_files()
    swept = _swept(tracked, lambda rel: (ROOT / rel).read_text(
        encoding="utf-8", errors="replace"))
    assert swept, ("the generated-header sweep matched nothing under backends/ — "
                   "it cannot fail, so it is not a gate")
    declared = _declared_files()
    undeclared = [rel for rel in swept if rel not in declared and not _exempt(rel)]
    assert not undeclared, (
        "committed emitted artifact(s) that no `tools/regen_goldens.py` target "
        "declares, so nothing regenerates them and `--check` cannot see them "
        "drift:\n  " + "\n  ".join(undeclared) +
        "\nEither add them to the target that produces them, or add an entry to "
        "_EXEMPT in this file saying what gates them instead.")


def test_every_exemption_still_names_a_real_file():
    """A stale exemption is a hole with a reason attached. Each entry must
    still match something on disk, and carry a reason long enough to be one."""
    tracked = set(_tracked_backend_files())
    for key, reason in _EXEMPT.items():
        if key.endswith("/"):
            assert any(rel.startswith(key) for rel in tracked), \
                f"_EXEMPT names {key}, which matches no tracked file"
        else:
            assert key in tracked, f"_EXEMPT names {key}, which is not tracked"
        assert len(reason) >= 80, f"_EXEMPT[{key}] needs a real reason, not a label"


def test_the_sweep_can_actually_fail():
    """Teeth. A synthetic tree carrying one emitted file that no target
    declares must come back as exactly that one file — and a hand-written file
    that merely mentions generated code must not."""
    tree = {
        "backends/fake/gen.go": "// Code generated by backends/fake/emit.py — DO NOT EDIT.\n",
        "backends/fake/hand.go": "// Talks about code generated by emit.py; edit freely.\n",
        "backends/fake/late.go": ("\n" * (_HEADER_LINES + 2)
                                  + "// Code generated by x — do not edit.\n"),
    }
    swept = _swept(sorted(tree), tree.__getitem__)
    assert swept == ["backends/fake/gen.go"], swept
    # and the undeclared arm reports it: no target owns backends/fake, and it
    # is not exempt, so this is precisely what the real check would raise on.
    declared = _declared_files()
    assert [rel for rel in swept if rel not in declared and not _exempt(rel)] == \
        ["backends/fake/gen.go"]


# --- the wiring: a gate is only a gate in a job that runs it ----------------

#: What a `requires` tool needs from the job that runs the check. `gofmt` ships
#: with the Go toolchain, so a job that sets Go up has it.
_TOOL_PROVIDERS: dict[str, tuple[str, ...]] = {"gofmt": ("actions/setup-go",)}

_CHECK = re.compile(r"regen_goldens\.py\s+--check(?P<targets>(?:\s+[a-z][a-z-]*)*)")


def _jobs() -> dict[str, dict]:
    jobs: dict[str, dict] = {}
    for path in sorted(WORKFLOWS.glob("*.yml")):
        document = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
        for name, job in (document.get("jobs") or {}).items():
            jobs[f"{path.name}:{name}"] = job
    return jobs


def _checking_jobs(jobs: dict[str, dict], known: set[str]) -> dict[str, set[str]]:
    """job id -> the target names its `--check` steps cover. A `--check` with no
    target list covers every target."""
    found: dict[str, set[str]] = {}
    for job_id, job in jobs.items():
        covered: set[str] = set()
        for step in job.get("steps") or []:
            run = step.get("run") or ""
            for match in _CHECK.finditer(run):
                named = {word for word in match["targets"].split() if word in known}
                covered |= named or set(known)
        if covered:
            found[job_id] = covered
    return found


def _job_tools(job: dict) -> set[str]:
    """The `requires` tools a job provides, read off the actions it uses."""
    text = "\n".join(str(step.get("uses") or "") for step in (job.get("steps") or []))
    return {tool for tool, markers in _TOOL_PROVIDERS.items()
            if any(marker in text for marker in markers)}


def test_every_golden_target_is_drift_checked_by_a_job_that_can_see_it():
    """Issue #1083's shape, applied to the golden registry. Before this,
    `regen_goldens.py --check` ran in NO workflow at all — only in
    tools/pre_merge.sh, for one of eight targets — so seven targets' byte
    comparison happened on a developer's machine or nowhere.

    A target also has to be checked in a job that HAS its producer's tools:
    `worker()` prints `SKIP` and returns 3 for a missing tool, and the driver
    counts that as skipped rather than failed. A `--check go` in a job without
    Go is a green step that compared nothing."""
    targets = {t.name: t for t in _regen_goldens().TARGETS}
    jobs = _jobs()
    checking = _checking_jobs(jobs, set(targets))
    assert checking, ("no CI job runs `tools/regen_goldens.py --check`. Every "
                      "committed golden's byte comparison then happens nowhere.")
    gaps = []
    for name, target in targets.items():
        homes = [job_id for job_id, covered in checking.items()
                 if name in covered and set(target.requires) <= _job_tools(jobs[job_id])]
        if not homes:
            where = [job_id for job_id, covered in checking.items() if name in covered]
            gaps.append(f"{name} (requires {', '.join(target.requires) or 'no tools'}; "
                        f"checked in {', '.join(where) or 'no job'})")
    assert not gaps, (
        "golden target(s) with no CI job that both drift-checks them and "
        "provides their producer's tools:\n  " + "\n  ".join(gaps))


def test_the_ci_pairing_check_can_actually_fail():
    """Teeth for the pairing, against the exact bug it exists for: a `--check`
    of a tool-needing target in a job that does not provide the tool."""
    targets = {t.name: t for t in _regen_goldens().TARGETS}
    assert "go" in targets and targets["go"].requires == ("gofmt",), \
        "the go target no longer requires gofmt — repoint this self-test"

    toolless = {"j": {"steps": [{"run": "python3 tools/regen_goldens.py --check go"}]}}
    checking = _checking_jobs(toolless, set(targets))
    assert checking == {"j": {"go"}}
    assert not set(targets["go"].requires) <= _job_tools(toolless["j"]), \
        "a job with no setup-go must not read as providing gofmt"

    tooled = {"j": {"steps": [{"uses": "actions/setup-go@v6"},
                              {"run": "python3 tools/regen_goldens.py --check go"}]}}
    assert set(targets["go"].requires) <= _job_tools(tooled["j"])

    # a bare `--check` covers every target
    bare = {"j": {"steps": [{"run": "python3 tools/regen_goldens.py --check"}]}}
    assert _checking_jobs(bare, set(targets))["j"] == set(targets)
