"""The embeddable-gate library surface — roadmap item 332 (py deliverable).

Exit tests for the `revl.gate` module (docs/design/332-embeddable-gate-api.md):

* LAYER 1, the verdict surface: `admit` returns the SAME accept/refuse verdict
  as the reference compiler on the same source, message verbatim (an accepted
  program AND a refused one); `compile_to` emits real reference target source;
  `gate_version()` returns the api/language/frontier pin.
* LAYER 2, the session facade: `Gate.load/admit/call/commit` runs a tool
  crossing with the same classification/approval behavior as `revl run`; a
  class-(c) crossing with NO approver REFUSES (fail closed); with an approver it
  fires once.
* ADDITIVITY: a standalone compile is unchanged; a second live `Gate` is refused.

The runtime proofs need a live cordis-py composition (install with
`sh backends/python/setup.sh`, run under its venv); the layer-1 verdict and
version tests are pure and always run.
"""

import importlib.util
import os
import sys
from pathlib import Path

import pytest

from revl.compiler import compile_source
from revl.errors import RevlError
from revl.gate import (
    Gate,
    GateError,
    GateRefused,
    Verdict,
    admit,
    compile_to,
    gate_version,
)

_ROOT = Path(__file__).resolve().parents[1]
_BACKEND = _ROOT / "backends" / "python"
if str(_BACKEND) not in sys.path:
    sys.path.insert(0, str(_BACKEND))

needs_cordis = pytest.mark.skipif(
    importlib.util.find_spec("cordis") is None,
    reason="the layer-2 session facade is proven against a live cordis-py "
           "composition — install it with `sh backends/python/setup.sh` and "
           "run under its venv",
)


@pytest.fixture(autouse=True)
def _no_leaked_gate():
    """Every test must leave the process-global single-gate slot clear, so an
    ordering-dependent second-Gate refusal never leaks between tests."""
    import revl.gate as gate_mod
    yield
    gate_mod._ACTIVE_GATE = None


# A program the reference compiler ACCEPTS, and one it REFUSES.
_ACCEPTED = (
    "service S { fn f(x: Int) -> Int }\n"
    "component C provides s: S {\n"
    "  provide s { fn f(x) = x }\n"
    "}\n"
)
# G1: a component reaches a service no component in the composition provides.
_REFUSED = (
    "service S { fn f(x: Int) -> Int }\n"
    "component C requires dep: Missing provides s: S {\n"
    "  provide s { fn f(x) = x }\n"
    "}\n"
)


# --------------------------------------------------------------------------- #
# Layer 1: the verdict matches the reference compiler, verbatim.
# --------------------------------------------------------------------------- #

def test_admit_matches_reference_on_an_accepted_program():
    # the reference gate: compile_source itself (compiler.py:243).
    ref_ok = True
    try:
        compile_source(_ACCEPTED)
    except RevlError:
        ref_ok = False

    verdict = admit(_ACCEPTED)
    assert ref_ok is True
    assert verdict.admitted is True
    assert verdict.code is None
    assert verdict.message is None


def test_admit_matches_reference_on_a_refused_program_verbatim():
    # the reference verdict for the SAME source, captured directly.
    with pytest.raises(RevlError) as exc:
        compile_source(_REFUSED)
    ref_message = str(exc.value)
    ref_code = getattr(exc.value, "code", None)

    verdict = admit(_REFUSED)
    assert verdict.admitted is False
    # the security clause: the gate refuses exactly what the reference refuses,
    # and the message is the reference diagnostic VERBATIM.
    assert verdict.message == ref_message
    assert verdict.code == ref_code


def test_compile_to_emits_reference_target_source():
    emit = compile_to(_ACCEPTED, "py")
    assert emit.verdict.admitted is True
    assert emit.output is not None
    assert "Generated by the revl cordis-py backend" in emit.output


def test_compile_to_refusal_carries_no_output():
    emit = compile_to(_REFUSED, "py")
    assert emit.verdict.admitted is False
    assert emit.output is None


def test_compile_to_unknown_tier_fails_closed():
    emit = compile_to(_ACCEPTED, "cobol")
    assert emit.verdict.admitted is False
    assert emit.verdict.code == "UNKNOWN_TIER"
    assert emit.output is None


def test_verdict_from_native_splits_at_first_pipe():
    # the tier-agnostic parser the crate reuses: empty admits, TAG|message
    # refuses, and a message carrying `|` survives intact.
    assert Verdict.from_native("").admitted is True
    v = Verdict.from_native("G2|provider table collides on a|b")
    assert v.admitted is False
    assert v.code == "G2"
    assert v.message == "provider table collides on a|b"


def test_gate_version_returns_the_frontier_pin():
    info = gate_version()
    assert set(info) == {"api", "language", "frontier"}
    assert info["api"] == "1.0.0"
    assert info["frontier"] == f"reference-full:{info['language']}"


# --------------------------------------------------------------------------- #
# Layer 2: the session facade, against a live composition.
# --------------------------------------------------------------------------- #

# The running composition (reused from the item-330 admit-crossing fixture): a
# granted tool surface (`Ops`) plus the in-language admit crossing.
_BASE = (
    "type Stash = { path: Str, bak: Str }\n"
    "type FsError = { code: Str }\n"
    "extern pure fn unstash(w: Stash) -> Unit = @py {\n"
    "    import os\n"
    "    if os.path.exists(w['bak']):\n"
    "        os.replace(w['bak'], w['path'])\n"
    "    return\n"
    "}\n"
    "extern witnessed[fs] fn stash_path(p: Str) -> Result[Stash, FsError]"
    " undo unstash(result) = @py {\n"
    "    import os\n"
    "    bak = p + '.bak'\n"
    "    os.replace(p, bak)\n"
    "    return Ok({'path': p, 'bak': bak})\n"
    "}\n"
    "extern emission fn announce(sink: Str, msg: Str) = @py {\n"
    "    with open(sink, 'a') as _f:\n"
    "        _f.write('announce:' + msg + '\\n')\n"
    "    return\n"
    "}\n"
    "service Ops {\n"
    "  emission fn stash(p: Str)\n"
    "  emission fn shout(sink: Str, msg: Str)\n"
    "}\n"
    "component Agent provides ops: Ops {\n"
    "  provide ops {\n"
    "    fn stash(p) { effect stash_path(p) }\n"
    "    fn shout(sink, msg) { emit announce(sink, msg) }\n"
    "  }\n"
    "}\n"
)

_TURN_OK = (
    "service Turn { emission fn run(p: Str, sink: Str) }\n"
    "component TurnComp requires ops: Ops provides turn: Turn {\n"
    "  provide turn {\n"
    '    fn run(p, sink) { emit ops.stash(p); emit ops.shout(sink, "from-turn") }\n'
    "  }\n"
    "}\n"
)


def _base_sources():
    from revl._paths import stdlib_root
    admit_path = str(stdlib_root() / "admit.rvl")
    base_abs = os.path.abspath("gate_base.rvl")
    # admit.rvl rides as a real on-disk co-root (value None), the base as an
    # in-memory draft — exactly the shape an agent loop uses.
    return {base_abs: _BASE, admit_path: None}


def _mutated(path):
    return not os.path.exists(path) and os.path.exists(path + ".bak")


def _pristine(path):
    return os.path.exists(path) and not os.path.exists(path + ".bak")


def _lines(sink):
    return Path(sink).read_text().splitlines() if os.path.exists(sink) else []


@needs_cordis
def test_gate_load_admit_call_commit_runs_a_tool_crossing(tmp_path):
    artifact = tmp_path / "artifact.txt"
    artifact.write_text("payload", encoding="utf-8")
    sink = str(tmp_path / "sink.log")

    gate = Gate()
    try:
        gate.load(_base_sources())

        # the per-turn admit verdict equals the reference compiler's: the turn
        # composes only granted providers, so it is admitted, and hands back a
        # Handle, never the emitted artifact.
        result = gate.admit(_TURN_OK, granted=["Ops"])
        assert result.admitted, result.message
        assert "turn" in result.keys
        assert result.handle is not None

        # run the turn through the handle: the witnessed fs mutation and the
        # emission register into the enclosing 245 frame.
        result.handle.call("turn", "run", [str(artifact), sink])
        assert _mutated(str(artifact)), "witnessed mutation did not apply"
        assert _lines(sink) == ["announce:from-turn"]

        # commit: the witnessed mutation persists, residue-free — decision for
        # decision the same as the same fixture through `revl run`/`revl mcp`.
        committed = gate.commit()
        assert committed["committed"]
        assert committed["noResidue"], committed.get("checks")
        assert _mutated(str(artifact))
    finally:
        gate.close()


@needs_cordis
def test_gate_admit_refusal_leaves_the_running_composition_untouched(tmp_path):
    gate = Gate()
    try:
        gate.load(_base_sources())
        # grant NOTHING: the turn's reach of `ops` is outside the allowlist.
        result = gate.admit(_TURN_OK, granted=[])
        assert not result.admitted
        assert result.code == "R2"
        assert result.handle is None
        # nothing was wired: the running composition is untouched.
        assert "turn" not in gate._session._driver._namespace()
    finally:
        gate.close()


# The approval fixture: `shout` is a plain emission (class (c)); `stash` is a
# witnessed rename (class (a)).
_APPROVAL_BASE = _BASE


@needs_cordis
def test_class_c_crossing_refuses_fail_closed_without_approver(tmp_path):
    sink = str(tmp_path / "sink.log")
    gate = Gate(approval_policy="auto", approver=None)
    try:
        gate.load(_APPROVAL_BASE)
        # a class-(c) crossing with NO approver fails closed: nothing fires.
        with pytest.raises(GateRefused) as exc:
            gate.call("ops", "shout", [sink, "hi"])
        assert exc.value.ticket is not None
        assert _lines(sink) == [], "the host body must NOT have run"
    finally:
        gate.close()


@needs_cordis
def test_class_a_crossing_auto_approves_under_policy(tmp_path):
    # additivity of the policy: a witnessed (class-a) crossing proceeds silently,
    # same as `revl mcp serve --approval-policy auto`.
    artifact = tmp_path / "a.txt"
    artifact.write_text("x", encoding="utf-8")
    gate = Gate(approval_policy="auto")
    try:
        gate.load(_APPROVAL_BASE)
        out = gate.call("ops", "stash", [str(artifact)])
        assert "result" in out
        assert _mutated(str(artifact))
    finally:
        gate.close()


@needs_cordis
def test_class_c_crossing_fires_once_with_an_approving_approver(tmp_path):
    sink = str(tmp_path / "sink.log")
    seen = []

    def approver(ticket):
        seen.append(ticket)
        return True

    gate = Gate(approval_policy="auto", approver=approver)
    try:
        gate.load(_APPROVAL_BASE)
        out = gate.call("ops", "shout", [sink, "hi"])
        assert "result" in out
        assert _lines(sink) == ["announce:hi"], "the approved crossing fired once"
        assert len(seen) == 1, "the approver was consulted exactly once"
    finally:
        gate.close()


@needs_cordis
def test_class_c_crossing_denied_by_approver_fails_closed(tmp_path):
    sink = str(tmp_path / "sink.log")
    gate = Gate(approval_policy="auto", approver=lambda _t: False)
    try:
        gate.load(_APPROVAL_BASE)
        with pytest.raises(GateRefused):
            gate.call("ops", "shout", [sink, "hi"])
        assert _lines(sink) == []
    finally:
        gate.close()


# --------------------------------------------------------------------------- #
# Additivity.
# --------------------------------------------------------------------------- #

def test_standalone_compile_is_unchanged_by_the_facade():
    # a program that never imports the facade compiles exactly as before; here we
    # assert the reference path the facade wraps is untouched.
    before = compile_source(_ACCEPTED)
    after = compile_source(_ACCEPTED)
    assert before == after
    # and the facade's layer-1 verdict does not perturb it.
    admit(_ACCEPTED)
    assert compile_source(_ACCEPTED) == before


def test_second_live_gate_is_refused():
    first = Gate()
    try:
        with pytest.raises(GateError) as exc:
            Gate()
        assert "single-gate-per-process" in str(exc.value)
    finally:
        first.close()
    # after close, a fresh Gate constructs cleanly.
    second = Gate()
    second.close()


def test_public_import_surface_is_pinned():
    import revl.gate as g
    expected = {
        "Verdict", "Emit", "admit", "admit_into", "compile_to",
        "gate_version", "Gate", "GateError", "GateRefused", "AdmitResult",
        "Handle", "recover",
    }
    assert expected <= set(g.__all__)
    for name in expected:
        assert hasattr(g, name), name
