"""Every committed emitted artifact is byte-compared against a fresh emission.

Issue #1089. `backends/go/scenarios/emitted/secret_trace/gen_secret_trace_test.go`
sat 239 lines stale on main. CI *compiled and ran* it, it was valid Go, it
satisfied its own assertions, and every check reported green — because
"this generated artifact still works" and "this generated artifact is what the
emitter produces today" are different properties, and only the second one
catches emitter drift.

That is the week's recurring shape rather than a one-off: a mechanism that
existed and could not see the thing it named. The `frontend-assets` job failed
at `npm ci` before reaching the legs it was added to run; `test_str_ordering_
agrees_everywhere` walked three of six tiers; `tests/test_cross_tier_execution.py`
named wasm in no tier tuple at all. Each reported green while the property went
unchecked.

`tools/regen_goldens.py` is the registry that answers the second question: each
target knows how to produce the bytes of every file it owns, and `--check`
emits them and compares. Its own docstring states the rule — "a target must
declare every file it owns: an undeclared file is an unchecked file" — and the
worker enforces one direction of it, refusing a producer that writes a file the
target does not declare. The other direction was not enforced anywhere: a
committed emitted file that NO target declares is invisible to the registry and
to `--check`, and so is exactly the artifact that drifts.

This file closes that direction, and the wiring question behind it:

  1. every committed file under `backends/` that says it was generated is
     declared by a golden target, or carries a written reason here;
  2. every golden target is `--check`ed by a CI job that also has the tools its
     producer requires — issue #1083's lesson, "the guard was never missing, it
     was only ever in a job nobody was required to watch", and `regen_goldens`
     loud-SKIPS a target whose tool is absent, so a check running in the wrong
     job is a green line that compared nothing.

Both checks carry a self-test that reintroduces the bug they exist for, because
a checker that has never been shown to catch anything is the same shape of gap
as the one it closes.
"""

from __future__ import annotations

import importlib.util
import re
import subprocess
import sys
from pathlib import Path

import pytest
# A HARD import (issue #266): `importorskip` here would let the CI-pairing
# check below skip wherever PyYAML is absent, which is a guard against silent
# skips silently skipping. `pyyaml` is in the `test` extra.
import yaml

ROOT = Path(__file__).resolve().parents[1]
WORKFLOWS = ROOT / ".github" / "workflows"


def _regen_goldens():
    """`tools/regen_goldens.py`, loaded by path under an explicit name (the
    module is a script, not an installed package)."""
    spec = importlib.util.spec_from_file_location(
        "revl_regen_goldens_registry", ROOT / "tools" / "regen_goldens.py")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module          # dataclasses needs the module visible
    spec.loader.exec_module(module)
    return module


def _declared_files() -> set[str]:
    """Every repo-relative path any golden target declares. A target may name a
    directory (the gate crates), which owns everything under it."""
    declared: set[str] = set()
    for target in _regen_goldens().TARGETS:
        for rel in target.files:
            path = ROOT / rel
            if path.is_dir():
                declared |= {str(child.relative_to(ROOT))
                             for child in path.rglob("*") if child.is_file()}
            else:
                declared.add(rel)
    return declared


# The marker every emitter in this repo writes into its own output, in each
# tier's comment syntax: "Code generated by …", "Generated by the revl cordis-rs
# backend …", "Generated by `revl import a2a`". Two independent halves, both
# required, so a hand-written file that merely discusses generated code is not
# swept in.
_GENERATED = re.compile(r"generated (?:by|from)", re.IGNORECASE)
_DO_NOT_EDIT = re.compile(r"do not edit", re.IGNORECASE)
_HEADER_LINES = 8


def _looks_generated(text: str) -> bool:
    head = "\n".join(text.splitlines()[:_HEADER_LINES])
    return bool(_GENERATED.search(head) and _DO_NOT_EDIT.search(head))


def _tracked_backend_files() -> list[str]:
    proc = subprocess.run(["git", "-C", str(ROOT), "ls-files", "backends"],
                          capture_output=True, text=True)
    if proc.returncode != 0:                 # a source tarball, no git
        pytest.skip("not a git checkout")
    return proc.stdout.split()


def _swept(paths: list[str], read) -> list[str]:
    """The pure half, so the self-test below can feed it a synthetic tree."""
    out = []
    for rel in paths:
        try:
            text = read(rel)
        except (OSError, UnicodeDecodeError):
            continue
        if _looks_generated(text):
            out.append(rel)
    return sorted(out)


# --- artifacts deliberately outside the golden registry ---------------------
#
# Point 3 of issue #1089: compile-and-run (or a gate somewhere else) can be the
# whole contract for a particular artifact, but then the reason is written down
# where the next reader finds it, so the absence is a recorded decision rather
# than a gap. Each entry is a repo-relative path or a `dir/` prefix.
_EXEMPT: dict[str, str] = {
    "backends/typescript/tests/generated/": (
        "REGENERATED BEFORE EVERY RUN, not compared. backends/typescript/"
        "vitest.config.ts calls emitFixtures() while the config is being "
        "evaluated — before vitest resolves its include glob — so the bytes the "
        "suite typechecks and executes are always a fresh emission and there is "
        "no committed copy in the loop to go stale. The copy IS committed, but "
        "only so a cold checkout collects the same test files as a warm one "
        "(one of them, v3_tests.test.ts, is itself a test module); "
        "backends/typescript/tests/generated_coverage.test.ts pins that and the "
        "count of lowered `test` blocks. A byte gate here would compare a file "
        "the next run overwrites."
    ),
    "backends/typescript/tests/fixtures/a2a_agent.rvl": (
        "BYTE-GATED ELSEWHERE. It is `revl import a2a`'s output rather than a "
        "backend emitter's, and tests/test_import_a2a.py::"
        "test_the_ts_backend_fixture_is_current re-runs the importer on the "
        "committed Agent Card and compares. Its producer is "
        "backends/typescript/tests/fixtures/_gen_a2a_agent.py."
    ),
}


def _exempt(rel: str) -> bool:
    return any(rel == key or (key.endswith("/") and rel.startswith(key))
               for key in _EXEMPT)


def test_every_committed_emitted_artifact_is_declared_or_exempt():
    """The direction `regen_goldens.py`'s worker does not check: a committed
    file that says an emitter wrote it, and that no target owns, is regenerated
    by nothing and compared to nothing."""
    tracked = _tracked_backend_files()
    swept = _swept(tracked, lambda rel: (ROOT / rel).read_text(
        encoding="utf-8", errors="replace"))
    assert swept, ("the generated-header sweep matched nothing under backends/ — "
                   "it cannot fail, so it is not a gate")
    declared = _declared_files()
    undeclared = [rel for rel in swept if rel not in declared and not _exempt(rel)]
    assert not undeclared, (
        "committed emitted artifact(s) that no `tools/regen_goldens.py` target "
        "declares, so nothing regenerates them and `--check` cannot see them "
        "drift:\n  " + "\n  ".join(undeclared) +
        "\nEither add them to the target that produces them, or add an entry to "
        "_EXEMPT in this file saying what gates them instead.")


def test_every_exemption_still_names_a_real_file():
    """A stale exemption is a hole with a reason attached. Each entry must
    still match something on disk, and carry a reason long enough to be one."""
    tracked = set(_tracked_backend_files())
    for key, reason in _EXEMPT.items():
        if key.endswith("/"):
            assert any(rel.startswith(key) for rel in tracked), \
                f"_EXEMPT names {key}, which matches no tracked file"
        else:
            assert key in tracked, f"_EXEMPT names {key}, which is not tracked"
        assert len(reason) >= 80, f"_EXEMPT[{key}] needs a real reason, not a label"


def test_the_sweep_can_actually_fail():
    """Teeth. A synthetic tree carrying one emitted file that no target
    declares must come back as exactly that one file — and a hand-written file
    that merely mentions generated code must not."""
    tree = {
        "backends/fake/gen.go": "// Code generated by backends/fake/emit.py — DO NOT EDIT.\n",
        "backends/fake/hand.go": "// Talks about code generated by emit.py; edit freely.\n",
        "backends/fake/late.go": ("\n" * (_HEADER_LINES + 2)
                                  + "// Code generated by x — do not edit.\n"),
    }
    swept = _swept(sorted(tree), tree.__getitem__)
    assert swept == ["backends/fake/gen.go"], swept
    # and the undeclared arm reports it: no target owns backends/fake, and it
    # is not exempt, so this is precisely what the real check would raise on.
    declared = _declared_files()
    assert [rel for rel in swept if rel not in declared and not _exempt(rel)] == \
        ["backends/fake/gen.go"]


# --- the wiring: a gate is only a gate in a job that runs it ----------------

#: What a `requires` tool needs from the job that runs the check. `gofmt` ships
#: with the Go toolchain, so a job that sets Go up has it.
_TOOL_PROVIDERS: dict[str, tuple[str, ...]] = {"gofmt": ("actions/setup-go",)}

#: Tools every runner image has before a single step runs. `bash` is declared by
#: the shell-producer targets so that a machine without it loud-SKIPS instead of
#: dying halfway, not because a job has to install it.
_AMBIENT = frozenset({"bash"})

#: A `--check` step, with the flags and target names it carries. `--strict` and
#: `--check` are read as flags; bare words after them are target names.
_CHECK = re.compile(
    r"regen_goldens\.py\s+--check(?P<rest>(?:\s+--?[a-z-]+|\s+[a-z][a-z-]*)*)")


def _parse_check(run: str, known: set[str]) -> list[tuple[set[str], set[str]]]:
    """Every `--check` invocation in one `run:` block, as (targets, flags)."""
    out = []
    for match in _CHECK.finditer(run):
        flags = {word for word in match["rest"].split() if word.startswith("-")}
        named = {word for word in match["rest"].split() if word in known}
        out.append((named or set(known), flags))
    return out


def _jobs() -> dict[str, dict]:
    jobs: dict[str, dict] = {}
    for path in sorted(WORKFLOWS.glob("*.yml")):
        document = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
        for name, job in (document.get("jobs") or {}).items():
            jobs[f"{path.name}:{name}"] = job
    return jobs


def _checking_jobs(jobs: dict[str, dict], known: set[str],
                   require_strict: bool = False) -> dict[str, set[str]]:
    """job id -> the target names its `--check` steps cover. A `--check` with no
    target list covers every target.

    With `require_strict`, an invocation that omits `--strict` covers NOTHING:
    without it a target whose tool the job lacks loud-skips and the step still
    exits 0, so the job reports green having compared nothing for that target.
    That is the failure the placement rule exists to prevent, and a check that
    tolerates a skip is not evidence the job can see the target."""
    found: dict[str, set[str]] = {}
    for job_id, job in jobs.items():
        covered: set[str] = set()
        for step in job.get("steps") or []:
            for named, flags in _parse_check(step.get("run") or "", known):
                if require_strict and "--strict" not in flags:
                    continue
                covered |= named
        if covered:
            found[job_id] = covered
    return found


def _job_tools(job: dict) -> set[str]:
    """The `requires` tools a job provides, read off the actions it uses."""
    text = "\n".join(str(step.get("uses") or "") for step in (job.get("steps") or []))
    return set(_AMBIENT) | {tool for tool, markers in _TOOL_PROVIDERS.items()
                            if any(marker in text for marker in markers)}


def test_every_golden_target_is_drift_checked_by_a_job_that_can_see_it():
    """Issue #1083's shape, applied to the golden registry. Before this,
    `regen_goldens.py --check` ran in NO workflow at all — only in
    tools/pre_merge.sh, for one of eight targets — so seven targets' byte
    comparison happened on a developer's machine or nowhere.

    A target also has to be checked in a job that HAS its producer's tools:
    `worker()` prints `SKIP` and returns 3 for a missing tool, and the driver
    counts that as skipped rather than failed. A `--check go` in a job without
    Go is a green step that compared nothing."""
    targets = {t.name: t for t in _regen_goldens().TARGETS}
    jobs = _jobs()
    checking = _checking_jobs(jobs, set(targets), require_strict=True)
    assert checking, ("no CI job runs `tools/regen_goldens.py --check --strict`. "
                      "Every committed golden's byte comparison then happens "
                      "nowhere, or happens where it can silently skip.")
    gaps = []
    for name, target in targets.items():
        homes = [job_id for job_id, covered in checking.items()
                 if name in covered and set(target.requires) <= _job_tools(jobs[job_id])]
        if not homes:
            lax = _checking_jobs(jobs, set(targets))
            where = [job_id for job_id, covered in lax.items() if name in covered]
            gaps.append(f"{name} (requires {', '.join(target.requires) or 'no tools'}; "
                        f"checked in {', '.join(where) or 'no job'} — a job listed here "
                        f"either lacks those tools or omits --strict)")
    assert not gaps, (
        "golden target(s) with no CI job that both drift-checks them and "
        "provides their producer's tools:\n  " + "\n  ".join(gaps))


def test_the_ci_pairing_check_can_actually_fail():
    """Teeth for the pairing, against the exact bug it exists for: a `--check`
    of a tool-needing target in a job that does not provide the tool."""
    targets = {t.name: t for t in _regen_goldens().TARGETS}
    assert "go" in targets and "gofmt" in targets["go"].requires, \
        "the go target no longer requires gofmt — repoint this self-test"

    run = "python3 tools/regen_goldens.py --check --strict go"
    toolless = {"j": {"steps": [{"run": run}]}}
    assert _checking_jobs(toolless, set(targets), require_strict=True) == {"j": {"go"}}
    assert not set(targets["go"].requires) <= _job_tools(toolless["j"]), \
        "a job with no setup-go must not read as providing gofmt"

    tooled = {"j": {"steps": [{"uses": "actions/setup-go@v6"}, {"run": run}]}}
    assert set(targets["go"].requires) <= _job_tools(tooled["j"])

    # WITHOUT --strict the same step covers nothing: a missing tool would make
    # it skip and still exit 0, so it is not evidence the job checked anything.
    lax = {"j": {"steps": [{"uses": "actions/setup-go@v6"},
                           {"run": "python3 tools/regen_goldens.py --check go"}]}}
    assert _checking_jobs(lax, set(targets), require_strict=True) == {}
    assert _checking_jobs(lax, set(targets)) == {"j": {"go"}}

    # a bare `--check --strict` covers every target
    bare = {"j": {"steps": [{"run": "python3 tools/regen_goldens.py --check --strict"}]}}
    assert _checking_jobs(bare, set(targets), require_strict=True)["j"] == set(targets)


# --- the interpreter half: a check that cannot RUN is not a check -----------
#
# The first version of the CI wiring above put `rust`, `java` and `wasm` in
# `lint` on the reasoning that their producers are pure Python, which is true,
# and `lint` reported DRIFT for all three anyway. The producers never ran: the
# registry invoked every `regen.sh` as `sh <script>`, the scripts are bash
# (`set -euo pipefail`, `${BASH_SOURCE[0]}`), and `/bin/sh` is dash on ubuntu
# and bash-in-POSIX-mode on macOS. It passed on a developer machine and died on
# line 7 of every script in CI, and — because a producer that fails to run was
# reported with the same word as a golden that is stale — the output said the
# goldens had drifted.
#
# Both halves are gated below: the interpreter a script is invoked with must be
# the one its own shebang names, and the targets a toolchain-free job claims to
# check must actually complete with no toolchain on PATH.

def test_every_shell_producer_runs_under_the_interpreter_its_shebang_names():
    """`sh` is not a synonym for `bash`. A script whose shebang says bash and
    whose body uses bash syntax must be invoked as bash, or it dies on a
    POSIX-only shell and the driver reports whatever that looks like."""
    registry = _regen_goldens()
    checked = 0
    for target in registry.TARGETS:
        for argv in target.commands:
            script = ROOT / argv[-1]
            if not script.is_file():
                continue
            declared = registry.script_interpreter(script)
            if declared is None:
                continue
            checked += 1
            assert Path(argv[0]).name == declared, (
                f"{target.name} runs {argv[-1]} as `{argv[0]}`, but the script's "
                f"shebang names `{declared}`. On a runner whose /bin/sh is dash "
                f"this dies before its first command and the target is reported "
                f"as something other than what happened.")
            if declared in {"bash", "ksh", "zsh"}:
                # and it really is not POSIX-portable, so the pairing is load-
                # bearing rather than cosmetic
                body = script.read_text(encoding="utf-8")
                assert ("BASH_SOURCE" in body or "pipefail" in body), (
                    f"{argv[-1]} declares {declared} but uses nothing that needs "
                    f"it — either give it a `sh` shebang or leave this comment")
    assert checked >= 5, f"only inspected {checked} shell producer(s) — wrong paths?"


def _toolchain_free_shim(tmp: Path) -> Path:
    """A PATH holding a shell, python3 and coreutils, and no language toolchain.

    `sh` points at a POSIX-only shell when the machine has one (dash — what
    ubuntu runners use), because that is the difference between this check
    reproducing CI and rubber-stamping a developer machine where /bin/sh is
    bash."""
    import os
    import shutil as sh_mod
    shim = tmp / "bin"
    shim.mkdir(parents=True, exist_ok=True)
    for name in ("bash", "env", "dirname", "pwd", "mkdir", "cat", "rm", "cp",
                 "mv", "ls", "sed", "grep", "date", "printf", "uname", "sort",
                 "head", "tail", "wc", "diff", "git", "gzip", "chmod"):
        found = sh_mod.which(name)
        if found:
            (shim / name).symlink_to(found)
    assert (shim / "bash").exists(), "no bash on PATH; the producers cannot run at all"
    posix_sh = next((c for c in ("/bin/dash", "/usr/bin/dash", sh_mod.which("dash"))
                     if c and os.path.exists(c)), sh_mod.which("sh"))
    (shim / "sh").symlink_to(posix_sh)
    (shim / "python3").symlink_to(sys.executable)
    for absent in ("go", "gofmt", "cargo", "rustc", "javac", "java", "node",
                   "npm", "wasmtime", "wasm-tools"):
        assert not (shim / absent).exists(), f"{absent} leaked into the shim"
    return shim


def _lint_check_targets() -> set[str]:
    """The targets the `lint` job claims to check."""
    jobs = _jobs()
    known = {t.name for t in _regen_goldens().TARGETS}
    lint = next(job for job_id, job in jobs.items() if job_id.endswith(":lint"))
    covered: set[str] = set()
    for step in lint.get("steps") or []:
        for named, _flags in _parse_check(step.get("run") or "", known):
            covered |= named
    return covered


def test_the_toolchain_free_targets_really_need_no_toolchain(tmp_path):
    """The placement claim, executed instead of argued.

    `lint` installs ruff and nothing else, so every target it checks has to
    complete with no Go, Rust, JDK, Node or wasm tooling anywhere. Run exactly
    that list in exactly that environment. A target that cannot run there
    belongs in its own `backend-*` job beside `go`."""
    targets = _lint_check_targets()
    assert targets, "the lint job checks no golden targets — read the wrong job?"
    shim = _toolchain_free_shim(tmp_path)
    proc = subprocess.run(
        [str(shim / "python3"), "tools/regen_goldens.py", "--check", "--strict",
         *sorted(targets)],
        cwd=ROOT, capture_output=True, text=True,
        env={"PATH": str(shim), "HOME": str(tmp_path)})
    assert proc.returncode == 0, (
        "the targets `lint` checks do not all complete without a toolchain, so "
        "that job reports on goldens it cannot see:\n"
        + proc.stdout + proc.stderr)
    assert "SKIP" not in proc.stdout, (
        "a target `lint` claims to check SKIPPED there:\n" + proc.stdout)


def test_the_interpreter_and_placement_checks_can_fail(tmp_path):
    """Teeth for both. The shebang pairing is re-run against the exact
    arrangement that reached CI (`sh` for a bash script), and the toolchain-free
    run is re-run against a target that genuinely needs one."""
    registry = _regen_goldens()
    script = ROOT / "backends" / "rust" / "scenarios" / "crashproof" / "regen.sh"
    assert registry.script_interpreter(script) == "bash"
    assert Path("sh").name != "bash", "the pairing assertion would be vacuous"

    # `go` needs gofmt, so it must NOT pass in the toolchain-free environment —
    # which is the whole reason it is checked in `backend-go` instead.
    shim = _toolchain_free_shim(tmp_path)
    proc = subprocess.run(
        [str(shim / "python3"), "tools/regen_goldens.py", "--check", "--strict", "go"],
        cwd=ROOT, capture_output=True, text=True,
        env={"PATH": str(shim), "HOME": str(tmp_path)})
    assert proc.returncode != 0 and "SKIP" in proc.stdout, (
        "a toolchain-free run of the `go` target came back clean, so this check "
        "would not notice a target placed in a job that cannot see it:\n"
        + proc.stdout + proc.stderr)
    assert "go" not in _lint_check_targets(), \
        "the `go` target is listed in `lint`, where it can only skip"


# --- twinned outputs: one emission, committed at two paths -----------------
#
# Issue #1288, and the third shape of the same week's bug: a mechanism that
# existed and could not see the thing it named.
#
# `produce_rust` binds ONE emission to two committed paths,
# `backends/rust/golden/user_cache.rs` and the placement runner's
# `src/components.rs`. `--check` did compare both against a fresh generation,
# so it did fire — but it fired as "1 file(s) differ from a fresh generation",
# which is the sentence a stale golden prints, on a PR that had not touched
# rust at all. The real fact is narrower and decides what to do: these two are
# one emission from one input, so one of them moving alone is a defect
# whichever version is the right one. It was mis-diagnosed twice before a lane
# isolated it.
#
# The stray bytes were an `ir_version 3` emission of `examples/outcome.rvl`
# (the reference IR for this target is `"ir_version": 1`, and `ir_version` is
# stamped from the input, so they could not have come from this producer). They
# were the placement runner's per-composition codegen, which used to write that
# committed module and not put it back; a docs commit swept the leftover up.
#
# So the invariant is declared as data on the target, and checked twice: by
# `regen_goldens.py`'s worker, where a producer that acquires an UNdeclared
# twin pair is refused outright, and here, off disk, with no emitter and no
# toolchain — which is what makes it fire on the PR that moves the file.


def _twin_groups() -> list[tuple[object, tuple[str, ...]]]:
    return [(target, group)
            for target in _regen_goldens().TARGETS for group in target.twins]


def test_at_least_one_target_declares_twinned_outputs():
    """A gate with nothing to gate is not a gate. If the rust target ever stops
    committing its emission twice, delete this section rather than leaving it
    green over nothing."""
    assert _twin_groups(), (
        "no golden target declares `twins=`, so the byte-identity check below "
        "compares nothing")


def test_every_twin_group_names_real_files_its_own_target_declares():
    """A twin group is only as good as its paths: an undeclared or misspelled
    member is a group that silently covers one file."""
    for target, group in _twin_groups():
        assert len(group) >= 2, f"{target.name}: a twin group of {len(group)} path(s)"
        assert len(set(group)) == len(group), f"{target.name}: repeated path in {group}"
        for rel in group:
            assert rel in target.files, (
                f"{target.name} declares {rel} as a twin but does not declare it as "
                f"a file it owns, so nothing regenerates or compares it")
            assert (ROOT / rel).is_file(), f"{target.name}: {rel} does not exist"


def test_twinned_goldens_are_byte_identical_on_disk():
    """The gate. No emitter, no toolchain, no subprocess: it reads the committed
    bytes, so it reds on the commit that moves one of them."""
    registry = _regen_goldens()

    def read(rel: str) -> bytes | None:
        path = ROOT / rel
        return path.read_bytes() if path.is_file() else None

    mismatched: list[str] = []
    for target in registry.TARGETS:
        mismatched += registry.twin_mismatches(target, read)
    assert not mismatched, (
        "committed golden(s) that one producer emits identically have diverged:\n  "
        + "\n  ".join(mismatched)
        + "\nRegenerate that target (python3 tools/regen_goldens.py <target>) and "
          "review BOTH files' diffs. A file that moved on its own was written by "
          "something other than its producer.")


def test_the_twin_check_can_actually_fail():
    """Teeth, driven off a synthetic tree: the exact shape of #1288 (one member
    replaced) and the one next to it (one member missing) must both be caught,
    and an untouched group must not be."""
    registry = _regen_goldens()
    target, group = _twin_groups()[0]

    same = dict.fromkeys(group, b"one emission\n")
    assert registry.twin_mismatches(target, same.get) == [], \
        "a group whose members agree was reported as a mismatch"

    moved_alone = dict(same)
    moved_alone[group[-1]] = b"//! ir_version 3\n"
    reported = registry.twin_mismatches(target, moved_alone.get)
    assert len(reported) == 1, reported
    assert group[0] in reported[0] and group[-1] in reported[0], reported

    absent = {group[0]: b"one emission\n"}
    assert registry.twin_mismatches(target, absent.get), \
        "a missing twin reads as a pass, so deleting one member is invisible"


def test_an_undeclared_twin_pair_is_refused_at_the_producer():
    """The other direction, and the one that keeps this section honest as
    targets are added: a producer that starts writing one emission to two paths
    without declaring it must not be allowed to go quiet the way rust did."""
    registry = _regen_goldens()
    silent = registry.Target(name="fake", what="", files=("a.rs", "b.rs", "c.rs"))
    assert registry.undeclared_twins(silent, {"a.rs": "X", "b.rs": "X", "c.rs": "Y"}) \
        == [("a.rs", "b.rs")]
    assert registry.undeclared_twins(silent, {"a.rs": "X", "b.rs": "Y"}) == []

    declared = registry.Target(name="fake", what="", files=("a.rs", "b.rs"),
                               twins=(("a.rs", "b.rs"),))
    assert registry.undeclared_twins(declared, {"a.rs": "X", "b.rs": "X"}) == []
    # ...and a declaration the producer does not back is refused too, so the
    # group cannot rot into a claim nothing checks.
    assert registry.stale_twin_declarations(declared, {"a.rs": "X", "b.rs": "Y"}) \
        == [("a.rs", "b.rs")]
    assert registry.stale_twin_declarations(declared, {"a.rs": "X", "b.rs": "X"}) == []


def test_the_real_targets_declare_every_twin_pair_they_emit():
    """Applied to the shipped registry rather than a fixture: no target may own
    two byte-identical committed files without saying so. This is the check that
    would have made #1288 a one-line registry edit instead of a cross-PR
    diagnosis. It reads the committed bytes of each target's declared FILES (a
    target that names a directory brings its own `--check`), so it needs no
    emitter and runs everywhere."""
    registry = _regen_goldens()
    by_bytes: list[str] = []
    for target in registry.TARGETS:
        produced = {rel: (ROOT / rel).read_text(encoding="utf-8", errors="replace")
                    for rel in target.files
                    if (ROOT / rel).is_file()}
        for group in registry.undeclared_twins(target, produced):
            by_bytes.append(f"{target.name}: {', '.join(group)}")
    assert not by_bytes, (
        "golden target(s) own byte-identical committed files that no `twins=` "
        "group covers:\n  " + "\n  ".join(by_bytes)
        + "\nIf they are one emission, declare them; if the match is a "
          "coincidence, this check is in the wrong place and should say so.")
