// Generated by the revl cordis4j backend (ir_version 3) — do not edit.
// Target: cordis4j (github.com/1na-ko/cordis4j).
package revl;

import io.cordis4j.core.Context;
import io.cordis4j.core.Disposable;
import io.cordis4j.core.Disposables;
import io.cordis4j.core.Plugin;
import io.cordis4j.core.ServiceKey;

public final class Components {
    private Components() {}

    public sealed interface RevlResult<T, E> permits RevlResult.Ok, RevlResult.Err {
        record Ok<T, E>(T value) implements RevlResult<T, E> {}
        record Err<T, E>(E value) implements RevlResult<T, E> {}
    }

    public static RevlResult<String, String> begin_row() {
        return new RevlResult.Ok<>("row#1");
    }

    public static void delete_row(String id) {
        // in-memory inverse: recover models the referent, no host state to touch
    }

    // docs/design/teardown-contract.md: the shared bracket/transactional/
    // compensation two-phase teardown loop (item 243 Slice 2b, item 247).
    private static final class RevlFrame {
        private boolean committed = false;
        private final java.util.List<Residue> residue = new java.util.ArrayList<>();
        private final java.util.ArrayDeque<Phase2Task> phase2 = new java.util.ArrayDeque<>();

        private record Residue(String kind, String crossing, String attempted,
                                boolean attemptedFlag, String error, String outcome) {}

        private record Phase2Task(String crossing, String attempted, Runnable action) {}

        void commit() {
            committed = true;
        }

        /** `bracket` (acquire): replays on every teardown, clean unload and
         * abort alike. Guarded so a failed inverse never skips the remaining
         * Phase-1 entries (contract-grade severity: bracket-fault). */
        Disposable bracket(String crossing, String attempted, Runnable inverse) {
            return () -> {
                try {
                    inverse.run();
                } catch (RuntimeException | Error err) {
                    residue.add(new Residue("bracket-fault", crossing, attempted,
                            true, String.valueOf(err), "failed"));
                }
            };
        }

        /** `transactional` (item 243, witnessed): replays the declared inverse
         * ONLY on abort; a committed activation DISCHARGES it (the mutation is
         * the deliverable and persists). Anticipated failure severity:
         * restore-residue. */
        Disposable transactional(String crossing, String attempted, Runnable undo) {
            return () -> {
                if (committed) {
                    return;
                }
                try {
                    undo.run();
                } catch (RuntimeException | Error err) {
                    residue.add(new Residue("restore-residue", crossing, attempted,
                            true, String.valueOf(err), "failed"));
                }
            };
        }

        /** `transactionalMethod` (item 318): the per-tool-call H1 seam — a
         * witnessed fs mutation fired from a PROVIDE-METHOD body (per request),
         * after activation, whose inverse must outlive the method call and
         * survive until the component/session commits or aborts. On java this
         * is BEHAVIOURALLY IDENTICAL to `transactional`, and deliberately so:
         * the py tier has to PARK a method-registered entry in a separate
         * `_deferred_transactional` list and dispose it inside `drain`, because
         * on py `_committed` only flips at TEARDOWN (drain), so a method entry
         * disposed as an ordinary sibling would observe committed==false on a
         * clean unload and wrongly revert the deliverable. Java has no such
         * window: `committed` flips once at ACTIVATION-END (the emitted
         * apply()'s `frame.commit()` before it returns), strictly before any
         * provide-method can run and before any teardown, so the disposer this
         * returns already observes the settled commit bit when the enclosing
         * component's `fx` disposes it at unload. The ONE soundness rule the
         * emitter must honour is that this entry is tracked into the COMPONENT
         * ACTIVATION `fx` (the provider struct's `this.fx`), never a per-call
         * scope: a per-call scope would dispose it at method-return with
         * committed==true, discharging it and dropping the undo, so a later
         * abort could not revert it (residue). */
        Disposable transactionalMethod(String crossing, String attempted, Runnable undo) {
            return transactional(crossing, attempted, undo);
        }

        /** Session-level reject seam (item 318; item 245's explicit commit/abort
         * UX is the eventual driver). A component that activated cleanly has
         * already run `commit()`, so a later unload would discharge every
         * transactional entry and PERSIST its mutation. Calling `abort()` before
         * teardown flips the discriminator back to false, so the next `fx`
         * dispose replays every transactional inverse — the activation-body ones
         * AND the per-tool-call method-registered ones — and the mutations
         * revert. Idempotent. */
        void abort() {
            committed = false;
        }

        /** `compensation` (item 247): abort-only, best-effort, Phase 2. A
         * committed activation DISCHARGES it (never runs). On abort this
         * disposer fires during fx's native Phase-1 walk, interleaved with
         * bracket/transactional entries, so it must not run inline: it
         * enqueues, and `runPhase2()` drains the queue after fx's walk (and
         * therefore every Phase-1 inverse) has returned. */
        Disposable compensation(String crossing, String attempted, Runnable emit) {
            return () -> {
                if (committed) {
                    return;
                }
                phase2.addLast(new Phase2Task(crossing, attempted, emit));
            };
        }

        private void runGuarded(Phase2Task task) {
            try {
                task.action().run();
            } catch (RuntimeException | Error err) {
                residue.add(new Residue("compensation-residue", task.crossing(), task.attempted(),
                        true, String.valueOf(err), "failed"));
            }
        }

        /** Phase 2: LIFO within the compensation class (entries queue in the
         * order fx's native walk visits them, already reverse-registration
         * order), best-effort, bounded by REVL_COMPENSATION_BUDGET_MS /
         * REVL_COMPENSATION_PER_CALL_MS (default 5000/1000 ms). Never throws:
         * the abort always succeeds. */
        void runPhase2() {
            if (phase2.isEmpty()) {
                return;
            }
            long budgetMs = envMs("REVL_COMPENSATION_BUDGET_MS", 5000L);
            long perCallMs = envMs("REVL_COMPENSATION_PER_CALL_MS", 1000L);
            long deadline = budgetMs <= 0 ? Long.MAX_VALUE
                    : System.nanoTime() + budgetMs * 1_000_000L;
            java.util.concurrent.ExecutorService pool = null;
            try {
                while (!phase2.isEmpty()) {
                    Phase2Task next = phase2.pollFirst();
                    if (budgetMs > 0 && System.nanoTime() >= deadline) {
                        residue.add(new Residue("compensation-residue", next.crossing(), next.attempted(),
                                false, "deadline-expired", "not-attempted"));
                        continue;
                    }
                    if (perCallMs <= 0) {
                        runGuarded(next);
                        continue;
                    }
                    if (pool == null) {
                        pool = java.util.concurrent.Executors.newCachedThreadPool(r -> {
                            Thread t = new Thread(r, "revl-compensation");
                            t.setDaemon(true);
                            return t;
                        });
                    }
                    java.util.concurrent.Future<?> future = pool.submit(() -> runGuarded(next));
                    try {
                        future.get(perCallMs, java.util.concurrent.TimeUnit.MILLISECONDS);
                    } catch (java.util.concurrent.TimeoutException timeout) {
                        // java per-tier rule: cancel(true) preempts only an
                        // interruptible blocking point. When the compensation
                        // ignores it, the task keeps running DETACHED past this
                        // point (go's abandon-the-wait shape) -> outcome unknown.
                        future.cancel(true);
                        residue.add(new Residue("compensation-residue", next.crossing(), next.attempted(),
                                true, "per-call bound exceeded", "unknown"));
                    } catch (InterruptedException interrupted) {
                        Thread.currentThread().interrupt();
                        residue.add(new Residue("compensation-residue", next.crossing(), next.attempted(),
                                true, "teardown thread interrupted", "unknown"));
                    } catch (java.util.concurrent.ExecutionException impossible) {
                        // runGuarded() already catches RuntimeException/Error
                        // internally, so the submitted task never actually
                        // throws; this branch only satisfies future.get()'s
                        // checked signature.
                        residue.add(new Residue("compensation-residue", next.crossing(), next.attempted(),
                                true, String.valueOf(impossible.getCause()), "failed"));
                    }
                }
            } finally {
                if (pool != null) {
                    pool.shutdown();
                }
            }
        }

        private static long envMs(String name, long fallback) {
            String raw = System.getenv(name);
            if (raw == null || raw.isEmpty()) {
                return fallback;
            }
            try {
                return Long.parseLong(raw.trim());
            } catch (NumberFormatException bad) {
                return fallback;
            }
        }
    }

    // item 318: the per-activation Disposable an emitted frame-bearing apply()
    // returns instead of the bare `fx` EffectScope. It carries the component's
    // `RevlFrame` alongside `fx` so a session-level reject can reach it AFTER a
    // clean activation (mirrors the py tier's ctx->Frame reachability, which
    // item 245's commit/abort UX drives). `dispose()` runs the native Phase-1
    // LIFO walk (`fx.dispose()`) and then drains any Phase-2 compensations the
    // walk enqueued — a no-op on a clean unload (committed => every entry
    // discharges, nothing enqueues) and the abort drain when `abort()` was
    // called first. `abort()` flips the commit discriminator so that dispose
    // reverts rather than persists. Existing callers that only `dispose()` the
    // returned Disposable are unaffected.
    public static final class RevlActivation implements Disposable {
        private final Context.EffectScope fx;
        private final RevlFrame frame;

        RevlActivation(Context.EffectScope fx, RevlFrame frame) {
            this.fx = fx;
            this.frame = frame;
        }

        /** Session-level reject: revert this activation's transactional work
         * (activation-body AND per-tool-call) on the next dispose. */
        public void abort() {
            frame.abort();
        }

        @Override
        public void dispose() {
            fx.dispose();
            frame.runPhase2();
        }
    }

    // ---- durable WAL recording sink (item 322 Slice 2, the java host recording channel) ----

    private static final String REVL_WAL_GUARANTEE =
            "the WAL records each committed effect's step identity, boundary "
            + "classification and inverse DESCRIPTOR (not its closure). On restart, "
            + "recovery runs the reconstructible boundary inverses newest-first (LIFO); "
            + "in-process inverses are moot (their captured memory died with the "
            + "process) and closure-only boundary inverses are reported as residue, "
            + "never silently claimed to have run.";

    private static java.io.FileOutputStream revlWalOut;
    private static java.nio.channels.FileChannel revlWalChannel;
    private static int revlWalSeq = 0;
    private static final java.util.List<Integer> revlWalSeqs = new java.util.ArrayList<>();
    private static final Object revlWalLock = new Object();

    static {
        revlWalOpen();
    }

    // Wire the sink to REVL_WAL (unset -> no-op recording) and stamp the header.
    // Runs once at class load. A failed open leaves the sink null (recording is
    // silently off) rather than crashing a composition that only wanted to run.
    private static void revlWalOpen() {
        String path = System.getenv("REVL_WAL");
        if (path == null || path.isEmpty()) {
            return;
        }
        try {
            revlWalOut = new java.io.FileOutputStream(path, true);
            revlWalChannel = revlWalOut.getChannel();
        } catch (java.io.IOException open) {
            revlWalOut = null;
            revlWalChannel = null;
            return;
        }
        revlWalWrite("{\"record\":\"header\",\"walVersion\":1,\"generation\":1,\"guarantee\":"
                + revlWalStr(REVL_WAL_GUARANTEE) + "}");
    }

    // One durable JSON line: write, flush, and fsync (FileChannel.force(true))
    // before returning — the write-ahead discipline the py tier uses, so a record a
    // caller saw acknowledged is on disk before the effect it describes may matter.
    private static void revlWalWrite(String json) {
        if (revlWalOut == null) {
            return;
        }
        synchronized (revlWalLock) {
            try {
                revlWalOut.write((json + "\n").getBytes(java.nio.charset.StandardCharsets.UTF_8));
                revlWalOut.flush();
                revlWalChannel.force(true);
            } catch (java.io.IOException ignored) {
            }
        }
    }

    // revlRecordTransactional appends the discharge-descriptor for one witnessed
    // transactional inverse: the re-issuable named call {receiver, method, args}
    // recover replays LIFO to undo the mutation, plus the forward `origin` it
    // reverses. Fsync'd before it returns, so a crash after this call still leaves
    // the inverse re-issuable from the log alone.
    public static void revlRecordTransactional(String receiver, String method, String[] args) {
        if (revlWalOut == null) {
            return;
        }
        synchronized (revlWalLock) {
            int seq = revlWalSeq++;
            revlWalSeqs.add(seq);
            String call = revlWalCall(receiver, method, args);
            revlWalWrite("{\"record\":\"discharge-descriptor\",\"seq\":" + seq
                    + ",\"entry\":\"transactional\",\"call\":" + call
                    + ",\"origin\":" + call
                    + ",\"witness\":null,\"idempotency\":null}");
        }
    }

    // revlRecordDischarge writes the commit-path proof that every recorded
    // transactional seq COMMITTED, so recover SKIPS it — a committed transaction is
    // never rolled back. Called on a clean unload, never on a crash.
    public static void revlRecordDischarge() {
        if (revlWalOut == null) {
            return;
        }
        synchronized (revlWalLock) {
            StringBuilder discharged = new StringBuilder("[");
            for (int i = 0; i < revlWalSeqs.size(); i++) {
                if (i > 0) {
                    discharged.append(',');
                }
                discharged.append(revlWalSeqs.get(i));
            }
            discharged.append(']');
            revlWalWrite("{\"record\":\"discharge\",\"discharged\":" + discharged + "}");
        }
    }

    // revlRecordActivationComplete stamps the terminal marker: its presence is the
    // whole roll-forward decision, its absence (a crash) is roll-back. Written only
    // after a clean unload.
    public static void revlRecordActivationComplete() {
        if (revlWalOut == null) {
            return;
        }
        synchronized (revlWalLock) {
            revlWalWrite("{\"record\":\"activation-complete\",\"generation\":1,\"components\":[]}");
        }
    }

    private static String revlWalCall(String receiver, String method, String[] args) {
        StringBuilder call = new StringBuilder("{\"receiver\":");
        call.append(revlWalStr(receiver)).append(",\"method\":").append(revlWalStr(method))
                .append(",\"args\":[");
        for (int i = 0; i < args.length; i++) {
            if (i > 0) {
                call.append(',');
            }
            call.append(revlWalStr(args[i]));
        }
        call.append("]}");
        return call.toString();
    }

    // Minimal JSON string escaper (quote/backslash/control chars) — enough for the
    // identifiers and stringified witnesses this schema carries, and it never
    // depends on a JSON library the emitted module would otherwise not need.
    private static String revlWalStr(String value) {
        StringBuilder out = new StringBuilder("\"");
        for (int i = 0; i < value.length(); i++) {
            char c = value.charAt(i);
            switch (c) {
                case '"' -> out.append("\\\"");
                case '\\' -> out.append("\\\\");
                case '\n' -> out.append("\\n");
                case '\r' -> out.append("\\r");
                case '\t' -> out.append("\\t");
                default -> {
                    if (c < 0x20) {
                        out.append(String.format("\\u%04x", (int) c));
                    } else {
                        out.append(c);
                    }
                }
            }
        }
        out.append('"');
        return out.toString();
    }
    public static final class CrasherPlugin implements Plugin {
        public CrasherPlugin() {
        }
        @Override
        public Disposable apply(Context ctx) {
            Context.EffectScope fx = ctx.effect();
            RevlFrame frame = new RevlFrame();
            try {
                var _revl_wit4419035648 = begin_row();
                if (_revl_wit4419035648 instanceof RevlResult.Ok<?, ?> _revl_ok4419035648) {
                    String result = (String) _revl_ok4419035648.value();
                    revlRecordTransactional("begin_row", "delete_row", new String[]{String.valueOf(result)});
                    fx.track(frame.transactional("begin_row", "delete_row", () -> delete_row(result)));
                }
                frame.commit();
                return new RevlActivation(fx, frame);
            } catch (RuntimeException | Error failure) {
                fx.dispose();
                frame.runPhase2();
                throw failure;
            }
        }
    }

}
