// Code generated by backends/go/emit.py — DO NOT EDIT.
// revl -> cordis-go, targeting github.com/0xdenny218/stc-go.
package declaredcompensate

import (
	stdctx "context"
	"fmt"
	"os"
	"reflect"
	"slices"
	"strconv"
	"sync"
	"testing"
	"time"

	stc "github.com/0xdenny218/stc-go"
)

var _ = fmt.Sprintf

// ---- host runtime (minimal, recording) --------------------------------

// R1 live-resource accounting (docs/backend-ir.md §Required semantics, the
// same pairing the py reference tier's `assert no_residue` checks): every host
// object acquired must be released by its `undo`, or the lifecycle
// `assert no_residue` fails. The counter is package-wide, so it is per-test
// and cross-test safe: a clean test returns to zero.
var _revlLiveMu sync.Mutex
var _revlLiveHostResources int

func revlHostAcquire() { _revlLiveMu.Lock(); _revlLiveHostResources++; _revlLiveMu.Unlock() }
func revlHostRelease() { _revlLiveMu.Lock(); _revlLiveHostResources--; _revlLiveMu.Unlock() }
func revlHostLive() int {
	_revlLiveMu.Lock()
	defer _revlLiveMu.Unlock()
	return _revlLiveHostResources
}

// A deterministic in-memory stand-in for revl host objects, instrumented so
// scenarios can assert the exact effect/undo order of emitted code.

var _hostMu sync.Mutex
var _hostLog []string

func hostRecord(op string) {
	_hostMu.Lock()
	_hostLog = append(_hostLog, op)
	_hostMu.Unlock()
}

// HostMarks returns an ordered snapshot of host operations.
func HostMarks() []string {
	_hostMu.Lock()
	defer _hostMu.Unlock()
	out := make([]string, len(_hostLog))
	copy(out, _hostLog)
	return out
}

// HostReset clears the host op log (call between scenarios).
func HostReset() {
	_hostMu.Lock()
	_hostLog = nil
	_hostMu.Unlock()
}

// Row is a query result row.
type Row = map[string]string

// Pool is a deterministic in-memory connection pool.
type Pool struct {
	url  string
	size int64
}

func PoolOpen(url string, size int64) *Pool {
	hostRecord("pool.open")
	revlHostAcquire()
	return &Pool{url: url, size: size}
}
func (p *Pool) Close() { hostRecord("pool.close"); revlHostRelease() }
func (p *Pool) Query(sql string) []Row {
	hostRecord("pool.query:" + sql)
	return nil
}
func (p *Pool) Execute(sql string) int64 {
	hostRecord("pool.execute:" + sql)
	return 0
}

// Map is a thread-safe map with Str keys. The value type is generic — each
// site's `Map.new()` pins `V` from how the map is used (FR-4: a revl
// `Map[Str, Int]` counter or `Map[Str, List[Msg]]` ledger, not only String),
// mirroring backends/rust/emit.py's `struct Map<V>`. Emit instantiates it at
// the acquisition (`MapNew[int64]()`), so the boundary carries the declared
// value type and Insert/Get type-check against the component's real values.
type Map[V any] struct {
	mu sync.Mutex
	m  map[string]V
}

func MapNew[V any]() *Map[V] {
	hostRecord("map.new")
	revlHostAcquire()
	return &Map[V]{m: map[string]V{}}
}
func (m *Map[V]) Drop() { hostRecord("map.drop"); revlHostRelease() }
func (m *Map[V]) Insert(k string, v V) {
	m.mu.Lock()
	m.m[k] = v
	m.mu.Unlock()
}

// InsertIfAbsent is the atomic compare-and-set (item 397). The per-op mutex is
// held across BOTH the membership test AND the insert, so the whole CAS is one
// critical section: no concurrent caller can witness the probe and the write as
// separable steps. Returns whether it inserted; a false (key already present)
// leaves the existing value untouched. Under N concurrent callers on one map,
// exactly one receives true.
func (m *Map[V]) InsertIfAbsent(k string, v V) bool {
	m.mu.Lock()
	defer m.mu.Unlock()
	if _, ok := m.m[k]; ok {
		return false
	}
	m.m[k] = v
	return true
}
func (m *Map[V]) Remove(k string) {
	m.mu.Lock()
	delete(m.m, k)
	m.mu.Unlock()
}
func (m *Map[V]) Get(k string) (V, bool) {
	m.mu.Lock()
	defer m.mu.Unlock()
	v, ok := m.m[k]
	return v, ok
}

// Iteration surface (docs/stdlib-2.0.md §Map): the checker promises
// `size()`/`keys()` on a host `Map.new()` receiver too, and emit lowers both
// as method calls on this object. `Size` is the entry count as the tier's
// revl Int (int64, matching the service-method return type); `Keys`
// yields the keys in ascending canonical Str order (UTF-8 byte lexicographic —
// go string < is exactly code-point order, and slices.Sort on []string orders
// by <, so the order is identical to the insertion sort this replaced, as it
// is in revlMapKeys). keys() IS the Map iteration surface, so this sits on
// every map traversal: O(n log n), not O(n^2) (item 434 (h)). Both are
// read-only queries, no host trace — like Get.
func (m *Map[V]) Size() int64 {
	m.mu.Lock()
	defer m.mu.Unlock()
	return int64(len(m.m))
}
func (m *Map[V]) Keys() []string {
	m.mu.Lock()
	ks := make([]string, 0, len(m.m))
	for k := range m.m {
		ks = append(ks, k)
	}
	m.mu.Unlock()
	slices.Sort(ks)
	return ks
}

// ---- witnessed/compensation teardown accumulator (items 243/247, docs/design/teardown-contract.md) ----

// RevlTeardownRecord is one entry of the merged residue schema (docs/design/
// teardown-contract.md, "the merged residue schema"): a Phase-1 inverse that
// failed (`bracket-fault` / `restore-residue`) or a Phase-2 compensation that
// failed, timed out, or was never attempted (`compensation-residue`).
type RevlTeardownRecord struct {
	Kind           string // "restore-residue" | "bracket-fault" | "compensation-residue"
	CrossingKey    string
	CrossingMethod string
	AttemptedCall  string
	AttemptedPhase int    // 1 or 2
	ErrorType      string // e.g. "panic" | "deadline-expired" | "per-call-timeout"
	ErrorMessage   string
	Outcome        string // "failed" | "unknown" | "not-attempted"
	Referent       string // what is still out in the world
	Hint           string // recovery hint for the operator
}

// revlCompEntry is one queued Phase-2 compensation: the offsetting call,
// captured at registration (`emit X compensate Y`), never re-read at
// teardown (docs/design/teardown-contract.md, "no data hazard").
type revlCompEntry struct {
	key    string
	method string
	run    func() error
}

// RevlFrame is one component activation's teardown accumulator: the
// commit-vs-abort bit, the Phase-2 compensation queue, and the surfaced
// residue. Bracket inverses need none of this — they stay plain `ctx.Effect`
// disposers, unchanged.
type RevlFrame struct {
	committed bool // see the package-level note above: single-writer, no lock
	aborting  bool // item 318: session-level abort seam — see (*RevlFrame).Abort
	mu        sync.Mutex
	pending   []revlCompEntry
	residue   []RevlTeardownRecord
	deferred  []func() error // item 318: parked provide-method witnessed inverses
}

// item 318: a package-level registry of every activation frame created, the go
// mirror of the py reference tier's `_frame_for_ctx` — the seam a session/test
// reaches a live frame through to Abort() it before unload (item 245's reject
// UX will drive this in production; the H1 exec test drives it directly).
var (
	_revlFrameRegMu sync.Mutex
	_revlFrameReg   []*RevlFrame
)

func newRevlFrame() *RevlFrame {
	f := &RevlFrame{}
	_revlFrameRegMu.Lock()
	_revlFrameReg = append(_revlFrameReg, f)
	_revlFrameRegMu.Unlock()
	return f
}

// RevlFrames returns a snapshot of every activation frame created since the
// last RevlResetFrames — the seam for reaching a live frame to Abort it.
func RevlFrames() []*RevlFrame {
	_revlFrameRegMu.Lock()
	defer _revlFrameRegMu.Unlock()
	out := make([]*RevlFrame, len(_revlFrameReg))
	copy(out, _revlFrameReg)
	return out
}

// RevlResetFrames clears the frame registry (call between scenarios, like
// HostReset), so a test can find its own activation's sole frame.
func RevlResetFrames() {
	_revlFrameRegMu.Lock()
	_revlFrameReg = nil
	_revlFrameRegMu.Unlock()
}

// Abort marks this activation as ABORTING (item 318, the go mirror of
// Frame.abort): its next teardown replays every parked per-tool-call witnessed
// inverse instead of committing it. Idempotent; a plain unload never calls it,
// so a commit stays a commit.
func (f *RevlFrame) Abort() {
	f.aborting = true
}

// registerMethodWitnessed parks one provide-method witnessed inverse (item
// 318): a per-tool-call mutation whose rollback must outlive the method call
// and survive until the component/session commits or aborts. It is NOT a
// stc-go disposer (see commit() for why); commit() disposes it once the
// commit-vs-abort bit is settled.
func (f *RevlFrame) registerMethodWitnessed(run func() error) {
	f.mu.Lock()
	f.deferred = append(f.deferred, run)
	f.mu.Unlock()
}

// registerMethodCompensation parks one provide-method `emit ... compensate ...`
// offset (the item-247 method-body remainder): the compensation analog of
// registerMethodWitnessed, and the method-body analog of the activation-body
// `emit ... compensate ...` (item 247). A method body runs AFTER activation, so
// the offset must outlive the method call and is owed ONLY on an abort, never on
// a clean commit (the emission it offsets was the deliverable). It is NOT a
// stc-go disposer (see commit() for the disposal-ordering hazard); commit()
// disposes the parked closure once the commit-vs-abort bit is settled. On a
// COMMIT the closure discharges (never runs). On an ABORT it hands the offset to
// `enqueue`, so runCompensationPhase (registered first, hence run LAST on the
// unwind) fires it in Phase 2 — after every bracket/transactional/method-
// witnessed inverse in this activation has completed, guarded and residue-
// collected. `key`/`method` are the offsetting call's descriptor for the WAL and
// residue, captured here at registration (the "no data hazard" rule).
func (f *RevlFrame) registerMethodCompensation(key, method string, run func() error) {
	f.mu.Lock()
	f.deferred = append(f.deferred, func() error {
		if f.committed {
			return nil // discharge — the emission was the deliverable
		}
		f.enqueue(key, method, run) // abort: defer to Phase 2
		return nil
	})
	f.mu.Unlock()
}

// commit flips the discriminator a clean unload reads (item 243 decision 1,
// the go mirror of `Frame._committed`/`Frame.drain`): every transactional
// entry and every compensation observes `committed == true` from here on,
// meaning discharge instead of replay/run.
func (f *RevlFrame) commit() {
	// item 318: an Abort() may have requested revert of already-applied
	// per-tool-call work; honour it before flipping the bit every parked and
	// activation-body inverse reads.
	if !f.aborting {
		f.committed = true
	}
	// Dispose the parked provide-method witnessed inverses HERE, now that the
	// commit-vs-abort bit is settled (the go mirror of Frame.drain disposing
	// `_deferred_transactional`): on a commit each discharges (mutation
	// persists, witness GC'd), on an abort each replays (reverts). They are not
	// stc-go disposers, so this is their sole disposal — no double-free with the
	// fiber's own unwind. commit() is the LAST-registered inverse, hence stc-go
	// runs it FIRST on unwind, so this is ordered before any body inverse runs.
	//
	// item 369: replay in reverse INVOCATION order (LIFO), NOT registration
	// order. `deferred` is appended newest-last as each provide-method fires
	// (registerMethodWitnessed), so it must be drained newest-FIRST — exactly
	// like the activation-body path, where stc-go unwinds its disposer stack
	// LIFO. On a COMMIT order is immaterial (every entry no-op discharges); on
	// an ABORT two inverses whose paths OVERLAP must undo newest-first or a FIFO
	// replay leaves residue or DESTROYS pre-session data (every stdlib/fs.rvl
	// inverse is idempotent-and-total, so the oldest inverse runs first, no-ops,
	// and the newer one undoes into the hole — G7, 243 §2). Mirrors the py/ts
	// runtimes.
	f.mu.Lock()
	deferred := f.deferred
	f.deferred = nil
	f.mu.Unlock()
	for i := len(deferred) - 1; i >= 0; i-- {
		_ = deferred[i]()
	}
}

// enqueue defers one compensation to Phase 2 (item 247): called from a
// compensation's inverse when the activation is aborting, never on a commit
// (the commit branch returns before reaching this). Entries queue in the
// order stc-go's unwind visits them, which is already reverse-registration
// (LIFO) order — "LIFO within itself" (docs/design/teardown-contract.md)
// falls out for free from the enqueue order, no re-sorting needed.
func (f *RevlFrame) enqueue(key, method string, run func() error) {
	f.mu.Lock()
	f.pending = append(f.pending, revlCompEntry{key: key, method: method, run: run})
	f.mu.Unlock()
}

func (f *RevlFrame) recordResidue(rec RevlTeardownRecord) {
	f.mu.Lock()
	f.residue = append(f.residue, rec)
	f.mu.Unlock()
}

// Residue is a snapshot of the merged residue records this activation's
// abort teardown surfaced (docs/design/teardown-contract.md, "surface
// (residue)"). Empty on a clean commit or when nothing failed.
func (f *RevlFrame) Residue() []RevlTeardownRecord {
	f.mu.Lock()
	defer f.mu.Unlock()
	out := make([]RevlTeardownRecord, len(f.residue))
	copy(out, f.residue)
	return out
}

// revlNoCompensationBound is the "0 means no bound" sentinel: a Duration long
// enough that a timer armed with it never meaningfully fires (~292 years),
// so `runOneCompensation`'s select always resolves via the real call instead.
const revlNoCompensationBound = time.Duration(1<<63 - 1)

// revlEnvDurationMS reads a `REVL_*_MS` env var once per call (docs/design/
// teardown-contract.md, "Budget values… read once at activation"; reading it
// per Phase-2 run is equivalent for a value that a process never mutates
// mid-run, and keeps the accumulator free of package-level init ordering).
// Unset or unparsable falls back to `defaultMS`; `"0"` returns 0, the
// caller's "no bound" signal.
func revlEnvDurationMS(name string, defaultMS int64) time.Duration {
	v, ok := os.LookupEnv(name)
	if !ok || v == "" {
		return time.Duration(defaultMS) * time.Millisecond
	}
	n, err := strconv.ParseInt(v, 10, 64)
	if err != nil || n < 0 {
		return time.Duration(defaultMS) * time.Millisecond
	}
	return time.Duration(n) * time.Millisecond
}

// runCompensationPhase is Phase 2 of the two-phase abort (docs/design/
// teardown-contract.md): best-effort, bounded, and it never runs on a clean
// commit (a5a — discharge, the queue is simply never drained). Every queued
// compensation not yet started when the budget expires is recorded
// `compensation-residue` with `error: deadline-expired`, `attempted: false` —
// every skip is recorded, nothing silently dropped.
func (f *RevlFrame) runCompensationPhase() {
	if f.committed {
		return
	}
	f.mu.Lock()
	pending := f.pending
	f.pending = nil
	f.mu.Unlock()
	if len(pending) == 0 {
		return
	}

	budgetMS := revlEnvDurationMS("REVL_COMPENSATION_BUDGET_MS", 5000)
	perCallMS := revlEnvDurationMS("REVL_COMPENSATION_PER_CALL_MS", 1000)
	hasDeadline := budgetMS != 0
	var deadline time.Time
	if hasDeadline {
		deadline = time.Now().Add(budgetMS)
	}

	for _, entry := range pending {
		if hasDeadline && !time.Now().Before(deadline) {
			f.recordResidue(RevlTeardownRecord{
				Kind: "compensation-residue", CrossingKey: entry.key, CrossingMethod: entry.method,
				ErrorType: "deadline-expired",
				ErrorMessage: "the phase-2 compensation budget (REVL_COMPENSATION_BUDGET_MS) expired " +
					"before this compensation started",
				Outcome: "not-attempted", AttemptedPhase: 2, Referent: entry.key,
				Hint: "the phase-2 budget expired before " + entry.key + "." + entry.method +
					" ran; verify and finish by hand",
			})
			continue
		}
		bound := revlNoCompensationBound
		if perCallMS != 0 {
			bound = perCallMS
		}
		if hasDeadline {
			if remaining := time.Until(deadline); remaining < bound {
				bound = remaining
			}
		}
		f.runOneCompensation(entry, bound)
	}
}

// runOneCompensation runs one Phase-2 compensation with go's normative
// in-call preemption: abandon-the-wait (docs/design/teardown-contract.md,
// per-tier table). The call runs in its own goroutine; the runtime waits up
// to `bound` and, on timeout, stops waiting and moves on to the next
// compensation — the call keeps running DETACHED, recorded `outcome:
// unknown` (the emission may still land after this abort completed).
//
// The goroutine MUST recover its own panic and route it over the channel
// (go's per-tier obligation, docs/design/teardown-contract.md, "Per-tier
// loop obligations"): an unrecovered panic in a detached goroutine kills the
// whole process, turning a best-effort phase into a crash. And abandonment
// relaxes seriality — once one compensation is abandoned and the next one
// starts, both may be running concurrently; "LIFO within itself" pins the
// START order of Phase-2 compensations only, never mutual exclusion.
func (f *RevlFrame) runOneCompensation(entry revlCompEntry, bound time.Duration) {
	done := make(chan error, 1) // buffered: an abandoned goroutine's send never blocks
	go func() {
		defer func() {
			if r := recover(); r != nil {
				done <- fmt.Errorf("panic: %v", r)
			}
		}()
		done <- entry.run()
	}()

	if bound < 0 {
		bound = 0
	}
	timer := time.NewTimer(bound)
	defer timer.Stop()
	select {
	case err := <-done:
		if err != nil {
			f.recordResidue(RevlTeardownRecord{
				Kind: "compensation-residue", CrossingKey: entry.key, CrossingMethod: entry.method,
				ErrorType: "compensation-failed", ErrorMessage: err.Error(),
				Outcome: "failed", AttemptedCall: entry.method, AttemptedPhase: 2, Referent: entry.key,
				Hint: "the compensation " + entry.key + "." + entry.method +
					" failed; verify and finish by hand",
			})
		}
	case <-timer.C:
		// abandon-the-wait: the call keeps running detached (its own
		// panic-guard already contains whatever it does).
		f.recordResidue(RevlTeardownRecord{
			Kind: "compensation-residue", CrossingKey: entry.key, CrossingMethod: entry.method,
			ErrorType:    "per-call-timeout",
			ErrorMessage: "compensation exceeded its per-call bound (REVL_COMPENSATION_PER_CALL_MS); abandoned in flight",
			Outcome:      "unknown", AttemptedCall: entry.method, AttemptedPhase: 2, Referent: entry.key,
			Hint: "the compensation " + entry.key + "." + entry.method +
				" was abandoned in flight; it may still land — verify by hand",
		})
	}
}

// revlDeclaredCrossing parks the compensation an extern DECLARES
// (`extern emission fn put(..) compensate undo()`) for one crossing made from a
// provide method, in whatever position the call is written (issue #1511). go
// evaluates the call before this runs, so the entry is owed only for a crossing
// that returned; a panicking crossing registers nothing. It is the registration
// a site-spelled method `emit .. compensate ..` makes: discharged on commit,
// Phase 2 on abort, newest first.
func revlDeclaredCrossing[T any](f *RevlFrame, key, method string, value T, run func() error) T {
	f.registerMethodCompensation(key, method, run)
	return value
}

func double(n int64) int64 {
	return n * 2
}

func plain(k string) int64 {
	hostRecord("put:site")
	return 1
}

func undo_site() {
	hostRecord("comp:site")
}

func undo_statement() {
	hostRecord("comp:statement")
}

func put_statement(k string) int64 {
	hostRecord("put:statement")
	return 1
}

func undo_let() {
	hostRecord("comp:let")
}

func put_let(k string) int64 {
	hostRecord("put:let")
	return 1
}

func undo_return() {
	hostRecord("comp:return")
}

func put_return(k string) int64 {
	hostRecord("put:return")
	return 1
}

func undo_argument() {
	hostRecord("comp:argument")
}

func put_argument(k string) int64 {
	hostRecord("put:argument")
	return 1
}

func undo_ifarm() {
	hostRecord("comp:ifarm")
}

func put_ifarm(k string) int64 {
	hostRecord("put:ifarm")
	return 1
}

func undo_nested() {
	hostRecord("comp:nested")
}

func put_nested(k string) int64 {
	hostRecord("put:nested")
	return 1
}

func undo_unit() {
	hostRecord("comp:unit")
}

func put_unit(k string) {
	hostRecord("put:unit")
}

func undo_first() {
	hostRecord("comp:first")
}

func put_first(k string) int64 {
	hostRecord("put:first")
	return 1
}

func undo_boom() {
	hostRecord("comp:boom")
}

func put_boom(k string) int64 {
	hostRecord("put:boom")
	panic("put:boom failed")
}

func undo_act() {
	hostRecord("comp:act")
}

func put_act(k string) int64 {
	hostRecord("put:act")
	return 1
}

// service Ops
type Ops interface {
	RunStatement() int64
	RunLet() int64
	RunReturn() int64
	RunArgument() int64
	RunIfarm(c bool) int64
	RunNested() int64
	RunUnit() int64
	RunBoom() int64
}

// service Every
type Every interface {
	Run() int64
}

var _keyOps = stc.NewKey[Ops]("ops")
var _keyAll = stc.NewKey[Every]("all")

func Agent() stc.Component {
	return stc.Component{
		Name:    "Agent",
		Provide: []stc.Key{_keyOps},
		Apply: func(ctx *stc.Context) (stc.Inverse, error) {
			_revlFrame := newRevlFrame()
			if err := ctx.Effect(func() stc.Inverse {
				return func() error { _revlFrame.runCompensationPhase(); return nil }
			}); err != nil {
				return nil, err
			}
			if err := ctx.Effect(func() stc.Inverse {
				plain("k")
				return func() error {
					if _revlFrame.committed {
						return nil // item 247 a5a: discharge — never runs
					}
					_revlFrame.enqueue("undo_site", "undo_site", func() error { undo_site(); return nil })
					return nil
				}
			}); err != nil {
				return nil, err
			}
			_implOps := &Agent_ops{ctx: ctx, revlFrame: _revlFrame}
			if _, err := ctx.Provide(_keyOps, Ops(_implOps)); err != nil {
				return nil, err
			}
			return func() error { _revlFrame.commit(); return nil }, nil
		},
	}
}

type Agent_ops struct {
	ctx       *stc.Context
	revlFrame *RevlFrame
}

func (revlSelf *Agent_ops) RunStatement() int64 {
	revlDeclaredCrossing(revlSelf.revlFrame, "undo_statement", "undo_statement", put_statement("k"), func() error { undo_statement(); return nil })
	return 0
}

func (revlSelf *Agent_ops) RunLet() int64 {
	var a int64 = revlDeclaredCrossing(revlSelf.revlFrame, "undo_let", "undo_let", put_let("k"), func() error { undo_let(); return nil })
	_ = a
	return a
}

func (revlSelf *Agent_ops) RunReturn() int64 {
	return revlDeclaredCrossing(revlSelf.revlFrame, "undo_return", "undo_return", put_return("k"), func() error { undo_return(); return nil })
}

func (revlSelf *Agent_ops) RunArgument() int64 {
	var s int64 = double(revlDeclaredCrossing(revlSelf.revlFrame, "undo_argument", "undo_argument", put_argument("k"), func() error { undo_argument(); return nil }))
	_ = s
	return s
}

func (revlSelf *Agent_ops) RunIfarm(c bool) int64 {
	if c {
		revlDeclaredCrossing(revlSelf.revlFrame, "undo_ifarm", "undo_ifarm", put_ifarm("k"), func() error { undo_ifarm(); return nil })
	}
	return 0
}

func (revlSelf *Agent_ops) RunNested() int64 {
	var b int64 = (revlDeclaredCrossing(revlSelf.revlFrame, "undo_nested", "undo_nested", put_nested("k"), func() error { undo_nested(); return nil }) + 1)
	_ = b
	return b
}

func (revlSelf *Agent_ops) RunUnit() int64 {
	func() {
		put_unit("k")
		revlSelf.revlFrame.registerMethodCompensation("undo_unit", "undo_unit", func() error { undo_unit(); return nil })
	}()
	return 0
}

func (revlSelf *Agent_ops) RunBoom() int64 {
	revlDeclaredCrossing(revlSelf.revlFrame, "undo_first", "undo_first", put_first("k"), func() error { undo_first(); return nil })
	return revlDeclaredCrossing(revlSelf.revlFrame, "undo_boom", "undo_boom", put_boom("k"), func() error { undo_boom(); return nil })
}

func Full() stc.Component {
	return stc.Component{
		Name:    "Full",
		Provide: []stc.Key{_keyAll},
		Apply: func(ctx *stc.Context) (stc.Inverse, error) {
			_revlFrame := newRevlFrame()
			if err := ctx.Effect(func() stc.Inverse {
				return func() error { _revlFrame.runCompensationPhase(); return nil }
			}); err != nil {
				return nil, err
			}
			if err := ctx.Effect(func() stc.Inverse {
				put_act("k")
				return func() error {
					if _revlFrame.committed {
						return nil // item 247 a5a: discharge — never runs
					}
					_revlFrame.enqueue("undo_act", "undo_act", func() error { undo_act(); return nil })
					return nil
				}
			}); err != nil {
				return nil, err
			}
			_implAll := &Full_all{ctx: ctx, revlFrame: _revlFrame}
			if _, err := ctx.Provide(_keyAll, Every(_implAll)); err != nil {
				return nil, err
			}
			return func() error { _revlFrame.commit(); return nil }, nil
		},
	}
}

type Full_all struct {
	ctx       *stc.Context
	revlFrame *RevlFrame
}

func (revlSelf *Full_all) Run() int64 {
	revlDeclaredCrossing(revlSelf.revlFrame, "undo_statement", "undo_statement", put_statement("k"), func() error { undo_statement(); return nil })
	var a int64 = revlDeclaredCrossing(revlSelf.revlFrame, "undo_let", "undo_let", put_let("k"), func() error { undo_let(); return nil })
	_ = a
	var s int64 = double(revlDeclaredCrossing(revlSelf.revlFrame, "undo_argument", "undo_argument", put_argument("k"), func() error { undo_argument(); return nil }))
	_ = s
	if true {
		revlDeclaredCrossing(revlSelf.revlFrame, "undo_ifarm", "undo_ifarm", put_ifarm("k"), func() error { undo_ifarm(); return nil })
	}
	plain("k")
	revlSelf.revlFrame.registerMethodCompensation("undo_site", "undo_site", func() error { undo_site(); return nil })
	var b int64 = (revlDeclaredCrossing(revlSelf.revlFrame, "undo_nested", "undo_nested", put_nested("k"), func() error { undo_nested(); return nil }) + 1)
	_ = b
	return revlDeclaredCrossing(revlSelf.revlFrame, "undo_return", "undo_return", put_return("k"), func() error { undo_return(); return nil })
}

func LoadAgent(target *stc.Context) *stc.Fiber {
	return target.Load(Agent())
}

func LoadFull(target *stc.Context) *stc.Fiber {
	return target.Load(Full())
}

// ---- lifecycle tests (docs/syntax-2.0.md §7.1) ----------------
// A `lifecycle test` drives the composition on a live stc-go
// context: load components, call through provision keys, unload
// LIFO, and assert no residue (R4 registry + R1 host resources).
type revlOptPair[T any] struct {
	value T
	ok    bool
}

func revlEq(a, b any) bool { return reflect.DeepEqual(a, b) }

func revlListIndexOfEq[T any](xs []T, x T) int64 {
	for i, v := range xs {
		if revlEq(v, x) {
			return int64(i)
		}
	}
	return -1
}

func TestCleanUnloadOfAnUnCalledAgentLeavesNoResidue(revlT *testing.T) {
	root := stc.New()
	_fibers := map[string]*stc.Fiber{}
	{
		_f := LoadAgent(root)
		if err := _f.Ready(stdctx.Background()); err != nil {
			revlT.Fatalf("%s: %v", "lifecycle test \"clean unload of an un-called agent leaves no residue\": load Agent", err)
		}
		_fibers["Agent"] = _f
	}
	if _f, _ok := _fibers["Agent"]; _ok {
		_f.Dispose()
		// disposal is orchestrated asynchronously; a
		// reload must not collide with the old fiber's
		// provisions, so wait for it to be Gone
		for i := 0; i < 200 && _f.State() != stc.StateGone; i++ {
			time.Sleep(5 * time.Millisecond)
		}
		delete(_fibers, "Agent")
	}
	// R4 + R1: the composition must leave the live
	// runtime holding nothing — the orchestrator reaps
	// disposed fibers asynchronously, so poll briefly.
	for i := 0; i < 200; i++ {
		if len(root.Fibers()) == 0 && revlHostLive() == 0 {
			break
		}
		time.Sleep(5 * time.Millisecond)
	}
	if !(len(root.Fibers()) == 0 && revlHostLive() == 0) {
		revlT.Fatalf("lifecycle test \"clean unload of an un-called agent leaves no residue\": residue \u2014 %d fiber(s), %d host resource(s) (R4/R1)", len(root.Fibers()), revlHostLive())
	}
}
