#!/usr/bin/env python3
"""Regenerate `js/examples.js` — the playground's preloaded programs.

Embedding (rather than fetching) means the examples load with zero extra
network round-trips and work regardless of how the static site is served.
Run from anywhere:  python3 site/gen_examples.py
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = Path(__file__).resolve().parent / "js" / "examples.js"

# (id, label, kind, path-relative-to-repo-root)
EXAMPLES = [
    ("live_counter", "★ live demo — boot it, call it, evolve it", "accept",
     "examples/live_counter.rvl"),
    ("playground_shell", "◐ the playground itself — swap the UI you're using", "accept",
     "site/playground_shell.rvl"),
    ("user_cache", "user_cache — effect/undo + a declared emission", "accept",
     "examples/user_cache.rvl"),
    ("outcome", "outcome — ADTs, Result and match (2.0)", "accept",
     "examples/outcome.rvl"),
    ("tenants", "tenants — realms: two providers, one key (2.0)", "accept",
     "examples/tenants.rvl"),
    ("verified_effect", "verified effect — inverses, round-trip tested", "accept",
     "examples/verified_effect.rvl"),
    ("heartbeat", "heartbeat — every/after timers as revertible schedules", "accept",
     "examples/heartbeat.rvl"),
    ("lifecycle_timer", "timers under test — advance the clock, assert firings", "accept",
     "examples/lifecycle_timer.rvl"),
    ("handoff_cache", "state handoff — a hot-swap that keeps the cache warm", "accept",
     "examples/handoff_cache.rvl"),
    ("tenant_attenuation", "spawn attenuation — least authority per instance", "accept",
     "examples/tenant_attenuation.rvl"),
    ("durable_log", "durable resources — acquire and the two undos", "accept",
     "examples/durable_log.rvl"),
    ("beacon", "beacon — polyglot mesh (wasm tier)", "accept",
     "examples/beacon.rvl"),
    ("g3_cycle", "G3 — dependency cycle (why-trace)", "reject",
     "examples/rejections/g3_dependency_cycle.rvl"),
    ("g1_undeclared", "G1 — undeclared access", "reject",
     "examples/rejections/g1_undeclared_access.rvl"),
    ("g2_conflict", "G2 — provision conflict", "reject",
     "examples/rejections/g2_provision_conflict.rvl"),
    ("g4_missing_undo", "G4 — mutation without an inverse", "reject",
     "examples/rejections/g4_missing_undo.rvl"),
    ("g4_emission", "G4 — undeclared emission", "reject",
     "examples/rejections/g4_emission_not_declared.rvl"),
    ("a1_async", "A1 — sync method reaching an async extern", "reject",
     "examples/rejections/a1_async_extern_sync_method.rvl"),
    ("g4_spawn", "G4 — spawn may narrow, never widen", "reject",
     "examples/rejections/g4_spawn_widens_capability.rvl"),
    ("t2_null", "T2 — there is no null (Opt[T])", "reject",
     "examples/rejections/t2_null_in_expression.rvl"),
    ("v2_match", "2.0 — non-exhaustive match", "reject",
     "examples/rejections/v2_match_nonexhaustive.rvl"),
]


def main() -> None:
    payload = []
    for ex_id, label, kind, rel in EXAMPLES:
        source = (ROOT / rel).read_text(encoding="utf-8")
        payload.append({"id": ex_id, "label": label, "kind": kind,
                        "file": Path(rel).name, "source": source})
    body = json.dumps(payload, indent=2, ensure_ascii=False)
    OUT.write_text(
        "// Generated by site/gen_examples.py — do not edit by hand.\n"
        "// Preloaded revl programs, embedded so the playground needs no\n"
        "// extra fetches. Regenerate with: python3 site/gen_examples.py\n"
        f"export const EXAMPLES = {body};\n",
        encoding="utf-8",
    )
    print(f"wrote {OUT.relative_to(ROOT)} ({len(payload)} examples)")


if __name__ == "__main__":
    main()
