//! Generated by the revl cordis-rs backend (ir_version 1) — do not edit.
//! Target: cordis-rs 0.3.x (docs.rs/cordis-rs).
#![allow(dead_code, unused_variables)]

use std::sync::Arc;
use cordis::Value;

pub trait Database: Send + Sync {
    fn query(&self, sql: String) -> Vec<Value>;
    /// emission — crosses the system boundary (DESIGN.md §3.5)
    fn execute(&self, sql: String) -> i64;
}

pub trait Cache: Send + Sync {
    fn get(&self, key: String) -> Option<String>;
    fn put(&self, key: String, value: String) -> ();
}

/// revl host object: a small thread-safe string map.
pub struct Map {
    inner: std::sync::Arc<std::sync::Mutex<std::collections::HashMap<String, String>>>,
}
impl Map {
    pub fn new() -> Self {
        Self {
            inner: std::sync::Arc::new(std::sync::Mutex::new(std::collections::HashMap::new())),
        }
    }
    pub fn drop_(&self) {
        self.inner.lock().unwrap().clear();
    }
    pub fn insert(&self, key: String, value: String) {
        self.inner.lock().unwrap().insert(key, value);
    }
    pub fn remove(&self, key: String) {
        self.inner.lock().unwrap().remove(&key);
    }
    pub fn get(&self, key: String) -> Option<String> {
        self.inner.lock().unwrap().get(&key).cloned()
    }
}

/// revl host object: a deterministic in-memory database fake.
pub struct Pool {
    _url: String,
    _size: i64,
}
impl Pool {
    pub fn open(url: String, size: i64) -> Self {
        Self { _url: url, _size: size }
    }
    pub fn close(&self) {}
    pub fn query(&self, _sql: String) -> Vec<Value> {
        vec![Value::new(String::from("fake-row"))]
    }
    pub fn execute(&self, _sql: String) -> i64 {
        1i64
    }
}

#[derive(Clone)]
struct PgDatabaseConfig {
    url: String,
    pool_size: i64,
}

impl Default for PgDatabaseConfig {
    fn default() -> Self {
        Self {
            url: String::new(),
            pool_size: 10i64,
        }
    }
}

struct PgDatabaseDb {
    pool: Arc<Pool>,
}
impl Database for PgDatabaseDb {
    fn query(&self, sql: String) -> Vec<Value> { self.pool.query(sql) }
    fn execute(&self, sql: String) -> i64 { self.pool.execute(sql) }
}

pub fn pg_database() -> cordis::PluginHandle {
    cordis::plugin_sync::<PgDatabaseConfig, _>(
        "PgDatabase",
        cordis::Inject::none(),
        |ctx, config| {
            let config = PgDatabaseConfig {
                url: config.url.clone(),
                pool_size: config.pool_size.clone(),
                ..Default::default()
            };
            let pool = Arc::new(Pool::open(config.url.clone(), config.pool_size.clone()));
            let pool_undo = pool.clone();
            ctx.effect("PgDatabase.pool.undo", move || { pool_undo.close(); Ok(()) })?;
            let db_box: Box<dyn Database> = Box::new(PgDatabaseDb { pool: pool.clone() });
            ctx.provide("db", db_box)?;
            Ok(cordis::PluginOutput::none())
        },
    )
}

struct UserCacheCache {
    store: Arc<Map>,
    db: Arc<Box<dyn Database>>,
    ctx: Arc<cordis::Context>,
}
impl Cache for UserCacheCache {
    fn get(&self, key: String) -> Option<String> { self.store.get(key) }
    fn put(&self, key: String, value: String) -> () {
        let store_undo = self.store.clone();
        let db_undo = self.db.clone();
        let key_undo = key.clone();
        let value_undo = value.clone();
        let _ = self.store.insert(key.clone(), value.clone());
        let _ = self.ctx.effect("UserCache.put.effect.0", move || { store_undo.remove(key_undo); Ok(()) });
        let _ = self.db.execute(format!("INSERT INTO cache_log VALUES ({0})", key.clone()));
    }
}

pub fn user_cache() -> cordis::PluginHandle {
    cordis::plugin_sync::<(), _>(
        "UserCache",
        cordis::Inject::new(["db"]),
        |ctx, config| {
            let db = ctx.require::<Box<dyn Database>>("db")?;
            let store = Arc::new(Map::new());
            let store_undo = store.clone();
            let db_undo = db.clone();
            ctx.effect("UserCache.store.undo", move || { store_undo.drop_(); Ok(()) })?;
            let cache_box: Box<dyn Cache> = Box::new(UserCacheCache { store: store.clone(), db: db.clone(), ctx: Arc::new(ctx.clone()) });
            ctx.provide("cache", cache_box)?;
            Ok(cordis::PluginOutput::none())
        },
    )
}
