//! cordis-rs placement runner: one process of a `revl run --placement`
//! composition placed on the Rust backend. Reads a spec JSON (argv[1]),
//! consumes cross-process keys through emitter-generated proxies, loads its own
//! cordis-rs components, optionally serves its provided keys over a socket,
//! runs probes, and (unless "once") holds until stdin closes OR a provider
//! dies (peer death withdraws the proxy so the consumer deactivates), then tears down.
//!
//! The proxies, the stub dispatch, and the component name->plugin table are all
//! GENERATED by backends/rust/emit.py into `components` (per composition), so
//! this runner carries no composition-specific knowledge: cordis-rs services
//! are static traits, so generality is codegen, not a runtime-generic proxy.

use serde_json::Value as J;
use std::io::{BufRead, BufReader, Read, Write};
use std::os::unix::net::{UnixListener, UnixStream};

mod components;
mod confidential;
mod estop;

fn args_of(probe: &J) -> Vec<J> {
    probe["args"].as_array().cloned().unwrap_or_default()
}

/// The contexts the served keys resolve in, filled as each key's provider
/// activates, and the keys refused by name (issue #1567).
type Served = std::sync::Arc<std::sync::Mutex<std::collections::HashMap<String, cordis::Context>>>;

/// Where a served or probed key resolves (issue #1567).
enum Resolved {
    In(cordis::Context),
    Refused(String),
}

/// Resolve `key` in the py tier's `resolve_key` order, off the spec's
/// `placements` (key -> this process's provisions of it, each with its realm):
/// the shared realm when the key is provided there, or when this process does
/// not provide it at all (a proxy); else its one isolated realm, read through
/// the providing component's isolated context (`_revl_isolate_ctx`, the context
/// `_revl_load` plugged it into). A key isolated in two or more realms has no
/// single provider for a call that names only the key, so it is refused naming
/// each provider and realm. A shared-realm read of an isolated key used to
/// leave the probe or serve plugin Pending forever, and the runner panicked.
fn resolve_key(root: &cordis::Context, placements: &J, key: &str) -> Resolved {
    let at = placements[key].as_array().cloned().unwrap_or_default();
    if at.is_empty() || at.iter().any(|p| p["realm"].is_null()) {
        return Resolved::In(root.clone());
    }
    if at.len() == 1 {
        let plugin = at[0]["plugin"].as_str().unwrap_or("");
        return Resolved::In(components::_revl_isolate_ctx(root, plugin));
    }
    let where_: Vec<String> = at
        .iter()
        .map(|p| format!("`{}` in realm `{}`",
                         p["component"].as_str().unwrap_or("?"), p["realm"].as_str().unwrap_or("?")))
        .collect();
    Resolved::Refused(format!(
        "key '{key}' is provided in {} realms ({}); a call names a key, not a realm, so it has no single provider to reach",
        at.len(), where_.join(", ")))
}

/// What this process serves: the keys other processes consume from it
/// (`serve.keys`) and, per key, the operations its service declaration admits
/// (`serve.methods`, the allowlist `placement.py` reads off the IR).
///
/// The generated `_revl_invoke` resolves EVERY key the document's components
/// provide, and answers a key or method it does not know with `null`, which
/// `handle_conn` used to wrap in `"ok": true` (issue #1599). So a raw call
/// reached a key this process provides but does not export, and a refused call
/// read as an answer. A request outside this surface is now refused with the
/// py bridge's wording and never dispatched.
struct Exported {
    keys: std::collections::BTreeSet<String>,
    methods: std::collections::BTreeMap<String, std::collections::BTreeSet<String>>,
}

impl Exported {
    fn from_spec(serve: &serde_json::Map<String, J>) -> Exported {
        let names = |v: &J| -> std::collections::BTreeSet<String> {
            v.as_array()
                .map(|a| {
                    a.iter()
                        .filter_map(|x| x.as_str().map(|s| s.to_string()))
                        .collect()
                })
                .unwrap_or_default()
        };
        let keys = serve.get("keys").map(names).unwrap_or_default();
        let methods = serve
            .get("methods")
            .and_then(|m| m.as_object())
            .map(|m| m.iter().map(|(k, v)| (k.clone(), names(v))).collect())
            .unwrap_or_default();
        Exported { keys, methods }
    }

    /// The refusal for a request outside the surface, or `None`. A key with
    /// no `methods` entry is left to the generated dispatch.
    fn refusal(&self, key: &str, method: &str) -> Option<String> {
        if !self.keys.contains(key) {
            return Some(format!("key '{key}' is not exported by this process"));
        }
        match self.methods.get(key) {
            Some(ops) if !ops.contains(method) => {
                let listed = if ops.is_empty() {
                    "(none)".to_string()
                } else {
                    ops.iter().cloned().collect::<Vec<_>>().join(", ")
                };
                Some(format!(
                    "method '{method}' is not exported for key '{key}' (exported: {listed})"
                ))
            }
            _ => None,
        }
    }
}

/// Provider side: dispatch one connection's requests to locally-provided
/// services via the generated `_revl_invoke`, inside the exported surface and
/// each in the context its key resolves in. The allowlist is checked first, so
/// a request outside the surface never reaches realm resolution.
fn handle_conn(
    stream: UnixStream,
    served: &Served,
    refused: &std::collections::HashMap<String, String>,
    exported: &Exported,
) {
    let reader = BufReader::new(match stream.try_clone() {
        Ok(s) => s,
        Err(_) => return,
    });
    let mut writer = stream;
    for line in reader.lines() {
        let line = match line {
            Ok(l) => l,
            Err(_) => break,
        };
        if line.is_empty() {
            continue;
        }
        let req: J = match serde_json::from_str(&line) {
            Ok(v) => v,
            Err(_) => continue,
        };
        let key = req["key"].as_str().unwrap_or("");
        let method = req["method"].as_str().unwrap_or("");
        let args = req["args"].as_array().cloned().unwrap_or_default();
        // item 443 / issue #122 — the ACCEPT side of the E-Stop seam. Once an
        // operator arms the latch this process REFUSES a new crossing before the
        // service method runs: nothing new crosses the boundary. The reply is an
        // error, not a value, and (unlike a cooperative teardown) no inverse is
        // replayed and nothing is discharged — the caller's attempt lands in
        // item 440's ambiguous tier, the designed outcome of a halt
        // (docs/design/443-estop.md).
        if estop::estop_engaged() {
            let reply = serde_json::json!({
                "ok": false,
                "error": format!(
                    "revl E-Stop engaged: this process is HALTED and refuses new \
                     crossings (key {key}, method {method}) — docs/design/443-estop.md"),
            });
            let mut out = serde_json::to_string(&reply).unwrap_or_else(|_| "{\"ok\":false}".into());
            out.push('\n');
            if writer.write_all(out.as_bytes()).is_err() {
                break;
            }
            continue;
        }
        if let Some(error) = exported.refusal(key, method) {
            let reply = serde_json::json!({ "ok": false, "error": error });
            let mut out = serde_json::to_string(&reply).unwrap_or_else(|_| "{\"ok\":false}".into());
            out.push('\n');
            if writer.write_all(out.as_bytes()).is_err() {
                break;
            }
            continue;
        }
        // Record the crossing as in flight WHILE its handler runs: a crossing
        // still executing when the latch trips is the AMBIGUOUS one the halt
        // inventory names (item 440). The guard clears it on any exit.
        let resolved = served.lock().ok().and_then(|m| m.get(key).cloned());
        let reply = match resolved {
            Some(ctx) => {
                let value = {
                    let _guard = estop::CrossingGuard::new(key, method, "accept");
                    components::_revl_invoke(&ctx, key, method, &args)
                };
                serde_json::json!({ "ok": true, "value": value })
            }
            None => serde_json::json!({
                "ok": false,
                "error": refused.get(key).cloned()
                    .unwrap_or_else(|| format!("key {key} is not exported by this process")),
            }),
        };
        let mut out = serde_json::to_string(&reply).unwrap_or_else(|_| "{\"ok\":false}".into());
        out.push('\n');
        if writer.write_all(out.as_bytes()).is_err() {
            break;
        }
    }
}

/// A plugin that requires one served key in the context it is plugged into
/// (so its provider component has activated there) and records that context
/// for the accept loop.
fn serve_plugin(key: String, served: Served) -> cordis::PluginHandle {
    cordis::plugin_sync::<(), _>("RevlServe", cordis::Inject::new([key.as_str()]), move |ctx, _config| {
        if let Ok(mut map) = served.lock() {
            map.insert(key.clone(), ctx.clone());
        }
        Ok(cordis::PluginOutput::none())
    })
}

/// The blocking accept loop that serves every key, each in its own context.
fn spawn_listener(
    socket: String,
    served: Served,
    refused: std::collections::HashMap<String, String>,
    exported: Exported,
) {
    let refused = std::sync::Arc::new(refused);
    let exported = std::sync::Arc::new(exported);
    std::thread::spawn(move || {
        let _ = std::fs::remove_file(&socket);
        let listener = match UnixListener::bind(&socket) {
            Ok(l) => l,
            Err(_) => return,
        };
        for conn in listener.incoming() {
            if let Ok(stream) = conn {
                let served = served.clone();
                let refused = refused.clone();
                let exported = exported.clone();
                std::thread::spawn(move || handle_conn(stream, &served, &refused, &exported));
            }
        }
    });
}

/// A driver plugin that requires `key` and runs one probe call during its
/// activation (the runtime has no root-level require, so probing rides a plugin).
fn probe_plugin(name: String, key: String, method: String, args: Vec<J>) -> cordis::PluginHandle {
    cordis::plugin_sync::<(), _>("RevlProbe", cordis::Inject::new([key.as_str()]), move |ctx, _config| {
        let value = components::_revl_invoke(&ctx, &key, &method, &args);
        // item 421 F6(c): this line is written by the runner, not by the emitted
        // runtime, so it does not pass through the emitted trace choke point.
        // The returned value is the one thing on this channel that can hold a
        // registered secret, so the whole rendered line goes through the funnel
        // (confidential.rs) rather than the value alone.
        println!("{}", confidential::revl_redact_text(format!(
            "[{name}] probe | {key}.{method}(...) -> {value}")));
        Ok(cordis::PluginOutput::none())
    })
}

/// Watch the provider behind `socket`; on EOF (it died) send `key` so the
/// runner can withdraw the proxy and let the consumer deactivate reactively.
fn spawn_monitor(socket: String, key: String, tx: std::sync::mpsc::Sender<String>) {
    std::thread::spawn(move || {
        let mut stream = None;
        for _ in 0..200 {
            match UnixStream::connect(&socket) {
                Ok(s) => {
                    stream = Some(s);
                    break;
                }
                Err(_) => std::thread::sleep(std::time::Duration::from_millis(50)),
            }
        }
        if let Some(mut s) = stream {
            let mut buf = [0u8; 64];
            loop {
                match s.read(&mut buf) {
                    Ok(0) | Err(_) => break, // EOF or error: provider gone
                    Ok(_) => {}              // the monitor connection never carries data
                }
            }
            let _ = tx.send(format!("peer:{key}"));
        }
    });
}

fn main() {
    let spec_path = std::env::args().nth(1).expect("usage: revl_placement_runner <spec.json>");
    let spec: J = serde_json::from_str(&std::fs::read_to_string(&spec_path).expect("read spec"))
        .expect("parse spec");
    let name = spec["name"].as_str().unwrap_or("proc").to_string();
    // item 421 F6(c): the runner's own console channels are one printer, so the
    // funnel sits here rather than at each call site — the whole rendered line,
    // the same choke point shape the go tier's `log` keeps. `confidential.rs`
    // holds the registry the emitted plugin closures register into, so the line
    // this printer writes is scrubbed by the same values the emitted sinks use.
    let log = |channel: &str, subject: &str, detail: &str| {
        println!("{}", confidential::revl_redact_text(format!(
            "[{name}] {channel:<6}| {subject:<16}| {detail}")));
    };
    // The uncaught channel: a panic unwinding out of a host body prints from the
    // runtime itself, before `log` runs and outside every funnel the emitted
    // program has. `set_hook` sees a panic on ANY thread, so one redacted line
    // replaces a raw message on a channel the runner does not otherwise own.
    // Installed here rather than at the top of `main` so the line can name the
    // process; the two `expect`s above can only fail on the runner's own static
    // text. Replacing the hook does not change what a panic does (unwind and a
    // non-zero exit) — only what it prints.
    let hook_name = name.clone();
    std::panic::set_hook(Box::new(move |info| {
        let message = match info.payload().downcast_ref::<&str>() {
            Some(text) => (*text).to_string(),
            None => match info.payload().downcast_ref::<String>() {
                Some(text) => text.clone(),
                None => "Box<dyn Any>".to_string(),
            },
        };
        let at = match info.location() {
            Some(loc) => format!(" at {}:{}", loc.file(), loc.line()),
            None => String::new(),
        };
        eprintln!("{}", confidential::revl_redact_text(format!(
            "[{hook_name}] FATAL panic: {message}{at}")));
    }));

    // item 443 / issue #122: publish the spec latch to the ambient variable the
    // accept seam (`handle_conn`) and the idle watcher below both read. Done
    // BEFORE any key is served, so a latch already armed at boot is honored from
    // the first crossing. A placement that was never armed carries no latch and
    // this is a no-op, so an unarmed run is byte-identical to the pre-443 runner.
    // A sandboxed child (item 411) need not inherit the conductor's environment,
    // which is why the latch travels in the spec rather than only the env.
    let estop_latch = spec["estopLatch"].as_str().unwrap_or("").to_string();
    if !estop_latch.is_empty() {
        std::env::set_var(estop::LATCH_ENV, &estop_latch);
    }

    let once = spec["once"].as_bool().unwrap_or(false);
    // issue #1621: the `--once` runner hands this process a per-run token as
    // the first line of stdin, and the four proof lines (`UP`, `NO-RESIDUE`,
    // `RESIDUE-LEFT`, `DOWN`) carry it, so a program's own output cannot forge
    // them. Read here, before any component loads (so before any host code
    // runs), into a local the generated `components` module cannot name. The
    // spec carries only the flag: it is a file the program could read.
    let proof_name = if spec["proofOnStdin"].as_bool().unwrap_or(false) {
        let mut token = String::new();
        let _ = std::io::stdin().read_line(&mut token);
        format!("{name}#{}", token.trim())
    } else {
        name.clone()
    };
    let root = cordis::Context::new();
    let mut fibers = Vec::new();
    let (tx, rx) = std::sync::mpsc::channel::<String>();

    // 1. proxies for keys provided by other processes (generated per service)
    if let Some(proxies) = spec["proxies"].as_object() {
        for (key, info) in proxies {
            let socket = info["socket"].as_str().unwrap_or("").to_string();
            let service = info["service"].as_str().unwrap_or("");
            match components::_revl_proxy_plugin(key, service, socket.clone()) {
                Some(handle) => {
                    let fiber = root.plugin(handle, ());
                    fiber.try_wait().unwrap();
                    fibers.push((format!("{key}-proxy"), fiber));
                    log("proxy", key, &format!("-> {socket} [{service}]"));
                    if !once {
                        spawn_monitor(socket.clone(), key.clone(), tx.clone());
                    }
                }
                None => log("proxy", key, &format!("UNSUPPORTED service {service}")),
            }
        }
    }

    // 2. this process's own components, in load order
    if let Some(list) = spec["components"].as_array() {
        for entry in list {
            let cname = entry.as_str().unwrap_or("");
            match components::_revl_load(&root, cname, &spec["config"]) {
                Some(fiber) => {
                    // A component's activation can fail: an author's `fail` step
                    // — or the fault sweep's injected L-Raise — makes `wait()`
                    // return the recorded error instead of an Active fiber. That
                    // is not a runner crash: cordis has already reverted this
                    // fiber's own accumulated effects LIFO (its effect guard on
                    // failure) and landed it FAILED. In `--once` mode we record
                    // the FAILED fiber like any other so the LIFO teardown below
                    // disposes it (clearing it from the registry) and still runs
                    // the no-residue proof the fault sweep reads. Outside `--once`
                    // there is no teardown-and-prove round-trip to salvage, so a
                    // boot failure stays fatal: tear down what booted, exit nonzero.
                    match fiber.try_wait() {
                        Ok(_) => {
                            log("load", cname, &format!("state={:?}", fiber.state()));
                            fibers.push((cname.to_string(), fiber));
                        }
                        Err(error) if once => {
                            log("load", cname,
                                &format!("FAILED (L-Raise, effects unwound) — {error}"));
                            fibers.push((cname.to_string(), fiber));
                        }
                        Err(error) => {
                            eprintln!("{}", confidential::revl_redact_text(format!(
                                "[{name}] boot failed loading {cname}: {error}")));
                            for (label, fiber) in fibers.iter().rev() {
                                let _ = fiber.dispose();
                                log("swap", label, "dispose");
                            }
                            std::process::exit(1);
                        }
                    }
                }
                None => log("load", cname, "UNKNOWN component"),
            }
        }
    }

    // 3. serve provided keys other processes need
    if let Some(serve) = spec["serve"].as_object() {
        let socket = serve["socket"].as_str().unwrap_or("").to_string();
        let keys: Vec<String> = serve["keys"]
            .as_array()
            .map(|a| a.iter().filter_map(|k| k.as_str().map(|s| s.to_string())).collect())
            .unwrap_or_default();
        let served: Served = Default::default();
        let mut refused = std::collections::HashMap::new();
        for key in &keys {
            match resolve_key(&root, &spec["placements"], key) {
                Resolved::In(ctx) => {
                    let fiber = ctx.plugin(serve_plugin(key.clone(), served.clone()), ());
                    fiber.try_wait().unwrap();
                    fibers.push(("serve".to_string(), fiber));
                }
                Resolved::Refused(why) => {
                    log("serve", key, &format!("REFUSED {why}"));
                    refused.insert(key.clone(), why);
                }
            }
        }
        spawn_listener(socket.clone(), served, refused, Exported::from_spec(serve));
        log("serve", &keys.join(", "), &format!("-> {socket}"));
    }

    // 4. probes (each rides a driver plugin that requires the probed key)
    if let Some(probes) = spec["probe"].as_array() {
        for probe in probes {
            let key = probe["key"].as_str().unwrap_or("").to_string();
            let method = probe["method"].as_str().unwrap_or("").to_string();
            let ctx = match resolve_key(&root, &spec["placements"], &key) {
                Resolved::In(ctx) => ctx,
                Resolved::Refused(why) => {
                    println!("{}", confidential::revl_redact_text(format!(
                        "[{name}] probe | {key}.{method}(...) ERROR {why}")));
                    continue;
                }
            };
            let fiber = ctx.plugin(
                probe_plugin(name.clone(), key, method, args_of(probe)),
                (),
            );
            fiber.try_wait().unwrap();
            fibers.push(("probe".to_string(), fiber));
        }
    }

    println!("[{proof_name}] UP");

    // item 443 / issue #122 — the idle watcher. The accept seam refuses lazily,
    // at the NEXT crossing, which is useless for a process parked waiting to be
    // stopped: it crosses nothing and would sit through the emergency. So the
    // runner polls the latch and, on the button, prints its in-flight inventory
    // on one `[name] HALTED {json}` line (the conductor merges it by prefix —
    // `src/revl/placement.py::pump` — with no second channel) and calls
    // `std::process::exit`, which runs NO teardown: no LIFO unwind, no inverse,
    // no no-residue proof, no `DOWN`. That is the whole point of the halt
    // (docs/design/443-estop.md). The rust twin of the py runner's
    // `estop_from_latch` and the ts runner's `haltOnLatch`. Spawned only when the
    // placement is armed, so an unarmed run spawns no watcher.
    if !estop_latch.is_empty() {
        let watch_name = name.clone();
        std::thread::spawn(move || loop {
            if let Some(record) = estop::read_latch(estop::latch_path(None, None, true).as_deref()) {
                let line = estop::estop_halt_line(
                    &watch_name, &estop::in_flight_crossings(), &Some(record));
                println!("{line}");
                use std::io::Write as _;
                let _ = std::io::stdout().flush();
                std::process::exit(0);
            }
            std::thread::sleep(std::time::Duration::from_millis(20));
        });
    }

    // 5. hold until stdin closes (graceful stop) or a provider dies; a dead
    //    provider withdraws its proxy so the consumer deactivates reactively.
    if !once {
        {
            let tx = tx.clone();
            std::thread::spawn(move || {
                let mut sink = String::new();
                let _ = std::io::stdin().read_to_string(&mut sink);
                let _ = tx.send("stdin".to_string());
            });
        }
        if let Ok(reason) = rx.recv() {
            if let Some(key) = reason.strip_prefix("peer:") {
                log("peer", key, "provider died: withdrawing the proxy");
                if let Some((_, pf)) = fibers.iter().find(|(l, _)| *l == format!("{key}-proxy")) {
                    let _ = pf.dispose();
                }
                for (label, fiber) in fibers.iter() {
                    if !label.ends_with("-proxy") {
                        log("withdraw", label, &format!("state={:?}", fiber.state()));
                    }
                }
            }
        }
    }

    // 6. teardown, consumers first (reverse load order)
    for (label, fiber) in fibers.iter().rev() {
        let _ = fiber.dispose();
        log("swap", label, "dispose");
    }

    // 7. no-residue proof (once mode only, so placement's stream is unchanged):
    //    after a LIFO teardown the live runtime must hold nothing — no plugin
    //    left in the registry, no service left in reflect. This is the cordis-rs
    //    mirror of the py driver's registry.size==0 / reflect.store=={} check
    //    (src/revl/run.py `_Driver._teardown`): the tier proves the composition
    //    left nothing behind, not merely that dispose was called.
    if once {
        let live_plugins = root.registry().len();
        let live_services = root.reflect().services().len();
        log("residue", "registry", &format!("{live_plugins} live plugin(s)"));
        log("residue", "provisions", &format!("{live_services} service(s) provided"));
        if live_plugins == 0 && live_services == 0 {
            println!("[{proof_name}] NO-RESIDUE — the composition left nothing behind");
        } else {
            println!("[{proof_name}] RESIDUE-LEFT — see the residue lines above");
        }
    }

    println!("[{proof_name}] DOWN");
}
