//! cordis-rs placement runner: one process of a `revl run --placement`
//! composition placed on the Rust backend. Reads a spec JSON (argv[1]),
//! consumes cross-process keys through emitter-generated proxies, loads its own
//! cordis-rs components, optionally serves its provided keys over a socket,
//! runs probes, and (unless "once") holds until stdin closes, then tears down.
//!
//! The proxies, the stub dispatch, and the component name->plugin table are all
//! GENERATED by backends/rust/emit.py into `components` (per composition), so
//! this runner carries no composition-specific knowledge: cordis-rs services
//! are static traits, so generality is codegen, not a runtime-generic proxy.

use serde_json::Value as J;
use std::io::{BufRead, BufReader, Read, Write};
use std::os::unix::net::{UnixListener, UnixStream};

mod components;

fn args_of(probe: &J) -> Vec<J> {
    probe["args"].as_array().cloned().unwrap_or_default()
}

/// Provider side: dispatch one connection's requests to locally-provided
/// services via the generated `_revl_invoke`.
fn handle_conn(stream: UnixStream, ctx: &cordis::Context) {
    let reader = BufReader::new(match stream.try_clone() {
        Ok(s) => s,
        Err(_) => return,
    });
    let mut writer = stream;
    for line in reader.lines() {
        let line = match line {
            Ok(l) => l,
            Err(_) => break,
        };
        if line.is_empty() {
            continue;
        }
        let req: J = match serde_json::from_str(&line) {
            Ok(v) => v,
            Err(_) => continue,
        };
        let key = req["key"].as_str().unwrap_or("");
        let method = req["method"].as_str().unwrap_or("");
        let args = req["args"].as_array().cloned().unwrap_or_default();
        let value = components::_revl_invoke(ctx, key, method, &args);
        let reply = serde_json::json!({ "ok": true, "value": value });
        let mut out = serde_json::to_string(&reply).unwrap_or_else(|_| "{\"ok\":false}".into());
        out.push('\n');
        if writer.write_all(out.as_bytes()).is_err() {
            break;
        }
    }
}

/// A plugin that requires the served keys (so its provider components have
/// activated), then spawns a blocking accept loop that serves them.
fn serve_plugin(socket: String, keys: Vec<String>) -> cordis::PluginHandle {
    let inject: Vec<&str> = keys.iter().map(|k| k.as_str()).collect();
    cordis::plugin_sync::<(), _>("RevlServe", cordis::Inject::new(inject), move |ctx, _config| {
        let served = ctx.clone();
        let socket = socket.clone();
        std::thread::spawn(move || {
            let _ = std::fs::remove_file(&socket);
            let listener = match UnixListener::bind(&socket) {
                Ok(l) => l,
                Err(_) => return,
            };
            for conn in listener.incoming() {
                if let Ok(stream) = conn {
                    let ctx = served.clone();
                    std::thread::spawn(move || handle_conn(stream, &ctx));
                }
            }
        });
        Ok(cordis::PluginOutput::none())
    })
}

/// A driver plugin that requires `key` and runs one probe call during its
/// activation (the runtime has no root-level require, so probing rides a plugin).
fn probe_plugin(name: String, key: String, method: String, args: Vec<J>) -> cordis::PluginHandle {
    cordis::plugin_sync::<(), _>("RevlProbe", cordis::Inject::new([key.as_str()]), move |ctx, _config| {
        let value = components::_revl_invoke(&ctx, &key, &method, &args);
        println!("[{name}] probe | {key}.{method}(...) -> {value}");
        Ok(cordis::PluginOutput::none())
    })
}

fn main() {
    let spec_path = std::env::args().nth(1).expect("usage: revl_placement_runner <spec.json>");
    let spec: J = serde_json::from_str(&std::fs::read_to_string(&spec_path).expect("read spec"))
        .expect("parse spec");
    let name = spec["name"].as_str().unwrap_or("proc").to_string();
    let log = |channel: &str, subject: &str, detail: &str| {
        println!("[{name}] {channel:<6}| {subject:<16}| {detail}");
    };

    let root = cordis::Context::new();
    let mut fibers = Vec::new();

    // 1. proxies for keys provided by other processes (generated per service)
    if let Some(proxies) = spec["proxies"].as_object() {
        for (key, info) in proxies {
            let socket = info["socket"].as_str().unwrap_or("").to_string();
            let service = info["service"].as_str().unwrap_or("");
            match components::_revl_proxy_plugin(key, service, socket.clone()) {
                Some(handle) => {
                    let fiber = root.plugin(handle, ());
                    fiber.wait().unwrap();
                    fibers.push((format!("{key}-proxy"), fiber));
                    log("proxy", key, &format!("-> {socket} [{service}]"));
                }
                None => log("proxy", key, &format!("UNSUPPORTED service {service}")),
            }
        }
    }

    // 2. this process's own components, in load order
    if let Some(list) = spec["components"].as_array() {
        for entry in list {
            let cname = entry.as_str().unwrap_or("");
            match components::_revl_load(&root, cname, &spec["config"]) {
                Some(fiber) => {
                    fiber.wait().unwrap();
                    log("load", cname, &format!("state={:?}", fiber.state()));
                    fibers.push((cname.to_string(), fiber));
                }
                None => log("load", cname, "UNKNOWN component"),
            }
        }
    }

    // 3. serve provided keys other processes need
    if let Some(serve) = spec["serve"].as_object() {
        let socket = serve["socket"].as_str().unwrap_or("").to_string();
        let keys: Vec<String> = serve["keys"]
            .as_array()
            .map(|a| a.iter().filter_map(|k| k.as_str().map(|s| s.to_string())).collect())
            .unwrap_or_default();
        let fiber = root.plugin(serve_plugin(socket.clone(), keys.clone()), ());
        fiber.wait().unwrap();
        fibers.push(("serve".to_string(), fiber));
        log("serve", &keys.join(", "), &format!("-> {socket}"));
    }

    // 4. probes (each rides a driver plugin that requires the probed key)
    if let Some(probes) = spec["probe"].as_array() {
        for probe in probes {
            let key = probe["key"].as_str().unwrap_or("").to_string();
            let method = probe["method"].as_str().unwrap_or("").to_string();
            let fiber = root.plugin(
                probe_plugin(name.clone(), key, method, args_of(probe)),
                (),
            );
            fiber.wait().unwrap();
            fibers.push(("probe".to_string(), fiber));
        }
    }

    println!("[{name}] UP");

    // 5. hold until stdin closes (the conductor closes it to stop us), unless once
    if !spec["once"].as_bool().unwrap_or(false) {
        let mut sink = String::new();
        let _ = std::io::stdin().read_to_string(&mut sink);
    }

    // 6. teardown, consumers first (reverse load order)
    for (label, fiber) in fibers.iter().rev() {
        let _ = fiber.dispose();
        log("swap", label, "dispose");
    }
    println!("[{name}] DOWN");
}
