"""`revl gen-types`: a typed model document becomes `types.rvl` (issue #1896).

A product that keeps its data model as data (entities, fields, relations,
identity keys, labels, locale) and compiles typed revl against it needs the
generated types to follow the model, not drift from it. This module turns one
model document into revl source: a record type and a key type per entity, and
one service signature over them. Same document, same bytes.

The generated header carries the sha256 of the model document's bytes. The
compiler checks it whenever it loads the file (`check_generated_header`), so a
`types.rvl` whose model has changed since it was generated is refused by
`revl compile`, by `revl_check` and at admission, and the digest rides on the IR
(`generated_from`) and so on the audit surface.

The model document (version 1) is JSON:

    {
      "revl_model": 1,
      "name": "Rentals",
      "locale": "en-GB",
      "service": "RentalsData",
      "entities": [
        {
          "name": "Customer",
          "label": "Customer",
          "key": ["id"],
          "fields": [
            {"name": "id", "type": "Str", "label": "Customer number"},
            {"name": "email", "type": "Str", "optional": true}
          ],
          "relations": [
            {"name": "orders", "to": "Order", "many": true}
          ]
        }
      ]
    }

Every key is checked and an unknown one is refused by name, so a misspelt
`optinal` is an error rather than a required field. The rules are in
docs/gen-types.md.
"""

from __future__ import annotations

import hashlib
import json
import os
import re

from ._paths import relpath_or_abs
from .errors import RevlError
from .import_openapi import _comment_safe, _line_of, _pointer
from .lexer import KEYWORDS
from .type_schema import _JSON_TYPES

MODEL_VERSION = 1

#: The field types a model may name: the revl scalars that have a JSON
#: rendering (`type_schema._JSON_TYPES`, the one definition), without `Unit`,
#: which carries no value. Each is a revl primitive, so a generated record is
#: plain data and needs no import.
FIELD_TYPES = tuple(name for name in _JSON_TYPES if name != "Unit")

#: The generated header. The compiler reads these three lines back
#: (`generated_header`), so their spelling is part of the format.
HEADER_FIRST = "// Generated by `revl gen-types`: do not edit by hand."
HEADER_MODEL = "// Model document: "
HEADER_DIGEST = "// Model sha256: "

_DOCUMENT_KEYS = ("revl_model", "name", "locale", "service", "entities")
_ENTITY_KEYS = ("name", "label", "key", "fields", "relations")
_FIELD_KEYS = ("name", "type", "label", "optional", "list")
_RELATION_KEYS = ("name", "to", "label", "many", "optional")

_TYPE_NAME = re.compile(r"[A-Z][A-Za-z0-9]*\Z")
_MEMBER_NAME = re.compile(r"[a-z_][a-z0-9_]*\Z")
_LOCALE = re.compile(r"[A-Za-z]{2,3}(-[A-Za-z0-9]{2,8})*\Z")

#: Names a generated type may not take: the builtin type heads, which a
#: record of the same name would shadow.
_RESERVED_TYPES = frozenset({
    "Str", "Int", "Float", "Bool", "Bytes", "Unit", "Never", "Any", "Value",
    "Opt", "List", "Map", "Set", "Result", "Secret", "Trusted", "Retained",
    "Approval", "Async", "Stream", "Job", "Pool", "Asset",
})


def sha256_bytes(data: bytes) -> str:
    """The digest the header carries: the sha256 of the model document's bytes,
    hex, exactly as `cert.source_digest` takes a source file's."""
    return hashlib.sha256(data).hexdigest()


# ------------------------------------------------------------------ the model

class _Model:
    """A validated model document, with the source text kept for line numbers
    in refusals."""

    def __init__(self, document: object, *, filename: str, source: str):
        self.filename = filename
        self.source = source
        self.doc = self._object(document, (), _DOCUMENT_KEYS, "the model document")
        version = self.doc.get("revl_model")
        if version != MODEL_VERSION:
            self._refuse((), f"`revl_model` must be {MODEL_VERSION} (the model "
                             f"document version this revl reads), got {version!r}")
        self.name = self._type_name(self.doc.get("name"), ("name",), "the model's `name`")
        self.locale = self._locale()
        self.service = (self._type_name(self.doc["service"], ("service",),
                                        "the model's `service`")
                        if "service" in self.doc else f"{self.name}Data")
        entities = self.doc.get("entities")
        if not isinstance(entities, list) or not entities:
            self._refuse(("entities",), "`entities` must be a non-empty list")
        self.entities = [self._entity(e, ("entities", i)) for i, e in enumerate(entities)]
        self._check_names()
        self._check_relations()

    # ---- refusals

    def _refuse(self, where: tuple, message: str, hint: str | None = None):
        pointer = _pointer(*where)
        raise RevlError(self.filename, _line_of(self.source, pointer),
                        f"{message} (at {pointer})", hint=hint)

    def _object(self, value: object, where: tuple, allowed: tuple, what: str) -> dict:
        if not isinstance(value, dict):
            self._refuse(where, f"{what} must be a JSON object")
        unknown = sorted(set(value) - set(allowed))
        if unknown:
            self._refuse(where + (unknown[0],),
                         f"{what} has an unknown key `{unknown[0]}`",
                         hint="the keys it may carry are "
                              + ", ".join(f"`{k}`" for k in allowed))
        return value

    def _type_name(self, value: object, where: tuple, what: str) -> str:
        if not isinstance(value, str) or not _TYPE_NAME.match(value):
            self._refuse(where, f"{what} must be a capitalised name such as "
                                f"`Customer`, got {value!r}")
        if value in _RESERVED_TYPES:
            self._refuse(where, f"{what} `{value}` is a builtin revl type name")
        return value

    def _member_name(self, value: object, where: tuple, what: str) -> str:
        if not isinstance(value, str) or not _MEMBER_NAME.match(value):
            self._refuse(where, f"{what} must be a lower-case name such as "
                                f"`email`, got {value!r}")
        if value in KEYWORDS:
            self._refuse(where, f"{what} `{value}` is a revl keyword")
        return value

    def _flag(self, value: dict, key: str, where: tuple, what: str) -> bool:
        flag = value.get(key, False)
        if not isinstance(flag, bool):
            self._refuse(where + (key,), f"{what}: `{key}` must be true or false")
        return flag

    def _label(self, value: dict, where: tuple, what: str) -> str | None:
        label = value.get("label")
        if label is not None and not isinstance(label, str):
            self._refuse(where + ("label",), f"{what}: `label` must be a string")
        return label

    def _locale(self) -> str | None:
        locale = self.doc.get("locale")
        if locale is not None and (not isinstance(locale, str)
                                   or not _LOCALE.match(locale)):
            self._refuse(("locale",), f"`locale` must be a language tag such as "
                                      f"`en-GB`, got {locale!r}")
        return locale

    # ---- entities

    def _entity(self, value: object, where: tuple) -> dict:
        entity = self._object(value, where, _ENTITY_KEYS, "an entity")
        name = self._type_name(entity.get("name"), where + ("name",), "an entity's `name`")
        what = f"entity `{name}`"
        fields = entity.get("fields")
        if not isinstance(fields, list) or not fields:
            self._refuse(where + ("fields",), f"{what}: `fields` must be a non-empty list")
        out_fields = [self._field(f, where + ("fields", i), what)
                      for i, f in enumerate(fields)]
        relations = entity.get("relations", [])
        if not isinstance(relations, list):
            self._refuse(where + ("relations",), f"{what}: `relations` must be a list")
        out_relations = [self._relation(r, where + ("relations", i), what)
                         for i, r in enumerate(relations)]
        seen: dict[str, str] = {}
        for member in out_fields + out_relations:
            if member["name"] in seen:
                self._refuse(member["where"] + ("name",),
                             f"{what}: `{member['name']}` is declared twice")
            seen[member["name"]] = member["kind"]
        key = entity.get("key")
        if not isinstance(key, list) or not key \
                or not all(isinstance(k, str) for k in key):
            self._refuse(where + ("key",), f"{what}: `key` must be a non-empty list "
                                           f"of field names (its identity key)")
        by_name = {f["name"]: f for f in out_fields}
        for index, part in enumerate(key):
            field = by_name.get(part)
            if field is None:
                self._refuse(where + ("key", index),
                             f"{what}: key `{part}` is not one of its fields")
            if field["optional"] or field["list"]:
                self._refuse(where + ("key", index),
                             f"{what}: key field `{part}` may not be optional or a list")
        if len(set(key)) != len(key):
            self._refuse(where + ("key",), f"{what}: `key` names a field twice")
        return {"name": name, "label": self._label(entity, where, what),
                "key": [by_name[k] for k in key], "fields": out_fields,
                "relations": out_relations, "where": where}

    def _field(self, value: object, where: tuple, owner: str) -> dict:
        field = self._object(value, where, _FIELD_KEYS, f"{owner}: a field")
        name = self._member_name(field.get("name"), where + ("name",),
                                 f"{owner}: a field's `name`")
        what = f"{owner}, field `{name}`"
        kind = field.get("type")
        if kind not in FIELD_TYPES:
            self._refuse(where + ("type",),
                         f"{what}: type {kind!r} is not a model field type",
                         hint="a field type is one of "
                              + ", ".join(f"`{t}`" for t in FIELD_TYPES)
                              + "; mark it `optional` or `list` for Opt[T] or "
                                "List[T], and point at another entity with a "
                                "relation")
        return {"kind": "field", "name": name, "type": kind,
                "optional": self._flag(field, "optional", where, what),
                "list": self._flag(field, "list", where, what),
                "label": self._label(field, where, what), "where": where}

    def _relation(self, value: object, where: tuple, owner: str) -> dict:
        relation = self._object(value, where, _RELATION_KEYS, f"{owner}: a relation")
        name = self._member_name(relation.get("name"), where + ("name",),
                                 f"{owner}: a relation's `name`")
        what = f"{owner}, relation `{name}`"
        target = relation.get("to")
        if not isinstance(target, str):
            self._refuse(where + ("to",), f"{what}: `to` must name an entity")
        return {"kind": "relation", "name": name, "to": target,
                "many": self._flag(relation, "many", where, what),
                "optional": self._flag(relation, "optional", where, what),
                "label": self._label(relation, where, what), "where": where}

    # ---- the whole model

    def _check_names(self) -> None:
        taken: dict[str, tuple] = {self.service: ("service",)}
        for entity in self.entities:
            for generated in (entity["name"], f"{entity['name']}Key"):
                if generated in taken:
                    self._refuse(entity["where"] + ("name",),
                                 f"entity `{entity['name']}` generates the type "
                                 f"`{generated}`, which another name in the model "
                                 f"already takes")
                taken[generated] = entity["where"]
        snakes: dict[str, str] = {}
        for entity in self.entities:
            snake = _snake(entity["name"])
            if snake in snakes:
                self._refuse(entity["where"] + ("name",),
                             f"entities `{snakes[snake]}` and `{entity['name']}` "
                             f"would both generate `get_{snake}`")
            snakes[snake] = entity["name"]

    def _check_relations(self) -> None:
        names = {entity["name"] for entity in self.entities}
        for entity in self.entities:
            for relation in entity["relations"]:
                if relation["to"] not in names:
                    self._refuse(relation["where"] + ("to",),
                                 f"entity `{entity['name']}`, relation "
                                 f"`{relation['name']}`: `{relation['to']}` is not "
                                 f"an entity of this model")


def _snake(name: str) -> str:
    return re.sub(r"(?<!^)(?=[A-Z])", "_", name).lower()


# ------------------------------------------------------------------ the source

def _field_type(member: dict) -> str:
    if member["kind"] == "field":
        base = member["type"]
        many = member["list"]
    else:
        base = f"{member['to']}Key"
        many = member["many"]
    shape = f"List[{base}]" if many else base
    return f"Opt[{shape}]" if member["optional"] else shape


def _record(name: str, members: list[dict]) -> str:
    body = "".join(f"  {m['name']}: {_field_type(m)},\n" for m in members)
    return f"pub type {name} = {{\n{body}}}\n"


def _labels(entity: dict) -> list[str]:
    title = f"// {entity['name']}"
    if entity["label"]:
        title += f": {_comment_safe(entity['label'])}"
    lines = [title, "// key: " + ", ".join(f["name"] for f in entity["key"])]
    for member in entity["fields"] + entity["relations"]:
        if member["label"]:
            lines.append(f"//   {member['name']}: {_comment_safe(member['label'])}")
    return lines


def generate(model: _Model, *, model_path: str, digest: str) -> str:
    """The generated source, a pure function of the model and the header's two
    facts. Entities, fields and relations keep the order the document gives
    them, so a reviewer reads the file in the order they wrote the model."""
    header = [HEADER_FIRST,
              HEADER_MODEL + _comment_safe(model_path),
              HEADER_DIGEST + digest,
              f"// Model: {model.name}"
              + (f" (locale {model.locale})" if model.locale else ""),
              "//",
              "// One record type per entity and a key type for its identity key;",
              "// a relation holds the key of the entity it points to. The compiler",
              "// refuses this file once the model document no longer has the",
              "// digest above: regenerate it rather than editing it."]
    parts = ["\n".join(header) + "\n"]
    for entity in model.entities:
        parts.append("\n".join(_labels(entity)) + "\n"
                     + _record(f"{entity['name']}Key", entity["key"])
                     + "\n" + _record(entity["name"],
                                      entity["fields"] + entity["relations"]))
    ops = []
    for entity in model.entities:
        name, snake = entity["name"], _snake(entity["name"])
        ops += [f"  // {name}",
                f"  fn get_{snake}(key: {name}Key) -> Opt[{name}]",
                f"  fn list_{snake}() -> List[{name}]",
                f"  emission fn put_{snake}(record: {name})",
                f"  emission fn delete_{snake}(key: {name}Key)"]
    parts.append(f"service {model.service} {{\n" + "\n".join(ops) + "\n}\n")
    return "\n".join(parts)


def load_model(data: bytes, *, filename: str) -> _Model:
    try:
        source = data.decode("utf-8")
    except UnicodeDecodeError:
        raise RevlError(filename, 0, "the model document is not UTF-8") from None
    try:
        document = json.loads(source)
    except json.JSONDecodeError as error:
        raise RevlError(filename, error.lineno,
                        f"the model document is not valid JSON: {error.msg}") from None
    return _Model(document, filename=filename, source=source)


def gen_types_file(path: str, output: str | None = None) -> str:
    """Generate the source for the model at `path`. The header names the model
    relative to the directory the output is written to (the current directory
    for stdout), which is where the compiler looks for it, so the model must sit
    in that directory or below it."""
    with open(path, "rb") as handle:
        data = handle.read()
    model = load_model(data, filename=path)
    base = os.path.dirname(os.path.abspath(output)) if output else os.getcwd()
    # on another drive there is no relative path and the helper returns the
    # absolute one (issue #1944), which is outside `base` as well
    rel = relpath_or_abs(os.path.abspath(path), base)
    model_path = rel.replace(os.sep, "/")
    if os.path.isabs(rel) or model_path == ".." or model_path.startswith("../"):
        raise RevlError(
            path, 0,
            f"the model document is outside the directory the generated file is "
            f"written to ({base})",
            hint="the compiler reads the model back from the generated file's own "
                 "directory tree to check its digest, so keep the model there or "
                 "below it, or write the output next to the model")
    return generate(model, model_path=model_path, digest=sha256_bytes(data))


# ------------------------------------------------------------------ the check

def generated_header(text: str) -> tuple[str, str] | None:
    """`(model path, digest)` from a generated file's header, None for any other
    file. A file that opens with the generated first line but does not carry
    the other two is refused, so a damaged header cannot pass as no header."""
    lines = text.split("\n", 3)
    if not lines or lines[0].rstrip("\r") != HEADER_FIRST:
        return None
    model = lines[1].rstrip("\r") if len(lines) > 1 else ""
    digest = lines[2].rstrip("\r") if len(lines) > 2 else ""
    if not model.startswith(HEADER_MODEL) or not digest.startswith(HEADER_DIGEST):
        return "", ""
    value = digest[len(HEADER_DIGEST):].strip()
    if not re.fullmatch(r"[0-9a-f]{64}", value):
        return "", ""
    return model[len(HEADER_MODEL):].strip(), value


def check_generated_header(text: str, abs_path: str, sources: dict,
                           is_virtual: bool) -> dict | None:
    """Refuse a generated file whose model no longer has the header's digest,
    and return its `generated_from` row otherwise (None for a file that is not
    generated).

    The model is read the way an asset is (item 459): a module compiled from
    disk reads it from disk, inside the generated file's own directory tree; an
    in-memory module only through the sources map, so a compile of foreign
    source reads nothing it was not given. The refusal names the header's
    digest and not the file's current one, so it is no digest oracle."""
    header = generated_header(text)
    if header is None:
        return None
    name = os.path.basename(abs_path)
    model, digest = header
    if not model:
        raise RevlError(abs_path, 1,
                        f"`{name}` opens with the `revl gen-types` header but does "
                        f"not carry its `Model document:` and `Model sha256:` lines",
                        hint="regenerate the file with `revl gen-types`",
                        category="admission")
    base = os.path.dirname(abs_path)
    key = os.path.normpath(os.path.join(base, model))
    if os.path.isabs(model) or os.path.commonpath([base, key]) != base:
        raise RevlError(abs_path, 2,
                        f"`{name}` names a model document outside its own "
                        f"directory: `{model}`",
                        hint="`revl gen-types` writes a path inside the output's "
                             "directory; regenerate the file",
                        category="admission")
    regenerate = f"regenerate it with `revl gen-types {model} -o {name}`"
    if is_virtual:
        if key not in sources:
            raise RevlError(abs_path, 2,
                            f"`{name}` was generated from `{model}`, which is not in "
                            f"the in-memory sources map, so its digest cannot be "
                            f"checked",
                            hint="an in-memory compile reads nothing from disk: "
                                 "supply the model document through the same "
                                 "`modules=`/`sources=` map",
                            category="admission")
        data = sources[key].encode("utf-8")
    else:
        real = os.path.realpath(key)
        if os.path.commonpath([os.path.realpath(base), real]) != os.path.realpath(base):
            raise RevlError(abs_path, 2,
                            f"`{name}` names a model document outside its own "
                            f"directory: `{model}`",
                            hint=regenerate, category="admission")
        try:
            with open(real, "rb") as handle:
                data = handle.read()
        except OSError:
            raise RevlError(abs_path, 2,
                            f"`{name}` was generated from `{model}`, which cannot "
                            f"be read, so its digest cannot be checked",
                            hint=f"restore the model document, or {regenerate}",
                            category="admission") from None
    if sha256_bytes(data) != digest:
        raise RevlError(abs_path, 3,
                        f"`{name}` was generated from `{model}` with sha256 "
                        f"{digest[:12]}, and that document has changed since",
                        hint=f"the generated types are stale: {regenerate}",
                        category="admission")
    return {"file": name, "model": model, "sha256": digest}


__all__ = ["MODEL_VERSION", "FIELD_TYPES", "generate", "load_model",
           "gen_types_file", "generated_header", "check_generated_header",
           "sha256_bytes"]
