"""Generated by the revl cordis-py backend (ir_version 1) — do not edit.

Components: PgDatabase, UserCache
"""

from runtime import ConfigSchema, Frame, Map, Pool, fmt

SERVICES = {
    'Database': {
        'query': {'params': ['sql'], 'emission': False},
        'execute': {'params': ['sql'], 'emission': True},
    },
    'Cache': {
        'get': {'params': ['key'], 'emission': False},
        'put': {'params': ['key', 'value'], 'emission': False},
    },
}


_PG_DATABASE_CONFIG = ConfigSchema([
    ('url', 'Str', None),
    ('pool_size', 'Int', 10),
])


def _pg_database_apply(ctx, config):
    config = _PG_DATABASE_CONFIG.resolve(config)
    frame = Frame(ctx, 'PgDatabase')

    def _body():
        pool = Pool.open(config['url'], config['pool_size'])
        yield lambda: pool.close()

        class _Db:
            """service Database, provided at key "db"."""

            def query(self, sql):
                return pool.query(sql)

            def execute(self, sql):
                return pool.execute(sql)

        yield ctx.provide('db')
        ctx.set('db', _Db())

        yield frame.drain

    frame.install(_body)


PgDatabase = {
    'name': 'PgDatabase',
    'inject': [],
    'apply': _pg_database_apply,
}


def _user_cache_apply(ctx, config):
    frame = Frame(ctx, 'UserCache')

    def _body():
        store = Map.new()
        yield lambda: store.drop()

        class _Cache:
            """service Cache, provided at key "cache"."""

            def get(self, key):
                return store.get(key)

            def put(self, key, value):
                def _effect_0():
                    store.insert(key, value)
                    yield lambda: store.remove(key)
                frame.adopt(ctx.effect(_effect_0, 'UserCache.cache.put#1'))
                ctx.db.execute(fmt('INSERT INTO cache_log VALUES ($0)', key))

        yield ctx.provide('cache')
        ctx.set('cache', _Cache())

        yield frame.drain

    frame.install(_body)


UserCache = {
    'name': 'UserCache',
    'inject': ['db'],
    'apply': _user_cache_apply,
}


COMPONENTS = {'PgDatabase': PgDatabase, 'UserCache': UserCache}
