"""The ts tier's runtime contract, gated (issue #295; docs/ts-runtime-contract.md).

`revl test --backend ts` runs the emitted module under VITEST. Everything that
ships runs it under PLAIN NODE (`revl run --backend ts` and
`revl run --placement` both spawn `["node", placement_runner.ts, spec]`). Vitest
is the larger environment: it supplies a CommonJS module scope (`require`,
`module`, `exports`, `__dirname`, `__filename`), vite's module resolution and
full TypeScript, none of which node gives an emitted `.ts` module.

So a green `--backend ts` suite meant "this runs under vitest", never "this runs
on the ts tier", and the suite could not report the difference. A downstream
consumer lost time to exactly that: `@ts` extern bodies calling bare
`require(...)`, green 34/34, a `ReferenceError` on the emitted module.

The gate is `src/revl/test.py::_ts_runtime_contract`, which re-executes the SAME
generated bytes under plain node. This file is its exit test:

  * `test_bare_require_is_green_under_vitest_alone` — the blindness itself,
    asserted rather than described. Remove the gate and this is all you get.
  * `test_bare_require_fails_the_ts_tier` — the same document through the tier
    runner, now a failure. This is the bite.
  * `test_a_contract_clean_document_still_passes` — the gate does not just
    reject everything.
  * plus the version predicate, which needs no toolchain at all.

WHY THIS FILE LIVES HERE and not in `tests/`: the `backend-typescript` CI job
runs `pytest backends/typescript/` against a checkout that has just done
`npm ci`, so node AND vitest are unconditionally present. A tier gate whose own
test can skip for want of the tier is the failure this issue is about.
"""

from __future__ import annotations

import importlib.util
import subprocess
import sys
from pathlib import Path

import pytest

_HERE = Path(__file__).resolve().parent
_ROOT = _HERE.parent.parent
if str(_ROOT / "src") not in sys.path:
    sys.path.insert(0, str(_ROOT / "src"))

from revl import compile_source                                    # noqa: E402
from revl.test import _node_can_run_emitted, _node_version, run_ts  # noqa: E402

_VITEST = _HERE / "node_modules" / ".bin" / "vitest"

# The downstream consumer's bug, reduced: a verbatim `@ts` extern body reaching
# for CommonJS `require`. Legal TypeScript, legal under vitest, a ReferenceError
# on the module the tier actually ships.
_BARE_REQUIRE = """
pub extern pure fn base(s: Str) -> Str
  = @ts { return require("node:path").basename(s) }

test "a bare require in a @ts body" { assert base("/a/b.txt") == "b.txt" }
"""

# The Temporal emission target (`emit(ir, target="temporal")`, roadmap 253)
# imports `@temporalio/workflow`, which is NOT a dependency of this package: it
# is provisioned in the `temporal-exit` CI job, where that golden is executed
# against a real dev server. The module is still plain-node ESM; what it needs
# is a package this checkout does not carry, which is an availability fact and
# not a contract violation. Named, so the exclusion cannot grow silently.
_GOLDEN_NOT_LOADABLE_HERE = frozenset({"temporal_booktrip.ts"})

_CONTRACT_CLEAN = """
pub fn add(a: Int, b: Int) -> Int { return a + b }

test "arithmetic is contract-clean" { assert add(1, 2) == 3 }
"""


def _emitter():
    spec = importlib.util.spec_from_file_location("revl_ts_emit_295", _HERE / "emit.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


needs_toolchain = pytest.mark.skipif(
    not _VITEST.exists() or not _node_can_run_emitted(_node_version()),
    reason="needs backends/typescript/node_modules and node >= 22.18 "
           "(`cd backends/typescript && npm ci`)",
)


# --------------------------------------------------------------------------- #
# the version predicate — no toolchain, so it can never go quiet               #
# --------------------------------------------------------------------------- #
@pytest.mark.parametrize(("version", "ok"), [
    (None, False),          # no node at all
    ((20, 19), False),      # no unflagged type stripping
    ((22, 17), False),      # 22.15 has registerHooks, 22.18 turns stripping on
    ((22, 18), True),
    ((22, 21), True),
    ((23, 5), False),       # the 23 line needs a flag until 23.6
    ((23, 6), True),
    ((26, 7), True),
])
def test_node_version_predicate(version, ok):
    assert _node_can_run_emitted(version) is ok


# --------------------------------------------------------------------------- #
# the blindness, and the bite                                                  #
# --------------------------------------------------------------------------- #
@needs_toolchain
def test_bare_require_is_green_under_vitest_alone(tmp_path):
    """Vitest passes the document the shipping runtime cannot run.

    This is the measurement the issue rests on, asserted so it cannot quietly
    stop being true: if a future vitest withheld `require`, the gate below
    would be testing nothing and this test says so.
    """
    ir = compile_source(_BARE_REQUIRE, "bare_require.rvl")
    generated = _HERE / "tests" / "generated"
    generated.mkdir(parents=True, exist_ok=True)
    path = generated / "contract_295_vitest_only.test.ts"
    path.write_text(_emitter().emit(ir, runtime_import="../../runtime.ts"),
                    encoding="utf-8")
    try:
        result = subprocess.run([str(_VITEST), "run", str(path)], cwd=_HERE,
                                capture_output=True, text=True, timeout=300)
    finally:
        path.unlink(missing_ok=True)
    assert result.returncode == 0, (
        "vitest is expected to PASS this document (that is the whole problem):\n"
        + result.stdout + result.stderr)


@needs_toolchain
def test_bare_require_fails_the_ts_tier():
    """The same document, through the tier runner, is a failure."""
    outcome, message = run_ts(compile_source(_BARE_REQUIRE, "bare_require.rvl"))
    assert outcome == "fail", f"expected a tier failure, got {outcome}: {message}"
    assert "plain node" in message
    assert "require is not defined" in message


@needs_toolchain
def test_a_contract_clean_document_still_passes():
    outcome, message = run_ts(compile_source(_CONTRACT_CLEAN, "clean.rvl"))
    assert outcome == "pass", f"{outcome}: {message}"
    assert "plain node" in message


@needs_toolchain
def test_the_shipped_golden_modules_load_under_plain_node():
    """Every checked-in emitted module imports on the shipping runtime.

    `golden/**` is the emitter's recorded output. It is typechecked and read;
    until now nothing loaded it on node, so a construct node refuses (an
    `enum`, an extensionless import) could have been goldened.
    """
    goldens = sorted(p for p in (_HERE / "golden").glob("*.ts")
                     if not p.name.endswith(".d.ts")
                     and p.name not in _GOLDEN_NOT_LOADABLE_HERE)
    assert goldens, "no golden modules found"
    for path in goldens:
        probe = subprocess.run(
            ["node", "--input-type=module", "-e",
             "await import(process.argv[1])", str(path.resolve().as_uri())],
            cwd=_HERE, capture_output=True, text=True, timeout=120)
        assert probe.returncode == 0, (
            f"{path.name} does not load under plain node "
            f"(docs/ts-runtime-contract.md):\n{probe.stderr}")


# --------------------------------------------------------------------------- #
# the shim's surface is the emitted surface                                    #
# --------------------------------------------------------------------------- #
def test_the_shim_covers_every_matcher_the_emitter_emits():
    """`emit.py` reaches for `it`, `expect(...).toBe` and `.toBeTruthy`.

    A new matcher in the emitter with no shim entry throws by name at runtime
    rather than passing; this catches it at the source, where the fix is.
    """
    emitted = (_HERE / "emit.py").read_text(encoding="utf-8")
    shim = (_HERE / "scripts" / "vitest-shim.mjs").read_text(encoding="utf-8")
    import re
    matchers = set(re.findall(r"\)\.(to[A-Z][A-Za-z]*)\(", emitted))
    assert matchers, "no `expect(...).toX(` found in emit.py — has the shape changed?"
    missing = sorted(m for m in matchers if f"{m}(" not in shim)
    assert not missing, (
        f"backends/typescript/scripts/vitest-shim.mjs is missing {missing}; "
        "add them (issue #295, docs/ts-runtime-contract.md)")
