//! The ADMISSION SURFACE — GENERATED by `tools/build_gate_crate.py`.
//! Do not edit; edit the generator and regenerate (`--check` is a CI gate).
//!
//! # The question this module answers
//!
//! `frontier.rs` bounds where this gate may REFUSE. This module bounds the far
//! smaller region where it may ADMIT.
//!
//! The two bounds are not the same shape and must not be confused. The native
//! gate decides the composition/guarantee layer and runs no type layer, so over
//! the language at large a no-objection from it is a PARTIAL answer: the
//! reference may still refuse the same bytes in a layer this gate never ran.
//! That is why [`crate::Verdict`] has no admitting arm and why
//! [`crate::Verdict::NoObjection`] is never a green.
//!
//! There is a region, though, in which the covered layer is the WHOLE question:
//! a source that declares nothing but service method signatures and scalar type
//! aliases carries NO TERM the reference type layer decides. No function body,
//! no expression, no literal, no generic head to instantiate, no alias pointing
//! off the scalar vocabulary. For such a source, "the composition/guarantee
//! gate found nothing to refuse" and "the reference admits this" are the same
//! statement, and the gate may say so.
//!
//! `certify` is the decision procedure for that region. It returns `Some(basis)`
//! only when it has walked the ENTIRE source and accounted for every token; a
//! single byte it cannot place returns `None`, and `None` means the caller falls
//! back to the refusal surface. It never partially certifies, and it never skips
//! what it does not understand — skipping is the wave-through this crate exists
//! to prevent.
//!
//! # What is deliberately NOT in the surface
//!
//! Everything that carries a term: `fn` bodies, `component`, `provide`, `realm`,
//! `use`, `pub`, attributes, literals, record and generic types, aliases of
//! aliases. A source holding any of them is not certified, which costs a caller
//! nothing but the fallback to `NoObjection` — the direction this crate is
//! allowed to err in.
//!
//! # The manifest half
//!
//! [`certify_into`] asks the same question against a RUNNING composition, and
//! the one thing the composition can say about a candidate's declarations is
//! whether they REDECLARE something it already holds. Measured on the reference
//! (`revl.admission._admit_service_replacement`, which `lower.py` reaches only
//! when the declared name is already in the ambient service table):
//!
//! * a candidate declaring a service whose name the running composition does NOT
//!   declare is admitted into it, whatever the composition holds — there is no
//!   toucher to break, so no §5 relation to satisfy;
//! * a candidate declaring a service whose name the running composition DOES
//!   declare is gated on that relation, which is the reference type layer's
//!   business and not this gate's. Withheld.
//!
//! So the certifier needs the running composition's service NAMES, and the
//! item-186 row wire carries them: a `!services` header followed by one
//! `:S,op,op` row per declared service (`revl.manifest.manifest_wire`), whose
//! operation names this surface reads but does not use. The HEADER is the
//! load-bearing half. A wire without it does not claim to enumerate anything, so
//! the running service set is UNKNOWN rather than empty and a candidate that
//! declares a service is withheld exactly as it was before the block existed.
//! Reading an absent block as "declares nothing" would be the wave-through this
//! module exists to prevent, so the claim is spelled on the wire instead of
//! inferred from the absence of rows.
//!
//! Scalar `type` aliases are certified into a running composition unconditionally
//! (a running composition's manifest carries no aliases for one to collide with,
//! and the reference admits an alias-only candidate into any composition), with
//! one conservative exception: an alias whose NAME is a running service name is
//! withheld, because the candidate's own signatures would then be written over a
//! name the ambient also binds and this gate does not resolve that.
//!
//! A wire carrying a WITHDRAWAL row (`-C`, the item-186 replacement wave) is not
//! certified into at all, even though the fold has a full answer for it. A
//! withdrawal changes which provisions survive and can strand a running consumer,
//! and the certifier does not re-derive that reasoning: it declines the wire and
//! leaves the question to the fold, which is the direction this module is allowed
//! to err in.

/// The type names a certified signature may mention. Derived from the
/// reference's own scalar data set (`revl.typecheck._CONFIG_DATA_SCALARS`):
/// every one is a concrete builtin with no type parameter and no erasure, so
/// a signature written over them resolves with no checker to run.
pub(crate) const SCALAR_TYPES: &[&str] = &[
    "Bool",
    "Bytes",
    "Float",
    "Int",
    "Int32",
    "Str",
    "Unit",
];

/// The type names a certified source may not DECLARE. Derived from
/// `revl.typecheck._BUILTIN_TYPE_NAMES` plus the reserved opaque
/// `Principal`. Shadowing one of these is the reference's business, so a
/// source that tries is not certified here.
pub(crate) const RESERVED_TYPE_NAMES: &[&str] = &[
    "Any",
    "Bool",
    "Bytes",
    "Float",
    "Int",
    "Int32",
    "List",
    "Map",
    "Never",
    "Opt",
    "Principal",
    "Result",
    "Str",
    "Unit",
    "Value",
];

/// The REFERENCE keyword set (`revl.lexer.KEYWORDS`), not the self-host one.
/// The question the certifier asks is what the REFERENCE would make of the
/// source, so a keyword the self-host has not ported must still not be
/// mistaken for a name.
pub(crate) const REFERENCE_KEYWORDS: &[&str] = &[
    "acquire",
    "after",
    "as",
    "assert",
    "async",
    "await",
    "break",
    "commutative",
    "compensate",
    "component",
    "config",
    "continue",
    "effect",
    "else",
    "emission",
    "emit",
    "every",
    "extern",
    "fail",
    "false",
    "fn",
    "for",
    "handoff",
    "hole",
    "idempotent",
    "if",
    "in",
    "intercept",
    "isolate",
    "let",
    "match",
    "null",
    "of",
    "provide",
    "provides",
    "pub",
    "pure",
    "realm",
    "requires",
    "return",
    "service",
    "spawn",
    "subscribe",
    "test",
    "true",
    "type",
    "undo",
    "use",
    "var",
    "verified",
    "while",
    "with",
];

/// An identifier of the region this gate is willing to ADMIT in. Versioned
/// apart from [`crate::FRONTIER_ID`]: the frontier bounds the refusals, this
/// bounds the admissions, and a consumer caching an admission compares THIS
/// before trusting it against a gate built from another tree.
pub(crate) const SURFACE_ID: &str = "admission-interface:e0aaa6e00b96755a";

/// The tail every certificate carries, so the two halves of the basis line
/// cannot drift apart.
const BASIS_TAIL: &str =
    "no term the reference type layer decides, and the composition/guarantee gate raised no objection";

/// What a certified source turned out to contain. Counts only: the certificate
/// is evidence that the walk ACCOUNTED for the whole source, and the counts are
/// what make that evidence readable.
struct Shape<'a> {
    /// The service names the source DECLARES, in declaration order.
    services: Vec<&'a str>,
    /// The scalar alias names the source declares.
    aliases: Vec<&'a str>,
    methods: usize,
}

fn is_ident_start(byte: u8) -> bool {
    byte.is_ascii_alphabetic() || byte == b'_'
}

fn is_ident_byte(byte: u8) -> bool {
    byte.is_ascii_alphanumeric() || byte == b'_'
}

/// The source as tokens, or `None` when it holds a byte outside the surface's
/// alphabet.
///
/// The alphabet is the point. A string literal, a number, an `@attribute`, an
/// operator, a `[`, a non-ASCII byte — every one of them returns `None` here,
/// which is how "carries no term the type layer decides" is enforced at the
/// bottom rather than argued about at the top. Comments and whitespace are the
/// only things dropped.
fn tokens(source: &str) -> Option<Vec<&str>> {
    let bytes = source.as_bytes();
    let n = bytes.len();
    let mut out: Vec<&str> = Vec::new();
    let mut i = 0usize;
    while i < n {
        let byte = bytes[i];
        if byte == b' ' || byte == b'\t' || byte == b'\r' || byte == b'\n' {
            i += 1;
            continue;
        }
        if byte == b'/' && i + 1 < n && bytes[i + 1] == b'/' {
            while i < n && bytes[i] != b'\n' {
                i += 1;
            }
            continue;
        }
        if is_ident_start(byte) {
            let start = i;
            i += 1;
            while i < n && is_ident_byte(bytes[i]) {
                i += 1;
            }
            out.push(&source[start..i]);
            continue;
        }
        if byte == b'-' && i + 1 < n && bytes[i + 1] == b'>' {
            out.push("->");
            i += 2;
            continue;
        }
        out.push(match byte {
            b'{' => "{",
            b'}' => "}",
            b'(' => "(",
            b')' => ")",
            b',' => ",",
            b':' => ":",
            b'=' => "=",
            _ => return None,
        });
        i += 1;
    }
    Some(out)
}

/// A token usable as a declared or bound NAME: an identifier that is not a
/// reference keyword. Checked against the REFERENCE keyword set, not the
/// self-host one, because the question is what the reference would make of the
/// source.
fn is_name(token: &str) -> bool {
    match token.as_bytes().first() {
        Some(&byte) if is_ident_start(byte) => !REFERENCE_KEYWORDS.contains(&token),
        _ => false,
    }
}

/// A name as a MANIFEST WIRE field: every byte an identifier byte, and not a
/// reference keyword.
///
/// [`is_name`] is written for tokens that already came out of [`tokens`], where
/// an identifier run is guaranteed and only the first byte has to be checked. A
/// wire field has no such guarantee: `A/b` and `a<b` reach here whole, and
/// reading either as a name would have the certifier compare a running service
/// list against strings it never verified. So this checks every byte, and a row
/// it cannot read is a wire the surface declines rather than one it guesses at.
fn is_wire_name(field: &str) -> bool {
    if field.is_empty() || REFERENCE_KEYWORDS.contains(&field) {
        return false;
    }
    let bytes = field.as_bytes();
    is_ident_start(bytes[0]) && bytes[1..].iter().all(|&b| is_ident_byte(b))
}

/// A name this source may DECLARE: a name that does not shadow a reference
/// builtin type or the reserved opaque `Principal`.
fn is_declarable(token: &str) -> bool {
    is_name(token) && !RESERVED_TYPE_NAMES.contains(&token)
}

fn has_duplicate(names: &[&str]) -> bool {
    for (i, name) in names.iter().enumerate() {
        if names[i + 1..].contains(name) {
            return true;
        }
    }
    false
}

/// Walk the whole source, or refuse to certify it.
///
/// The walk is total by construction: every iteration either consumes a token
/// and advances, or returns `None`. There is no "skip what I do not recognise"
/// branch, which is the property that makes the certificate mean something.
fn shape_of(source: &str) -> Option<Shape<'_>> {
    let toks = tokens(source)?;
    let n = toks.len();

    // Pass one: the alias names, so a signature may name an alias declared
    // further down the file. Pass two validates every one of them, so a name
    // collected here that is not a real alias declaration still fails below.
    let mut aliases: Vec<&str> = Vec::new();
    for (i, tok) in toks.iter().enumerate() {
        if *tok == "type" && i + 1 < n {
            aliases.push(toks[i + 1]);
        }
    }
    let known = |name: &str| SCALAR_TYPES.contains(&name) || aliases.contains(&name);

    let mut services: Vec<&str> = Vec::new();
    let mut methods_total = 0usize;
    let mut declared_aliases = 0usize;
    let mut i = 0usize;
    while i < n {
        if toks[i] == "type" {
            // `type <Name> = <Scalar>` — the right-hand side is a SCALAR and
            // never another alias, so the alias graph is one level deep and a
            // cycle (which the reference decides, and this gate does not) is
            // unrepresentable rather than checked.
            if i + 3 >= n || toks[i + 2] != "=" {
                return None;
            }
            if !is_declarable(toks[i + 1]) || !SCALAR_TYPES.contains(&toks[i + 3]) {
                return None;
            }
            declared_aliases += 1;
            i += 4;
            continue;
        }
        if toks[i] != "service" || i + 2 >= n {
            return None;
        }
        if !is_declarable(toks[i + 1]) || toks[i + 2] != "{" {
            return None;
        }
        services.push(toks[i + 1]);
        i += 3;
        let mut methods: Vec<&str> = Vec::new();
        while i < n && toks[i] != "}" {
            if toks[i] != "fn" || i + 1 >= n || !is_name(toks[i + 1]) {
                return None;
            }
            methods.push(toks[i + 1]);
            i += 2;
            if i >= n || toks[i] != "(" {
                return None;
            }
            i += 1;
            let mut params: Vec<&str> = Vec::new();
            while i < n && toks[i] != ")" {
                if !is_name(toks[i]) || i + 2 >= n || toks[i + 1] != ":" {
                    return None;
                }
                if !known(toks[i + 2]) {
                    return None;
                }
                params.push(toks[i]);
                i += 3;
                if i < n && toks[i] == "," {
                    i += 1;
                }
            }
            if i >= n || has_duplicate(&params) {
                return None;
            }
            i += 1; // the `)`
            if i < n && toks[i] == "->" {
                if i + 1 >= n || !known(toks[i + 1]) {
                    return None;
                }
                i += 2;
            }
            methods_total += 1;
        }
        if i >= n || has_duplicate(&methods) {
            return None;
        }
        i += 1; // the `}`
    }
    // The reference refuses a duplicate service and a duplicate method
    // (`duplicate service `A``, `duplicate method `f` in service A`) and the
    // native gate does not, so the certifier carries those two obligations
    // itself. Without them the surface would admit two programs the reference
    // refuses — measured, which is why they are here and not assumed away.
    if has_duplicate(&services) || has_duplicate(&aliases) {
        return None;
    }
    if declared_aliases != aliases.len() {
        return None;
    }
    for alias in &aliases {
        if services.contains(alias) {
            return None;
        }
    }
    Some(Shape {
        services,
        aliases,
        methods: methods_total,
    })
}

/// `Some(basis)` when `source` is inside the admission surface, `None`
/// otherwise. The basis is the certificate's why-trace, for a log or a receipt;
/// it is NOT on the admission wire, which is byte-identical to `revl.gate`'s.
pub(crate) fn certify(source: &str) -> Option<String> {
    let shape = shape_of(source)?;
    Some(format!(
        "admission surface {}: services={} aliases={} methods={}; {}",
        SURFACE_ID, shape.services.len(), shape.aliases.len(), shape.methods,
        BASIS_TAIL
    ))
}

/// `Some(basis)` when `source` may be admitted INTO the running composition
/// `manifest`, `None` otherwise.
///
/// The candidate has to clear `shape_of` exactly as it does standalone, and then
/// one more obligation the running composition imposes: nothing it declares may
/// REDECLARE a service the composition already declares. That is the only
/// interaction the reference has between an interface-only candidate and a
/// running manifest, and it is the one the item-186 service block
/// (`!services` + `:S,op,op` rows) exists to make answerable. The operations a
/// row carries are the FOLD's business (the member rule of docs/design/457 T4b);
/// this surface decides redeclaration, which is decided by name.
///
/// A wire with no service block does not say what the composition declares, so
/// the set is UNKNOWN: any declared service is withheld, which is exactly the
/// answer this function gave before the block existed. Fail closed on silence.
///
/// The empty manifest is the empty composition, and `crate::issue_admission_into`
/// routes it to `crate::issue_admission` before this is reached.
pub(crate) fn certify_into(source: &str, manifest: &str) -> Option<String> {
    let shape = shape_of(source)?;
    let running = manifest_shape(manifest)?;
    let declared = match running.services.as_ref() {
        // The wire is silent about the running services. A declared service could
        // be a redeclaration and this gate cannot tell, so it does not guess.
        None => {
            if !shape.services.is_empty() {
                return None;
            }
            &[][..]
        }
        Some(names) => names.as_slice(),
    };
    // Aliases are held to the same disjointness even though only services can
    // redeclare: an alias sharing a running service's name would have the
    // candidate's own signatures written over a name the ambient also binds, and
    // this gate does not resolve that.
    for name in shape.services.iter().chain(shape.aliases.iter()) {
        if declared.contains(name) {
            return None;
        }
    }
    Some(format!(
        "admission surface {}: services={} aliases={} methods={}, none of them redeclaring one of the running composition's {}; its {} provision rows resolve its {} requirement rows; {}",
        SURFACE_ID,
        shape.services.len(),
        shape.aliases.len(),
        shape.methods,
        match running.services.as_ref() {
            Some(names) => format!("{} declared services", names.len()),
            None => "unenumerated services (the candidate declares none)".to_string(),
        },
        running.provisions,
        running.requirements,
        BASIS_TAIL
    ))
}

/// What the admission surface reads off a manifest wire.
struct Running<'a> {
    provisions: usize,
    requirements: usize,
    /// The running composition's declared service names, `None` when the wire
    /// carries no `!services` header and therefore makes no claim about them.
    /// `None` is NOT the empty set: see [`certify_into`].
    services: Option<Vec<&'a str>>,
}

/// The [`Running`] reading of a manifest wire every one of whose rows the
/// admission surface can account for, `None` otherwise.
///
/// The accountable kinds are the provision (`C/k/r`), the requirement in its
/// three spellings (`C<k`, `C<k/r`, `C<*k`), the route (`C>k/r1,r2`), the
/// handoff (`C=k:T`) and the service block (`!services`, `:S` or `:S,op,op`).
/// Everything else declines the wire, which is a withheld admission and
/// not a refusal: a `!halted` header, and — deliberately, even
/// though the fold has a full answer for it — a WITHDRAWAL row (`-C`). A
/// withdrawal changes which provisions survive and can strand a running
/// consumer; re-deriving that here would be a second implementation of the fold's
/// reasoning, and a second implementation is exactly where the two would drift.
///
/// Two obligations beyond the kinds. Every requirement must find its KEY on some
/// provision row — the running composition is supposed to be one the reference
/// already admitted, and a requirement naming a key nothing provides says the
/// wire is not describing one. By KEY and not by (key, realm), deliberately: the
/// realm a requirement row carries is the consumer's own `isolate` of that key,
/// which is not always the realm `_link` resolves it in, so a per-realm
/// obligation here would decline compositions the reference did admit. This
/// check exists to catch a bogus wire, not to re-derive the link. And a `:S` row
/// only counts inside a block a `!services` header CLAIMED: a service list nobody
/// vouched for is not a list an admission may rest on.
///
/// A ROUTE row (issue #1036) is READ and counted as nothing. Its key is already
/// on the wire as a `C<*k` requirement and already carries the by-key
/// obligation; the legs say which realms it binds, and a per-realm obligation
/// here would be the same re-derivation of the link the by-key rule above
/// declines. Reading it is the point: a row this function cannot parse declines
/// the WHOLE wire, so leaving route rows out would have silently withheld the
/// admission surface from every routed composition — the shape of the bug the
/// `C<*k` and `C<k/r` spellings had here until they were read.
///
/// A HANDOFF row (`C=k:T`, item 186 wave part 2) is read the same way, for the
/// same reason: it is the running provider's EXPORTED state shape, the fold
/// compares it against the candidate's accepted shape with the §5 relation, and
/// nothing here counts it. Its key is already on the wire as that component's
/// own provision row. It is read BEFORE the route row because the TYPE field is
/// the one place on the wire carrying an arbitrary type SPELLING and a function
/// type spells `->`: read after, `Store=st:(Int) -> Str` would split at its `>`
/// and look like a route. The TYPE itself is NOT validated against
/// [`is_wire_name`] — it is a type spelling, not a name, and the only thing that
/// may judge it is the relation that compares it.
fn manifest_shape(manifest: &str) -> Option<Running<'_>> {
    let mut provided: Vec<&str> = Vec::new();
    let mut required: Vec<&str> = Vec::new();
    let mut services: Option<Vec<&str>> = None;
    for row in manifest.split(';') {
        if row.is_empty() {
            return None;
        }
        if row == "!services" {
            // One header per wire: two blocks leave it undecidable which of them
            // is the complete one, and "undecidable" is not a ground to admit on.
            if services.is_some() {
                return None;
            }
            services = Some(Vec::new());
            continue;
        }
        if let Some(spec) = row.strip_prefix(':') {
            // `:S` or `:S,op,op` — the name, and optionally the operations the
            // running service declares. THIS surface reads only the name: the
            // one obligation it has is that the candidate redeclares no running
            // service, and that is decided by name. The operations are read to
            // VALIDATE them, so a garbled row declines the whole wire here
            // exactly as it refuses it in the fold, rather than one reader
            // admitting on a row the other cannot parse.
            let (name, ops) = match spec.split_once(',') {
                Some((name, ops)) => (name, Some(ops)),
                None => (spec, None),
            };
            let claimed = services.as_mut()?;
            if !is_wire_name(name) || claimed.contains(&name) {
                return None;
            }
            if let Some(ops) = ops {
                // `:S,` is the EMPTY operation claim and is well formed; any
                // other list is a comma-separated run of wire names.
                if !ops.is_empty() && ops.split(',').any(|op| !is_wire_name(op)) {
                    return None;
                }
            }
            claimed.push(name);
            continue;
        }
        if row.starts_with('-') {
            // A withdrawal. The fold decides it; this surface does not.
            return None;
        }
        if let Some((component, spec)) = row.split_once('=') {
            // `C=k:T` — the state shape `component` exports at `k` (item 53).
            let (key, state) = spec.split_once(':')?;
            if !is_wire_name(component) || !is_wire_name(key) || state.is_empty() {
                return None;
            }
            continue;
        }
        if let Some((component, spec)) = row.split_once('>') {
            // `C>k/r1,r2` — the realms a running component binds `k` across. It
            // is read BEFORE the provision fallback because it carries a `/` of
            // its own and would otherwise look like a provision whose component
            // name is `C>k`.
            let (key, realms) = spec.split_once('/')?;
            if !is_wire_name(component) || !is_wire_name(key) {
                return None;
            }
            // an empty label is the shared realm, exactly as on a provision row
            if realms.split(',').any(|r| !r.is_empty() && !is_wire_name(r)) {
                return None;
            }
            continue;
        }
        if let Some((component, spec)) = row.split_once('<') {
            if component.is_empty() || spec.is_empty() || component.contains('/') {
                return None;
            }
            if !is_wire_name(component) {
                return None;
            }
            // `*k` is the item-162 multi-realm bind. Its per-realm legs are not
            // on the wire at all, so a spelling that also names a realm is a
            // garbled row rather than a requirement.
            let (spec, routed) = match spec.strip_prefix('*') {
                Some(rest) => (rest, true),
                None => (spec, false),
            };
            // the realm is CHECKED and not kept: resolution below is by key
            // (see this function's contract), but a realm field that is not a
            // name still means a row this surface cannot read.
            let (key, realm) = match spec.split_once('/') {
                Some(_) if routed => return None,
                Some((key, realm)) => (key, realm),
                None => (spec, ""),
            };
            if !is_wire_name(key) || (!realm.is_empty() && !is_wire_name(realm)) {
                return None;
            }
            required.push(key);
            continue;
        }
        let mut parts = row.splitn(3, '/');
        let component = parts.next()?;
        let key = parts.next()?;
        let realm = parts.next()?;
        if component.is_empty() || key.is_empty() {
            return None;
        }
        if !is_wire_name(component) || !is_wire_name(key) {
            return None;
        }
        if !realm.is_empty() && !is_wire_name(realm) {
            return None;
        }
        provided.push(key);
    }
    for key in &required {
        if !provided.contains(key) {
            return None;
        }
    }
    Some(Running {
        provisions: provided.len(),
        requirements: required.len(),
        services,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    const INTERFACE: &str = "service Store {\n  fn get(key: Str) -> Str\n  fn put(key: Str, value: Str)\n}\n";

    #[test]
    fn an_interface_only_source_is_certified() {
        let basis = certify(INTERFACE).expect("an interface-only source is inside the surface");
        assert!(basis.contains("services=1"), "{}", basis);
        assert!(basis.contains("methods=2"), "{}", basis);
        assert!(basis.contains(SURFACE_ID), "{}", basis);
    }

    #[test]
    fn the_empty_source_is_the_empty_composition_and_is_certified() {
        for source in ["", "   \n", "// just a note\n"] {
            let basis = certify(source).expect("a source with no declarations is admissible");
            assert!(basis.contains("services=0 aliases=0 methods=0"), "{}", basis);
        }
    }

    #[test]
    fn a_scalar_alias_is_certified_and_usable_in_a_signature() {
        let source = "type Key = Str\nservice S {\n  fn get(k: Key) -> Key\n}\n";
        assert!(certify(source).is_some());
    }

    #[test]
    fn an_alias_of_an_alias_is_not_certified() {
        // The alias graph is one level deep by construction, so a cycle cannot
        // be written rather than having to be detected.
        assert!(certify("type A = Str\ntype B = A\n").is_none());
    }

    #[test]
    fn a_term_of_any_kind_leaves_the_surface() {
        for source in [
            "fn id(x: Int) -> Int { return x }",
            "component C provides s: S {\n  provide s {\n    fn f(x) = x\n  }\n}\n",
            "service S {\n  fn f(x: Str) -> Str\n}\nfn g() -> Int { return 1 }",
            "type R = { id: Int }",
            "service S {\n  fn f(x: List[Int]) -> Int\n}\n",
            "use \"./other.rvl\" { S }\n",
            "pub service S {\n  fn f(x: Int) -> Int\n}\n",
        ] {
            assert!(certify(source).is_none(), "must not certify: {:?}", source);
        }
    }

    #[test]
    fn the_two_obligations_the_native_gate_does_not_carry() {
        // The reference refuses both of these and `admit_src` raises no
        // objection to either, so the certifier has to decide them itself or the
        // surface would issue an admission the reference refuses.
        assert!(certify("service A {\n  fn f(x: Int) -> Int\n}\nservice A {\n  fn g(x: Int) -> Int\n}\n").is_none());
        assert!(certify("service A {\n  fn f(x: Int) -> Int\n  fn f(y: Int) -> Int\n}\n").is_none());
    }

    #[test]
    fn a_declaration_may_not_shadow_a_reference_builtin_type() {
        for source in ["service Int {\n}\n", "type Opt = Str\n", "type Principal = Str\n"] {
            assert!(certify(source).is_none(), "must not certify: {:?}", source);
        }
    }

    #[test]
    fn a_type_outside_the_scalar_vocabulary_leaves_the_surface() {
        assert!(certify("service S {\n  fn f(x: Unknown) -> Int\n}\n").is_none());
        assert!(certify("service S {\n  fn f(x: Any) -> Int\n}\n").is_none());
    }

    #[test]
    fn a_non_ascii_byte_leaves_the_surface() {
        assert!(tokens("service Ünicode {}").is_none());
        assert!(certify("service S {\n  fn f(x: Str) -> Str // caf\u{e9}\n}\n").is_some());
    }

    #[test]
    fn a_duplicate_parameter_name_leaves_the_surface() {
        assert!(certify("service S {\n  fn f(x: Int, x: Int) -> Int\n}\n").is_none());
    }

    #[test]
    fn an_unterminated_declaration_leaves_the_surface() {
        for source in ["service S {", "service S {\n  fn f(x: Int\n}", "type A =", "service"] {
            assert!(certify(source).is_none(), "must not certify: {:?}", source);
        }
    }

    // The manifest half.

    #[test]
    fn a_declaration_free_candidate_is_certified_into_a_running_composition() {
        let basis = certify_into("// nothing to add\n", "Kv/store/;App/app/;App<store")
            .expect("a candidate that declares nothing cannot collide with the running shapes");
        assert!(basis.contains("2 provision rows"), "{}", basis);
        assert!(basis.contains("1 requirement rows"), "{}", basis);
    }

    #[test]
    fn an_interface_candidate_is_not_certified_into_a_running_composition() {
        // The wire carries no service shapes, so a declared `Store` may or may
        // not be the running one and this gate cannot tell. Not certified.
        assert!(certify(INTERFACE).is_some());
        assert!(certify_into(INTERFACE, "Kv/store/").is_none());
    }

    #[test]
    fn a_row_the_surface_cannot_account_for_is_not_certified_into() {
        for wire in ["!halted", "Kv/store/;-Kv/store/", "Kv/store=Int", "!wat", "Kv/store/;"] {
            assert!(certify_into("", wire).is_none(), "must not certify into {:?}", wire);
        }
    }

    #[test]
    fn a_dangling_requirement_row_is_not_certified_into() {
        assert!(certify_into("", "App/app/;App<store").is_none());
        assert!(certify_into("", "Kv/store/;App<store").is_some());
    }

    // The item-186 replacement wave's own row shapes, which this surface has to
    // read rather than trip over.

    #[test]
    fn the_waves_requirement_spellings_are_read_rather_than_tripped_over() {
        // `C<k/r` (realm-bearing) and `C<*k` (the item-162 multi-realm bind) are
        // the replacement wave's own row shapes. Both are READ: the key is what
        // has to resolve, in any realm, because the realm a requirement row
        // carries is the consumer's own isolate and not necessarily where the
        // link resolves it.
        assert!(certify_into("", "Kv/store/t1;App/app/;App<store/t1").is_some());
        assert!(certify_into("", "Kv/store/;App/app/;App<store/t1").is_some());
        assert!(certify_into("", "Kv/store/t1;App/app/;App<*store").is_some());
        // a key nothing provides is still a wire this surface declines
        assert!(certify_into("", "Kv/other/;App/app/;App<*store").is_none());
        assert!(certify_into("", "Kv/other/;App/app/;App<store/t1").is_none());
        // and a spelling that tries to be both routed and realm-qualified is a
        // garbled row, not a requirement
        assert!(certify_into("", "Kv/store/t1;App/app/;App<*store/t1").is_none());
    }

    #[test]
    fn a_withdrawal_row_declines_the_wire_rather_than_being_re_derived() {
        // The fold decides a withdrawal in full (item 186, the replacement
        // wave). This surface does not re-derive it: a wire carrying one is
        // withheld, whatever the candidate is.
        for wire in ["Kv/store/;-Kv", "Kv/store/;!services;:Store;-Kv", "-Kv"] {
            assert!(certify_into("", wire).is_none(), "must not certify into {:?}", wire);
        }
    }

    #[test]
    fn a_handoff_row_is_read_rather_than_tripped_over() {
        // `C=k:T` (item 186, wave part 2) is the running provider's EXPORTED
        // state shape. The fold compares it against the candidate's accepted
        // shape; this surface counts it as nothing, exactly as it counts a
        // route row as nothing, and must not decline a wire for carrying one —
        // declining would have silently withheld the admission arm from every
        // STATEFUL running composition.
        assert!(certify_into("", "Kv/store/;Kv=store:Str").is_some());
        assert!(certify_into("", "Kv/store/;Kv=store:Str;App/app/;App<store").is_some());
        // a function-typed shape carries a `>`, which is why the handoff row is
        // read AHEAD of the route row: read after, this would split at its own
        // arrow and look like a garbled route.
        assert!(certify_into("", "Kv/store/;Kv=store:(Int) -> Str").is_some());
        // the type is opaque here: it is a type SPELLING, not a wire name, and
        // the only thing that may judge it is the relation that compares it
        assert!(certify_into("", "Kv/store/;Kv=store:Map[Str, Int]").is_some());
        // a garbled handoff row is still a row this surface cannot read
        for wire in ["Kv/store/;Kv=store", "Kv/store/;Kv=store:", "Kv/store/;Kv=:Str",
                     "Kv/store/;=store:Str"] {
            assert!(certify_into("", wire).is_none(), "must not certify into {:?}", wire);
        }
    }

    // The item-186 service block (issue #346).

    const ENUMERATED: &str = "Kv/store/;App/app/;App<store;!services;:Store;:AppSvc";

    #[test]
    fn a_fresh_interface_is_certified_into_an_enumerated_composition() {
        // `Cache` is not a name the running composition declares, so there is no
        // running toucher for the §5 relation to protect and the reference admits
        // it into the composition. This is the admission the wire's service block
        // buys; without the block the same bytes are withheld (below).
        let basis = certify_into("service Cache {\n  fn lookup(key: Str) -> Str\n}\n", ENUMERATED)
            .expect("a fresh interface cannot redeclare a running service");
        assert!(basis.contains("services=1"), "{}", basis);
        assert!(basis.contains("2 declared services"), "{}", basis);
    }

    #[test]
    fn a_redeclared_interface_is_withheld_from_an_enumerated_composition() {
        // `Store` IS declared by the running composition, so whether this is an
        // admissible replacement is the §5 compatibility relation - the reference
        // type layer, which this gate does not run. Withheld.
        assert!(certify_into(INTERFACE, ENUMERATED).is_none());
        // ... including when the candidate's shape is byte-identical to the
        // running one. The wire carries the NAME, not the shape, so "identical"
        // is not a question this gate can ask.
        assert!(certify_into("service AppSvc {\n  fn snapshot() -> Str\n}\n", ENUMERATED).is_none());
    }

    #[test]
    fn a_wire_without_the_header_makes_no_claim_about_the_running_services() {
        // Silence is not "declares nothing": the same fresh interface certified
        // above is withheld here, because nothing on this wire says the running
        // composition does not already hold a `Cache`.
        let fresh = "service Cache {\n  fn lookup(key: Str) -> Str\n}\n";
        assert!(certify_into(fresh, ENUMERATED).is_some());
        assert!(certify_into(fresh, "Kv/store/;App/app/;App<store").is_none());
    }

    #[test]
    fn an_empty_service_block_is_a_composition_that_declares_no_service() {
        assert!(certify_into(INTERFACE, "Kv/store/;!services").is_some());
    }

    #[test]
    fn a_scalar_alias_is_certified_into_a_running_composition() {
        // A running composition's manifest carries no aliases, so there is
        // nothing for one to collide with and the reference admits an alias-only
        // candidate into any composition.
        assert!(certify_into("type Key = Str\n", "Kv/store/;App/app/;App<store").is_some());
        assert!(certify_into("type Key = Str\n", ENUMERATED).is_some());
        // ... but an alias that takes a running service's NAME is withheld: the
        // candidate's signatures would then be written over a name the ambient
        // also binds.
        assert!(certify_into("type Store = Str\n", ENUMERATED).is_none());
    }

    #[test]
    fn the_block_reads_the_same_beside_the_waves_own_rows() {
        // The interaction the two additions create: a wire carrying realm-bearing
        // and routed requirement rows AND a service block still reads, and the
        // block still decides the same way it does on a plain wire.
        let combined = "Kv/store/t1;App/app/;App<store/t1;Log/log/;Sink<*log;\
!services;:Store;:AppSvc;:Logger";
        assert!(certify_into("service Cache {\n  fn lookup(key: Str) -> Str\n}\n", combined).is_some());
        assert!(certify_into(INTERFACE, combined).is_none());
        assert!(certify_into("type Logger = Str\n", combined).is_none());
    }

    #[test]
    fn a_malformed_service_block_is_not_certified_into() {
        for wire in [
            // a `:S` row outside a claimed block - a list nobody vouched for
            "Kv/store/;:Store",
            // the header twice: which block is the complete one?
            "Kv/store/;!services;:Store;!services;:AppSvc",
            // a duplicate, and a name that is not one
            "Kv/store/;!services;:Store;:Store",
            "Kv/store/;!services;:9bad",
            "Kv/store/;!services;:",
            "Kv/store/;!services;:service",
            "Kv/store/;!services;:A/b",
        ] {
            assert!(certify_into("", wire).is_none(), "must not certify into {:?}", wire);
        }
    }
}
