//! `revl-gate` — the revl admission gate as an embeddable rust library
//! (roadmap item 332, Stage 3; design `docs/design/332-embeddable-gate-api.md`).
//!
//! GENERATED by `tools/build_gate_crate.py` from the self-host compiler. Do not
//! edit by hand: CI regenerates from the same tree and fails on any byte
//! difference (`tests/test_gate_crate_drift.py`).
//!
//! # What this crate is
//!
//! Layer 1 of the gate API, admit-only: [`admit`] is a PURE function of its
//! argument — no disk, no clock, no live state, no cordis runtime boot —
//! returning the self-host compiler's verdict on a STANDALONE program. It is
//! `selfhost/lower.rvl::admit_src` (lex -> parse -> the composition/guarantee
//! gate) compiled to rust through the reference rust backend. [`admit_into`] is
//! the same gate reached across a composition boundary: the verdict on `source`
//! once it is admitted INTO a RUNNING manifest (item 186).
//!
//! ```no_run
//! use revl_gate::{admit, Verdict};
//!
//! match admit("fn id(x: Int) -> Int { return x }") {
//!     // A definitive refusal. Byte-agreeing with the reference compiler on
//!     // the covered corpus: stop here, and show the message as-is.
//!     Verdict::Refused { code, message } => println!("refused ({}): {}", code, message),
//!     // NOT an admission. See "This gate issues no admissions" below.
//!     Verdict::NoObjection => println!("nothing this gate can refuse"),
//!     // The gate declined to decide at all.
//!     Verdict::OutsideFrontier { reason } => println!("undecided: {}", reason),
//! }
//! ```
//!
//! # This gate issues no admissions
//!
//! Read this before wiring the crate into anything.
//!
//! The self-host compiler is behind the reference implementation (roadmap item
//! 391), and the shape of that gap is not "a few missing constructs" — it is a
//! whole missing LAYER. `admit_src` decides the composition and guarantee layer
//! (`G1`..`G4`, `A1`, `PRELUDE`, and parse failures as `BAD`). It does **not**
//! run the reference's type layer. Measured, not assumed: the reference refuses
//! `fn f() -> Int { return "s" }`, `fn f() -> Int { return undefined_name }`
//! and `fn f() -> { }`; the self-host gate raises no objection to any of them.
//!
//! So there is no `Verdict::Admitted` arm, and no `is_admitted()`. The
//! non-refusing outcome is [`Verdict::NoObjection`], which means exactly
//! *"this gate found nothing it is able to refuse"* and never *"the reference
//! would admit this"*. A host that must ADMIT — because it is about to run the
//! program — still has to get a reference verdict (`revl compile`, or
//! `revl.gate.admit` on py). What this crate buys is the other direction: a
//! local, in-process, allocation-cheap REFUSAL that agrees with the reference
//! byte for byte on the covered corpus, with no round trip and no Python.
//!
//! The two divergence directions are not symmetric, and this asymmetry is the
//! whole design: refusing what the reference admits is an inconvenience;
//! ADMITTING what the reference refuses is the defect class the admission-gate
//! arc exists to prevent. A crate that cannot issue an admission cannot commit
//! that defect.
//!
//! On the wire, [`Verdict::to_json`] therefore emits `"admitted": false` for
//! EVERY arm. A consumer written against the fixed `{admitted, code, message}`
//! shape (`docs/design/332-embeddable-gate-api.md`) reads this gate as
//! "never admits" rather than misreading a no-objection as an admission; the
//! arm itself is carried in the extra `"verdict"` field.
//!
//! # Fail closed, always
//!
//! [`Verdict::OutsideFrontier`] means *this gate is not entitled to decide*,
//! and the crate returns it whenever:
//!
//! * the source uses a construct in the generated frontier table
//!   (see [`FRONTIER_ID`] and `src/frontier.rs`);
//! * the source is larger than [`MAX_SOURCE_BYTES`] — the emitted front end is
//!   deeply recursive and a stack exhaustion ABORTS, which cannot be turned
//!   back into a refusal;
//! * the native gate panics while deciding (caught via `catch_unwind`);
//! * the native gate returns a verdict wire shape this crate does not
//!   recognise;
//! * in [`admit_into`], the manifest wire itself is longer than
//!   [`MAX_SOURCE_BYTES`] (the fold parses it with the same front end), or the
//!   fold's answer is a shape this crate does not recognise.
//!
//! # The manifest arm (issue #346)
//!
//! [`admit_into(source, manifest)`](admit_into) answers a different question
//! from [`admit`]: not "is this text well formed on its own", but "does this
//! text compose with the composition that is ALREADY RUNNING". `source` is
//! decided against the union of the manifest and the incoming text, so a key the
//! running composition already holds conflicts (G2), a route into a realm the
//! union does not provide dangles (G2), and a dependency cycle that spans the
//! manifest boundary is a cycle (G3). The manifest arrives as item 186's row
//! wire (`docs/design/186-ambient-admission-guarantees.md`), and the fold is
//! `selfhost/lower.rvl::admit_ambient`, compiled to rust like [`admit`].
//!
//! What this arm decides is the G2/G3 legs of ambient admission and nothing
//! else. The wire has room for row kinds the landed wave does not carry —
//! replacement (`-C`) and handoff (`C=k:T`), both of which need the type layer —
//! and those rows are REFUSED as `MANIFEST` rather than skipped, because a row
//! this gate cannot honour is exactly where a stub that ignored its inputs would
//! wave a program through. An empty `manifest` (`""`) is the empty composition,
//! which makes [`admit_into`] byte-identical to [`admit`]: the arm is a
//! generalisation, not a second implementation.
//!
//! ```no_run
//! use revl_gate::{admit_into, Verdict};
//!
//! // `Kv/store/` is a provision the running composition already holds.
//! let running = "Kv/store/;App/app/;App<store";
//! let candidate = "service Store { fn get(k: Str) -> Str } \
//!                  component CacheLayer provides store: Store { \
//!                    provide store { fn get(k) { return k } } }";
//! match admit_into(candidate, running) {
//!     // A refusal the reference agrees with: this candidate re-provides `store`.
//!     Verdict::Refused { code, message } => println!("refused ({}): {}", code, message),
//!     // NOT an admission. See "This gate issues no admissions" above.
//!     Verdict::NoObjection => println!("nothing this gate can refuse"),
//!     // The gate declined to decide at all: a row it cannot honour, a frontier
//!     // gap, or an aborted fold. Fail closed.
//!     Verdict::OutsideFrontier { reason } => println!("undecided: {}", reason),
//! }
//! ```
//!
//! Like [`admit`], this arm NEVER admits. It does not run the reference type
//! layer, so a type-incorrect candidate lands on `NoObjection`; and the
//! requirements a candidate declares are checked for disjointness and
//! acyclicity, not resolved. Use `revl.gate.admit_into` on py when the decision
//! must be an admission.
//!
//! # `compile_to` is Stage 4
//!
//! Exported so the shape is fixed; it refuses unconditionally today, because
//! the self-host emitters still carry `@py`-only helper externs and do not emit
//! to rust at all.
//!
//! # The navigation surface
//!
//! [`symbols`] is a SECOND, independent surface over the same front end: the
//! declarations a document contains and the line each sits on, which is what an
//! editor needs for go-to-definition and hover (roadmap item 336 slice 2). It
//! issues no verdicts and says nothing about whether a program may run — a
//! refused program has declarations to navigate like any other — so it is
//! versioned separately from the admission surface above, by
//! [`SYMBOLS_API_VERSION`] rather than by [`GATE_API_VERSION`] (which is held in
//! lockstep with `revl.gate` on py, and `revl.gate` has no navigation surface).
//! Its own fail-closed rule is the mirror of this one: it answers only what it
//! can answer EXACTLY, and every uncertainty is an absence rather than a guess.
//!
//! # Layer 2: the session surface (item 334 slice 1)
//!
//! See [`session`]. [`session::Session`] is the foundational first slice of the
//! rust host: the generation state machine, the untrusted-author admission entry
//! (`propose`/`admit`, reusing this crate's [`admit`]), and the item-245
//! witnessed-call recording path (`call`/`commit`/`abort`/`unload`). The ACCEPT
//! half of `propose` (activate + health-gate + swap), the witnessed-effect
//! runtime, the WAL, and the approver callback are the remaining slices; a
//! candidate the native gate does not refuse is fail-closed, never waved through.
//!
//! # Two host obligations
//!
//! * The fail-closed panic path uses [`std::panic::catch_unwind`]. A profile
//!   built with `panic = "abort"` defeats it: a native gate abort then takes the
//!   process down instead of producing `OutsideFrontier`. That is loud, not
//!   silent, so it is still not a false admission — but prefer
//!   `panic = "unwind"` in any profile that calls this crate.
//! * The default panic hook still prints to stderr when the fail-closed path
//!   fires. Install your own hook if that noise matters.

#![forbid(unsafe_code)]

// The generated module carries the reference emitter's output verbatim,
// including the self-host's own `test` blocks (which run under `cargo test`).
// It is machine-written, so its style lints are noise in a consumer's build.
#[allow(non_snake_case, unused_braces, clippy::all)]
mod selfhost;

mod frontier;
pub mod ir;
pub mod session;
pub mod symbols;

pub use frontier::{FRONTIER_ID, MAX_SOURCE_BYTES};
pub use ir::{check_ir_boundary, IrRefusal, KNOWN_IR_FIELDS, KNOWN_IR_REVISIONS};

/// The semver of the GATE SURFACE itself (`gate_version().api`). Bumped by
/// surface changes only, independent of the language version. Kept in lockstep
/// with `revl.gate.GATE_API_VERSION` on py; the generator refuses to run if the
/// two disagree.
pub const GATE_API_VERSION: &str = "1.0.0";

/// The revl language/package version this gate's refusals are drawn from.
pub const LANGUAGE_VERSION: &str = "2.0.0";

/// The semver of the NAVIGATION surface ([`symbols`]), versioned on its own.
/// It is not part of the admission surface [`GATE_API_VERSION`] names and has
/// no twin on py, so the two move independently; the self-host pin both are
/// drawn from is [`FRONTIER_ID`].
pub const SYMBOLS_API_VERSION: &str = "0.1.0";

/// What this gate actually decides, in one line. The reference type layer is
/// deliberately absent — see the crate docs, "This gate issues no admissions".
pub const COVERED_LAYER: &str = "composition + guarantee layer (G1..G4, A1, PRELUDE) and parse (BAD); NOT the reference type layer";

/// The `code` a frontier gap reports on the wire.
pub const FRONTIER_CODE: &str = "FRONTIER";

/// The three values a host can branch on (design "Versioning").
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GateVersion {
    /// Semver of the gate surface. Bumped by surface changes only.
    pub api: &'static str,
    /// The revl language/package version this gate's refusals are drawn from.
    pub language: &'static str,
    /// An identifier of the COVERED surface. Compare before trusting two gates'
    /// agreement: different ids cover different languages.
    pub frontier: &'static str,
    /// The layer this gate decides, as prose. See [`COVERED_LAYER`].
    pub layer: &'static str,
}

/// A verdict from the native gate.
///
/// Three arms, none of which is an admission. `code` is API (the guarantee tags
/// are append-only; an existing code never changes meaning); `message` is the
/// gate's why-trace verbatim at this version and is NOT promised stable across
/// versions.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Verdict {
    /// The gate refuses this program. `code` is the guarantee tag (`G1`..`G4`,
    /// `A1`, `PRELUDE`, `BAD`, ...); `message` is the diagnostic verbatim, and
    /// byte-agrees with the reference compiler's on the covered corpus.
    Refused { code: String, message: String },
    /// The gate found nothing it is able to refuse.
    ///
    /// **This is not an admission.** This gate does not run the reference type
    /// layer, so a type-incorrect program lands here. Get a reference verdict
    /// before running anything.
    NoObjection,
    /// The gate is NOT ENTITLED TO DECIDE this program at all: it is outside
    /// the covered frontier, or the native gate could not complete.
    OutsideFrontier { reason: String },
}

impl Verdict {
    /// True for a definitive refusal. This is the arm worth acting on: it
    /// agrees with the reference compiler on the covered corpus.
    ///
    /// There is deliberately no `is_admitted()` — see the crate docs.
    pub fn is_refused(&self) -> bool {
        matches!(self, Verdict::Refused { .. })
    }

    /// True when the gate declined to decide (a frontier gap).
    pub fn is_undecided(&self) -> bool {
        matches!(self, Verdict::OutsideFrontier { .. })
    }

    /// The arm's stable wire name: `"refused"`, `"no_objection"`, or
    /// `"outside_frontier"`.
    pub fn kind(&self) -> &'static str {
        match self {
            Verdict::Refused { .. } => "refused",
            Verdict::NoObjection => "no_objection",
            Verdict::OutsideFrontier { .. } => "outside_frontier",
        }
    }

    /// The guarantee tag for a refusal; `Some(FRONTIER_CODE)` for a frontier
    /// gap; `None` for a no-objection.
    pub fn code(&self) -> Option<&str> {
        match self {
            Verdict::Refused { code, .. } => Some(code),
            Verdict::NoObjection => None,
            Verdict::OutsideFrontier { .. } => Some(FRONTIER_CODE),
        }
    }

    /// The why-trace (or the frontier reason). Verbatim, never rewritten.
    pub fn message(&self) -> Option<&str> {
        match self {
            Verdict::Refused { message, .. } => Some(message),
            Verdict::NoObjection => None,
            Verdict::OutsideFrontier { reason } => Some(reason),
        }
    }

    /// The design's fixed `{"admitted", "code", "message"}` shape, plus the
    /// `"verdict"` arm name.
    ///
    /// `"admitted"` is `false` for EVERY arm, because this gate issues no
    /// admissions. A consumer written against the fixed three-field shape
    /// therefore reads this gate as "never admits" — the fail-closed reading —
    /// instead of mistaking a no-objection for an admission. The real signal is
    /// `"verdict"`.
    pub fn to_json(&self) -> String {
        let mut out = String::from("{\"verdict\":");
        out.push_str(&json_string(self.kind()));
        out.push_str(",\"admitted\":false,\"code\":");
        match self.code() {
            Some(code) => out.push_str(&json_string(code)),
            None => out.push_str("null"),
        }
        out.push_str(",\"message\":");
        match self.message() {
            Some(message) => out.push_str(&json_string(message)),
            None => out.push_str("null"),
        }
        out.push('}');
        out
    }
}

/// The target tiers `compile_to` names. Both refuse today (Stage 4).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Tier {
    Py,
    Rust,
}

/// The native gate's verdict for `source`.
///
/// Pure and disk-pure. Returns [`Verdict::Refused`] only where the self-host
/// gate refuses — a verdict that byte-agrees with the reference compiler on the
/// covered corpus. Everything else is [`Verdict::NoObjection`] (not an
/// admission) or [`Verdict::OutsideFrontier`] (declined). No input produces an
/// admission, by construction.
pub fn admit(source: &str) -> Verdict {
    if let Some(reason) = frontier::scan(source) {
        return Verdict::OutsideFrontier { reason };
    }
    let owned = source.to_string();
    // The emitted stages are total over the surface they were written for, and
    // "written for" is exactly the thing this crate refuses to assume. An abort
    // inside the native gate must become a refusal to decide, not a verdict.
    let wire = match std::panic::catch_unwind(move || selfhost::admit_src(owned)) {
        Ok(wire) => wire,
        Err(_) => {
            return Verdict::OutsideFrontier {
                reason: String::from(
                    "the native gate aborted while deciding this source, so no verdict was reached; this is a frontier gap — ask the reference `revl` toolchain",
                ),
            }
        }
    };
    verdict_from_wire(&wire)
}

/// The native gate's verdict for `source` once it is admitted INTO the running
/// composition `manifest` (item 186's ambient gate; issue #346).
///
/// `manifest` is the row wire (`docs/design/186-ambient-admission-guarantees.md`):
/// `C/k/r` for a provision (`r` is the realm, `""` for shared), `C<k` for a
/// requirement, `!halted` for a halted composition, joined by `;`. The empty
/// string is the empty composition, so `admit_into(source, "")` is
/// `admit(source)` byte for byte — this arm generalises [`admit`] rather than
/// re-implementing it.
///
/// The decision is the native fold `selfhost/lower.rvl::admit_ambient`,
/// compiled to rust like [`admit`]: the incoming text is decided as the
/// standalone gate decides it, and then the LINK is recomputed over the UNION
/// of the manifest and the incoming text. That union is where a key the running
/// composition already holds surfaces (G2 provision conflict), where a route
/// into a realm the union does not provide dangles (G2), and where a dependency
/// cycle spanning the manifest boundary is a cycle (G3). Refusals come out
/// ordered exactly as the single-source composition of `manifest ++ source`
/// orders them.
///
/// What this arm does NOT decide, stated here rather than discovered later:
///
/// * the reference TYPE layer — a type-incorrect candidate is
///   [`Verdict::NoObjection`] here, exactly as it is in [`admit`];
/// * the row kinds the wire reserves for the deferred waves — a replacement row
///   (`-C`) or a handoff row (`C=k:T`) is REFUSED with the fold's own `MANIFEST`
///   code, never skipped. Skipping a row this gate cannot honour is the
///   wave-through this crate exists to prevent;
/// * it does not RESOLVE the requirements a candidate declares; it checks them
///   for disjointness and acyclicity. A `requires` the union does not provide is
///   a no-objection, and the reference is the only tier that decides it.
///
/// As with [`admit`], no input produces an admission: the arm is
/// `Refused` / `NoObjection` / `OutsideFrontier` like the rest of the surface.
pub fn admit_into(source: &str, manifest: &str) -> Verdict {
    if let Some(reason) = frontier::scan(source) {
        return Verdict::OutsideFrontier { reason };
    }
    // The fold parses the manifest with the same deeply-recursive front end, so
    // the bound that guards the source guards the wire too — and a manifest over
    // it is declined rather than risked.
    if manifest.len() > MAX_SOURCE_BYTES {
        return Verdict::OutsideFrontier {
            reason: format!(
                "manifest is {} bytes, above the {}-byte bound this gate will decide (the native front end is deeply recursive and an overflow aborts rather than refusing); ask the reference `revl` toolchain",
                manifest.len(),
                MAX_SOURCE_BYTES
            ),
        };
    }
    let owned = source.to_string();
    let rows = manifest.to_string();
    // Same contract as `admit`: the emitted stages are total over the surface
    // they were written for, and "written for" is the thing this crate refuses
    // to assume. An abort must become a refusal to decide, not a verdict.
    let wire = match std::panic::catch_unwind(move || selfhost::admit_ambient(owned, rows)) {
        Ok(wire) => wire,
        Err(_) => {
            return Verdict::OutsideFrontier {
                reason: String::from(
                    "the native fold aborted while admitting this source into the running manifest, so no verdict was reached; this is a frontier gap — ask the reference `revl` toolchain",
                ),
            }
        }
    };
    verdict_from_wire(&wire)
}

/// Parse the self-host gate's internal `"<TAG>|<message>"` protocol into the
/// structured verdict, message verbatim, splitting at the FIRST `|` only so a
/// message carrying `|` survives intact.
///
/// `""` is a no-objection. Anything non-empty with no `|` is a shape this crate
/// does not recognise, and an unrecognised shape is a frontier gap.
fn verdict_from_wire(wire: &str) -> Verdict {
    if wire.is_empty() {
        return Verdict::NoObjection;
    }
    match wire.find('|') {
        Some(bar) => Verdict::Refused {
            code: wire[..bar].to_string(),
            message: wire[bar + 1..].to_string(),
        },
        None => Verdict::OutsideFrontier {
            reason: format!(
                "the native gate returned an unrecognised verdict shape ({:?}); treating it as undecided",
                wire
            ),
        },
    }
}

/// Verdict plus emitted target source — **Stage 4, not available**.
///
/// Always `Err(Verdict::OutsideFrontier)` today: the self-host emitters
/// (`selfhost/emit_py.rvl`, `selfhost/emit_rust.rvl`) still carry `@py`-only
/// helper externs (`string_lit`, `num_str`, `py_repr`, `mangle`) and do not emit
/// to rust at all, so no native emitter exists to call. The signature is fixed
/// here so its arrival is additive.
pub fn compile_to(_source: &str, tier: Tier) -> Result<String, Verdict> {
    let tier_name = match tier {
        Tier::Py => "py",
        Tier::Rust => "rust",
    };
    Err(Verdict::OutsideFrontier {
        reason: format!(
            "compile_to({}) is not available in this crate: the self-host emitters still depend on @py-only helper externs, so there is no native emitter to run (roadmap item 332 Stage 4). Emit with the reference `revl compile --backend {}`.",
            tier_name, tier_name
        ),
    })
}

/// The gate's version surface. Compare `frontier` before trusting agreement
/// between two gates, and read `layer` before trusting a non-refusal.
pub fn gate_version() -> GateVersion {
    GateVersion {
        api: GATE_API_VERSION,
        language: LANGUAGE_VERSION,
        frontier: FRONTIER_ID,
        layer: COVERED_LAYER,
    }
}

/// Minimal JSON string encoder — the boundary carries strings only, so this is
/// the whole serialisation need and the shim takes no serde dependency for it.
fn json_string(value: &str) -> String {
    let mut out = String::with_capacity(value.len() + 2);
    out.push('"');
    for ch in value.chars() {
        match ch {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 => out.push_str(&format!("\\u{:04x}", c as u32)),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

#[cfg(test)]
mod wire_tests {
    use super::*;

    #[test]
    fn an_empty_wire_is_a_no_objection_and_not_an_admission() {
        assert_eq!(verdict_from_wire(""), Verdict::NoObjection);
        assert!(!verdict_from_wire("").is_refused());
        // the fixed three-field shape reads false for every arm
        assert!(verdict_from_wire("").to_json().contains("\"admitted\":false"));
    }

    #[test]
    fn an_unrecognised_shape_is_undecided() {
        assert!(verdict_from_wire("something-unexpected").is_undecided());
    }

    #[test]
    fn a_message_carrying_a_bar_survives_intact() {
        match verdict_from_wire("G3|a -> b | c") {
            Verdict::Refused { code, message } => {
                assert_eq!(code, "G3");
                assert_eq!(message, "a -> b | c");
            }
            other => panic!("expected a refusal, got {:?}", other),
        }
    }

    #[test]
    fn every_arm_serialises_as_not_admitted() {
        let arms = [
            Verdict::NoObjection,
            Verdict::Refused { code: String::from("G4"), message: String::from("m") },
            Verdict::OutsideFrontier { reason: String::from("r") },
        ];
        for arm in arms {
            assert!(
                arm.to_json().contains("\"admitted\":false"),
                "{} must serialise as not admitted: {}",
                arm.kind(),
                arm.to_json()
            );
        }
    }

    #[test]
    fn json_escapes_a_quote_and_a_newline() {
        assert_eq!(json_string("a\"b\nc"), "\"a\\\"b\\nc\"");
    }

    // The manifest arm (issue #346).

    /// The running composition the ambient tests admit into: `Kv` provides
    /// `store`, `App` provides `app` and requires `store`.
    const RUNNING: &str = "Kv/store/;App/app/;App<store";

    /// A component that re-provides `store`, the key `Kv` already holds.
    const AMBIENT_CONFLICT: &str = "service Cache { fn lookup(key: Str) -> Str }\n\
component CacheLayer requires store: Store provides store: Store {\n\
  provide store {\n\
    fn get(key) = key\n\
    fn bump(n) = n\n\
    fn put(key, value) = value\n\
  }\n\
}\n";

    #[test]
    fn an_empty_manifest_is_the_standalone_gate() {
        for source in [
            "fn id(x: Int) -> Int { return x }",
            AMBIENT_CONFLICT,
            "component X provides { fn = }",
        ] {
            assert_eq!(
                admit_into(source, ""),
                admit(source),
                "an empty manifest must be the empty composition, decided exactly as the standalone gate decides it"
            );
        }
    }

    #[test]
    fn the_manifest_arm_refuses_an_ambient_provision_conflict() {
        match admit_into(AMBIENT_CONFLICT, RUNNING) {
            Verdict::Refused { code, message } => {
                assert_eq!(code, "G2");
                assert!(message.contains("provision conflict"), "{}", message);
                assert!(message.contains("Kv") && message.contains("CacheLayer"), "{}", message);
            }
            other => panic!("expected an ambient G2 refusal, got {:?}", other),
        }
    }

    #[test]
    fn the_manifest_arm_reads_the_manifest_rather_than_ignoring_it() {
        // The same bytes ask a DIFFERENT question without the running
        // composition: standalone, the candidate requires a key it provides
        // itself (G3). A stub that ignored its manifest argument could not
        // produce two different codes here.
        match admit(AMBIENT_CONFLICT) {
            Verdict::Refused { code, .. } => assert_eq!(code, "G3"),
            other => panic!("expected a standalone G3 refusal, got {:?}", other),
        }
        match admit_into(AMBIENT_CONFLICT, "Kv/store/") {
            Verdict::Refused { code, .. } => assert_eq!(code, "G2"),
            other => panic!("expected an ambient G2 refusal, got {:?}", other),
        }
    }

    #[test]
    fn a_halted_composition_refuses_every_admission() {
        match admit_into("fn id(x: Int) -> Int { return x }", "Kv/store/;!halted") {
            Verdict::Refused { code, .. } => assert_eq!(code, "HALTED"),
            other => panic!("a halted composition must refuse, got {:?}", other),
        }
    }

    #[test]
    fn a_deferred_manifest_row_is_refused_not_skipped() {
        // Replacement (item 186) belongs to a wave this crate has not landed, and
        // a row it cannot honour is REFUSED rather than dropped: skipping a row
        // is the wave-through this crate exists to prevent.
        for rows in [
            "Kv/store/;-Kv/store/",
            "Kv/store/;Kv/store=Int",
            "!paused",
        ] {
            match admit_into("fn id(x: Int) -> Int { return x }", rows) {
                Verdict::Refused { code, .. } => assert_eq!(code, "MANIFEST"),
                other => panic!("expected a MANIFEST refusal for {:?}, got {:?}", rows, other),
            }
        }
    }

    #[test]
    fn the_manifest_arm_never_admits() {
        let arms = [
            admit_into("fn id(x: Int) -> Int { return x }", RUNNING),
            admit_into(AMBIENT_CONFLICT, RUNNING),
            admit_into(AMBIENT_CONFLICT, "!halted"),
            admit_into("fn id(x: Int) -> Int { return x }", ""),
        ];
        for arm in arms {
            assert!(
                arm.to_json().contains("\"admitted\":false"),
                "{} must serialise as not admitted: {}",
                arm.kind(),
                arm.to_json()
            );
        }
    }

    #[test]
    fn an_unrecognised_manifest_row_is_refused_rather_than_skipped() {
        // A row shape the wire does not define: refused as MANIFEST (a real
        // refusal), never skipped over.
        match admit_into("fn id(x: Int) -> Int { return x }", "!wat") {
            Verdict::Refused { code, .. } => assert_eq!(code, "MANIFEST"),
            other => panic!("expected a MANIFEST refusal, got {:?}", other),
        }
    }
}
