// item 369 — the H1 flagship proof on the TS tier: the witnessed `stdlib/fs.rvl`
// catalog, driven end to end through a real cordis composition, PERSISTS its
// mutations on a clean commit and REVERTS them residue-free on abort — on ts
// exactly as on py (the peer of tests/test_fs_stdlib.py's
// `test_h1_persists_on_clean_commit` / `test_h1_reverts_residue_free_on_abort`).
//
// The fixture (tests/fixtures/ts_witnessed_fs.ir.json, generated by
// _gen_ts_witnessed_fs.py) carries the REAL fs externs (compiled from
// stdlib/fs.rvl) and two activations running the same witnessed sequence —
// write (overwrite), write (create), rm, mkdir, move — the exact ops the shell
// classifier lowers `cp`/`touch`/`rm`/`mkdir`/`mv` onto (item 252), so this also
// proves those lowered ops execute AND revert on ts. `FsCommit` unloads cleanly
// (persist-on-commit); `FsAbort` fails after every op registers (revert-on-abort,
// residue-free).
import { beforeEach, describe, expect, it } from 'vitest'
import { Context, FiberState } from 'cordis'
import * as fs from 'node:fs'
import * as path from 'node:path'
import * as os from 'node:os'
import { createHash } from 'node:crypto'
import { fileURLToPath } from 'node:url'
// item 410 stage 5: the fs externs are now `= @ts ref` imports of the per-extern
// entry points in `../revl_fs_ts.ts`, resolved lazily at each op's first call.
// The stdlib-origin thunk joins the recorded relative path against the runner-
// provided `globalThis.__REVL_STDLIB_REF_ROOT__` (the install tree) — set here to
// the repo root, exactly as the node placement runner self-derives it. No
// pre-import and no `globalThis.__revlFs` seam: this is the retirement itself.
// This runs during module evaluation, before any `it` invokes the first fs op.
const _installRoot = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)), '..', '..', '..')
;(globalThis as { __REVL_STDLIB_REF_ROOT__?: string }).__REVL_STDLIB_REF_ROOT__ =
  _installRoot
import { FsCommit, FsAbort, FsAbortSamePath } from './generated/ts_witnessed_fs.ts'

let ws: string

const GARBAGE = '.revl-fs-garbage'
const PREIMAGE = '.revl-fs-preimage'

function abs(rel: string): string {
  return path.join(ws, rel)
}
function read(rel: string): string {
  return fs.readFileSync(abs(rel), 'utf-8')
}
function present(rel: string): boolean {
  try {
    fs.statSync(abs(rel))
    return true
  } catch {
    return false
  }
}
function isDir(rel: string): boolean {
  try {
    return fs.statSync(abs(rel)).isDirectory()
  } catch {
    return false
  }
}

/** A content hash of the workspace EXCLUDING the reversal machinery dirs — the
 * "before" state has no such dirs, the post-abort state has them but empty, so
 * excluding them lets the two states compare identical iff the real content is
 * byte-for-byte restored. (The dirs' emptiness is asserted separately.) */
function hashTree(root: string): string {
  const entries: string[] = []
  const walk = (dir: string): void => {
    for (const name of fs.readdirSync(dir).sort()) {
      if (name === GARBAGE || name === PREIMAGE) continue
      const full = path.join(dir, name)
      const rel = path.relative(root, full)
      const st = fs.statSync(full)
      if (st.isDirectory()) {
        entries.push('D ' + rel)
        walk(full)
      } else {
        entries.push('F ' + rel + '\0' + fs.readFileSync(full, 'utf-8'))
      }
    }
  }
  walk(root)
  return createHash('sha256').update(entries.sort().join('\n')).digest('hex')
}

/** Every reversal sidecar consumed: the garbage + preimage dirs are empty (or
 * were never created) — residue-free reversal (item 243). */
function expectMachineryEmpty(): void {
  for (const d of [GARBAGE, PREIMAGE]) {
    if (present(d)) expect(fs.readdirSync(abs(d))).toEqual([])
  }
}

beforeEach(() => {
  ws = fs.mkdtempSync(path.join(os.tmpdir(), 'revl-fs-ts-'))
  process.env.REVL_FS_WORKSPACE = ws
  fs.writeFileSync(abs('artifact.txt'), 'v1')
  fs.writeFileSync(abs('stale.txt'), 'junk')
  fs.writeFileSync(abs('movable.txt'), 'mv-me')
})

describe('item 369 — witnessed fs on ts: persist on commit', () => {
  it('applies every mutation, and a clean unload discharges them (does NOT revert)', async () => {
    const ctx = new Context()
    const fiber = ctx.plugin(FsCommit)
    await fiber.await()

    // the activation applied all five mutations
    expect(read('artifact.txt')).toBe('v2') // overwrite
    expect(read('fresh.txt')).toBe('new') // create
    expect(present('stale.txt')).toBe(false) // rm (parked)
    expect(isDir('newdir')).toBe(true) // mkdir
    expect(present('movable.txt')).toBe(false) // move source gone
    expect(read('moved.txt')).toBe('mv-me') // move dest

    await fiber.dispose() // clean unload == implicit commit

    // the mutations ARE the deliverable: they persist, inverses discharged.
    expect(read('artifact.txt')).toBe('v2')
    expect(read('fresh.txt')).toBe('new')
    expect(present('stale.txt')).toBe(false)
    expect(isDir('newdir')).toBe(true)
    expect(read('moved.txt')).toBe('mv-me')
    // NB: commit DISCHARGES the inverses (never runs them), so the preimage
    // snapshot + parked-rm sidecars legitimately remain on disk inside the root
    // — exactly as on py (tests/test_fs_stdlib.py's commit proof asserts no
    // machinery-emptiness; that is an abort-only, residue-free property).
  })
})

describe('item 369 — witnessed fs on ts: revert residue-free on abort (H1 flagship)', () => {
  it('reverts every mutation, lands the fiber FAILED, and the workspace hash is IDENTICAL to before', async () => {
    const before = hashTree(ws)

    const ctx = new Context()
    const fiber = ctx.plugin(FsAbort)
    await fiber.await().catch(() => undefined)
    expect(fiber.state).toBe(FiberState.FAILED)

    // every witnessed inverse replayed: the world is back to its preimage.
    expect(read('artifact.txt')).toBe('v1') // restore preimage
    expect(present('fresh.txt')).toBe(false) // created file deleted
    expect(read('stale.txt')).toBe('junk') // un-parked
    expect(present('newdir')).toBe(false) // rmdir_if_empty
    expect(read('movable.txt')).toBe('mv-me') // unmove
    expect(present('moved.txt')).toBe(false)

    // residue-free: every snapshot + parked file the mutations created is gone,
    // and the whole-workspace content hash matches the pristine state exactly.
    expectMachineryEmpty()
    expect(hashTree(ws)).toBe(before)
  })
})

describe('item 369 — witnessed fs on ts: multi-op-same-path abort replays LIFO', () => {
  // The ordering hazard the py-side item-369 bug gets wrong: inverses MUST
  // replay in strict LIFO (reverse-registration) order, not registration order,
  // or an abort over repeated writes to one path restores the WRONG preimage
  // (data corruption) or leaves a created file behind. The ts tier replays the
  // transactional inverses through cordis' disposer chain, which is LIFO by
  // construction — this proves it end to end.
  it('restores the ORIGINAL content of an overwritten path, and deletes a created-then-overwritten one', async () => {
    fs.writeFileSync(abs('A.txt'), 'orig') // A pre-exists; B does not
    const before = hashTree(ws)

    const ctx = new Context()
    const fiber = ctx.plugin(FsAbortSamePath)
    await fiber.await().catch(() => undefined)
    expect(fiber.state).toBe(FiberState.FAILED)

    // A.txt: orig -> v1 -> v2, abort. LIFO restores v2->v1->orig. Registration
    // order would leave "v1" — the item-369 data-corruption failure.
    expect(read('A.txt')).toBe('orig')
    // B.txt: absent -> b1(create) -> b2(overwrite), abort. LIFO restores the
    // overwrite (b2->b1) THEN deletes the created file -> absent. Registration
    // order would delete first, then a stale restore would resurrect "b1".
    expect(present('B.txt')).toBe(false)

    expectMachineryEmpty()
    expect(hashTree(ws)).toBe(before)
  })
})
