// item 243 Slice 2b — the witnessed-effects three-entry-kind teardown loop,
// driven end to end through a real cordis composition (docs/design/
// teardown-contract.md, docs/design/243-witnessed-externs.md).
//
// The fixture (tests/fixtures/witnessed_teardown.ir.json, generated by
// _gen_witnessed_teardown.py) is one activation registering all three entry
// kinds, in this order:
//
//   1. bracket        — a host `Map` ("store"), undo = store.drop()
//   2. transactional  — the witnessed `wit_stash`/`wit_unstash` pair,
//                       distinct from the bracket: it must NOT revert on a
//                       clean unload (persist-on-commit) and MUST revert on
//                       abort (revert-on-abort) — the one thing 243 exists
//                       to get right.
//   3. compensation   — `ledger_insert("row")` / compensate
//                       `ledger_remove("row")`, best-effort, abort-only,
//                       Phase 2. Deliberately over a resource SEPARATE from
//                       `store` — Phase 2 runs after `store`'s own bracket
//                       inverse has already torn it down.
//
// `WorkflowCommit` unloads cleanly (proves persist-on-commit + discharge);
// `WorkflowAbort` fails mid-body after all three register (proves the
// two-phase abort: Phase 1 — bracket + transactional LIFO to completion —
// strictly before Phase 2 — the compensation).
import { beforeEach, describe, expect, it } from 'vitest'
import { Context, FiberState } from 'cordis'
import { WorkflowAbort, WorkflowCommit } from './generated/witnessed_teardown.ts'
import { hostLog, resetHost } from '../runtime.ts'

function box(): { value: string } {
  return (globalThis as any).__revlWitnessBox
}

function ledger(): string[] {
  return (globalThis as any).__revlLedger
}

beforeEach(() => {
  resetHost()
  ;(globalThis as any).__revlWitnessBox = { value: 'ORIGINAL' }
  ;(globalThis as any).__revlLedger = []
})

describe('witnessed teardown — persist on commit', () => {
  it('the witnessed mutation runs, and a clean unload discharges it (does NOT revert)', async () => {
    const ctx = new Context()
    const fiber = ctx.plugin(WorkflowCommit)
    await fiber.await()

    // forward mutation ran during activation
    expect(box().value).toBe('STASHED')
    expect(hostLog).toContain('wit_stash was=ORIGINAL')
    expect(ledger()).toEqual(['row'])

    await fiber.dispose() // clean, successful unload == implicit commit

    // the transactional inverse did NOT replay — the mutation persists. This
    // is exactly what a bracket must NOT do (the acquire contrast below).
    expect(box().value).toBe('STASHED')
    expect(hostLog.some((e) => e.startsWith('wit_unstash'))).toBe(false)

    // compensation discharged too: never ran, because the forward emission
    // was already the deliverable.
    expect(ledger()).toEqual(['row'])
    expect(hostLog.some((e) => e.startsWith('ledger.remove'))).toBe(false)
  })

  it('the bracket is UNCHANGED: it still reverts on the very same clean unload', async () => {
    const ctx = new Context()
    const fiber = ctx.plugin(WorkflowCommit)
    await fiber.await()
    expect(hostLog.some((e) => e.endsWith('.new'))).toBe(true) // Map acquired

    await fiber.dispose()

    // the bracket inverse replays on a clean unload — the store IS dropped —
    // proving the transactional entry above is observably distinct at
    // runtime, not just distinct by declaration.
    expect(hostLog.some((e) => e.endsWith('.drop'))).toBe(true)
  })
})

describe('witnessed teardown — two-phase abort', () => {
  it('reverts the witnessed mutation and lands the fiber FAILED', async () => {
    const ctx = new Context()
    const fiber = ctx.plugin(WorkflowAbort)
    await fiber.await().catch(() => undefined)

    expect(fiber.state).toBe(FiberState.FAILED)
    // the transactional inverse replayed: the box is back to its pre-stash
    // value, residue-free.
    expect(box().value).toBe('ORIGINAL')
    expect(hostLog).toContain('wit_unstash was=ORIGINAL')
  })

  it('Phase 1 (bracket + transactional) completes, LIFO, strictly before Phase 2 (compensation) starts', async () => {
    const ctx = new Context()
    const fiber = ctx.plugin(WorkflowAbort)
    await fiber.await().catch(() => undefined)

    const dropIndex = hostLog.findIndex((e) => e.endsWith('.drop'))
    const unstashIndex = hostLog.findIndex((e) => e === 'wit_unstash was=ORIGINAL')
    const removeIndex = hostLog.findIndex((e) => e === 'ledger.remove row')

    expect(dropIndex).toBeGreaterThanOrEqual(0)
    expect(unstashIndex).toBeGreaterThanOrEqual(0)
    expect(removeIndex).toBeGreaterThanOrEqual(0)

    // LIFO within Phase 1: transactional was registered AFTER the bracket,
    // so its undo (wit_unstash) runs first, then the bracket's (drop).
    expect(unstashIndex).toBeLessThan(dropIndex)
    // and the compensation (Phase 2) fires strictly after BOTH Phase-1
    // inverses — the exact inversion of the old single-phase a5 ordering,
    // where the compensation fired before the earlier bracket unlock.
    expect(dropIndex).toBeLessThan(removeIndex)
  })

  it('the compensation actually offsets the forward emission (best-effort cleanup ran)', async () => {
    const ctx = new Context()
    const fiber = ctx.plugin(WorkflowAbort)
    await fiber.await().catch(() => undefined)

    // the forward `ledger_insert` ran before the fail step, and Phase 2's
    // compensation reversed it — proving best-effort intent actually fired,
    // not merely that it was registered.
    expect(hostLog).toContain('ledger.insert row')
    expect(hostLog).toContain('ledger.remove row')
    expect(ledger()).toEqual([]) // offset: the row is gone
  })
})
