// Generated by revl backends/typescript/emit.py — do not edit.
// Target runtime: cordis v4 (https://github.com/cordiverse/cordis).
import type { Context } from 'cordis'
import { host } from '../runtime.ts'

export async function remote(msgs: string): Promise<string> {
  return msgs + " -> reply" 
}

export async function agent_loop(current: string, complete: ((a0: string) => Promise<string>)): Promise<string> {
    const resp = (await complete(current))
    return resp
}

export interface Model {
  /** emission — crosses the system boundary (DESIGN.md §3.5) */
  complete(msgs: string): Promise<string>
}

export interface Runner {
  /** emission — crosses the system boundary (DESIGN.md §3.5) */
  run(prompt: string): Promise<string>
}

declare module 'cordis' {
  interface Context {
    model: Model
    runner: Runner
  }
}

export const RealModel = {
  name: "RealModel",
  inject: [],
  provide: ["model"],
  apply(ctx: Context) {
    ctx.effect(function* () {
      yield ctx.provide("model", {
        async complete(msgs: string) {
          return (await remote(msgs))
        },
      } satisfies Model)
    }, "RealModel.body")
  },
}

export const Agent = {
  name: "Agent",
  inject: ["model"],
  provide: ["runner"],
  apply(ctx: Context) {
    ctx.effect(function* () {
      yield ctx.provide("runner", {
        async run(prompt: string) {
          return (await agent_loop(prompt, (async (msgs: any) => (ctx.model.complete(msgs)))))
        },
      } satisfies Runner)
    }, "Agent.body")
  },
}
