// Generated by revl backends/typescript/emit.py — do not edit.
// Target runtime: cordis v4 (https://github.com/cordiverse/cordis).
import type { Context } from 'cordis'
import { host } from '../runtime.ts'

function revlLen(x: string | ArrayLike<unknown>): bigint {
  return BigInt(typeof x === "string" ? Array.from(x).length : x.length)
}
function revlSlice(x: string, a: bigint, b: bigint): string
function revlSlice(x: Uint8Array, a: bigint, b: bigint): Uint8Array
function revlSlice<T>(x: T[], a: bigint, b: bigint): T[]
function revlSlice(x: unknown, a: bigint, b: bigint): string | Uint8Array | unknown[]
function revlSlice(x: unknown, a: bigint, b: bigint): string | Uint8Array | unknown[] {
  const i = Number(a), j = Number(b)
  return typeof x === "string"
    ? Array.from(x).slice(i, j).join("")
    : (x as string | Uint8Array | unknown[]).slice(i, j)
}
function revlCharAt(s: string, i: bigint): string {
  const c = Array.from(s)[Number(i)]
  return c === undefined ? "" : c
}
function revlCharCodeAt(s: string, i: bigint): bigint {
  const c = Array.from(s)[Number(i)]
  return BigInt(c === undefined ? NaN : (c.codePointAt(0) as number))
}
function revlIndexOf(x: string | unknown[], v: unknown): bigint {
  if (typeof x === "string") {
    const at = x.indexOf(v as string)
    return BigInt(at < 0 ? -1 : Array.from(x.slice(0, at)).length)
  }
  return BigInt(x.indexOf(v))
}

export interface ToolCall {
  name: string
  args: string[]
}

export function json_parse(s: string): any {
  return JSON.parse(s) 
}

export function json_stringify(v: any): string {
  return JSON.stringify(v) 
}

export function tool_name(s: string): string {
    const tc = json_parse(s)
    return tc.name
}

export function arg_count(s: string): bigint {
    const tc = json_parse(s)
    return revlLen(tc.args)
}

export function roundtrip(s: string): string {
    return json_stringify(json_parse(s))
}
