// Generated by revl backends/typescript/emit.py (--target temporal) — do not edit.
// Target: the Temporal TypeScript SDK. This is a CODE-GENERATION target: it
// emits the workflow/activity split, the derived write-ahead saga, and the
// two-phase drain revl proves at compile time. It does NOT provide durable
// execution; a Temporal cluster runs it (docs/design/253-temporal-target.md §5).
import { proxyActivities, ApplicationFailure, setHandler, defineQuery } from "@temporalio/workflow"
import type * as activities from './activities'

// item 253 §3: RETRY POLICIES ARE DERIVED, NEVER AUTHORED. Every
// activity below sits in the class the item-309/440 idempotency ledger
// put it in, and `at-most-once` is the fall-through: a crossing whose
// evidence does not PROVE re-delivery is safe keeps revl's own
// at-most-once semantics, because a Temporal retry fires on every
// transient failure and would turn an unproven claim into a
// double-apply. Raising one of these by hand defeats the derivation.
const AT_MOST_ONCE = { maximumAttempts: 1 }
// A crossing whose declaration carries `idempotent(key: <param>)`:
// dedup-safe BY CONSTRUCTION (item 309's `keyed` register, the
// forward half of item 440's REDISPATCH_FREE set), so a redelivery
// is the remote's dedup, not a second effect. BOUNDED on purpose —
// an unbounded forward retry never reaches the catch, so the
// compensation phase would never run and the saga could not abort.
const DEDUP_SAFE_RETRY = { initialInterval: "1 second", backoffCoefficient: 2, maximumInterval: "30 seconds", maximumAttempts: 5 }
const { flightsCancel, flightsReserve, paymentsCharge, paymentsRefund, recordResidue } = proxyActivities<typeof activities>({
  startToCloseTimeout: "1 minute",  // revl perCallMs — per-call, Temporal-honoured (HIGH 1)
  retry: AT_MOST_ONCE,
})
const { settle } = proxyActivities<typeof activities>({
  startToCloseTimeout: "1 minute",  // revl perCallMs — per-call, Temporal-honoured (HIGH 1)
  retry: DEDUP_SAFE_RETRY,
})

// revl budgetMs (runtime.ts:880): a SINGLE Phase-2 total budget, checked
// workflow-side BETWEEN compensations (HIGH 1). Never a per-activity timeout.
const COMPENSATION_BUDGET_MS = 5000

type SagaStep = { name: string; run: () => Promise<unknown>; args: () => unknown[] }
type Residue = Record<string, unknown>
type SagaReport = { outstanding: Residue[]; worldRemaining: number; proof: string }

// A compensation activity's error text is HOST TEXT this workflow did not
// write, and it crosses into ApplicationFailure.details, which PERSISTS IN
// TEMPORAL HISTORY for the namespace retention period, plus the residue
// record and the live residue query (item 421 F7). `Secret[Str]` erases to
// plain `string` in RevlActivities, so a compensation implementer gets no
// type-level warning before a confidential value ends up embedded in a
// thrown Error's message (e.g. `throw new Error('close failed for '+h)`).
// Mirror of backends/typescript/bridge.ts's seamFailure/REDACTED_ARG (item
// 421 F5): the values this compensation call was made with (SagaStep.args,
// evaluated lazily so a write-ahead referent is read at failure time, not
// frozen at its pre-acquire undefined) are scrubbed out of the error text
// before it is kept anywhere, so the exception TYPE and the sentence around
// it survive but the caller's own bytes do not.
const REDACTED_ARG = '<redacted:arg>'
const MIN_MATCHABLE_ARG = 3
function argNeedles(value: unknown, into: Set<string>): void {
  if (value === null || value === undefined || typeof value === 'boolean') return
  if (typeof value === 'string') {
    if (value.length >= MIN_MATCHABLE_ARG) into.add(value)
    return
  }
  if (typeof value === 'number' || typeof value === 'bigint') {
    const form = String(value)
    if (form.length >= MIN_MATCHABLE_ARG) into.add(form)
    return
  }
  if (Array.isArray(value)) {
    for (const item of value) argNeedles(item, into)
    return
  }
  if (typeof value === 'object') {
    for (const item of Object.values(value as Record<string, unknown>)) argNeedles(item, into)
  }
}
function redactResidueError(error: unknown, args: unknown[]): string {
  let text = String(error)
  const needles = new Set<string>()
  argNeedles(args ?? [], needles)
  for (const needle of [...needles].sort((a, b) => b.length - a.length)) {
    if (needle && text.includes(needle)) text = text.split(needle).join(REDACTED_ARG)
  }
  return text
}

// The residue envelope revl recover guarantees (outstanding/worldRemaining/proof), exposed for live inspection while an aborting BookTrip run drains (attack 7).
export const BookTripResidue = defineQuery<Residue[]>("BookTrip.residue")

export async function BookTrip(): Promise<void> {
  // The compensation stack IS the derived saga: pushed write-ahead,
  // drained LIFO in the G7 order recovery.py uses, not hand-authored.
  const saga: SagaStep[] = []
  const residue: Residue[] = []
  setHandler(BookTripResidue, () => residue)
  try {
    saga.push({ name: "flights.cancel", run: () => flightsCancel("ABC"), args: () => [] })  // write-ahead: registered before the forward await
    await flightsReserve("ABC")
    saga.push({ name: "payments.refund", run: () => paymentsRefund("visa", 100n), args: () => [] })  // write-ahead: registered before the forward await
    await paymentsCharge("visa", 100n)
    await settle("visa", 100n)
    // clean completion: the saga stack is discharged, never run.
  } catch (err) {
    // ABORT. Phase 2: pop LIFO, continue-and-record, honour the
    // WORKFLOW-SIDE budget between compensations. A byte-for-byte
    // port of runtime.ts::runPhase2 (HIGH 1).
    const deadline = Date.now() + COMPENSATION_BUDGET_MS  // frozen to workflow-task time; replay-safe
    for (const step of saga.reverse()) {
      if (Date.now() >= deadline) {
        residue.push({ kind: 'compensation-residue', name: step.name,
                       reason: 'deadline-expired', outcome: 'not-attempted' })
        continue  // record and skip; the budget stops the phase, not one call
      }
      // the per-call cutoff is each compensation activity's
      // startToCloseTimeout, NOT this budget (HIGH 1).
      try { await step.run() }
      catch (e) { residue.push({ kind: 'compensation-residue', name: step.name, error: redactResidueError(e, step.args()) }) }
    }
    // Residue sink (attack 7): a durable record, plus the same
    // envelope on the workflow-failure details, so a failed run
    // still carries the proof revl recover produces.
    const report = { outstanding: residue, worldRemaining: saga.length, proof: 'revl-saga-abort' }
    await recordResidue(report)
    throw ApplicationFailure.create({ message: 'saga aborted', type: 'SagaAbort', nonRetryable: true, details: [report] })
  }
}

// ---- activities.ts (implement the crossings; host IO lives here) ----
export interface RevlActivities {
  flightsCancel(key: string): Promise<string>
  flightsReserve(itinerary: string): Promise<string>
  paymentsCharge(card: string, total: bigint): Promise<string>
  paymentsRefund(card: string, total: bigint): Promise<string>
  recordResidue(report: SagaReport): Promise<void>
  settle(card: string, total: bigint): Promise<string>
}
