// Generated by revl backends/typescript/emit.py — do not edit.
// Target runtime: cordis v4 (https://github.com/cordiverse/cordis).
import type { Context } from 'cordis'
import { host } from '../runtime.ts'

export interface Database {
  query(sql: any): any
  /** emission — crosses the system boundary (DESIGN.md §3.5) */
  execute(sql: any): any
}

export interface Cache {
  get(key: any): any
  put(key: any, value: any): any
}

declare module 'cordis' {
  interface Context {
    db: Database
    cache: Cache
  }
}

export interface PgDatabaseConfig {
  url: string
  /** default: 10 */
  pool_size?: number
}
export const PgDatabase = {
  name: "PgDatabase",
  inject: [],
  provide: ["db"],
  apply(ctx: Context, rawConfig: PgDatabaseConfig) {
    const config = host.applyConfigDefaults("PgDatabase", rawConfig, { url: { required: true }, pool_size: { default: 10 } }) as Required<PgDatabaseConfig>
    ctx.effect(function* () {
      const pool = host.Pool.open(config.url, config.pool_size)
      yield () => pool.close()
      yield ctx.provide("db", {
        query(sql: any) {
          return pool.query(sql)
        },
        execute(sql: any) {
          return pool.execute(sql)
        },
      } satisfies Database)
    }, "PgDatabase.body")
  },
}

export const UserCache = {
  name: "UserCache",
  inject: ["db"],
  provide: ["cache"],
  apply(ctx: Context) {
    ctx.effect(function* () {
      const store = host.Map.new()
      yield () => store.drop()
      yield ctx.provide("cache", {
        get(key: any) {
          return store.get(key)
        },
        put(key: any, value: any) {
          ctx.effect(() => {
            store.insert(key, value)
            return () => store.remove(key)
          })
          ctx.db.execute(`INSERT INTO cache_log VALUES (${key})`)
        },
      } satisfies Cache)
    }, "UserCache.body")
  },
}
