// cordis-go placement runner: one process of a `revl run --placement`
// composition placed on the Go backend. Reads a spec JSON (argv[1]), consumes
// cross-process keys through emitter-generated proxies, loads its own cordis-go
// components, optionally serves its provided keys over a Unix socket, runs
// probes, and (unless a peer dies first) holds until SIGTERM/stdin-close, then
// tears down consumers-first.
//
// The proxies, the stub dispatch, the key->service table and the component
// loader are all GENERATED by backends/go/emit.py into the `emitted` package
// (per composition), so this runner carries no composition-specific knowledge:
// cordis-go services are static Go interfaces, so generality is codegen, not a
// runtime-generic proxy. This mirrors backends/rust/placement_runner/main.rs.
//
// Peer death is withdrawal (R2/R3, docs/interop-bridge.md): a monitor
// connection sees EOF when a provider dies; the runner disposes that key's
// proxy fiber, which withdraws the provision, and every dependent deactivates
// reactively — the same reactive path a local provider swap takes.
package main

import (
	stdctx "context"
	"encoding/json"
	"fmt"
	"io"
	"net"
	"os"
	"os/signal"
	"strings"
	"syscall"
	"time"

	stc "github.com/0xdenny218/stc-go"

	"revl.goplacement/bridge"
	"revl.goplacement/emitted"
)

type proxyInfo struct {
	Socket  string   `json:"socket"`
	Methods []string `json:"methods"`
	Service string   `json:"service"`
}

type serveInfo struct {
	Socket  string              `json:"socket"`
	Keys    []string            `json:"keys"`
	Methods map[string][]string `json:"methods"`
}

type probe struct {
	Key    string   `json:"key"`
	Method string   `json:"method"`
	Args   []string `json:"args"`
}

type spec struct {
	Name       string                     `json:"name"`
	Components []string                   `json:"components"`
	Config     map[string]json.RawMessage `json:"config"`
	Provides   []string                   `json:"provides"`
	Proxies    map[string]proxyInfo       `json:"proxies"`
	Probe      []probe                    `json:"probe"`
	Serve      *serveInfo                 `json:"serve"`
}

type labeledFiber struct {
	label string
	fiber *stc.Fiber
}

func main() {
	if len(os.Args) < 2 {
		fmt.Fprintln(os.Stderr, "usage: revl_placement_runner <spec.json>")
		os.Exit(2)
	}
	raw, err := os.ReadFile(os.Args[1])
	if err != nil {
		fmt.Fprintln(os.Stderr, "read spec:", err)
		os.Exit(1)
	}
	var s spec
	if err := json.Unmarshal(raw, &s); err != nil {
		fmt.Fprintln(os.Stderr, "parse spec:", err)
		os.Exit(1)
	}
	name := s.Name
	if name == "" {
		name = "proc"
	}
	log := func(channel, subject, detail string) {
		fmt.Printf("[%s] %-6s| %-16s| %s\n", name, channel, subject,
			strings.TrimRight(detail, " "))
	}

	root := stc.New()
	var fibers []labeledFiber
	var clients []*bridge.Client
	peer := make(chan string, 8)
	ready := stdctx.Background()

	// 1. proxies for keys provided by other processes (generated per service)
	for key, info := range s.Proxies {
		client, err := bridge.NewClient(info.Socket)
		if err != nil {
			log("proxy", key, "dial failed: "+err.Error())
			continue
		}
		clients = append(clients, client)
		comp, ok := emitted.RevlProxyComponent(key, info.Service, client)
		if !ok {
			log("proxy", key, "UNSUPPORTED service "+info.Service)
			continue
		}
		fiber := root.Load(comp)
		if err := fiber.Ready(ready); err != nil {
			log("proxy", key, "load error: "+err.Error())
		}
		fibers = append(fibers, labeledFiber{key + "-proxy", fiber})
		log("proxy", key, "-> "+info.Socket+" ["+info.Service+"]")
		k := key
		bridge.Monitor(info.Socket, func() { peer <- k })
	}

	// 2. this process's own components, in IR load order
	for _, cname := range s.Components {
		fiber, ok := emitted.RevlLoad(root, cname, s.Config)
		if !ok {
			log("load", cname, "UNKNOWN component")
			continue
		}
		if err := fiber.Ready(ready); err != nil {
			log("load", cname, "load error: "+err.Error())
		}
		fibers = append(fibers, labeledFiber{cname, fiber})
		log("load", cname, "state="+fiber.State().String())
	}

	// 3. serve the keys other processes need
	var listener net.Listener
	if s.Serve != nil && s.Serve.Socket != "" {
		os.Remove(s.Serve.Socket)
		ln, err := net.Listen("unix", s.Serve.Socket)
		if err != nil {
			log("serve", strings.Join(s.Serve.Keys, ", "), "listen error: "+err.Error())
		} else {
			listener = ln
			go bridge.Serve(ln, func(key, method string, args []json.RawMessage) (any, error) {
				return emitted.RevlInvoke(root, key, method, args)
			})
			log("serve", strings.Join(s.Serve.Keys, ", "), "-> "+s.Serve.Socket)
		}
	}

	// 4. probes: call provided services (may cross a seam), print results
	for _, pr := range s.Probe {
		args := make([]json.RawMessage, len(pr.Args))
		for i, a := range pr.Args {
			b, _ := json.Marshal(a)
			args[i] = b
		}
		label := pr.Key + "." + pr.Method + "(...)"
		value, err := emitted.RevlInvoke(root, pr.Key, pr.Method, args)
		if err != nil {
			log("probe", label, "ERROR "+err.Error())
			continue
		}
		encoded, _ := json.Marshal(value)
		log("probe", label, "=> "+string(encoded))
	}

	fmt.Printf("[%s] UP\n", name)

	// 5. hold until the conductor stops us (SIGTERM, or stdin EOF) OR a peer
	//    dies. A dead provider withdraws its proxy so consumers deactivate.
	stop := make(chan struct{}, 1)
	sig := make(chan os.Signal, 1)
	signal.Notify(sig, syscall.SIGTERM, syscall.SIGINT)
	go func() { <-sig; stop <- struct{}{} }()
	go func() { io.Copy(io.Discard, os.Stdin); stop <- struct{}{} }()

	select {
	case key := <-peer:
		log("peer", key, "provider died: withdrawing the proxy")
		for _, lf := range fibers {
			if lf.label == key+"-proxy" {
				lf.fiber.Dispose()
			}
		}
		// Observe dependents leave Active: the provision is withdrawn, so the
		// orchestrator deactivates every consumer of the lost key (R2/R3).
		deadline := time.Now().Add(3 * time.Second)
		for _, lf := range fibers {
			if strings.HasSuffix(lf.label, "-proxy") {
				continue
			}
			for time.Now().Before(deadline) && lf.fiber.State() == stc.StateActive {
				time.Sleep(20 * time.Millisecond)
			}
			log("withdraw", lf.label, "state="+lf.fiber.State().String())
		}
	case <-stop:
	}

	// 6. teardown, consumers first (reverse load order)
	for i := len(fibers) - 1; i >= 0; i-- {
		fibers[i].fiber.Dispose()
		log("swap", fibers[i].label, "dispose")
	}
	if listener != nil {
		listener.Close()
	}
	for _, c := range clients {
		c.Close()
	}
	fmt.Printf("[%s] DOWN\n", name)
}
