// cordis-go placement runner: one process of a `revl run --placement`
// composition placed on the Go backend. Reads a spec JSON (argv[1]), consumes
// cross-process keys through emitter-generated proxies, loads its own cordis-go
// components, optionally serves its provided keys over a Unix socket, runs
// probes, and (unless a peer dies first) holds until SIGTERM/stdin-close, then
// tears down consumers-first.
//
// The proxies, the stub dispatch, the key->service table and the component
// loader are all GENERATED by backends/go/emit.py into the `emitted` package
// (per composition), so this runner carries no composition-specific knowledge:
// cordis-go services are static Go interfaces, so generality is codegen, not a
// runtime-generic proxy. This mirrors backends/rust/placement_runner/main.rs.
//
// Peer death is withdrawal (R2/R3, docs/interop-bridge.md): a monitor
// connection sees EOF when a provider dies; the runner disposes that key's
// proxy fiber, which withdraws the provision, and every dependent deactivates
// reactively — the same reactive path a local provider swap takes.
package main

import (
	stdctx "context"
	"encoding/json"
	"fmt"
	"io"
	"net"
	"os"
	"os/signal"
	"strings"
	"syscall"
	"time"

	stc "github.com/0xdenny218/stc-go"

	"revl.goplacement/bridge"
	"revl.goplacement/emitted"
)

type proxyInfo struct {
	Socket  string   `json:"socket"`
	Methods []string `json:"methods"`
	Service string   `json:"service"`
}

type serveInfo struct {
	Socket  string              `json:"socket"`
	Keys    []string            `json:"keys"`
	Methods map[string][]string `json:"methods"`
}

type probe struct {
	Key    string   `json:"key"`
	Method string   `json:"method"`
	Args   []string `json:"args"`
}

type spec struct {
	Name       string                     `json:"name"`
	Components []string                   `json:"components"`
	Config     map[string]json.RawMessage `json:"config"`
	Provides   []string                   `json:"provides"`
	Proxies    map[string]proxyInfo       `json:"proxies"`
	Probe      []probe                    `json:"probe"`
	Serve      *serveInfo                 `json:"serve"`
	// Once (revl run --backend go --once) replaces the hold-until-stopped
	// loop with the boot -> LIFO teardown -> no-residue-proof -> exit
	// round-trip, the same driver contract the rust/java/wasm tiers run.
	Once bool `json:"once"`
}

type labeledFiber struct {
	label string
	fiber *stc.Fiber
}

func main() {
	if len(os.Args) < 2 {
		fmt.Fprintln(os.Stderr, "usage: revl_placement_runner <spec.json>")
		os.Exit(2)
	}
	raw, err := os.ReadFile(os.Args[1])
	if err != nil {
		fmt.Fprintln(os.Stderr, "read spec:", err)
		os.Exit(1)
	}
	var s spec
	if err := json.Unmarshal(raw, &s); err != nil {
		fmt.Fprintln(os.Stderr, "parse spec:", err)
		os.Exit(1)
	}
	name := s.Name
	if name == "" {
		name = "proc"
	}
	log := func(channel, subject, detail string) {
		fmt.Printf("[%s] %-6s| %-16s| %s\n", name, channel, subject,
			strings.TrimRight(detail, " "))
	}

	root := stc.New()
	var fibers []labeledFiber
	var clients []*bridge.Client
	peer := make(chan string, 8)
	ready := stdctx.Background()

	// 1. proxies for keys provided by other processes (generated per service)
	for key, info := range s.Proxies {
		client, err := bridge.NewClient(info.Socket)
		if err != nil {
			log("proxy", key, "dial failed: "+err.Error())
			continue
		}
		clients = append(clients, client)
		comp, ok := emitted.RevlProxyComponent(key, info.Service, client)
		if !ok {
			log("proxy", key, "UNSUPPORTED service "+info.Service)
			continue
		}
		fiber := root.Load(comp)
		if err := fiber.Ready(ready); err != nil {
			log("proxy", key, "load error: "+err.Error())
		}
		fibers = append(fibers, labeledFiber{key + "-proxy", fiber})
		log("proxy", key, "-> "+info.Socket+" ["+info.Service+"]")
		k := key
		bridge.Monitor(info.Socket, func() { peer <- k })
	}

	// 2. this process's own components, in IR load order
	for _, cname := range s.Components {
		fiber, ok := emitted.RevlLoad(root, cname, s.Config)
		if !ok {
			log("load", cname, "UNKNOWN component")
			continue
		}
		if err := fiber.Ready(ready); err != nil {
			log("load", cname, "load error: "+err.Error())
		}
		fibers = append(fibers, labeledFiber{cname, fiber})
		log("load", cname, "state="+fiber.State().String())
	}

	// 3. serve the keys other processes need
	var listener net.Listener
	if s.Serve != nil && s.Serve.Socket != "" {
		os.Remove(s.Serve.Socket)
		ln, err := net.Listen("unix", s.Serve.Socket)
		if err != nil {
			log("serve", strings.Join(s.Serve.Keys, ", "), "listen error: "+err.Error())
		} else {
			listener = ln
			go bridge.Serve(ln, func(key, method string, args []json.RawMessage) (any, error) {
				return emitted.RevlInvoke(root, key, method, args)
			})
			log("serve", strings.Join(s.Serve.Keys, ", "), "-> "+s.Serve.Socket)
		}
	}

	// 4. probes: call provided services (may cross a seam), print results
	for _, pr := range s.Probe {
		args := make([]json.RawMessage, len(pr.Args))
		for i, a := range pr.Args {
			b, _ := json.Marshal(a)
			args[i] = b
		}
		label := pr.Key + "." + pr.Method + "(...)"
		value, err := emitted.RevlInvoke(root, pr.Key, pr.Method, args)
		if err != nil {
			log("probe", label, "ERROR "+err.Error())
			continue
		}
		encoded, _ := json.Marshal(value)
		log("probe", label, "=> "+string(encoded))
	}

	// 5. THE STOP HANDLER GOES UP BEFORE THE `UP` LINE, and that ordering is
	//    the whole contract (the go half of the fix py got in #226; issue 290).
	//    `[name] UP` is what the conductor waits on: `run_placement`'s `--once`
	//    path blocks on every child's UP and then calls `stop_all` immediately,
	//    so the SIGTERM can land microseconds after the print. Printing first
	//    left a window in which go's DEFAULT SIGTERM disposition was still in
	//    force, and a signal arriving inside it killed this process outright —
	//    no LIFO unwind, no inverses replayed, no residue proof, no `DOWN` (G7
	//    and R4, both violated). The window belongs to the LAST process to boot
	//    — every earlier one is still being waited on — which is why it lands
	//    on the process most likely to still owe an inverse and a residue proof.
	//
	//    The restructure the reorder needed: `signal.Notify` cannot simply move
	//    up on its own, because the channels it feeds are consumed by the
	//    `select` below, which must stay AFTER the print (it blocks). So the
	//    whole rendezvous — `stop`, `sig`, and the two feeder goroutines — is
	//    hoisted here, and only the blocking `select` is left behind. Both
	//    channels are buffered (cap 1), so a signal arriving in the old window
	//    is now merely PARKED in `stop` and the `select` below returns from it
	//    at once: the unwind runs either way, and `UP` means what it says —
	//    loaded, serving, AND able to be stopped.
	//
	//    Installed in once mode too, where there is no `select` to reach it: a
	//    SIGTERM landing during the immediate once-mode teardown is absorbed
	//    rather than turned back into a kill of a half-finished unwind.
	stop := make(chan struct{}, 1)
	sig := make(chan os.Signal, 1)
	signal.Notify(sig, syscall.SIGTERM, syscall.SIGINT)
	go func() { <-sig; stop <- struct{}{} }()
	go func() { io.Copy(io.Discard, os.Stdin); stop <- struct{}{} }()

	fmt.Printf("[%s] UP\n", name)

	// 5b. once mode: the round-trip ends here — boot, then straight to LIFO
	//     teardown + the no-residue proof. Otherwise hold until the conductor
	//     stops us (SIGTERM, or stdin EOF) OR a peer dies. A dead provider
	//     withdraws its proxy so consumers deactivate.
	if !s.Once {
		select {
		case key := <-peer:
			log("peer", key, "provider died: withdrawing the proxy")
			for _, lf := range fibers {
				if lf.label == key+"-proxy" {
					lf.fiber.Dispose()
				}
			}
			// Observe dependents leave Active: the provision is withdrawn, so the
			// orchestrator deactivates every consumer of the lost key (R2/R3).
			deadline := time.Now().Add(3 * time.Second)
			for _, lf := range fibers {
				if strings.HasSuffix(lf.label, "-proxy") {
					continue
				}
				for time.Now().Before(deadline) && lf.fiber.State() == stc.StateActive {
					time.Sleep(20 * time.Millisecond)
				}
				log("withdraw", lf.label, "state="+lf.fiber.State().String())
			}
		case <-stop:
		}
	}

	// 6. teardown, consumers first (reverse load order). In once mode each
	//    dispose is awaited out of the fiber registry, so the residue proof
	//    below reads a settled runtime, not an in-flight one.
	goneCtx, cancel := stdctx.WithTimeout(stdctx.Background(), 5*time.Second)
	defer cancel()
	for i := len(fibers) - 1; i >= 0; i-- {
		fibers[i].fiber.Dispose()
		if s.Once {
			log("swap", fibers[i].label, "dispose -> inverses replay (LIFO)")
			_ = fibers[i].fiber.Gone(goneCtx)
		} else {
			log("swap", fibers[i].label, "dispose")
		}
	}
	if listener != nil {
		listener.Close()
	}
	for _, c := range clients {
		c.Close()
	}

	// 7. no-residue proof (once mode): after a full LIFO teardown the live
	//    runtime must hold nothing — no fiber left in the registry, and no
	//    provided key still resolving. The go mirror of the py driver's
	//    registry.size/reflect.store check and the rust runner's
	//    registry().len()/reflect().services() check; NO-RESIDUE is printed
	//    only when both hold.
	if s.Once {
		live := len(root.Fibers())
		log("residue", "plugins", fmt.Sprintf("%d live plugin(s)", live))
		still := 0
		for _, key := range s.Provides {
			if emitted.RevlStillProvided(root, key) {
				still++
				log("residue", key, "STILL LIVE")
			}
		}
		log("residue", "provisions", fmt.Sprintf("%d service(s) still provided", still))
		if live == 0 && still == 0 {
			fmt.Printf("[%s] NO-RESIDUE — the composition left nothing behind\n", name)
		} else {
			fmt.Printf("[%s] RESIDUE-LEFT — see the residue lines above\n", name)
		}
	}
	fmt.Printf("[%s] DOWN\n", name)
}
