// Generated by the revl cordis4j backend (ir_version 1) — do not edit.
// Target: cordis4j (github.com/1na-ko/cordis4j).
package revl;

import io.cordis4j.core.Context;
import io.cordis4j.core.Disposable;
import io.cordis4j.core.Disposables;
import io.cordis4j.core.Plugin;
import io.cordis4j.core.ServiceKey;

public final class Components {
    private Components() {}

    public interface Database {
        java.util.List<Object> query(String sql);
        long execute(String sql);
    }

    public interface Cache {
        java.util.Optional<String> get(String key);
        void put(String key, String value);
    }

    // host object runtime (Map) — minimal working Java implementation
    public static final class Map {
        private final java.util.HashMap<String, String> values = new java.util.HashMap<>();
        private Map() {}
        // revl `Map.new()` — renamed: `new` is a Java reserved word.
        public static Map create() {
            return new Map();
        }
        public void drop() {
            values.clear();
        }
        public void insert(String key, String value) {
            values.put(key, value);
        }
        public void remove(String key) {
            values.remove(key);
        }
        public java.util.Optional<String> get(String key) {
            return java.util.Optional.ofNullable(values.get(key));
        }
    }

    // host object runtime (Pool) — functional placeholder
    public static final class Pool {
        private final String url;
        private final long poolSize;
        private Pool(String url, long poolSize) {
            this.url = url;
            this.poolSize = poolSize;
        }
        public static Pool open(String url, long poolSize) {
            return new Pool(url, poolSize);
        }
        public void close() {
            // Placeholder: a real pool would close its connections here.
        }
        public java.util.List<Object> query(String sql) {
            return java.util.List.of();
        }
        public long execute(String sql) {
            return 0L;
        }
    }

    public static final class PgDatabaseDb implements Database {
        private final Pool pool;
        PgDatabaseDb(Pool pool) {
            this.pool = pool;
        }
        public java.util.List<Object> query(String sql) { return this.pool.query(sql); }
        public long execute(String sql) { return this.pool.execute(sql); }
    }

    public static final class PgDatabasePlugin implements Plugin {
        private final String url;
        private final long pool_size;
        public PgDatabasePlugin(String url, long pool_size) {
            this.url = url;
            this.pool_size = pool_size;
        }
        public PgDatabasePlugin() {
            this.url = null;
            this.pool_size = 10L;
        }
        @Override
        public Disposable apply(Context ctx) {
            Pool pool = Pool.open(url, pool_size);
            Disposable db_provision = ctx.provide(ServiceKey.of(Database.class), new PgDatabaseDb(pool));
            return Disposables.composite(
                Disposables.of(() -> pool.close()),
            db_provision
            );
        }
    }

    public static final class UserCacheCache implements Cache {
        private final Context ctx;
        private final Context.EffectScope fx;
        private final Database db;
        private final Map store;
        UserCacheCache(Context ctx, Context.EffectScope fx, Database db, Map store) {
            this.ctx = ctx;
            this.fx = fx;
            this.db = db;
            this.store = store;
        }
        public java.util.Optional<String> get(String key) {
            return this.store.get(key);
        }
        public void put(String key, String value) {
            this.store.insert(key, value);
            fx.track(Disposables.of(() -> this.store.remove(key)));
            this.db.execute(String.format("INSERT INTO cache_log VALUES (%s)", key));
        }
    }

    public static final class UserCachePlugin implements Plugin {
        public UserCachePlugin() {
        }
        @Override
        public Disposable apply(Context ctx) {
            Context.EffectScope fx = ctx.effect();
            Database db = ctx.get(Database.class);
            var store = Map.create();
            fx.track(Disposables.of(() -> store.drop()));
            fx.track(ctx.provide(ServiceKey.of(Cache.class), new UserCacheCache(ctx, fx, db, store)));
            return fx;
        }
    }

}
