// Generated by the revl cordis4j backend (ir_version 1) — do not edit.
// Target: cordis4j (github.com/1na-ko/cordis4j).
package revl;

import io.cordis4j.core.Context;
import io.cordis4j.core.Disposable;
import io.cordis4j.core.Disposables;
import io.cordis4j.core.Plugin;
import io.cordis4j.core.ServiceKey;

public final class Components {
    private Components() {}

    public interface Database {
        java.util.List<Object> query(String sql);
        long execute(String sql);
    }

    public interface Cache {
        java.util.Optional<String> get(String key);
        void put(String key, String value);
    }

    // host object runtime (Map) — minimal working Java implementation.
    // The value type is generic — each site's `Map.create()` pins `V`
    // (FR-4: `Map[Str, List[Msg]]` and friends, not just String).
    public static final class Map<V> {
        // item 397: a ConcurrentHashMap, not a bare HashMap. The tier's
        // placement runner serves each bridge connection on its own thread,
        // so the former unsynchronized HashMap was not memory-safe under
        // concurrent put; migrating the backing class makes insert/remove/get
        // thread-safe AND gives insert_if_absent an atomic putIfAbsent.
        private final java.util.concurrent.ConcurrentHashMap<String, V> values =
            new java.util.concurrent.ConcurrentHashMap<>();
        private Map() {}
        // revl `Map.new()` — renamed: `new` is a Java reserved word.
        public static <V> Map<V> create() {
            return new Map<>();
        }
        public void drop() {
            values.clear();
        }
        public void insert(String key, V value) {
            values.put(key, value);
        }
        // The atomic compare-and-set (item 397): ConcurrentHashMap.putIfAbsent
        // is a single atomic operation over the test AND the insert. It returns
        // the previous value (null when absent), so a null return means this
        // call inserted. Under N concurrent callers, exactly one sees null.
        // (ConcurrentHashMap forbids null values; revl host inserts never pass
        // null, and `get` already wraps absence in Optional.)
        public boolean insert_if_absent(String key, V value) {
            return values.putIfAbsent(key, value) == null;
        }
        public void remove(String key) {
            values.remove(key);
        }
        public java.util.Optional<V> get(String key) {
            return java.util.Optional.ofNullable(values.get(key));
        }
        // Iteration surface (docs/stdlib-2.0.md §Map): the checker promises
        // `size()`/`keys()` on a host `Map.new()` receiver, and emit lowers
        // both as method calls on this object. `size` is the entry count as a
        // long (revl Int); `keys` yields the keys in ascending canonical Str
        // (code-point) order — String.compareTo is UTF-16 code-unit order, so
        // the inline comparator walks code points to stay canonical past
        // U+FFFF. Read-only queries, no host trace.
        public long size() {
            return values.size();
        }
        public java.util.List<String> keys() {
            java.util.List<String> ks = new java.util.ArrayList<>(values.keySet());
            ks.sort((a, b) -> {
                int i = 0, j = 0;
                while (i < a.length() && j < b.length()) {
                    int ca = a.codePointAt(i), cb = b.codePointAt(j);
                    if (ca != cb) { return Integer.compare(ca, cb); }
                    i += Character.charCount(ca); j += Character.charCount(cb);
                }
                return Boolean.compare(i >= a.length(), j >= b.length());
            });
            return java.util.List.copyOf(ks);
        }
    }

    // host object runtime (Pool) — a bounded connection pool over a
    // deterministic in-memory database (no driver dependency).  Semantics
    // are shared across tiers: backends/python/runtime.py, section
    // `.. _pool-job-semantics:`.
    public static final class Pool {
        private final String url;
        private final long poolSize;
        private final java.util.ArrayList<Long> idle = new java.util.ArrayList<>();
        private final java.util.ArrayList<Long> checkedOut = new java.util.ArrayList<>();
        private boolean closed = false;
        private Pool(String url, long poolSize) {
            this.url = url;
            this.poolSize = poolSize;
            for (long i = 1L; i <= poolSize; i++) {
                idle.add(i);
            }
        }
        public static Pool open(String url, long poolSize) {
            if (poolSize < 1L) {
                throw new IllegalStateException(
                    "pool size must be an integer >= 1 (got " + poolSize + ")");
            }
            return new Pool(url, poolSize);
        }
        public String url() {
            return url;
        }
        public long capacity() {
            if (closed) {
                return 0L;
            }
            return poolSize;
        }
        public long inUse() {
            return checkedOut.size();
        }
        public long available() {
            return idle.size();
        }
        // Statements borrow silently; only an explicit acquire/release is a
        // traced operation on the tiers that trace.
        private long borrow(String op) {
            if (closed) {
                throw new IllegalStateException(
                    "pool." + op + " after close/drop — use-after-free");
            }
            if (idle.isEmpty()) {
                throw new IllegalStateException(
                    "pool." + op + " exhausted (size=" + poolSize
                        + ", in_use=" + checkedOut.size() + ")");
            }
            long conn = idle.remove(0);
            checkedOut.add(conn);
            return conn;
        }
        private void giveBack(long conn) {
            checkedOut.remove(Long.valueOf(conn));
            idle.add(conn);
            java.util.Collections.sort(idle);
        }
        public long acquire() {
            return borrow("acquire");
        }
        public void release(long conn) {
            if (closed) {
                throw new IllegalStateException(
                    "pool.release after close/drop — use-after-free");
            }
            if (!checkedOut.contains(Long.valueOf(conn))) {
                throw new IllegalStateException(
                    "pool.release conn=" + conn + " is not checked out");
            }
            giveBack(conn);
        }
        public void close() {
            if (closed) {
                throw new IllegalStateException(
                    "pool.close after close/drop — use-after-free");
            }
            checkedOut.clear();
            idle.clear();
            closed = true;
        }
        public java.util.List<Object> query(String sql) {
            long conn = borrow("query");
            giveBack(conn);
            return java.util.List.of();
        }
        public long execute(String sql) {
            long conn = borrow("execute");
            giveBack(conn);
            return 1L;
        }
    }

    public static final class PgDatabaseDb implements Database {
        private final Pool pool;
        PgDatabaseDb(Pool pool) {
            this.pool = pool;
        }
        public java.util.List<Object> query(String sql) { return this.pool.query(sql); }
        public long execute(String sql) { return this.pool.execute(sql); }
    }

    public static final class PgDatabasePlugin implements Plugin {
        private final String url;
        private final long pool_size;
        public PgDatabasePlugin(String url, long pool_size) {
            this.url = url;
            this.pool_size = pool_size;
        }
        public PgDatabasePlugin() {
            this.url = null;
            this.pool_size = 10L;
        }
        @Override
        public Disposable apply(Context ctx) {
            java.util.ArrayList<Disposable> undos = new java.util.ArrayList<>();
            try {
                Pool pool = Pool.open(url, pool_size);
                undos.add(Disposables.of(() -> pool.close()));
                undos.add(ctx.provide(ServiceKey.of(Database.class), new PgDatabaseDb(pool)));
                java.util.Collections.reverse(undos);
                return Disposables.composite(undos.toArray(new Disposable[0]));
            } catch (RuntimeException | Error failure) {
                for (int i = undos.size() - 1; i >= 0; i--) {
                    undos.get(i).dispose();
                }
                throw failure;
            }
        }
    }

    public static final class UserCacheCache implements Cache {
        private final Context ctx;
        private final Context.EffectScope fx;
        private final Database db;
        private final Map<String> store;
        UserCacheCache(Context ctx, Context.EffectScope fx, Database db, Map<String> store) {
            this.ctx = ctx;
            this.fx = fx;
            this.db = db;
            this.store = store;
        }
        public java.util.Optional<String> get(String key) {
            return this.store.get(key);
        }
        public void put(String key, String value) {
            this.store.insert(key, value);
            fx.track(Disposables.of(() -> this.store.remove(key)));
            this.db.execute(String.format("INSERT INTO cache_log VALUES (%s)", key));
        }
    }

    public static final class UserCachePlugin implements Plugin {
        public UserCachePlugin() {
        }
        @Override
        public Disposable apply(Context ctx) {
            Context.EffectScope fx = ctx.effect();
            Database db = ctx.get(Database.class);
            try {
                Map<String> store = Map.create();
                fx.track(Disposables.of(() -> store.drop()));
                fx.track(ctx.provide(ServiceKey.of(Cache.class), new UserCacheCache(ctx, fx, db, store)));
                return fx;
            } catch (RuntimeException | Error failure) {
                fx.dispose();
                throw failure;
            }
        }
    }

}
