// Code generated by backends/go/emit.py — DO NOT EDIT.
// revl -> cordis-go (ir_version 3, pure typed-core tier): ordinary Go.
package stdlib

import (
	"strconv"
	"strings"
	"unicode/utf8"
)

// ---- built-in Opt as a generic sealed interface -----------------------
type RevlOpt[T any] interface{ isRevlOpt() }
type RevlSome[T any] struct{ Value T }

func (RevlSome[T]) isRevlOpt() {}

type RevlNone[T any] struct{}

func (RevlNone[T]) isRevlOpt() {}

func revlOptMap[A any, B any](o RevlOpt[A], f func(A) B) RevlOpt[B] {
	if s, ok := o.(RevlSome[A]); ok {
		return RevlSome[B]{Value: f(s.Value)}
	}
	return RevlNone[B]{}
}

func revlOptOr[T any](o RevlOpt[T], d T) T {
	if s, ok := o.(RevlSome[T]); ok {
		return s.Value
	}
	return d
}

// ---- built-in Result as a generic sealed interface --------------------
type RevlResult[T any, E any] interface{ isRevlResult() }
type RevlOk[T any, E any] struct{ Value T }

func (RevlOk[T, E]) isRevlResult() {}

type RevlErr[T any, E any] struct{ Value E }

func (RevlErr[T, E]) isRevlResult() {}

// ---- stdlib builtins (docs/stdlib-2.0.md); positions are code-point based
func revlStrLen(s string) int64 { return int64(utf8.RuneCountInString(s)) }

func revlStrSlice(s string, a, b int64) string {
	r := []rune(s)
	n := int64(len(r))
	if a < 0 {
		a = 0
	}
	if a > n {
		a = n
	}
	if b > n {
		b = n
	}
	if b < a {
		b = a
	}
	return string(r[a:b])
}

func revlStrIndexOf(s, sub string) int64 {
	rs := []rune(s)
	rn := []rune(sub)
	if len(rn) == 0 {
		return 0
	}
	if len(rn) > len(rs) {
		return -1
	}
	for i := 0; i+len(rn) <= len(rs); i++ {
		ok := true
		for j := range rn {
			if rs[i+j] != rn[j] {
				ok = false
				break
			}
		}
		if ok {
			return int64(i)
		}
	}
	return -1
}

func revlStrConcat(a, b string) string { return a + b }

func revlStrSplit(s, sep string) []string {
	if sep == "" {
		r := []rune(s)
		out := make([]string, len(r))
		for i, c := range r {
			out[i] = string(c)
		}
		return out
	}
	return strings.Split(s, sep)
}

func revlStrRepeat(s string, n int64) string {
	if n < 0 {
		n = 0
	}
	return strings.Repeat(s, int(n))
}

// revlStrCharAt / revlStrCharCodeAt walk to the code point at index i with
// utf8.DecodeRuneInString instead of materializing `[]rune(s)`. Both are
// code-point indexed exactly as before (docs/strings.md); the difference is
// that one read no longer allocates a copy of the whole string, so a scan loop
// stops being quadratic in bytes (item 434 (c): a 780-code-point scan measured
// 781 allocs / 2,496,127 B, one whole-string rune copy per character, against
// 0 / 0 for the hand-written `for _, r := range s`). An out-of-range index
// falls through to the `[]rune(s)[i]` it always was, so it panics with the
// same Go index-out-of-range error on exactly the same inputs.
func revlStrCharAt(s string, i int64) string {
	if i >= 0 {
		t := s
		for j := int64(0); len(t) > 0; j++ {
			r, w := utf8.DecodeRuneInString(t)
			if j == i {
				if r == utf8.RuneError && w == 1 {
					// invalid encoding: []rune(s) substitutes U+FFFD, so
					// answer the replacement character, not the raw byte
					return string(utf8.RuneError)
				}
				return t[:w] // a substring shares s's bytes: no allocation
			}
			t = t[w:]
		}
	}
	return string([]rune(s)[i])
}

func revlStrCharCodeAt(s string, i int64) int64 {
	if i >= 0 {
		t := s
		for j := int64(0); len(t) > 0; j++ {
			r, w := utf8.DecodeRuneInString(t)
			if j == i {
				return int64(r)
			}
			t = t[w:]
		}
	}
	return int64([]rune(s)[i])
}

func revlJoin(xs []string, sep string) string { return strings.Join(xs, sep) }

func revlListLen[T any](xs []T) int64 { return int64(len(xs)) }

func revlListSlice[T any](xs []T, a, b int64) []T {
	n := int64(len(xs))
	if a < 0 {
		a = 0
	}
	if a > n {
		a = n
	}
	if b > n {
		b = n
	}
	if b < a {
		b = a
	}
	out := make([]T, b-a)
	copy(out, xs[a:b])
	return out
}

func revlListConcat[T any](a, b []T) []T {
	out := make([]T, 0, len(a)+len(b))
	out = append(out, a...)
	out = append(out, b...)
	return out
}

func revlListPush[T any](xs []T, x T) []T {
	out := make([]T, 0, len(xs)+1)
	out = append(out, xs...)
	out = append(out, x)
	return out
}

func revlListIndexOf[T comparable](xs []T, x T) int64 {
	for i, v := range xs {
		if v == x {
			return int64(i)
		}
	}
	return -1
}

type Row struct {
	Id   int64  `json:"id"`
	Name string `json:"name"`
}

func strLen(s string) int64 {
	return revlStrLen(s)
}

func pushed(xs []int64, x int64) []int64 {
	return revlListPush(xs, x)
}

func sliced(xs []int64) []int64 {
	return revlListSlice(xs, 1, 3)
}

func concatLists(a []int64, b []int64) []int64 {
	return revlListConcat(a, b)
}

func splitOn(s string, sep string) []string {
	return revlStrSplit(s, sep)
}

func joinWith(xs []string, sep string) string {
	return revlJoin(xs, sep)
}

func repeated(s string, n int64) string {
	return revlStrRepeat(s, n)
}

func indexOfSub(s string, sub string) int64 {
	return revlStrIndexOf(s, sub)
}

func charAtOf(s string, i int64) string {
	return revlStrCharAt(s, i)
}

func codeAtOf(s string, i int64) int64 {
	return revlStrCharCodeAt(s, i)
}

func greetN(name string, n int64) string {
	return ("hi " + name + "#" + strconv.FormatInt(n, 10) + "!")
}

func optName(row RevlOpt[Row]) RevlOpt[string] {
	return revlOptMap(row, func(_x Row) string { return _x.Name })
}

func optCode(s RevlOpt[string]) RevlOpt[int64] {
	return revlOptMap(s, func(_x string) int64 { return revlStrCharCodeAt(_x, 0) })
}

func unwrapOr(o RevlOpt[int64], d int64) int64 {
	return func() int64 {
		switch _m := o.(type) {
		case RevlSome[int64]:
			v := _m.Value
			_ = v
			return v
		case RevlNone[int64]:
			_ = _m
			return d
		default:
			_ = _m
			panic("unreachable: non-exhaustive match")
		}
	}()
}

func adder() func(int64) int64 {
	return func(y int64) int64 { return (y + 1) }
}

func okOf(n int64) RevlResult[int64, string] {
	return RevlOk[int64, string]{Value: n}
}

func errOf(m string) RevlResult[int64, string] {
	return RevlErr[int64, string]{Value: m}
}

func resultFold(r RevlResult[int64, string]) int64 {
	return func() int64 {
		switch _m := r.(type) {
		case RevlOk[int64, string]:
			v := _m.Value
			_ = v
			return v
		case RevlErr[int64, string]:
			e := _m.Value
			_ = e
			return (-revlStrLen(e))
		default:
			_ = _m
			panic("unreachable: non-exhaustive match")
		}
	}()
}
