#!/usr/bin/env python3
"""Regenerate `examples.js` — the preloaded programs, embedded as a JS module.

Embedding (rather than fetching) means the examples load with zero extra
network round-trips and work regardless of how the static site is served.
Run from anywhere:  python3 playground/gen_examples.py
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = Path(__file__).resolve().parent / "examples.js"

# (id, label, kind, path-relative-to-repo-root)
EXAMPLES = [
    ("user_cache", "user_cache — provider + cache (v0 demo)", "accept",
     "examples/user_cache.rvl"),
    ("beacon", "beacon — polyglot mesh (wasm tier)", "accept",
     "examples/beacon.rvl"),
    ("g1_undeclared", "G1 — undeclared access (rejected)", "reject",
     "examples/rejections/g1_undeclared_access.rvl"),
    ("g2_conflict", "G2 — provision conflict (rejected)", "reject",
     "examples/rejections/g2_provision_conflict.rvl"),
    ("g3_cycle", "G3 — dependency cycle (rejected)", "reject",
     "examples/rejections/g3_dependency_cycle.rvl"),
    ("g4_emission", "G4 — undeclared emission (rejected)", "reject",
     "examples/rejections/g4_emission_not_declared.rvl"),
]


def main() -> None:
    payload = []
    for ex_id, label, kind, rel in EXAMPLES:
        source = (ROOT / rel).read_text(encoding="utf-8")
        payload.append({"id": ex_id, "label": label, "kind": kind,
                        "file": Path(rel).name, "source": source})
    body = json.dumps(payload, indent=2, ensure_ascii=False)
    OUT.write_text(
        "// Generated by gen_examples.py — do not edit by hand.\n"
        "// Preloaded revl programs, embedded so the playground needs no\n"
        "// extra fetches. Regenerate with: python3 playground/gen_examples.py\n"
        f"export const EXAMPLES = {body};\n",
        encoding="utf-8",
    )
    print(f"wrote {OUT.relative_to(ROOT)} ({len(payload)} examples)")


if __name__ == "__main__":
    main()
