// Code generated by backends/go/emit.py — DO NOT EDIT.
// revl -> cordis-go, targeting github.com/0xdenny218/stc-go.
package usercache

import (
	"fmt"
	"sync"

	stc "github.com/0xdenny218/stc-go"
)

var _ = fmt.Sprintf

// ---- host runtime (minimal, recording) --------------------------------

// R1 live-resource accounting (docs/backend-ir.md §Required semantics, the
// same pairing the py reference tier's `assert no_residue` checks): every host
// object acquired must be released by its `undo`, or the lifecycle
// `assert no_residue` fails. The counter is package-wide, so it is per-test
// and cross-test safe: a clean test returns to zero.
var _revlLiveMu sync.Mutex
var _revlLiveHostResources int

func revlHostAcquire() { _revlLiveMu.Lock(); _revlLiveHostResources++; _revlLiveMu.Unlock() }
func revlHostRelease() { _revlLiveMu.Lock(); _revlLiveHostResources--; _revlLiveMu.Unlock() }
func revlHostLive() int {
	_revlLiveMu.Lock()
	defer _revlLiveMu.Unlock()
	return _revlLiveHostResources
}

// A deterministic in-memory stand-in for revl host objects, instrumented so
// scenarios can assert the exact effect/undo order of emitted code.

var _hostMu sync.Mutex
var _hostLog []string

func hostRecord(op string) {
	_hostMu.Lock()
	_hostLog = append(_hostLog, op)
	_hostMu.Unlock()
}

// HostMarks returns an ordered snapshot of host operations.
func HostMarks() []string {
	_hostMu.Lock()
	defer _hostMu.Unlock()
	out := make([]string, len(_hostLog))
	copy(out, _hostLog)
	return out
}

// HostReset clears the host op log (call between scenarios).
func HostReset() {
	_hostMu.Lock()
	_hostLog = nil
	_hostMu.Unlock()
}

// Row is a query result row.
type Row = map[string]string

// Pool is a deterministic in-memory connection pool.
type Pool struct {
	url  string
	size int
}

func PoolOpen(url string, size int) *Pool {
	hostRecord("pool.open")
	revlHostAcquire()
	return &Pool{url: url, size: size}
}
func (p *Pool) Close() { hostRecord("pool.close"); revlHostRelease() }
func (p *Pool) Query(sql string) []Row {
	hostRecord("pool.query:" + sql)
	return nil
}
func (p *Pool) Execute(sql string) int {
	hostRecord("pool.execute:" + sql)
	return 0
}

// Map is a thread-safe map with Str keys. The value type is generic — each
// site's `Map.new()` pins `V` from how the map is used (FR-4: a revl
// `Map[Str, Int]` counter or `Map[Str, List[Msg]]` ledger, not only String),
// mirroring backends/rust/emit.py's `struct Map<V>`. Emit instantiates it at
// the acquisition (`MapNew[int64]()`), so the boundary carries the declared
// value type and Insert/Get type-check against the component's real values.
type Map[V any] struct {
	mu sync.Mutex
	m  map[string]V
}

func MapNew[V any]() *Map[V] {
	hostRecord("map.new")
	revlHostAcquire()
	return &Map[V]{m: map[string]V{}}
}
func (m *Map[V]) Drop() { hostRecord("map.drop"); revlHostRelease() }
func (m *Map[V]) Insert(k string, v V) {
	m.mu.Lock()
	m.m[k] = v
	m.mu.Unlock()
}

// InsertIfAbsent is the atomic compare-and-set (item 397). The per-op mutex is
// held across BOTH the membership test AND the insert, so the whole CAS is one
// critical section: no concurrent caller can witness the probe and the write as
// separable steps. Returns whether it inserted; a false (key already present)
// leaves the existing value untouched. Under N concurrent callers on one map,
// exactly one receives true.
func (m *Map[V]) InsertIfAbsent(k string, v V) bool {
	m.mu.Lock()
	defer m.mu.Unlock()
	if _, ok := m.m[k]; ok {
		return false
	}
	m.m[k] = v
	return true
}
func (m *Map[V]) Remove(k string) {
	m.mu.Lock()
	delete(m.m, k)
	m.mu.Unlock()
}
func (m *Map[V]) Get(k string) (V, bool) {
	m.mu.Lock()
	defer m.mu.Unlock()
	v, ok := m.m[k]
	return v, ok
}

// Iteration surface (docs/stdlib-2.0.md §Map): the checker promises
// `size()`/`keys()` on a host `Map.new()` receiver too, and emit lowers both
// as method calls on this object. `Size` is the entry count as the tier's
// revl Int (int, matching the service-method return type); `Keys`
// yields the keys in ascending canonical Str order (UTF-8 byte lexicographic —
// go string < is exactly code-point order, matching sort.Strings; the inline
// insertion sort keeps it import-free, as revlMapKeys does). Both are
// read-only queries, no host trace — like Get.
func (m *Map[V]) Size() int {
	m.mu.Lock()
	defer m.mu.Unlock()
	return int(len(m.m))
}
func (m *Map[V]) Keys() []string {
	m.mu.Lock()
	ks := make([]string, 0, len(m.m))
	for k := range m.m {
		ks = append(ks, k)
	}
	m.mu.Unlock()
	for i := 1; i < len(ks); i++ {
		for j := i; j > 0 && ks[j] < ks[j-1]; j-- {
			ks[j], ks[j-1] = ks[j-1], ks[j]
		}
	}
	return ks
}

// service Database
type Database interface {
	Query(sql string) []Row
	Execute(sql string) int
}

// service Cache
type Cache interface {
	Get(key string) (string, bool)
	Put(key string, value string)
}

var _keyDb = stc.NewKey[Database]("db")
var _keyCache = stc.NewKey[Cache]("cache")

type PgDatabaseConfig struct {
	Url      string
	PoolSize int
}

func DefaultPgDatabaseConfig() PgDatabaseConfig {
	return PgDatabaseConfig{
		PoolSize: 10,
	}
}

func PgDatabase(cfg PgDatabaseConfig) stc.Component {
	return stc.Component{
		Name:    "PgDatabase",
		Provide: []stc.Key{_keyDb},
		Apply: func(ctx *stc.Context) (stc.Inverse, error) {
			var pool *Pool
			if err := ctx.Effect(func() stc.Inverse {
				pool = PoolOpen(cfg.Url, cfg.PoolSize)
				return func() error { pool.Close(); return nil }
			}); err != nil {
				return nil, err
			}
			_implDb := &PgDatabase_db{ctx: ctx, cfg: cfg, pool: pool}
			if _, err := ctx.Provide(_keyDb, Database(_implDb)); err != nil {
				return nil, err
			}
			_ = pool
			_ = cfg
			return nil, nil
		},
	}
}

type PgDatabase_db struct {
	ctx  *stc.Context
	cfg  PgDatabaseConfig
	pool *Pool
}

func (revlSelf *PgDatabase_db) Query(sql string) []Row {
	return revlSelf.pool.Query(sql)
}

func (revlSelf *PgDatabase_db) Execute(sql string) int {
	return revlSelf.pool.Execute(sql)
}

func UserCache() stc.Component {
	return stc.Component{
		Name:    "UserCache",
		Inject:  []stc.Key{_keyDb},
		Provide: []stc.Key{_keyCache},
		Apply: func(ctx *stc.Context) (stc.Inverse, error) {
			db, err := stc.Service[Database](ctx, _keyDb)
			if err != nil {
				return nil, err
			}
			var store *Map[string]
			if err := ctx.Effect(func() stc.Inverse {
				store = MapNew[string]()
				return func() error { store.Drop(); return nil }
			}); err != nil {
				return nil, err
			}
			_implCache := &UserCache_cache{ctx: ctx, store: store, db: db}
			if _, err := ctx.Provide(_keyCache, Cache(_implCache)); err != nil {
				return nil, err
			}
			_ = store
			_ = db
			return nil, nil
		},
	}
}

type UserCache_cache struct {
	ctx   *stc.Context
	store *Map[string]
	db    Database
}

func (revlSelf *UserCache_cache) Get(key string) (string, bool) {
	return revlSelf.store.Get(key)
}

func (revlSelf *UserCache_cache) Put(key string, value string) {
	revlSelf.ctx.Effect(func() stc.Inverse {
		revlSelf.store.Insert(key, value)
		return func() error { revlSelf.store.Remove(key); return nil }
	})
	revlSelf.db.Execute(fmt.Sprintf("INSERT INTO cache_log VALUES (%v)", key))
}

// LoadPgDatabase isolates the load-target per the component's realm placement, then loads it.
func LoadPgDatabase(target *stc.Context, cfg PgDatabaseConfig) *stc.Fiber {
	return target.Load(PgDatabase(cfg))
}

func LoadUserCache(target *stc.Context) *stc.Fiber {
	return target.Load(UserCache())
}
